Fix 10001
metabase/metabase pull request #10323
Opened 2019-07-10 18:08 UTC by paulrosenzweig

Resolves #10001 

That issue describes two problems:

1. Filters can't be dragged without disappearing.

There was a missing `index` prop. Adding that back fixes it.

2. Removing the filter name while editing removes filter

I moved the name into component state while editing. If onBlur, the name is still blank, it's replaced with "unnamed".

I think the issue with blank name was actually due to the slug rather than name, but it felt like it should be solved for name itself.

2019-07-10 18:47 UTC, flamber commented
@paulrosenzweig Also fixes #10299

2019-07-10 21:14 UTC, flamber commented
@paulrosenzweig A question, since I'm looking at preview2, it looks like the SQL widgets are using the same code now, since they now disappear in similar fashion when moved. Will this also resolve that? If so, then you can resolve 9357 and 7460 (not linking in case I'm wrong)

2019-07-10 22:25 UTC, paulrosenzweig commented
@flamber thanks for flagging those!

Those are still broken on the branch for this PR, and it looks like they're also broken (but in different ways) on notebook-mode.

I guess we know it's not worth fixing those on master before notebook-mode is merged in then! 🤷‍♂

2019-07-26 19:29 UTC, tlrobinson requested changes

2019-07-26 19:29 UTC, tlrobinson commented on frontend/src/metabase/parameters/components/ParameterWidget.jsx
> +            value={this.state.editingNameValue}
I try to always declare every state property when defining state, so just add `editingNameValue: null` in the ` state = {` block at the top.

2019-07-26 21:44 UTC, tlrobinson approved these changes

2019-07-26 21:52 UTC, merged