avoid setState in rapid setInterval loop
metabase/metabase pull request #10505
Opened 2019-08-06 19:21 UTC by paulrosenzweig

Resolves #9019

To know when we should refresh a dashboard, we check elapsed time every 250ms. Though maybe a bit too often, 250ms should be plenty of time to update a counter and check if we need to refresh. The high CPU issues occured because the elapsed time sum was stored in React component state and apparently `setState` is really slow. Instead, I just stored the elapsed sum directly on the instance (i.e. `this.refreshElapsed` rather than `this.state.refreshElapsed`).

We prevent multiple `setInterval` timers from running concurrently and clear it when unmounting. Are there any potential issues with storing it directly on the instance? It feels wrong, but it was slightly simpler than pulling `refreshElapsed` into some closure, so I went with it.

On my MacBook Pro, the `setInterval`-invoked function was noticable in a profile, but wasn't causing issues.

<img width="715" src="https://user-images.githubusercontent.com/691495/62569795-fc3f0000-b85c-11e9-86bc-069c2a8c2b47.png">

But, with 4x CPU throttling on, you can see the issue:

<img width="769" src="https://user-images.githubusercontent.com/691495/62569798-ffd28700-b85c-11e9-858c-299bdcd32e67.png">

After pulling `refreshElapsed` out of component state, there are no issues even with CPU throttling turned on.
<img width="731" src="https://user-images.githubusercontent.com/691495/62569966-34464300-b85d-11e9-8996-266bc33d2806.png">

2019-08-06 21:48 UTC, tlrobinson requested changes
Search the rest of the codebase for `refreshElapsed`. This component passes its `state` to the `ComposedComponent` so that `DashboardHeader` etc can display the elapsed time on the `RefreshWidget` clock.

I'm not sure what the ideal fix is, but we should definitely avoid re-rendering the entire dashboard when the clock changes (if that's what's happening)

2019-08-07 16:24 UTC, paulrosenzweig commented
@tlrobinson good catch. I updated the code and PR description. I don't love this solution, but at least it doesn't break the refresh widget!

2019-08-22 00:31 UTC, tlrobinson approved these changes

2019-08-23 16:57 UTC, kdoh approved these changes

2019-08-23 17:37 UTC, merged

2019-08-23 19:40 UTC, flamber commented
@paulrosenzweig FYI Just doing local testing, but I don't see any CPU usage when refresh is activated, so it seems like you fixed it :rocket: Did a very quick test on rPi3+ and wasn't cooking it.