Don't lookup field ID for template tags, without a query
metabase/metabase pull request #10653
Opened 2019-08-21 00:26 UTC by walterl

Based on snarfed/metabase@846f884

I isolated the mentioned patch to the only code path that requires that `datasetQuery` has a value.

@tlrobinson Does this look OK to you? I'm still figuring out what this actually does :mag:

2019-08-22 01:50 UTC, walterl commented
This fixes #10247, so it should probably be merged regardless of #7633.

2019-08-22 19:08 UTC, tlrobinson commented on frontend/src/metabase/meta/Parameter.js
> +      datasetQuery !== undefined
Generally if I expect an object I just check for falsey-ness, i.e. just `datasetQuery`, `!!datasetQuery`, or at most double equals like  `datasetQuery != null` which checks for `null` and `undefined` (really the only case you should ever use `==` in JS)

2019-08-22 20:11 UTC, tlrobinson requested changes
Just a couple little things

2019-08-22 20:15 UTC, walterl commented on frontend/src/metabase/meta/Parameter.js
> +    ) {
I thought about that, but realized that that would then keep the `else`-clause from executing, which I thought was "better" than falling through to the `return null`. Do you agree?

2019-08-22 23:22 UTC, tlrobinson commented on frontend/src/metabase/meta/Parameter.js
> +    ) {
Actually no, because if `dimension[0] === "template-tag"` then calling `getFieldTargetId` on it doesn't make sense.

2019-08-23 21:03 UTC, tlrobinson approved these changes

2019-08-23 21:12 UTC, merged