Add unique constraint on database [name/engine]
metabase/metabase pull request #11228
Opened 2019-10-30 00:33 UTC by mohammedamarnah

Fixes #11106

The issue was happening because there weren't any constraints/checks on the uniqueness of database names across engines. This PR adds a test function that checks if a pair [db-name engine] exists or not, and returns 400 with a message if it already exists.

##### PS: This is my first _serious_ contribution in any open-source project, so any comment would be valuable!

2020-01-13 17:26 UTC, camsaul requested changes
*  We should make this a DB-level constraint. See [this migration](https://github.com/metabase/metabase/blob/master/resources/migrations/000_migrations.yaml#L5208) for an example where we did something similar

2020-01-16 17:45 UTC, kdoh commented
Hi @mohammedamarnah. Congrats on your first OSS contribution! That's very exciting. Sorry it took us a while to get to reviewing it.

Since it has been a while since the initial PR was opened I just wanted to follow up and confirm that you'd still be willing to make the changes @camsaul suggested. Let us know either way or if you need more information.

2020-01-16 19:17 UTC, mohammedamarnah commented
Hello, @kdoh! Thank you so much :)

I would love to make the changes!
I was just trying to figure out some more information about running the migrations. I come from a rails background, so running DB migrations there is pretty simple. Do you have a guide on that?
Thank you again! :)

2020-01-19 11:23 UTC, mohammedamarnah commented
@camsaul Hello! :)
I added the migration and I think running `lein test` ran the migrations and I think its working, but I'm not sure if this is right or not. :sweat_smile:

2020-01-21 20:49 UTC, flyingmachine commented
@mohammedamarnah this is looking great! Congrats again on your first contribution!

For the `constraintName` I think that instead of `idx_uniq_table_name_engine` we want to use `idx_uniq_database_name_engine`. Could you make that change?

2020-01-22 00:09 UTC, mohammedamarnah commented
@flyingmachine Oh thank you so much! 
Of course! At first, I thought that `name` and `engine` were columns in `metabase_table`, and wrote everything based on that, but then realized that it's in `metabase_database` instead and changed everything accordingly but seems like I missed this one. 😅

2020-01-22 19:08 UTC, camsaul commented
I think this is a good idea, and the changes look good to me at a glance, but we need to do some work updating our tests. A few of our tests make copies of the current test database so they can change the synced metadata without affecting other tests. I think most of those funnel thru our `with-temp-copy-of-db` macro so it would be straightforward to have it generate a unique name for the copies. (I think it would be easiest for a member of the Metabase team to tackle that work.)

Also for the next commit we need to add `[ci mysql] [ci postgres]` to the commit message so it runs against Postgres and MySQL.

2020-01-22 19:09 UTC, camsaul requested changes
LGTM but we need to fix tests (I or another member of the MB team should tackle this since it involves reworking some of our test scaffolding)

2020-01-22 19:17 UTC, mohammedamarnah commented
@camsaul That's wonderful! Would you like me to edit anything else then?

2020-01-29 12:13 UTC, walterl commented
@camsaul Is [this](https://github.com/metabase/metabase/pull/11228/files#diff-dd1ef3aafdf7b7ce7b51d32205694027) what you had in mind for the test scaffolding changes?

2020-02-03 19:03 UTC, camsaul commented
This PR does look good overall but the one problem we have is when someone uses our tool to migrate from H2 -> MySQL/MariaDB/Postgres the new DB will have these constraints in place and if the old DB had some data that didn't follow those constraints the migration will fail (see related issue #10961, which arose after we added a constraint for to make user emails unique.)

I still think we should merge this PR but since it could cause issues with the migration tool I want to think of a way to resolve that issue as well

2020-02-03 19:03 UTC, camsaul commented
Let me think about it for a bit and hopefully I can have a fix ready for the next release so we can fix #10961 and merge this without causing new issues

2020-02-03 19:06 UTC, camsaul requested changes
~~I want to address #10961 first before merging. I'm going to try to come up with fix this week and then I'll merge this afterwards~~

2020-02-03 22:36 UTC, camsaul requested changes
It actually looks like the syntax for the `preCondtions` is wrong here: see #11847 (we were using the wrong syntax in the migrations this was modeled on).

Before we can merge this, the syntax needs to be fixed and a test should get added to this PR to make sure the constraint actually works as expected. Add `[ci mysql]` and `[ci postgres]` to the commit message so tests will run against MySQL and Postgres. 

Once that's done, I can figure out how to get our H2->MySQL/Postgres tool working correctly in combination with this PR (address #10961 first before merging)

2020-02-06 16:02 UTC, mohammedamarnah commented
@camsaul I think I added the test but I'm not sure if I did it the right way. Let me know if it should be done in some other way 😅.

2020-02-24 19:10 UTC, camsaul commented on test/metabase/models/database_test.clj
> +(deftest disallow-duplicate-databases-with-same-name-and-engine
we should only run these if we're currently testing against that database, for example we want to be able to run tests against just `:h2` without having a MySQL or Postgres database running. What we usually do is 

```clj
(require '[metabase.driver :as driver] '[metabase.test :as mt])

(deftest my-test
  ;; test-drivers will run the body against :mysql, :postgres, etc. if tests are enabled for that DB
  (mt/test-drivers #{:mysql :postgres :h2}
    ;; driver/*driver* will be bound to :mysql, :postgres, etc.
    (testing driver/*driver*
      ...)))
```

2020-02-24 19:10 UTC, camsaul requested changes
need to tweak the tests so they only run against DBs when tests for those DBs are enabled

2020-02-24 19:13 UTC, camsaul commented on test/metabase/models/database_test.clj
> +(deftest disallow-duplicate-databases-with-same-name-and-engine
actually on second thought you don't really to test this against the different DB types, you can just write the test once, we run tests with all of our supported backing application database types anyway. But you should clear out the DB when you're done. Maybe a test like

```clj
(deftest my-test
  (try
    (create-database! "My DB")
    (is (thrown? ...))
    (finally
      (delete-database "My DB"))))
```

that should probably do it

2020-09-19 07:12 UTC, mohammedamarnah commented
Hi everyone!
Any updates on this?

2020-11-24 00:24 UTC, camsaul approved these changes

2020-11-24 00:24 UTC, camsaul commented
I fixed the merge conflicts and opened PR #13878 to rebase this on latest `master`, so assuming the tests pass we can go ahead and merge it

2020-11-24 01:41 UTC, camsaul commented
Merged in as part of #13878

2020-11-24 01:41 UTC, closed without merging