Use correct JSON base/special type for MySQL
metabase/metabase pull request #11291
Opened 2019-11-10 05:08 UTC by flamber

Removes warning on sync and sets Field Type correctly, which I should probably have tested :man_facepalming: 
Simply just stole from the Postgres driver.
Addendum to #11286, as noted in https://github.com/metabase/metabase/issues/9800#issuecomment-552158818

2019-11-25 18:43 UTC, camsaul commented on src/metabase/driver/mysql.clj
> +  ;; Used when syncing. If it's :JSON type then it's :type/SerializedJSON special-type
Based on the documentation it sounds like a `JSON` column isn't really a `TEXT` column: https://dev.mysql.com/doc/refman/5.7/en/json.html – it sounds like it's stored as a binary representation. So I'm not sure these types make sense – wouldn't it make more sense to match the way we treat JSON columns in Postgres? 

Either way, we'll need some tests before we can merge this. Something like this at the very least https://github.com/metabase/metabase/blob/master/test/metabase/driver/postgres_test.clj#L66

Altho ideally I think we'd want another test that looks at the values in the results as well

2019-11-25 18:44 UTC, camsaul requested changes
*  MySQL JSON type is binary (?)
*  Needs test

2019-11-25 22:33 UTC, flamber commented
@camsaul 
But haven't I matched how it works on Postgres? It's `type/Text` there too. Or did I miss your point?

I have tried to add a test (slightly modified from Postgres), but I'm not sure how to make it check if the returned column is binary or just `:type/SerializedJSON` - it always finishes without error. Not sure if that's because I'm running it locally and not on CI. `lein test :only metabase.driver.mysql-test`

And I'm getting a little :confused: about the implementations...
MariaDB server `JSON` is just an alias of `LONGTEXT`: https://mariadb.com/kb/en/library/json-data-type/
MariaDB Connector/J does some conversion to `VARCHAR` from `BINARY`, if I understood it: https://github.com/MariaDB/mariadb-connector-j/commit/5c10812ecced7c17fc58434c5274ef4b4da5f77e

I think this is above my Clojure level, so feel free to kill this PR, since I don't see how I can finish this without a lot of help.

2019-12-03 15:57 UTC, kdoh commented
Closing for now per @flamber's request in the comment. Thanks for taking a stab at it!

2019-12-03 15:57 UTC, closed without merging