fix mongo field value scan bug
metabase/metabase pull request #11486
Opened 2019-12-10 06:36 UTC by sytuacmdyh

When I manual sync mongo field-values in the admin panel, data in mysql does't be updated properly. values colum always keep null, like `[null, null, null, null, null]`.

After lot's of  debug (since I am familiar with clojure), I find it is because that in mongodb, not all row contains the target field, and this caused some chained problem. Thus, I made this fix.

![image](https://user-images.githubusercontent.com/13233969/70501402-f0d84a00-1b58-11ea-9f8f-895473726e3f.png)

2020-01-13 17:30 UTC, camsaul commented
Thanks @sytuacmdyh, I do think this change makes sense in general. I'm worried about the performance implications of this change, I'm going to take a look at the exact query we generate to make sure it's not going to destroy computers

2020-01-13 17:51 UTC, camsaul requested changes
After looking at this a little longer @sytuacmdyh I'm not confident this fix won't introduce unacceptable performance issues for people with very large datasets. The code being changed is used across all of the databases we support, and with large datasets Metabase would potentially be scanning millions or even billions of rows looking for the first 5000 non-null values, which it may never find. 

It would probably make more sense to do a nested query along these lines (example in SQL since I am better at writing it off the top of my head)

```sql
SELECT DISTINCT some_field
FROM (
  SELECT some_field
  FROM some_table
  LIMIT 100000
) t
WHERE some_field IS NOT NULL
LIMIT 101 -- if there are more than 100 (?) values, we don't want to store the values
```

(i.e., scan up to hundred thousand rows, and select up to 101 distinct non-null values. IIRC the limit for storing field values is 100 distinct values. Not sure if that number is actually correct or not, so don't quote me on that)

That upper bound would at least prevent a potentially massive full table scan. Also I think that it would be a better long-term change to rework the way this step is done in the first place, and generate optimized queries for different databases instead of compiling the generic MBQL query currently used. 

Since this would require reworking some of our driver architecture I think it's an issue the core team would best be equipped to address.

2020-01-13 17:53 UTC, camsaul commented
This *might* be fine for MongoDB

2020-01-13 17:53 UTC, closed without merging

2020-01-13 18:02 UTC, camsaul commented
I've opened #11700 to track this issue

2020-10-21 18:08 UTC, dpsutton commented
This fix is a bit confusing to me. Since we are doing a `:breakout` (essentially a distinct here), removing nils from the query should remove at most one row from the breakout yes?