a way for async exceptions to get treated as such
metabase/metabase pull request #11726
Opened 2020-01-15 16:19 UTC by flyingmachine

This addresses #11108 

When an exception occurs on an API endpoint that returns async responses, the frontend doesn't "know" about it. This is because async responses always return a 200 status, and the frontend thinks that a 200 status means the request was successful.

This PR honestly feels like a hack. I think it would be better to establish a single error representation and always return. Going by [api-exception-response](https://github.com/metabase/metabase/blob/master/src/metabase/middleware/exceptions.clj#L43) it seems like, at the very least, response bodies can be either strings or maps.

2020-01-15 17:31 UTC, flyingmachine commented
@paulrosenzweig @tlrobinson the FE tests are failing on this but before fixing them I'd love to hear whether you think this approach is a good one :)

2020-01-15 20:46 UTC, paulrosenzweig commented
I think it'd be best to submit to the will of HTTP and using status codes, but from our chat yesterday it sounds like that was a difficult thing to restructure. Given that, I think this is the place to hook in.

Are there only a few routes where we can expect this type of error? If so, rather than have this setup for every API call, I'd prefer to explicitly tell those API methods to expect this kind of error. For example, to have the card creation endpoint check for an error we could pass this option:

`POST("/api/card", {bodyHasError: (body) => body.async_status === "error"})`

2020-01-15 21:26 UTC, flyingmachine commented
Yeah - my understanding is that the way the async response works is that the serve immediately responds with a 200 and then streams a body. The streaming is not a function of the body's size, it's a consequence of handling the request asynchronously in the backend.

I did a quick and dirty survey of how many routes we can expect this kind of error from, and it looks like it's `/api/card` and `/api/dataset` endpoints

2020-01-16 00:26 UTC, flyingmachine commented
@paulrosenzweig would it be possible to hand this off to you for any further frontend work?

2020-01-16 20:43 UTC, paulrosenzweig commented
I added an option called `bodyHasError` and set it up for Card create/update. It looks like those are the only routes that use the async handler, but if I misread, we can add it to the other routes.

If I add `(throw (Exception. "oh no"))` to `save-new-card-async!`, I see the error message after trying to save:
![image](https://user-images.githubusercontent.com/691495/72561109-79dc5280-3876-11ea-921d-8a5a24ecd1d6.png)

2020-01-16 21:43 UTC, camsaul commented
I don't think it makes a ton of sense to have async error responses be either strings or maps, especially since I'm 95% sure it comes back with `Content-Type: application/json` headers either way. We should return them in some sort of standard error map instead.

What we really need is to come up with a few standard REST API patterns we can agree on and write them up in a wiki page

2020-01-20 23:59 UTC, tlrobinson requested changes
Maybe we should use `_status` (or `_status_code`) as the special property? Rails used `_method` for a similar purpose, for example.

2020-01-20 23:59 UTC, tlrobinson commented on frontend/src/metabase/lib/api.js
> +          let status_code = xhr.status;
We don't typically use snake case in JavaScript. I'd just call it `status`.

2020-01-20 23:59 UTC, tlrobinson commented on frontend/src/metabase/lib/api.js
> +          if (status_code === 202) {
Might want to also check that `body.status_code` is not null/undefined.

2020-01-21 00:00 UTC, flyingmachine commented
it would be good to implement deeper structural changes to always return a 202 status for async requests, but I'd prefer to leave that for a separate PR.

2020-01-21 19:01 UTC, flyingmachine commented
@tlrobinson this is ready for another look :)

2020-01-22 19:14 UTC, camsaul approved these changes
Cool LGTM.

Could you write some of this down in https://github.com/metabase/metabase/wiki/Metabase-REST-API-Patterns ? It will save us some time in the long run, when someone new joins we'll have to explain the pattern anyway so better to do it in one canonical place

2020-01-22 19:15 UTC, camsaul commented
Also (not sure if there's already an open issue) can you open an issue for returning the 202 response for all async API requests, so we don't forget to do it? 🙏

2020-01-23 00:52 UTC, flyingmachine commented
it looks like I need @tlrobinson to approve, or for an admin to merge :'(

2020-01-23 20:07 UTC, tlrobinson commented on frontend/src/metabase/lib/api.js
> +            body._status !== null &&
This is super minor but the idiomatic way to check for `null` or `undefined` in JS is `!= null` (the only reason you should ever use `==` or `!=` over `===` and `!==`)

2020-01-23 20:30 UTC, tlrobinson approved these changes
Looks good, I made one small tweak, we can merge once it passes CI.

2020-01-27 19:20 UTC, merged