Scope down URLs where a 403 triggers a error page
metabase/metabase pull request #11747
Opened 2020-01-17 22:57 UTC by paulrosenzweig

Resolves #10816

Previously our default behavior displayed an error page when any API call returned a 403. We had a list of excepted URLs.

This PR flips that logic. Now, we ignore 403s by default and have a list of api calls that should trigger the error page. That should prevent errors where a stray API call broke an otherwise functional page by blocking it with the error page. However, it increases the likelihood of failing to display the error page when it would be useful.

I added some tests to ensure we still show the error page on blocked pages: question, dashboard, collection, etc.

2020-01-17 23:17 UTC, tlrobinson reviewed
Any reason not to include other artifacts like `GET /api/card/:id` and `GET /api/pulse/:id`?

2020-01-21 00:59 UTC, paulrosenzweig commented
@tlrobinson accessing pulses and questions both popped up that error screen on their own. I wanted to keep the regex list as small as possible, but it's probably better to have it make sense rather than be minimal. I just added those two with a test for pulses.

Are there any others you can think of? Do alerts need this?

2020-01-22 18:06 UTC, tlrobinson commented
@paulrosenzweig should this be against `release-0.34.x` branch? I think my PR #11751 removes some code that could cause a regression without this PR: https://github.com/metabase/metabase/pull/11751/files#diff-f6fa358f37cc8e642b13e3a9f07d3204L457-L464 Currently it's also on master but I think these should both be in `release-0.34.x`.

(I was going to add a Cypress test but first need to get #11746 which sets up multiple users with varying permissions)

2020-01-22 18:19 UTC, paulrosenzweig commented
@tlrobinson 👍 just updated the base of this PR.

2020-01-23 21:28 UTC, tlrobinson requested changes
Looks like CI is failing due to lack of snapshot/restore in this branch. Not sure how to best resolve that. You could just leave the test out of this PR?

2020-01-23 22:21 UTC, paulrosenzweig commented
@tlrobinson fixed. Thanks for pointing that out.

2020-01-24 18:54 UTC, tlrobinson approved these changes

2020-01-24 18:55 UTC, merged