Convert MySQL report_card table to utf8mb4 to fix 'Incorrect string value'
metabase/metabase pull request #11752
Opened 2020-01-18 02:30 UTC by camsaul

Fixes #10691 for people with existing setups

2020-01-18 02:30 UTC, camsaul commented on src/metabase/driver/mysql.clj
> +   :connectionCollation  "utf8mb4_unicode_ci"
these changes aren't part of this fix but this seems to be the way the MySQL dox suggest you set these params.

2020-01-21 22:14 UTC, flyingmachine requested changes
If I'm not mistaken, it looks like other tables suffer from this problem? For example https://github.com/metabase/metabase/issues/9786 shows the problem showing up with this query:

```
Query is: INSERT INTO metabase_fieldvalues ( id, created_at, updated_at, values, human_readable_values, field_id ) VALUES ( 1513, '2018-10-09 18:09:47.375', '2018-11-16 18:23:24.457', '["Constant ↔ "]', , 4656 )
```

2020-01-22 18:24 UTC, camsaul commented
@flyingmachine PR #11573 is the same thing but converts the entire database. I'm not sure what the implications of converting an entire database to `utf8mb4` will be. Since it involves converting the byte encoding of every text column in the entire database I want to make sure we're not going to be shipping a database migration that potentially takes days to run. That's why I asked for people to test it on #10691 before proceeding further.

This PR exists in case I decide not to pull the trigger on #11573. It's a subset that I'm comfortable merging that would solve 99% of the problems we're seeing.

2020-02-03 19:08 UTC, camsaul commented
Closing with out merge in favor of alternative fix PR #11573

2020-02-03 19:08 UTC, closed without merging