Fix bug in chart column settings back behavior
metabase/metabase pull request #11833
Opened 2020-01-31 20:18 UTC by paulrosenzweig

Resolves #11775

## Fix

This PR updates how nested columns settings override the back behavior of the settings sidebar. Previously, the back behavior was always set to unselect the current column. This was ineffective if there was only one column because it was immediately reselected. Now, we unset the current _section_ if there's just one column.

Another issue, was for settings with just one section. There resetting the current section wouldn't do anything, so we leave the standard back behavior of returning to the visualization types.

## Gifs

### Table

![table](https://user-images.githubusercontent.com/691495/73571487-a7abc480-443c-11ea-9de4-d54f5ca385fe.gif)

### Gauge

![gauge](https://user-images.githubusercontent.com/691495/73571494-ad090f00-443c-11ea-8399-691f385afbb4.gif)

### Number

![number](https://user-images.githubusercontent.com/691495/73571499-af6b6900-443c-11ea-9ec3-b94c3a67d2aa.gif)

@mazameli this one seems a bit weird to me. What do you think about not overriding title with the column name in this case?

## Design

It feels wrong that the nested settings are aware of all this external context. It seemed like the alternative was to spread the behavior across multiple components so I left it this way.

2020-01-31 20:25 UTC, mazameli commented
Tables look right, but Gauge and Number both look wrong to me in the Gifs. 

Like you suggested, Number charts should say "Number options" to follow the current pattern of all the other visualization settings.

Gauges shouldn't have the tabs disappear when clicking on the "Formatting tab." Instead, the Formatting tab should be highlighted, and there is no need for a back button other than the existing one that says "< Gauge settings," which takes you back to visualization selection. It should be transparent to the user that this is technically showing the "column settings" for the single cell result that's being visualized.

2020-01-31 22:19 UTC, tlrobinson requested changes

2020-01-31 22:19 UTC, tlrobinson commented on frontend/src/metabase/visualizations/components/settings/ChartNestedSettingColumns.jsx
> +      const overrides = { title: displayNameForColumn(object) };
I think your suggestion to change the title based on whether there are multiple objects or sections makes sense.

2020-01-31 23:55 UTC, paulrosenzweig commented
New gifs:

### Table (same)

![table](https://user-images.githubusercontent.com/691495/73582365-da64b580-445a-11ea-8814-41be545ff132.gif)


### Gauge

![gauge](https://user-images.githubusercontent.com/691495/73582363-d6d12e80-445a-11ea-89b3-22ea26f47aa9.gif)


### Number

![number](https://user-images.githubusercontent.com/691495/73582361-d3d63e00-445a-11ea-9c9a-058c444a0fdf.gif)

2020-02-01 00:00 UTC, mazameli commented
New gifs look good to me! 👍

2020-02-03 17:34 UTC, tlrobinson approved these changes

2020-02-03 17:34 UTC, merged