Fix stack overflow when using non-existent MetaBot command
metabase/metabase pull request #11972
Opened 2020-02-25 00:24 UTC by celwell

Giving a Slack message to MetaBot with a command that doesn't exist (e.g., `metabot cool`) causes a stack overflow and responds with a null error message:
![image](https://user-images.githubusercontent.com/1365334/75202622-d5cdad00-5739-11ea-999a-c4215a98eceb.png)

This PR fixes that bug, and another instance of the same bug within `metabot show`.

Also, an (unused?) let form was removed. Let me know if you want me to revert that (i.e., if it was being kept around for some reason). And, I have aggressive-indent-mode on, so let me know if you want me to undo the automatic indentation changes.

2020-02-26 20:00 UTC, camsaul commented on src/metabase/metabot/command.clj
> -                                           [:in :collection_id other-visible-collection-ids])]
I think I must have forgot to remove this when I put in the 

```clj
(collection/visible-collection-ids->honeysql-filter-clause (metabot-visible-collection-ids))
```

which accomplishes the same thing but more generally. good catch 👍

2020-02-26 20:01 UTC, camsaul commented on src/metabase/metabot/command.clj
> +   (log/debug (trs "Loading Kanye quotes..."))
[The body of `delay` forms should be indented by 2 spaces](https://guide.clojure.style/#body-indentation), please revert this indentation change

2020-02-26 20:02 UTC, camsaul commented on src/metabase/metabot/command.clj
> +     (edn/read-string (slurp url)))))
[The body of `delay` forms should be indented by 2 spaces](https://guide.clojure.style/#body-indentation), please revert this indentation change

2020-02-26 20:02 UTC, camsaul commented on src/metabase/metabot/events.clj
> -(defn- respond-to-message! [message response]
👍

2020-02-26 20:03 UTC, camsaul requested changes
This looks great.

One minor request: please revert that indentation change you made with the body of the `delay` form.

2020-02-26 20:12 UTC, camsaul commented
Out of curiousity: if you're using `aggressive-indent-mode` are you using `clojure-mode` as well? Curious why it indented `delay` with one space for you.

Not sure how familiar you are with Emacs Lisp, but the way `clojure-mode` determines how to indent things is by looking a the value of `clojure-indent-function` in [the property list cell](https://www.gnu.org/software/emacs/manual/html_node/elisp/Symbol-Plists.html#Symbol-Plists) of the symbol with the same name. So for `delay` it does 

```emacs-lisp
;; Emacs Lisp
(get 'delay 'clojure-indent-function) ; -> 0
```

which tells it to indent it as a form with 0 args on the first line, in other words use 2 spaces e.g.

```clj
(delay
  ...)
```

(If you have CIDER connected to a REPL, it also looks at the `:style/indent` metadata for the var in question, but failing that it falls back to the value of `clojure-indent-function`).

2020-02-26 21:51 UTC, celwell commented
Oh, apparently it was corrected in clojure-mode 5.11 (https://github.com/clojure-emacs/clojure-mode/issues/524). I've updated my package version, and `delay` now properly indents.

2020-03-09 23:07 UTC, camsaul commented
Cool. Thanks!

2020-03-09 23:07 UTC, merged