MBQL: fix expressions+joins+multiple columns with same name [WiP]
metabase/metabase pull request #12328
Opened 2020-04-15 18:50 UTC by sbelak

Fixes a bug where nested queries didn't distinguish between fields with the same name but from different tables (eg. when joining 2 tables with the field `created_at` the results have the first `created_at` duplicated instead of two distinct fields with distinct values). Once we started lifting expressions to a subselect, the bug became more prominent.

Fixes #12252

2020-04-15 18:52 UTC, mazameli commented
This should go into `release-0.35.x`, yeah?

2020-04-15 18:56 UTC, sbelak commented
@mazameli: yes, fixed

2020-04-16 21:29 UTC, tlrobinson requested changes
@sbelak This does not resolve #12252, my comment here about `field_ref` being incorrect is still true https://github.com/metabase/metabase/issues/12252#issuecomment-608620779

2020-04-17 19:32 UTC, sbelak commented
Split the `field_ref` part into #12345 as it is somewhat problematic.

2020-04-20 17:52 UTC, camsaul approved these changes
Cool this works for me, but can you run it with `[ci drivers]` one last time and make sure it's green

2020-04-20 18:21 UTC, tlrobinson approved these changes

2020-04-20 18:49 UTC, merged