Display field description in field list
metabase/metabase pull request #12508
Opened 2020-05-12 14:39 UTC by rthouvenin

Addresses  #6316

2020-05-13 18:20 UTC, mazameli requested changes
Thanks for the contribution!

Adding the description in though is going to require some rebalancing of the other elements for each list item in order to make things look right.

### Current appearance in the branch

![image](https://user-images.githubusercontent.com/2223916/81844070-6464f580-9503-11ea-8e5a-25103f51c1dd.png)

### Desired

![image](https://user-images.githubusercontent.com/2223916/81849411-587d3180-950b-11ea-9e59-38c6f417800e.png)

2020-05-14 13:17 UTC, rthouvenin commented
Ah my bad, I tested the change on a v0.33 build I had handy, and did notice that the styling of the page changed when I rebased my commit on master.

I made some adjustment to the style, looks better? I didn't move the raw name to the right as suggested in the image, as I found the current way more legible.

One more thing I forgot to mention when I created the PR: the Edit mode doesn't let the user modify the description. Should it?

Thanks for the review!

2020-05-28 09:28 UTC, rthouvenin commented
@mazameli Did you get a chance to review my changes

2020-11-16 20:06 UTC, mazameli commented
@rthouvenin, sincere apologies for letting this PR slip through the cracks! I'm just going to put a couple of spacing suggestions in the code in your PR shortly and then I think we'll be able to merge this.

2020-11-16 21:56 UTC, mazameli requested changes
With these two spacing changes, we should be good to merge this.

2020-11-16 21:56 UTC, mazameli commented on frontend/src/metabase/reference/components/Field.jsx
> +  <div className={cx(S.item, "p1", "mt1", "border-top")}>
```suggestion
  <div className={cx(S.item, "pt1", "border-top")}>
```

2020-11-16 21:56 UTC, mazameli commented on frontend/src/metabase/reference/components/Field.jsx
> +        <div className={cx(S.itemSubtitle, { mt1: isEditing })}>
```suggestion
        <div className={cx(S.itemSubtitle, "mb2", { mt1: isEditing })}>
```

2020-11-17 11:17 UTC, rthouvenin commented
I rebased (locally) the  branch on 0.37.2 and compared with/without the suggestions. The rebase didn't require any manual merge and and page looks crispier with your suggestion.
Thanks for looking into it, better late than never :)

2020-11-24 17:04 UTC, mazameli approved these changes

2020-11-25 20:04 UTC, mazameli commented
@camsaul or @robdaemon, I'm unsure why there are three BE tests failing on this PR, which only touches one FE file. What should I do here?

2020-11-25 20:27 UTC, robdaemon commented
@mazameli the Oracle and Vertica failures are because this is a third-party PR - they don't have access to certain parameters, so nothing to worry about there. The Cloverage failure is a flake. Feel free to merge this as-is.

2020-11-25 21:00 UTC, merged