make jetty request header size configurable
metabase/metabase pull request #12683
Opened 2020-06-11 15:42 UTC by emurphy

Make jetty request header size configurable.

In our case the need arises as our Metabase installation shares a domain with another application that uses AWS Cognito's cookie storage feature, despite its [notoriously large cookies](https://github.com/aws-amplify/amplify-js/issues/1545). A temporal need has also [come up before](https://github.com/metabase/metabase/pull/1820) and will likely come up for other Metabase users as well.

###### Before submitting the PR, please make sure you do the following
~~- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.~~
### Tests
~~-  [ ] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)~~
-  [X] If there are changes to the backend codebase, run the backend tests with `lein test && lein lint && ./bin/reflection-linter`

-  [X] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

2020-06-11 16:42 UTC, flamber commented
This looks like a duplicate of #12082

2020-06-11 17:25 UTC, camsaul commented
Supercedes #12802

2020-06-11 17:25 UTC, camsaul commented
Closes #9386

2020-06-12 20:21 UTC, robdaemon requested changes

2020-06-12 20:21 UTC, robdaemon commented on src/metabase/config.clj
> +   :mb-jetty-request-header-size  "8192"
We'd like to not specify the default here and not set the value if it's not overridden, that way if the default changes in the Jetty library in the future, we don't need to update this value. I'll provide an example.

2020-06-12 20:21 UTC, robdaemon commented on src/metabase/server.clj
> +            :request-header-size (config/config-int :mb-jetty-request-header-size)})
This will require a change to not add to the map if it's not set. Will provide an example.

2020-06-12 20:25 UTC, robdaemon commented
Inside `server.clj`, you can do this:

```clj
(defn- jetty-config []
  (cond-> (m/filter-vals
           some?
           {:port          (config/config-int :mb-jetty-port)
            :host          (config/config-str :mb-jetty-host)
            :max-threads   (config/config-int :mb-jetty-maxthreads)
            :min-threads   (config/config-int :mb-jetty-minthreads)
            :max-queued    (config/config-int :mb-jetty-maxqueued)
            :max-idle-time (config/config-int :mb-jetty-maxidletime)})
    (config/config-int :mb-jetty-request-header-size) (assoc :request-header-size (config/config-int
                                                                                   :mb-jetty-request-header-size))
    (config/config-str :mb-jetty-daemon)              (assoc :daemon? (config/config-bool :mb-jetty-daemon))
    (config/config-str :mb-jetty-ssl)                 (-> (assoc :ssl? true)
                                                          (merge (jetty-ssl-config)))))
```

2020-06-12 23:59 UTC, robdaemon approved these changes
Awesome, thanks for the contribution! Once the CI tests finish, I'll merge this.

2020-06-13 01:19 UTC, emurphy commented
Thank you! 🎉

2020-06-15 20:21 UTC, merged