Sync views in Snowflake databases
metabase/metabase pull request #12936
Opened 2020-07-17 07:43 UTC by asavoy

The Snowflake driver currently uses the SQL query `SHOW TABLES IN DATABASE ...` in `describe-databases` to fetch the tables in the database.

Unfortunately, this excludes views from being visible to Metabase for sync, even though views work fine in the Metabase custom query editor. This might be a contributing factor to similar issues reported on Snowflake, it can be easy to confuse tables and views because they interchangeable much of the time:

- #8864 Metabase can't find Snowflake tables
- #9511 Snowflake Tables Don't Show
- [Issue with filter using Snowflake database](https://discourse.metabase.com/t/issue-with-filter-using-showflake-database/6142)

By changing to `SHOW OBJECTS IN DATABASE ...`, this will return views and tables, as mentioned in the [Snowflake docs](https://docs.snowflake.com/en/sql-reference/sql/show-objects.html) - and not any other types of objects.

###### Before submitting the PR, please make sure you do the following

- [x] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

 **NOTE: I ran the tests and there were a handful of failures, but these seem to occur on master branch and so I don't think I've introduced them here**

-  [x] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein lint && ./bin/reflection-linter`  

-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

2020-07-17 15:53 UTC, sbelak requested changes
This looks good -- thanks for the PR! -- but would be nice to add a test. See for example for how to do a test with a temporary DB https://github.com/metabase/metabase/blob/master/test/metabase/driver/postgres_test.clj#L179

Happy to assist if you have any questions.

2020-07-18 17:03 UTC, asavoy commented
@sbelak OK, I've added a test following a similar pattern to the test you referenced

2020-07-20 22:56 UTC, sbelak commented
Thanks. Looks good. I have re-push this branch to our repo as #12961 so our CI with the drivers tests picks it up.

2020-07-22 19:28 UTC, camsaul commented
Tests passed in #12961

2020-07-22 19:28 UTC, merged