Make jetty client SSL auth configurable
metabase/metabase pull request #13297
Opened 2020-09-22 20:49 UTC by pdbrown

Add :mb-jetty-ssl-client-auth boolean config key to require ssl client auth when set.

Hi there! My use-case for this configuration is to improve security when running metabase on a public IP. Required client SSL certs add a second layer of authentication on top of username/password credentials. Jetty's `TrustStore` is already configurable, but an included CA cert isn't used to validate client certs unless the `SslContextFactory$Server#setNeedClientAuth` flag is set too.

I added this configuration as a boolean, instead of passing `:need` or `:want` through to ring, since there's nothing the server will do with an available, but optional, valid client cert in the case of `:want`. If anyone ever needed the `:want` option, it'd be pretty straightforward to relax the config from boolean to keyword though.
(See also: http://ring-clojure.github.io/ring/ring.adapter.jetty.html)

FWIW, Google Cloud's Identity Aware Proxy (see https://github.com/metabase/metabase/issues/6709) would address my particular use-case too, and I'd be happy to contribute that as well, but this change seems useful nonetheless.

###### Before submitting the PR, please make sure you do the following
-  [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein lint && ./bin/reflection-linter`

-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

2021-10-21 02:41 UTC, pawit-metabase requested changes
Can you provide some instruction on how I can verify that this PR is working as expected?

@camsaul This looks pretty valid to me but to confirm, are you OK with adding an additional option here?

2021-11-04 03:47 UTC, pdbrown commented on docs/operations-guide/environment-variables.md
> +#### `MB_JETTY_SSL_CLIENT_AUTH`
Sure thing!

2021-11-04 03:57 UTC, pawit-metabase commented
@flamber including you as FYI

2021-11-04 04:02 UTC, pdbrown commented
I didn't do anything too fancy, but tested this by manually setting up certs and checking that jetty and the browser handle things correctly. I'm running my fork in production too, and it appears to be working fine.

Here's what I did, on debian 10 with `openssl` installed:
```bash
mkdir -p /tmp/certs && cd /tmp/certs

export KEY_PASSWORD=mb-test

# Make self-signed certificate authority to use as metabase keystore, truststore,
# and to sign client certs.
CA_NAME=mb-test-ca
CA_SUBJECT_DN="/CN=$CA_NAME,O=mb-test/"
# Generate AES encrypted 2048 bit RSA key for CA
openssl genrsa -aes256 -passout env:KEY_PASSWORD -out "$CA_NAME.key" 2048
# Use it to generate self-signed cert to use as CA
openssl req -x509 -new -key "$CA_NAME.key" -sha256 \
        -days 3650 \
        -subj "$CA_SUBJECT_DN" \
        -passin env:KEY_PASSWORD \
        -out "$CA_NAME.crt"
# Export CA as p12 truststore
openssl pkcs12 -inkey "$CA_NAME.key" -in "$CA_NAME.crt" \
        -passin env:KEY_PASSWORD \
        -passout env:KEY_PASSWORD \
        -export -out "$CA_NAME.p12"

# Make client cert signed by CA
KEY_NAME=mb-test-client
SUBJECT_DN="/CN=$KEY_NAME,O=mb-test/"
# Generate client private key
openssl genrsa -aes256 -passout env:KEY_PASSWORD -out "$KEY_NAME.key" 2048
# Generate certificate signing request for key
openssl req -new -key "$KEY_NAME.key" -passin env:KEY_PASSWORD \
        -subj "$SUBJECT_DN" -out "$KEY_NAME.csr"
# Generate cert for private key signed by self-signed CA
openssl x509 -req -in "$KEY_NAME.csr" \
        -CA "$CA_NAME.crt" \
        -CAkey "$CA_NAME.key" \
        -CAcreateserial \
        -passin env:KEY_PASSWORD \
        -out "$KEY_NAME.crt" -days 3650 -sha256
# Package keys into p12 archive for installion in browser
openssl pkcs12 -inkey "$KEY_NAME.key" -in "$KEY_NAME.crt" \
        -passin env:KEY_PASSWORD \
        -passout env:KEY_PASSWORD \
        -export -out "$KEY_NAME.p12"
```

Then build metabase, and run it as follows:

```
export MB_JETTY_PORT=8080
export MB_JETTY_SSL=true
export MB_JETTY_SSL_PORT=8443
export MB_JETTY_SSL_KEYSTORE=/tmp/certs/mb-test-ca.p12
export MB_JETTY_SSL_TRUSTSTORE=/tmp/certs/mb-test-ca.p12
export MB_JETTY_SSL_CLIENT_AUTH=true
export MB_JETTY_SSL_KEYSTORE_PASSWORD=mb-test
export MB_JETTY_SSL_TRUSTSTORE_PASSWORD=mb-test

java -jar metabase.jar
```

Now navigate to metabase SSL endpoint (before installing client cert) at
`https://localhost:8443/setup`
Should see an error page for ERR_BAD_SSL_CLIENT_AUTH_CERT error since the browser has no client certs to offer.

Then install client certs and try again.
```
E.g. in chrome:
Go to chrome://settings/
-> Privacy and security - Security
-> Advanced - Mange Certificates
-> Your certificates - Import
-> Choose /tmp/certs/mb-test-client.p12
   with password: mb-test
```

Now client auth should work: Go back to `https://localhost:8443/setup` and choose the imported `mb-test-client` cert when prompted at the "Select a certificate" popup.

The page loads!

2021-11-04 04:05 UTC, pawit-metabase approved these changes
LGTM, waiting for feedback from other team members.

2021-11-04 17:46 UTC, flamber commented
Seems simple and small, and just makes use of a config in Jetty, so I don't see why not.
Though, I would probably handle certificates in an external reverse-proxy for added flexibility.

2021-11-05 07:45 UTC, camsaul approved these changes

2021-11-05 07:46 UTC, camsaul commented
Failing tests are because we don't inject env vars that have credentials for cloud DBs into 3rd party PRs. Everything else is passing as expected

2021-11-05 07:46 UTC, merged

2021-11-05 21:40 UTC, pdbrown commented
Sweet, thanks for the reviews!