Add Singapore timezone
metabase/metabase pull request #13403
Opened 2020-10-08 07:18 UTC by dmfilipenko

###### Before submitting the PR, please make sure you do the following
- [X] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.
### Tests
-  [x] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein lint && ./bin/reflection-linter`

-  [X] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

2020-10-14 17:46 UTC, robdaemon approved these changes

2020-10-14 19:12 UTC, camsaul commented
See comments in #9609 -- having a hardcoded list of timezones that require a bunch of PRs for people to add the ones they want isn't really a sustainable approach. We should go with the approach from #8943 instead and get the timezones from the system

2020-10-14 19:13 UTC, camsaul requested changes
Instead of adding timezones one at a time we should query the system for everything available and show them all. Discussed more in #8943 and #9609

2021-01-15 21:39 UTC, tsmacdonald commented
Closing this in favor of #14429

2021-01-15 21:39 UTC, closed without merging