File download testing
metabase/metabase pull request #13430
Opened 2020-10-10 01:31 UTC by nemanjaglumac

### Status
WIP

2020-10-16 13:44 UTC, nemanjaglumac commented
5.4.0 is out already 
https://github.com/cypress-io/cypress/releases/tag/v5.4.0

2020-11-10 00:34 UTC, dacort requested changes
We also need to test the different cases mentioned in https://github.com/metabase/metabase/issues/10803#issuecomment-638480542 as there are a number of issues with date/timestamp formats. I attempted to start this (see code below) but ran into some issues with unexpected results. Feel free to pick it up, but I can get to it tomorrow as well.

```javascript


  describe.only("for unsaved questions", () => {
    it("should format the date properly", () => {
      // Setup the query
      cy.visit("/question/new");
      cy.findByText("Native query").click();
      cy.get(".ace_editor").type(
        "SELECT PARSEDATETIME('2020-06-03', 'yyyy-MM-dd') AS \"birth_date\", PARSEDATETIME('2020-06-03 23:41:23', 'yyyy-MM-dd hh:mm:ss') AS created_at",
      );
      cy.get(".Icon-play")
        .first()
        .click();
      cy.get(".Icon-download").click();

      cy.wrap(testCases).each(testCase => {
        let downloadClassName = `.Icon-${testCase.type}`;
        let endpoint = `/api/dataset/${testCase.type}`;
        let sheetName = testCase.firstSheetName;

        cy.log(`downloading a ${testCase.type} file`);

        cy.get(downloadClassName)
          .parent()
          .parent()
          .get('input[name="query"]')
          .invoke("val")
          .then(download_query_params => {
            cy.request({
              url: endpoint,
              method: "POST",
              form: true,
              body: { query: download_query_params },
              encoding: "binary",
            }).then(resp => {
              cy.log(resp.body);
              let workbook = xlsx.read(resp.body, { type: "binary" });

              expect(workbook.SheetNames[0]).to.eq(sheetName);
              expect(workbook.Sheets[sheetName]["A1"].v).to.eq("birth_date");
              expect(workbook.Sheets[sheetName]["A2"].v).to.eq("2020-06-03");
            });
          });
      });
    });
  });
```

2020-11-10 00:34 UTC, dacort commented on frontend/test/metabase/scenarios/excel/downloads.cy.spec.js
> +  it("downloads Excel file", () => {
Discussed in Slack, but pushing up a change to refactor this a little bit.

2020-11-10 17:32 UTC, dacort commented
> We also need to test the different cases mentioned in [#10803 (comment)](https://github.com/metabase/metabase/issues/10803#issuecomment-638480542) as there are a number of issues with date/timestamp formats.

Merging this as the initial step in being able to further test Excel/CSV downloads.

2020-11-10 17:37 UTC, dacort approved these changes
🚀

2020-11-10 19:03 UTC, merged