Docs - added first day of week option to localization docs page
metabase/metabase pull request #13446
Opened 2020-10-12 21:15 UTC by jeff-bruemmer

Small, but important change.

2020-10-15 13:45 UTC, kdoh requested changes, later dismissed
Small copy suggestion just to reinforce that it's not something you necessarily have to fiddle with.

2020-10-15 13:45 UTC, kdoh commented on docs/administration-guide/localization.md
> +You can set the first day of the week (default: Sunday). Setting the first day of the week affects things like grouping by week and filtering in GUI queries ([simple](../users-guide/04-asking-questio
```suggestion
If you need to, you can change the first day of the week for your instance (the default is Sunday). Setting the first day of the week affects things like grouping by week and filtering in GUI queries ([simple](../users-guide/04-asking-questions.html) and [custom questions](../users-guide/custom-questions.html) composed in the notebook editor). This setting does not affect [SQL queries](../users-guide/writing-sql.html).
```

2020-10-21 23:47 UTC, mazameli approved these changes
Looks like @kdoh's feedback got addressed, and this looks 👍 to me.

2020-10-22 00:06 UTC, kdoh approved these changes

2020-10-22 00:33 UTC, merged