resources/log4j2.xml: remove ansi formatting.
metabase/metabase pull request #13553
Opened 2020-10-21 15:40 UTC by jimmy-outschool

Avoid ansi output from log4j2 so that the environment variable `NO_COLOR` behaves as expected.

Fixes #13538.

2020-10-21 18:00 UTC, robdaemon requested changes, later dismissed
Thanks for the contribution!

I'd like to take a different approach here, where we don't remove the highlights if NO_COLOR isn't specified. Is that possible?

2020-10-21 18:04 UTC, jimmy-outschool commented
Was following agreement from @camsaul on removing entirely. Conditional on `NO_COLOR` sounds better, but I am not sure how to handle that properly. I believe log4j2 has `disableAnsi` property on the pattern, but I am not sure how to connect that to an environment variable.

2020-10-21 18:12 UTC, robdaemon commented
Here's how to do that: https://github.com/metabase/metabase/pull/13556

@camsaul can you weigh in here on which you would prefer?

2020-10-21 18:14 UTC, jimmy-outschool commented
My preference would be your PR, assuming that works.

2020-10-21 18:16 UTC, robdaemon commented
![no-color](https://user-images.githubusercontent.com/287213/96764708-c36e4680-138e-11eb-96cb-109e9941b678.png)

this is my PR in action (please ignore the `include-drivers middleware` messages, those are only in development since I'm running through leiningen)

Normally, if there's no pty attached, the ANSI output wouldn't happen, but Docker creates a pty. systemd, for example, does not.

2020-10-21 18:24 UTC, jimmy-outschool commented
Depending on your terminal emulator I've found the bolds do not show up (if it considers the default font to be bold for example). Dumping to a file and analyzing is the best way to catch them. If they are not there, lets go with yours.

2020-10-21 21:48 UTC, jimmy-outschool commented
Never mind I see it in your screneshot.

2020-10-21 23:18 UTC, robdaemon approved these changes

2020-10-22 18:39 UTC, merged

2020-10-22 19:11 UTC, jimmy-outschool commented
Thanks.