Show engine in Task trouble shooting logs
metabase/metabase pull request #13608
Opened 2020-10-27 19:25 UTC by dpsutton

## Including database engine

<img width="854" alt="image" src="https://user-images.githubusercontent.com/6377293/97351122-53b0fd80-185f-11eb-9b9e-9cd5d3abba9c.png">

---
#### When no database:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/6377293/97351240-7a6f3400-185f-11eb-8e2a-aa372210f489.png">

in an effort to get better feedback when people raise issues about
long running sync processes, include the database engine in the logs.

Also wrapped `th` in a `tr` inside the `thead` to remove react warning

2020-10-27 19:38 UTC, dpsutton commented
things would love feedback on:
- what to put when there's no db_id and therefore no engine: is null fine, a dash, "N/A", don't care... etc
- stylistically, i didn't know what to name the `id->engine` map. i went with `db_id_to_engine`. In clojure it would have been `id->engine` which is nice and pretty clear. The underscores and `to` leave a lot to be desired IMO.

small quibbles but interested

2020-10-27 21:12 UTC, kdoh requested changes
Looking pretty good. Mostly just a few style related things on the code side related to naming and so forth.

From the non code side, I left a note about possibly replacing the database ID with the name, I think the ID is basically not helpful. As far as your question about what to put if there's no relevant engine for a task, I think having nothing in the cell is ok.

2020-10-27 21:12 UTC, kdoh commented on frontend/src/metabase/admin/tasks/containers/TasksApp.jsx
> +    for (const db of databases) {
For what it's doing, I don't think it's worth moving this to an outside function or putting it inside `connect` or anything, but I might just leave a little note about what's being done here and why so it stands out a bit more and it's easier to grok on subsequent viewing.

2020-10-27 21:30 UTC, dpsutton commented on frontend/src/metabase/admin/tasks/containers/TasksApp.jsx
> +                    ? db_id_to_engine[task.db_id] || "Unknown engine"
@kdoh when i make this change is there some process to make sure this phrase gets slated for translation or is that automatically handled with tooling?

2020-10-28 15:11 UTC, dpsutton commented
@kdoh can you approve the changes i made in response to your comments? And i'm assuming the failing tests are general flakiness not due to my changes. I tried to rerun from failed but got the same failing result.

2020-10-28 19:29 UTC, kdoh approved these changes

2020-10-28 20:48 UTC, merged