Allow the Administrators group to sync
metabase/metabase pull request #13629
Opened 2020-10-29 19:18 UTC by robdaemon

Allows the Administrators group to sync from LDAP or SAML providers.
This was previously not allowed to avoid a user accidentally locking
themselves out of the admin group.

Fixes metabase/metabase-enterprise#445

2020-10-29 20:43 UTC, robdaemon commented
I'll rebase this once #13632 is merged

2020-11-05 00:18 UTC, dacort commented
Tested this locally and it worked - one question, though, will this now _remove_ users from the administrators group?

2020-11-05 00:42 UTC, robdaemon commented
@dacort that is a very good question and not one I know if we have a test for

2020-11-05 23:57 UTC, camsaul commented
Do we still want to merge this based on discussion in Slack today? Not sure what we decided WRT the behavior we want.

If we *do* merge this, I think we should definitely get a test around removing admins as well. We have to get the behavior here locked down 100% since admin access is pretty much the keys to the kingdom

2020-11-09 22:24 UTC, camsaul requested changes
We need a test for removing someone from the Admin group

2020-11-09 22:47 UTC, robdaemon commented
@camsaul okay added an explicit test for that

2020-11-09 23:33 UTC, camsaul approved these changes
LGTM

2020-11-10 00:37 UTC, merged