Add an error from SQLite
metabase/metabase pull request #14479
Opened 2021-01-21 22:02 UTC by paoliniluis

Added a few lines to make sure that users don't run on the IOError or using the /tmp dir inside the container for SQLite

https://github.com/metabase/metabase/issues/8084

2021-01-21 22:17 UTC, jeff-bruemmer requested changes
Thanks for including this, @paoliniluis! Just some small suggestions.

2021-01-21 22:17 UTC, jeff-bruemmer commented on docs/troubleshooting-guide/docker.md
> +- if you are running Metabase from the docker container, make sure that you are using the `/metabase.db` folder which is owned by the metabase user who is the one that runs the java process inside th
```suggestion
### Metabase can't write or read to/from a file or directory

#### How to detect this:

A message in the logs will clearly indicate an IOError/Permission denied from Java, or errors from SQLite with the `org.sqlite.core.NativeDB._open_utf8` form.

#### How to fix this:

Ensure that the user who is running Metabase has permission to read and write to the file or directory:

- If you are running Metabase as a JAR file in your local machine or server, check the user who is running the Java process.
- If you're running Metabase from the Docker container, make sure you're using the `/metabase.db` directory.
```

We may want to tell people how to check permissions.

2021-01-21 22:17 UTC, jeff-bruemmer commented on docs/troubleshooting-guide/running.md
> +
```suggestion
### Metabase can't read or write from a file or directory (IOError)

```

2021-01-22 00:06 UTC, ariya commented on docs/troubleshooting-guide/running.md
> +Check the issue [here](docker.md)
I suggest not using "here" as the link text (see [this old advice](https://www.w3.org/QA/Tips/noClickHere)).
If anything, "here" isn't a good search-able keyword.

2021-02-25 22:27 UTC, jeff-bruemmer approved these changes
Couple of suggestions.: including one mandatory suggestion that fixes a broken link. Thanks @paoliniluis!

2021-02-25 22:27 UTC, jeff-bruemmer commented on docs/troubleshooting-guide/running.md
> +If you find an error regarding file permissions when using Metabase, like not being able to read a SQLite database or a custom GeoJSON, we also have you covered in this section about [Metabase not be
```suggestion
If you find an error regarding file permissions, like Metabase being unable to read a SQLite database or a custom GeoJSON, check out the section "Metabase can't read to/from a file or directory" in our [Docker troubleshooting guide](docker.md).
```

2021-02-25 22:27 UTC, jeff-bruemmer commented on docs/troubleshooting-guide/docker.md
> +If you are running metabase from the jar file in any *nix (Unix like) operating system, in order to see which user is running metabase you have to open a terminal and type `ps -uA | grep metabase`.
```suggestion
If you're running Metabase from the JAR in any *nix (Unix like) operating system, in order to see which user is running Metabase, you have to open a terminal and type `ps -uA | grep metabase`.
```

2021-02-26 13:08 UTC, merged