Try bluer bg colors for pivot tables
metabase/metabase pull request #14556
Opened 2021-01-27 22:28 UTC by mazameli

This makes pivot tables look a bit more like our design mockups.

## Before

![image](https://user-images.githubusercontent.com/2223916/106062623-e30ebc80-60ab-11eb-96b4-9439095da5cf.png)

## After

![image](https://user-images.githubusercontent.com/2223916/106062638-e99d3400-60ab-11eb-8c31-2a3fb4dce735.png)

2021-01-28 13:33 UTC, kdoh commented
Did you test this out w/ dark mode on dashboards?

2021-01-28 16:14 UTC, mazameli commented
Hadn't, but it looks like this:

![image](https://user-images.githubusercontent.com/2223916/106166187-c2447680-6140-11eb-813c-c86929996579.png)

Detail:

![image](https://user-images.githubusercontent.com/2223916/106166110-ac36b600-6140-11eb-9701-03d5e4904a2e.png)

2021-01-28 18:59 UTC, kdoh requested changes
I'm not sure I'm 100% feeling that blue tint in dark mode but It's relatively minor all things considered. Do think we should simplify the implementation of this though and just do this inside of the pivot table file itself since these are truly one off CSS classes we wouldn't use anywhere else.

2021-01-28 18:59 UTC, kdoh commented on frontend/src/metabase/visualizations/visualizations/PivotTable.css
> +:local .PivotBGLight {
If possible I'd like to not keep creating new css modules code so we can eventually rip it out and get rid of yet another CSS solution. I'd just define two new variables in the Pivot Table file and use our `metabase/lib/color` library there to get this effect.

2021-01-28 22:40 UTC, mazameli commented
@kdoh, I've killed the separate CSS module and got the in-file CSS styles working.

2021-01-29 13:38 UTC, kdoh approved these changes

2021-01-29 14:41 UTC, merged