Adding the ability to sync admin groups in EE
metabase/metabase pull request #14993
Opened 2021-02-26 23:35 UTC by robdaemon

Adds a LDAP setting for EE to enable to LDAP Administrator group syncs.

2021-02-27 01:34 UTC, robdaemon commented on enterprise/backend/src/metabase_enterprise/enhancements/integrations/ldap.clj
> +  (deferred-tru "Sync the admin group?")
I'm sure @mazameli will have some comments on the wording of this stuff :)

2021-02-27 05:11 UTC, camsaul commented on test/metabase/integrations/common_test.clj
> +             (group-memberships user)))))
```suggestion
    (with-user-in-groups [group {:name (str ::group)}
                          user  [group]]
      (integrations.common/sync-group-memberships! user #{group} false)
      (is (= #{"All Users" ":metabase.integrations.common-test/group"}
             (group-memberships user))))
```

2021-02-27 05:13 UTC, camsaul commented on test/metabase/integrations/common_test.clj
> +             (group-memberships user)))))
```suggestion
(with-user-in-groups [group-1 {:name (str ::group-1)}
                          group-2 {:name (str ::group-2)}
                          user    [group-1]]
      (integrations.common/sync-group-memberships! user #{group-1 group-2} false)
      (is (= #{":metabase.integrations.common-test/group-1"
               ":metabase.integrations.common-test/group-2"
               "All Users"}
             (group-memberships user))))
```

2021-02-27 05:15 UTC, camsaul commented on test/metabase/integrations/common_test.clj
> +             (group-memberships user)))))
```suggestion
    (with-user-in-groups [group-1 {:name (str ::group-1)}
                          group-2 {:name (str ::group-2)}
                          user    [group-1]]
      (integrations.common/sync-group-memberships! user #{} false)
      (is (= #{"All Users"}
             (group-memberships user)))))
```

2021-02-27 05:17 UTC, camsaul commented on test/metabase/integrations/common_test.clj
> +             (group-memberships user)))))
```suggestion
    (with-user-in-groups [group-1 {:name (str ::group-1)}
                          group-2 {:name (str ::group-2)}
                          user    [group-1]]
      (integrations.common/sync-group-memberships! user #{group-2} false)
      (is (= #{":metabase.integrations.common-test/group-2" "All Users"}
             (group-memberships user)))))
```

2021-02-27 05:17 UTC, camsaul commented on test/metabase/integrations/common_test.clj
> +             (group-memberships user)))))
```suggestion
    (with-user-in-groups [group {:name (str ::group)}
                          user  [group]]
      (integrations.common/sync-group-memberships! user [Integer/MAX_VALUE group] false)
      (is (= #{"All Users" ":metabase.integrations.common-test/group"}
             (group-memberships user)))))
```

2021-02-27 05:18 UTC, camsaul commented on test/metabase/integrations/common_test.clj
> +                 (group-memberships user)))))
```suggestion
        (with-user-in-groups [user]
          (integrations.common/sync-group-memberships! user [(group/admin)] true)
          (is (= #{"Administrators" "All Users"}
                 (group-memberships user)))))
```

2021-02-27 05:18 UTC, camsaul commented on test/metabase/integrations/common_test.clj
> +                 (group-memberships user)))))))
```suggestion
        (with-user-in-groups [user [(group/admin)]]
          (integrations.common/sync-group-memberships! user [] true)
          (is (= #{"All Users"}
                 (group-memberships user)))))))
```

2021-02-27 05:19 UTC, camsaul commented on test/metabase/integrations/common_test.clj
> +               (group-memberships user)))))
```suggestion
      (with-user-in-groups [user]
        (integrations.common/sync-group-memberships! user [(group/admin)] false)
        (is (= #{"All Users"}
               (group-memberships user)))))
```

2021-02-27 05:19 UTC, camsaul commented on test/metabase/integrations/common_test.clj
> +               (group-memberships user)))))))
```suggestion
      (with-user-in-groups [user [(group/admin)]]
        (integrations.common/sync-group-memberships! user [] false)
        (is (= #{"Administrators" "All Users"}
               (group-memberships user)))))))
```

2021-02-27 05:20 UTC, camsaul commented on test/metabase/integrations/common_test.clj
> +             (group-memberships user)))))
```suggestion
    (with-user-in-groups [group-1 {:name (str ::group-1)}
                          group-2 {:name (str ::group-2)}
                          user    [group-1]]
      (integrations.common/sync-group-memberships! user #{} false)
      (is (= #{"All Users"}
             (group-memberships user)))))
```

2021-02-27 05:23 UTC, camsaul approved these changes

2021-02-27 05:23 UTC, camsaul commented on test/metabase/integrations/common_test.clj
> +               (group-memberships user)))))
```suggestion
        (with-user-in-groups [user]
          (integrations.common/sync-group-memberships! user [(group/admin)] true)
          (is (= #{"Administrators" "All Users"}
                 (group-memberships user)))))
```

2021-02-27 05:23 UTC, camsaul commented
You should mention the issue number in the description for cross-referencing purposes

2021-03-01 22:37 UTC, daltojohnso requested changes
Nice job, just two small things

2021-03-01 22:37 UTC, daltojohnso commented on frontend/src/metabase/admin/settings/components/SettingsLdapForm.jsx
> +    console.log("SettingsLdapForm.props", typeof this.props.settingValues);
```suggestion
```
let's get rid of this `console.log`

2021-03-01 22:37 UTC, daltojohnso commented on frontend/src/metabase/admin/settings/components/SettingsLdapForm.jsx
> +            ],
```suggestion
            ].filter(Boolean),
```
I don't see any filtering done in `SettingsBatchForm` so probably safest to add a `filter(Boolean)` here to remove the potentially falsy value from this array.

2021-03-01 23:30 UTC, robdaemon commented
@daltojohnso okay applied your fixes!

2021-03-01 23:38 UTC, daltojohnso approved these changes

2021-03-01 23:54 UTC, merged