Repro/issue 14985
metabase/metabase pull request #15018
Opened 2021-03-01 21:25 UTC by nemanjaglumac

###### Before submitting the PR, please make sure you do the following

- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [ ] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [ ] If there are changes to the backend codebase, run the backend tests with `lein test && lein lint && ./bin/reflection-linter`

- [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

2021-03-01 22:24 UTC, camsaul requested changes
The way this test is written, it should be a backend test. Cypress tests that just hit API endpoints to see if queries run successfully aren't adding anything the backend tests wouldn't cover

2021-03-01 22:43 UTC, camsaul approved these changes

2021-03-02 11:15 UTC, flamber approved these changes
From what I can see, this is a frontend issue. It never even touches `/api/dataset/pivot` and there's no log errors generated on commit `44ce694`.
If you create the question as Pivot Table and save, then it's possible to view the question, but after changing Data Model, and when the question becomes "dirty" (change filter etc), then the UI breaks.

2021-03-02 16:34 UTC, nemanjaglumac commented
> It never even touches `/api/dataset/pivot`

This test checks for that as well. It will first fail on pivot table not being recommended visualization, but even with that fixed, the next "hurdle" is waiting for pivot dataset. And only then can we move on to the final assertion.

2021-03-02 16:35 UTC, merged