Parallel frontend and drivers to accelerate building
metabase/metabase pull request #15819
Opened 2021-04-26 21:48 UTC by paoliniluis

Tried to recreate the CI process as much as possible with containers. building the frontend and drivers in parallel yield 15% faster build time

2021-04-29 15:33 UTC, ariya requested changes
If this is tweaking the build, `yarn.lock` should not be changed at all (because then we're updating dependencies).

2021-04-29 15:34 UTC, ariya commented on bin/docker/Dockerfile
> +=======
Looks like this is a merge conflict?

2021-05-03 19:57 UTC, paoliniluis commented
Sorry @ariya for the previous commit, it was a complete disaster. I force pushed one with the correct changes

2021-05-11 22:35 UTC, ariya approved these changes
LGTM

2021-05-12 00:42 UTC, merged