Custom expression: display only one error message
metabase/metabase pull request #15818
Opened 2021-04-26 19:56 UTC by ariya

It's terrifying to see lots of error messages when the expression is invalid or not completed yet. To overcome this, we display only one, the highest-priority and most friendly message. The rank is:

* tokenization error, e.g. mismatched parentheses
* type-checking error, e.g. incorrect count of function arguments
* syntax error (from the parser)

Steps to try:
1. Ask a question, Custom question
2. Sample Dataset, Orders table
3. Summarize, Custom Expression
4. Type `countif` and press Tab

**Before this PR**

![image](https://user-images.githubusercontent.com/7288/116142377-b1979400-a68e-11eb-99fa-a3e36e347cd7.png)

**After this PR**

![image](https://user-images.githubusercontent.com/7288/116142453-c6742780-a68e-11eb-9d7c-53a93731fa14.png)

2021-04-26 22:51 UTC, daltojohnso requested changes
one small thing

2021-04-26 22:51 UTC, daltojohnso commented on frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx
>          <div className="text-error mt1 mb1" style={{ whiteSpace: "pre-wrap" }}>
Don't forget a `key` 🙂

2021-04-26 22:51 UTC, daltojohnso approved these changes
Read that the wrong way... LGTM!

2021-04-27 08:45 UTC, flamber reviewed
I'm loosing track of which PRs are fixing what, but I can now input a completely invalid "function" and not getting any feedback
![image](https://user-images.githubusercontent.com/1447303/116212478-2927fa80-a745-11eb-9e3e-b84e5c2436cf.png)

Is this PR only for metrics? Because I'm still getting full errors with Custom Column `concat` or Filter `case`

2021-04-27 15:34 UTC, ariya commented
> I'm loosing track of which PRs are fixing what, but I can now input a completely invalid "function" and not getting any feedback

Ugh, thanks for catching this! There still seems to be an array vs non-array confusion in the code. Will fix it shortly.

2021-04-27 19:47 UTC, ariya commented
> Because I'm still getting full errors with Custom Column `concat` or Filter `case`

`concat` baffled my a little bit, but `case` isn't surprise cause it is still treated separately (from other regular functions). Perhaps the latter can only be solved with a bit more refactoring beyond the scope of this one.

2021-04-27 20:45 UTC, ariya commented
> I can now input a completely invalid "function" and not getting any feedback

Invalid reference should be taken care of now. The other cases need some more serious investigation/internal changes.

2021-04-27 20:45 UTC, merged