Add slugs to URLs to make them friendlier
metabase/metabase pull request #15989
Opened 2021-05-10 18:41 UTC by kulyk

This PR appends friendly entity name slugs to URLs. It can help people understand, reference, and consume content within the application. Updates links to databases, questions, dashboards, and collections. Admin links are out of scope here.

**Examples**

* `/question/1` would now be `/question/1-avg-orders-per-month`
* `/dashboard/33` would now be `/dashboard/33-customer-success-metrics`
* `/browse/4` would now be `/browse/4-app-db`
* `/collection/3` would now be `/collection/3-engineering-team`

**Note on IDs and slugs**

When parsing a URL, we just drop the slug and only use the ID, which means:

1. URLs without slugs will still work fine
2. People can just put anything instead of a slug, and it will work if an entity ID is valid. So if a question with ID 1 is actually called "Monthly Orders", but we try to visit `/question/1-whatever`, it will resolve to "Monthly Orders".

**Note about collection URLs**

* "Our analytics" is still `/collection/root`
* personal collection contains user's name (`/collection/1-bobby-tables-s-personal-collection`)
* other users' personal collections are also slugified (`collection/7-read-only-tableton-s-personal-collection`)

### To Verify

Just jump between any questions, dashboards, databases, or collections.

Closes #15765 
Closes #15256

2021-05-10 18:58 UTC, kulyk commented
One more thing. This PR also fixes a few small bugs I found while working on URLs

1. When opening the "Saved Questions" browse page (`/browse/-1337`), "Saved Questions" was missing in breadcrumbs
2. When duplicating a dashboard from the Collections page, a modal was not closing automatically as it usually does

2021-05-11 12:16 UTC, nemanjaglumac commented on frontend/src/metabase/collections/components/BulkActions.jsx
> +              handleCloseModal();
In that case, the repro should've been unskipped together with this commit, and there should be a clear reference to this issue in the PR description.

2021-05-11 12:26 UTC, nemanjaglumac requested changes
Left a few comments that need to be addressed.
Summary:
1. Please unskip related repros (for the small issues that you fixed along the way) and clearly reference them in the PR description
2. Don't create any new folders inside `frontend/test/metabase/scenarios`


Note: I have reviewed only test files so far.

2021-05-11 12:32 UTC, flamber reviewed
Seems to have problems with symbol-based languages:
Danish: `æbleflæsk` => `/dashboard/1-aebleflaesk`
Chinese: `培根` => `/dashboard/1-`
Russian: `бекон` => `/dashboard/1-bekon`
Japanese: `ベーコン` => `/dashboard/1-`

Though it's not doing any magic in `/reference` or the x-rays (probably less important) `/auto/...`

And interestingly it's sluggifying certain symbols - try giving a name like `$ & % | # " \\` => `/dashboard/1-dollar-and-percent-or-`

2021-05-11 13:15 UTC, kulyk commented on frontend/src/metabase/collections/components/BulkActions.jsx
> +              handleCloseModal();
Thanks! I turned on the test locally, but it fails for non-admin users. After the dashboard is duplicated, we assert the duplicated records is present in "Our analytics". However, the duplicate popup initially suggests saving a new dashboard to the user's personal collection. This behavior is fixed by #15999. I'll rebase the PR on `master` as soon as #15999 is merged and commit the unskipped repro

2021-05-11 13:33 UTC, kdoh reviewed
Overall looking good in my testing around the basic cases, although we'll want to deal with the internationalization situation @flamber found around symbols. 

Just for fun I created a few collections with Emoji only names and in every case it's appending `%3F%3F` to the id for the slug (e.x. `7-%3F%3F`). Doesn't seem to cause any issues (and it's not that important in the grand scheme of things) but just found it curious.

2021-05-11 15:52 UTC, brunobergher commented
This approach makes a ton of sense. It may not encompass all cases but this is is an optional/cosmetic feature in that links continue to be shareable, just carry less info. Also given the design, we can always iterate on this algorithm, since the slug doesn't affect the resolution of the URL.

👍 👍

2021-05-11 16:39 UTC, alxnddr reviewed
Overall looks great! 

I agree that symbols like `$` should be just removed instead of extrapolating.

Also, I noticed that we don't have it on the reference pages, is this intentional?
<img width="1004" alt="Screen Shot 2021-05-11 at 19 27 49" src="https://user-images.githubusercontent.com/14301985/117851915-7781e100-b28f-11eb-8285-590f070e4615.png">

And one more modal right after adding a database also lacks a slug
<img width="773" alt="Screen Shot 2021-05-11 at 19 23 11" src="https://user-images.githubusercontent.com/14301985/117851852-65a03e00-b28f-11eb-9835-4b291638a4dc.png">

2021-05-12 22:30 UTC, brunobergher approved these changes

2021-05-12 22:35 UTC, kulyk commented
@alxnddr the modal you mentioned is on `/admin` right? If so, admin URLs are out of scope here. The main goal of this project is to make it easier to reference and understand the content within the app. Admin URLs are not shared too often, so adding slugs here is not that necessary. Kudos for checking everything so accurately!

<img width="773" alt="117851852-65a03e00-b28f-11eb-9835-4b291638a4dc" src="https://user-images.githubusercontent.com/17258145/118052325-340c9d00-b38b-11eb-97d9-13fe4ee81eec.png">

2021-05-12 22:37 UTC, kulyk commented
@kdoh @flamber fixed slugs for symbol-based languages and edge cases like emojis, characters, etc.

@nemanjaglumac enabled the #15256 issue reference and linked at within the PR (via "Closes" keyword), also moved the new `urls` Cypress tests to `onboarding` group as you asked

Huge thanks for reviewing such a massive PR 🙏

2021-05-13 10:50 UTC, alxnddr approved these changes
Looks great 🥇

2021-05-13 18:44 UTC, nemanjaglumac commented on frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
> +                it("should be able to duplicate the dashboard without obstructions from the modal (metabase#15256)", () => {
Thank you for catching and fixing this!

2021-05-13 18:45 UTC, nemanjaglumac approved these changes
Looks good! 🎉

2021-05-14 08:33 UTC, merged

2021-06-16 13:36 UTC, JayJayM commented
Question for you @kulyk:
What happens if the name of the dashboard changes? Would the link break? 

Our users often bookmark dashboards URLs. We don't want to break that link if we change the name of a dashboard.

cc @brunobergher

2021-06-16 13:43 UTC, kulyk commented
Hi @JayJayM. If you change a question / dashboard / collection name, all their previous URLs will still be valid. As long as there is a correct id before a slug, the links should work