Fix missing time series footer
metabase/metabase pull request #16478
Opened 2021-06-07 22:32 UTC by ariya

This should fix #11183. It is a regression introduced in the refactoring in commit d32039aca (as part of PR #10655). It missed the proper property lookup for the query mode's footer.

Run the E2E tests:
```
yarn test-cypress-no-build --spec frontend/test/metabase/scenarios/question/new.cy.spec.js 
```

Steps to verify manually (copied here from #11183 for convenience):

1. Ask a question, Custom question
2. Sample Dataset, Orders table
3. Summarize by _Sum of Subtotal_, group by _Created At (Monthly)_
4. Visualize

**Before this PR**:

At the bottom, there isn't any drop-down to adjust for filter and granularity.

![image](https://user-images.githubusercontent.com/7288/121095528-54baed80-c7a5-11eb-8d38-9eeb395994a5.png)

**After this PR**:

At the bottom, there are two drop-down for filter and granuality.

![image](https://user-images.githubusercontent.com/7288/121095550-5dabbf00-c7a5-11eb-92d6-778ec8ceb459.png)

2021-06-08 00:15 UTC, gusaiani approved these changes
Works as described.
Nice fix, Ariya 👏👏👏👏👏 

🚀

2021-06-08 11:47 UTC, alxnddr requested changes
The part that is related to showing it looks good, however when I tried to change View from "All time" to any value it did not work with an error:
<img width="1427" alt="Screen Shot 2021-06-08 at 14 46 01" src="https://user-images.githubusercontent.com/14301985/121179311-41248b00-c868-11eb-99c7-9c845541d767.png">

2021-06-09 07:02 UTC, ariya commented
> The part that is related to showing it looks good, however when I tried to change View from "All time" to any value it did not work with an error:

Thanks for catching this @alxnddr ! Apparently there was another minor tweak in the filter query necessary to make this run. I've adjusted the code, please take another look.

2021-06-09 08:32 UTC, alxnddr approved these changes
Works great, thanks for fixing!

2021-06-09 14:19 UTC, flamber reviewed
It seems like it's breaking if you use a SQL as base instead of table or QB.
Can we try disabling "Something went wrong" to figure out if it would still work, but it's just some minor console error, which didn't cause the frontend reload (or UI breakage) in pre-39?

<details><summary>Something went wrong</summary>

```
    in ViewTitleHeader
    in div
    in Unknown
    in div
    in div
    in t
    in View
    in t
    in FitViewport
    in Unknown
    in Title[]
    in Title[Title[]]
    in QueryBuilder
    in Unknown
    in UserIsAuthenticated(Component)
    in Connect(UserIsAuthenticated(Component))
    in MetabaseIsSetup(Connect(UserIsAuthenticated(Component)))
    in Connect(MetabaseIsSetup(Connect(UserIsAuthenticated(Component))))
    in div
    in t
    in ScrollToTop
    in t
    in App
    in Title[App]
    in RouterContext
    in Router
    in t
    in DragDropContextProvider
    in a
```

</details>

2021-06-09 15:46 UTC, ariya commented
> It seems like it's breaking if you use a SQL as base instead of table or QB.

There's some inconsistency, see the filter pill "CREATED_AT Previous 24 Months" while the time-series footer still shows "All Time". But I think it's a separate issue.

![image](https://user-images.githubusercontent.com/7288/121386678-0c174780-c8ff-11eb-9090-f54d82aa8646.png)


This is what I did:
1. Ask a question, Native question, `SELECT * from ORDERS`, save as "Orders (in SQL)"
2. Ask a question, Custom question, Saved Questions, choose "Orders (in SQL)" and summarize on Sum of SUBTOTAL by CREATED AT:Month.
3. Use the time-series footer to View Previous 25 Months.

Note that this requires PR #16373 (to fix the subdimension binning).

> Can we try disabling "Something went wrong" to figure out if it would still work, but it's just some minor console error, which didn't cause the frontend reload (or UI breakage) in pre-39?

@daltojohnso I think you made this change. Is it possible to accommodate the above suggested tweak as well?

2021-06-09 22:28 UTC, ariya commented
> @ariya After you have changed the period in step 3, then try doing it again, or manually selecting "All time" again.

I stand corrected, this was precisely because of the (symptom of) inconsistency between the filter pill and the footer's filter widget. As soon as I tweaked it to stay in sync, now the footer's date picker should work for both SQL result and regular table.

![image](https://user-images.githubusercontent.com/7288/121437545-603e1e00-c937-11eb-8ad2-770e676eefe7.png)

2021-06-10 08:52 UTC, flamber approved these changes
@ariya Let's get her on the train :bullettrain_front:

2021-06-10 14:55 UTC, merged