Include more documentation on "Smart" column ordering
metabase/metabase pull request #16788
Opened 2021-06-27 15:55 UTC by johnbacon

In an attempt to discover how "smart" ordering worked and whether we wanted to use it, I had to find the relevant comment in the code itself:
https://github.com/metabase/metabase/blob/f3847cb8fd9025f20f39822a073a8c9bf7db3373/src/metabase/models/table.clj#L29-L30

Instead of this, we can add the same information to the documentation. Feel free to modify the copy as preferred.

2024-08-26 19:04 UTC, jeff-bruemmer approved these changes
Thanks, @johnbacon!

2024-08-26 19:33 UTC, camsaul requested changes
I was going to merge this but there are merge conflicts, can you fix them? 

The file you changed was moved to `/docs/data-modeling/metadata-editing.md`. Once you do that we can merge this

2024-08-30 13:33 UTC, johnbacon commented
@camsaul I no longer have a copy of Metabase on my local machine. I'd prefer it if you or your team could do this. Thank you!

2025-04-23 13:43 UTC, johnbacon commented
I'm going to go ahead and close this since it's been _checks watch_ four years without any forward movement.

2025-04-23 13:43 UTC, closed without merging