Avoid nested <a>
metabase/metabase pull request #16865
Opened 2021-07-02 07:11 UTC by ariya

There is no need to wrap the icon as a link, since each grid item (which encloses the icon) is already a link.

To give a try, just login and then open the browser console.

**Before this PR**
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
![image](https://user-images.githubusercontent.com/7288/124235399-06f68400-daca-11eb-815c-c09339b453d4.png)

**After this PR**
No such message.

2021-07-02 08:13 UTC, kulyk approved these changes

2021-07-02 08:37 UTC, nemanjaglumac requested changes
I don't think this was ever about grid items "A look at your ___ table".
![image](https://user-images.githubusercontent.com/31325167/124245207-0f79a980-db20-11eb-8279-b64750482b45.png)

This warning was shown regarding cards with references to the databases and their documentation.

![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/mXurDW0g/335744f2-d86b-455b-835f-3de0e7c0ee96.gif?source=viewer&v=7098736917fffc90ca461ec0c81e299e)

Notice how icon appears only on hover, and notice in the lower left corner that links are actually quite different.

1. card takes you to the browse page (`/browse/1`)
2. icon takes you to the reference page (`/reference/databases/1`)

We can easily confirm this in a console:
```javascript
document.querySelectorAll("a a")
```

Yields only one element:
```html
<a class="Link-sc-1fq3w5c-0 lqvkz tether-target tether-element-attached-top tether-element-attached-center tether-target-attached-bottom tether-target-attached-center" href="reference/databases/1">
  <svg class="Icon Icon-reference Icon-sc-1x67v3y-1 eiDYCT" viewBox="0 0 32 32" width="16" height="16" fill="currentcolor" role="img" aria-label="reference icon">
    <path d="M32 25h-5V7a2 2 0 0 0-2-2H7a2 2 0 1 0 0 4h16v23H4a4 4 0 0 1-4-4V6a6 6 0 0 1 6-6h22a4 4 0 0 1 4 4v21z">
    </path>
  </svg>
</a>
```

It's worth discussing with the "product" whether this alteration is an acceptable trade-off. Just keep in mind we have more UI patterns like this one on many other pages so I think it would make sense to abstract this pattern in a new component and apply it everywhere.

One of the possible solutions that would get rid of this warning but keep visual appearance of the card the same is to absolutely position the icon wrapped in a link, relative to the card.

2021-07-02 14:28 UTC, ariya commented
> Notice how icon appears only on hover, and notice in the lower left corner that links are actually quite different.

Good catch @nemanjaglumac! Apparently I missed that the two links are different.
I agree with you, the second link should be still preserved (and we just need to render it differently, without the nesting).

2022-04-27 13:57 UTC, nemanjaglumac commented
@ariya do you agree this should be closed? It's been a while.
If some new initiative around this appears, it can live in a separate PR.

2022-05-05 15:23 UTC, ariya commented
> @ariya do you agree this should be closed? It's been a while.

Agreed. Closing this for now.

2022-05-05 15:23 UTC, closed without merging