Optimize circleci file
metabase/metabase pull request #16890
Opened 2021-07-05 19:10 UTC by paoliniluis

This PR attempts to reduce the number of lines in the CircleCI config by using matrixes.

2021-07-06 18:30 UTC, nemanjaglumac requested changes
Please rebase on the latest`master`. There was at least one new e2e CI group added ("filters"), and we are now also running smoke tests as a "regular" e2e CI group.

2021-07-06 18:31 UTC, nemanjaglumac commented on .circleci/config.yml
> +              test: ["admin", "binning", "collections", "dashboard", "onboarding", "native", "question", "sharing", "visualizations"]
```suggestion
              test: ["admin", "binning", "collections", "dashboard", "filters", "onboarding", "native", "question", "sharing", "smoketests", "visualizations"]
```

2021-07-08 14:10 UTC, nemanjaglumac approved these changes
🎉

2021-07-08 15:08 UTC, paoliniluis commented
can't merge as it seems that there are some status reports that aren't completed due to the name changes, so if @camsaul can merge it would be great! (BTW: all steps green)

2021-07-17 00:08 UTC, paoliniluis commented
I'm going to close this as this would be implemented in @nemanjaglumac 's PR

2021-07-17 00:10 UTC, nemanjaglumac commented
Oh no, you shouldn't.
My PR deals oy with the Cypress changes.

We could still benefit from other matrices.

Please reopen and do your magic 🪄

2021-07-19 13:00 UTC, paoliniluis commented
oh! thanks, thought that it was imported in your PR, thanks!

2021-08-11 03:22 UTC, camsaul approved these changes
WFM 👍

2021-09-01 01:42 UTC, paoliniluis commented
This one too is ready to rumble, once we fix the "/api/login-history/" endpoint issues

2021-09-01 01:43 UTC, paoliniluis commented
@camsaul is the strategy of building just 1 time the drivers and reusing those for both uberjars OK?

2021-10-16 13:38 UTC, nemanjaglumac requested changes
This PR has been open for far too long.
On top of that, it's touching a lot of different areas and should be broken down into several individual smaller PRs for easier damage control.
- executors
- cache
- resource allocation
- updated requirements and version updates
- matrix refactor (simplification of long and repetitive code)

2021-12-27 19:52 UTC, paoliniluis commented
I'm closing this PR to separate it between:
- https://github.com/metabase/metabase/pull/19489
- https://github.com/metabase/metabase/pull/19490

using smaller resources needs some more investigation now that CircleCI supports seeing resources in the process

2021-12-27 19:52 UTC, closed without merging