Fix serialization dump error when there are no collections
metabase/metabase pull request #17388
Opened 2021-08-10 02:05 UTC by jeff303

Update `select-collections` to correctly handle the case where there are no collections

Adding new test that removes all collections, then ensures that dump works with no errors

2021-08-16 09:00 UTC, kidd approved these changes
lgtm :+1:

2021-08-16 10:22 UTC, flamber commented on src/metabase/models/metric.clj
> +  (db/delete! 'Dependency :model "Metric", :model_id id))
Segments are similar to Metrics, but none can be deleted - only retired/archived. Perhaps I'm not understanding what this code is supposed to do.

2021-08-16 11:13 UTC, flamber requested changes
Testing `ebc9dcd`

When I do a load without any mode-parameter (or mode=skip), then a lot of things stops working. And it still seems to be updating a dashboard, when I re-run the load without mode (#16954)

Without mode=update, it seems like it's breaking 14914 and 14909 and EE533 and EE532 and EE487 - and possibly other nested things?
Also seems to convert some GUI nested questions to SQL - haven't completely understood what's happening here.
Doesn't update the SQL correctly (`-- DUMMY QUERY FOR SERIALIZATION FIRST PASS INSERT`)

When using mode=update, then it seems like it's not correctly removing the existing cards on the dashboard, so all updated cards gets duplicated (I updated the text with "UPDATED" to the two first textboxes, and changed a question to reference another question, and then added a new card)
![image](https://user-images.githubusercontent.com/1447303/129554652-b434ecac-bbbd-4b2c-bb3b-432cd36d643d.png)

I'm just going to block this for now, since it has an approve.

2021-08-16 21:16 UTC, jeff303 commented on src/metabase/models/metric.clj
> +  (db/delete! 'Dependency :model "Metric", :model_id id))
There likely are other places.  However, the "hard delete" path only seems to be available via tests, which is what led to the error this is intended to fix.  The actual production workflow doesn't do a hard delete, just an archive.  So this change will only impact tests.

2021-08-16 21:32 UTC, jeff303 commented
I continue to be troubled at how difficult it is to "see" the same behavior from the backend tests, which are clearly belie the state of the functionality.  Once I narrow down on what is causing this latest round of discrepancies, it might be time to revamp the test suite yet again.

2021-08-17 15:49 UTC, jeff303 commented
OK, here is the fundamental issue at play, I believe.  It all comes down to the `identity-condition` as seen [here](https://github.com/metabase/metabase/blob/master/enterprise/backend/src/metabase_enterprise/serialization/upsert.clj#L32).  This is the set of fields that will be checked to determine if an entity loaded from the YAML is the same as an existing one in the target app DB.

If the load process reads an entity `A` from YAML, and does not find a "matching" target entity, then `A` will be inserted as a new record into the target DB.  This is true regardless of `--mode`, because the process considers it to be "new".  So in the case of `DashboardCard`, for instance, changing the text in a card will make the load process consider the YAML entity to be new.  That's because the text is technically under the `visualization_settings`, [which **is** part](https://github.com/metabase/metabase/blob/master/enterprise/backend/src/metabase_enterprise/serialization/upsert.clj#L40) of the `identity-condition`.

The `--mode` flag only controls what happens on an identity match (not a miss, which - as outlined above - will always result in an insert). If set to `:update` then the entity will be updated if any other of its fields (i.e. things not in the `identity-condition`) changed.  If not, then it will also be skipped.

One idea would be to simply remove `visualization_settings` from the `identity-condition` for `DashboardCard`, but I don't think that would work.  These text cards only _have_ difference there (the `:card-id` is `nil`).

What we could do is always drop all existing DashboardCard instances `DC` for a Dashboard `D`, if and only if mode is `:update` and we are about to update `D`.  Then all loaded YAML `DC` instances will simply replace everything that was there.  But we will need to think about whether this makes sense, and whether the idea should be extended to other entities.

2021-08-20 18:56 UTC, flamber approved these changes
Tested `3a3e5fb` - it works great :tada: - now :taco: :man_dancing: :wink: after a little lint :broom: 

We probably want to create an issue about https://github.com/metabase/metabase/pull/17388#issuecomment-900415001, so we can figure out how to handle dashcards better (removal, Textbox, multiple of the same card_id, ...)
Do you wanna do it @jeff303, since you got the best technical context?

2021-08-20 22:04 UTC, merged

2021-08-23 07:46 UTC, rlotun commented
@metabase-bot backport release-x.40.x