Display official collection tooltips
metabase/metabase pull request #17453
Opened 2021-08-13 19:16 UTC by kulyk

This PR adds a tooltip to any official collection's "ribbon" icon in Metabase.

### To Verify

1. Spin up Metabase Enterprise and sign in as admin
2. Go through #17125 steps, hover "ribbon" icons, you should see "Official collection" tooltips
3. Go through #17167 steps, hover "ribbon" icons, you should see "Belongs to an Official collection" tooltips

### Demo

<img width="566" alt="CleanShot 2021-08-13 at 22 12 04@2x" src="https://user-images.githubusercontent.com/17258145/129407732-57f490e6-0f80-4c97-a99e-af859330e6c8.png">

Slightly different text in the tooltip for a card from an official collection included in an unofficial dashboard:

![CleanShot 2021-08-13 at 22 13 15@2x](https://user-images.githubusercontent.com/17258145/129407893-7345b183-d252-476c-912e-1a79ad797e69.png)

2021-08-13 19:16 UTC, kulyk commented
@metabase-bot run visual tests

2021-08-13 19:39 UTC, kulyk commented
@metabase/frontend-developers anyone is experienced with `Tooltipify` and `Popover` land? If a component wrapped with `Tooltify` is close to the screen edge, the tooltip is placed too far from it, however, there is definitely some space to fit. Would appreciate an advice here

<img width="340" alt="CleanShot 2021-08-13 at 22 36 52@2x" src="https://user-images.githubusercontent.com/17258145/129410174-1c2c84d5-c5f3-4a37-a91b-f6b3156a9699.png">

2021-08-13 21:00 UTC, mazameli commented
In this context, we don't need a tooltip on the ribbon; we should just change the `Collection` subheading to `Official collection`:

![image](https://user-images.githubusercontent.com/2223916/129417940-28450cd4-cfd5-4233-b04c-80dad77011f4.png)

2021-08-13 21:26 UTC, mazameli requested changes
Just two changes: one on seach suggestions, on on search listings. Otherwise, looking great!

2021-08-16 12:44 UTC, kulyk commented
Thanks for your review @mazameli 🙏  Here's an update:

https://user-images.githubusercontent.com/17258145/129565659-80b3783a-6154-4b87-96fa-9ae11adb549c.mov

2021-08-17 02:27 UTC, daltojohnso commented
@kulyk -- check out what I'm doing in `ModerationReviewBanner.jsx`. At the top of the page I've defined a `TOOLTIP_X_OFFSET` based on the icon `size` and I'm passing that as the `targetOffsetX` prop on `Tooltip`.

2021-08-17 17:12 UTC, kulyk commented
@daltojohnso the offset prop worked like a charm! Thank you

2021-08-17 17:13 UTC, kulyk commented
@mazameli could you please give this PR one more look?

2021-08-17 17:13 UTC, kulyk commented
Ended up covering ItemPicker with unit tests to pass the coverage threshold -- EE features are not easy to mock for now

2021-08-17 17:19 UTC, daltojohnso approved these changes
looks good!

2021-08-17 17:19 UTC, daltojohnso commented on frontend/src/metabase/collections/containers/CollectionSidebar/Collections/CollectionsList/CollectionsList.unit.spec.js
> +    describe("EE", () => {
nice setup here with OSS/EE. we should definitely try to think of ways to make this easier

2021-08-18 16:33 UTC, mazameli approved these changes
Looks good!

2021-08-18 16:41 UTC, merged