When creating database, pass syncing schedule options to api
metabase/metabase pull request #17639
Opened 2021-08-27 16:18 UTC by gusaiani

Fixes #17450

## Issue we're fixing

Setting up a new database and specifying the "This is a large database ...", the choice is not persisted to backend and default sync+scan settings are used.

## How to Test

1. Admin > Databases > create new database
2. Enable "This is a large database, so let me choose when Metabase syncs and scans" - click Next

![image](https://user-images.githubusercontent.com/1447303/129395064-c1d10f13-b48c-4858-bfbd-d416586fbfe6.png)

3. Do not make any change, when it shows the Scheduling-page - just click Save

![image](https://user-images.githubusercontent.com/1447303/129395228-2ea7210c-3937-432c-8a1b-38bfd797e3e1.png)

4. Now go to the newly created database and click the Scheduling-tab - and it has saved what was shown before.

![image](https://user-images.githubusercontent.com/380816/131162069-1746d87d-b091-412e-bef0-0cd96c8dbbce.png)

2021-08-27 22:18 UTC, daltojohnso requested changes

2021-08-28 11:59 UTC, flamber reviewed
It only saves scanning correctly - the sync uses the default (hourly) instead of what was shown (daily)
![image](https://user-images.githubusercontent.com/1447303/131217113-1e3dff72-3a18-4dbe-925d-13f588660d84.png)

2021-08-30 11:46 UTC, gusaiani commented on frontend/src/metabase/admin/databases/database.js
>  export const createDatabase = function(database) {
Yup this is confusing to me indeed. 

Once again, here I tried to go with a minimal "cherry-pickable" change and failed (see below).

Will work on it more in its structure.

2021-08-30 15:09 UTC, gusaiani commented on frontend/src/metabase/admin/databases/database.js
>  export const createDatabase = function(database) {
@daltojohnso, there doesn't seem to be a trivial way to merge what happens in `proceedWithDbCreation` and in `createDatabase`.

After having learned more, the separation of these functions still makes sense to me. It ensures early that the db is ok, even if there will be scheduling and syncing details added as a second step.

But it was possible to separate the customization we do into their own functions and even a file that is now unit-tested.

2021-08-30 15:11 UTC, gusaiani commented
> It only saves scanning correctly - the sync uses the default (hourly) instead of what was shown (daily)

@flamber, thank you for pointing that out.

Seems like now it's functionally covered, please let me know if not.

2021-08-30 16:11 UTC, flamber reviewed
Tested `cc0774d` - seems to be working exactly like you expect :tada:

2021-08-30 18:38 UTC, daltojohnso approved these changes

2021-08-30 18:38 UTC, daltojohnso commented on frontend/src/metabase/admin/databases/database.js
>  export const createDatabase = function(database) {
thanks for poking at it some more

2021-08-30 18:52 UTC, merged

2021-08-30 19:00 UTC, flamber commented
@gusaiani Is this back-portable, or for 41?

2021-08-30 19:13 UTC, gusaiani commented
@flamber It's back-portable, now I gotta figure out the latest steps to do it.
Happy to learn them from you if you just know by heart.

2021-08-30 19:45 UTC, flamber commented
If you added `backport` label before merge, then it would automagically do it.

Otherwise you can write a comment only containing this `@metabase-bot backport release-x.40.x`

2021-08-30 19:56 UTC, gusaiani commented
@flamber Thank you for the tip.

I used JS optional chaining in this PR. (check against someObject?.someKey, the ? there…)
To my surprise, this feature is not in branch 40.

Opened a manual PR with a simple adaptation: https://github.com/metabase/metabase/pull/17671