Edit Permissions help text
metabase/metabase pull request #17741
Opened 2021-09-02 22:08 UTC by nemanjaglumac

### Status
PENDING REVIEW

### What does this PR accomplish?
- Edits the copy of permissions sidebar help text according to @mazameli 's suggestions in #17739 
- Closes #17739

2021-09-02 23:53 UTC, mazameli commented on frontend/src/metabase/admin/permissions/components/DataPermissionsHelp/DataPermissionsHelp.jsx
> +      <p>{t`Unless a user group has “block” for a given database or table, they’ll be able to view any saved questions based on that data if they have access to the collection it’s saved in.`}</p>
```suggestion
      <p>{t`Unless a user group's access for a given database is set to “block," they’ll be able to view any saved question based on that data if they have access to the collection it’s saved in.`}</p>
```

2021-09-02 23:55 UTC, mazameli requested changes
Just one small change. Thanks for doing this!

2021-09-03 08:50 UTC, nemanjaglumac commented on frontend/src/metabase/admin/permissions/components/DataPermissionsHelp/DataPermissionsHelp.jsx
> +      <p>{t`Unless a user group has “block” for a given database or table, they’ll be able to view any saved questions based on that data if they have access to the collection it’s saved in.`}</p>
Done :)

2021-09-03 11:16 UTC, alxnddr approved these changes
Thanks for taking care of it

2021-09-03 15:10 UTC, mazameli approved these changes

2021-09-03 15:35 UTC, merged