Attempt to fix #17751: filter widget input value overflowing
metabase/metabase pull request #17761
Opened 2021-09-03 21:43 UTC by nemanjaglumac

### Status
PENDING REVIEW

### What does this PR accomplish?
- Attempts to fix #17751 by constraining `FieldValuesWidget`'s container's max-width to 100% of its parent.

### Additional info:
While this seems to work for this particular scenario, I am not sure if it has any unforeseen consequences in some other parts of the app.  @gusaiani you're probably the most familiar with this component and the popover by now. Can you please take a look?

![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/JruxOxOv/830f50d9-03de-4e70-aa5b-0aa3fd24156a.gif?source=viewer&v=99c736be7374170fb0dcb8a56c4be1f2)

2021-09-03 22:17 UTC, gusaiani approved these changes
Yup, looks great. 

Given the nature of what's in Popover, there _might_ be regressions elsewhere.

One thing we can do is add visual regression tests.
For example, adding one visual test to cover this very filter here, so other future PRs don't regress this.
An idea for a separate PR or, if you prefer, this PR.

Approved nonetheless.

2021-09-04 09:57 UTC, flamber requested changes
Seems like the problem is not with that `div`, but the `ul`'s `min-width`
`Rediculous extremely long value that totally hides the X-button after reopening the filter widget Popover`
![image](https://user-images.githubusercontent.com/1447303/132090471-bf3ba220-78e7-47e0-a205-cbf7386e932f.png)
https://github.com/metabase/metabase/blob/802a8a7a3f4a77695a7489a2ee1ea6537a3b5ea2/frontend/src/metabase/components/TokenField.jsx#L603

2021-09-07 21:25 UTC, nemanjaglumac commented
@flamber updated the code to reflect your findings, rebased and unskipped the repro.

To make sure this works, I tried with the whole paragraph for the filter. And while it overflows the whole page (that's a separate issue, imo), it works as expected inside the popover.
![ ](https://p58.f1.n0.cdn.getcloudapp.com/items/P8uGQLoQ/efb16369-f376-4663-85c0-943aa04a43b6.gif?v=11854a13a402aa879250059a60f0c689)

@daltojohnso you are familiar with popover. Please make sure this solution doesn't have any unforeseen effects/consequences anywhere else in the app.

2021-09-08 09:27 UTC, flamber approved these changes

2021-09-08 17:47 UTC, daltojohnso approved these changes

2021-09-08 17:48 UTC, merged