Fix saving chart with custom expressions only retains first 2 data series
metabase/metabase pull request #17855
Opened 2021-09-13 10:22 UTC by pawit-metabase

See https://github.com/metabase/metabase/issues/15882#issuecomment-917984049 for detailed explanation.

Fixes #15882

2021-09-13 10:42 UTC, flamber reviewed
Awesome :tada: - now works on old questions.

2021-09-15 01:36 UTC, camsaul requested changes
Can we have a test for this? We should add a `normalize-visualization-settings-test` in the test namespace

2021-09-15 03:47 UTC, pawit-metabase commented
Test added (and verified that it failed before the change)

2021-09-28 03:24 UTC, camsaul approved these changes

2021-09-28 03:26 UTC, merged