When fetching Field also fetch its associated human_readable_field_id
metabase/metabase pull request #17958
Opened 2021-09-17 21:20 UTC by daltojohnso

Fixes #12904

We aren't fetching the mapped field when initializing the native query builder. If you've previously done something to fetch and cache the proper field value (like going into Admin > Data Model > Sample Dataset and then back to the query builder) you'll see the correct behavior, but if not then you won't.

The simplest fix for this is... gross. This function, `fetchField` is deprecated, but it is what is used when fetching fields for parameter widgets. It's only used for this specific purpose, however, so we can pretty safely fix this specific bug by fetching the mapped field after fetching the initial field.

Obviously, there's probably a cleaner/better fix for this out there, but for `ParameterValueWidget` it entails a lot of refactoring.

Recording of the fix:

https://user-images.githubusercontent.com/13057258/133854852-a29c88d7-7b28-4013-b5c3-b6edbcc4f271.mov

2021-09-18 14:26 UTC, flamber requested changes
See comment below.

~~Just blocking this.
It actually works great for Search, but if you set it to List, then it only adds the remapped value (string) in the filter (id). You'll get a query data conversion error.
I'm guessing whatever would fix that, would also fix issue 13235~~

https://user-images.githubusercontent.com/1447303/133892111-2486c50a-2946-4aa1-9d4a-6be104aa0667.mp4

2021-09-18 14:34 UTC, flamber approved these changes
Wait, that is also happening on existing release. Sorry. These state issues are tricky, and browser refresh isn't always enough, sometimes a new window/tab is needed.

Seems like issue 13235 is actually a regression between 0.31 and 0.36

2021-09-20 17:46 UTC, alxnddr reviewed
Wdyt about adding a test?

2021-09-21 20:18 UTC, alxnddr approved these changes
👍

2021-09-21 22:39 UTC, merged