Do not unset filter values with click behavior
metabase/metabase pull request #18025
Opened 2021-09-23 11:47 UTC by ranquild

Fixes https://github.com/metabase/metabase/issues/16304

2021-09-23 12:43 UTC, ranquild commented
@mazameli Could you also have a look at https://github.com/metabase/metabase/pull/18025 and this fix? I'm not sure if the new behavior was approved by anyone.

2021-09-23 16:48 UTC, gusaiani approved these changes
LGTM.

I haven't used click behaviors enough to anticipate possible side effects of this change.

Maybe a more QA-focused check around the fix might be a good thing.

2021-09-23 17:52 UTC, flamber reviewed
Looking at the code, it seems like it was the intended behavior to unset.

2021-09-23 17:53 UTC, ranquild commented
> Looking at the code, it seems like it was the intended behavior to unset.

Yep that bothers me as well.

2021-09-23 19:06 UTC, mazameli requested changes
I had a suspicion about what was going on here that proved correct. The old behavior was due to an exception centered around visualizations like region maps or bar charts, where you _want_ the filter to be reset when you click on the selected item in the visualization again. It allows for a sort of toggling behavior. Here's how it worked (note the region map's behavior specifically):

![old-behavior](https://user-images.githubusercontent.com/2223916/134568291-c7e28df2-21ce-4094-be67-405aec4fc621.gif)

Here's the new behavior. I agree that this PR corrects the behavior for _tables_, but I think it degrades the behavior for other visualizations.

![new-behavior](https://user-images.githubusercontent.com/2223916/134568358-9077c27a-47fa-45f7-a7a2-2e08f56d8497.gif)

Could we restrict this fix to affect only Tables and Pivot Tables? @flamber, let me know if you disagree with what I'm saying here.

2021-09-23 19:14 UTC, flamber commented
@mazameli Totally makes sense. I'm almost more inclined to not do anything and see if the issue gets traction, since have some conditional behaviors will require it to be documented too.

2021-09-23 19:38 UTC, ranquild commented
Could we post this explanation to the original issue?

2021-09-24 21:52 UTC, mazameli commented
@ranquild @flamber I've commented on #16304. I suggest closing this PR, and as @flamber suggested, waiting and seeing if anyone else cares or not about #16304 in the future.

2021-09-27 10:07 UTC, closed without merging