Custom expression editor: use icons to distinguish the suggestions
metabase/metabase pull request #18744
Opened 2021-10-28 19:29 UTC by ariya

Still WIP.

How to try:
1. Ask a question, Custom question
2. Sample Dataset, Product table
3. Filter, Custom expression, and type `c`

**Before this PR**

The suggestions are separated by their types, e.g. `FIELDS`, `FUNCTIONS`, and `SEGMENTS` in the following screenshot.

![image](https://user-images.githubusercontent.com/7288/140586168-d9f10dea-c6d7-40ea-b03f-f79628aef413.png)
**After this PR**

There is no explicit separator. Each suggestion has a corresponding icon indicating its type.

![image](https://user-images.githubusercontent.com/7288/141030775-9d27af33-bcbf-43ff-802d-b3c350724ca9.png)

2021-11-08 10:44 UTC, flamber approved these changes
Wow - this is insanely useful compared to currently, where I have to guess some column types:
![image](https://user-images.githubusercontent.com/1447303/140727327-dad8bdfc-f71b-49a3-86b4-8e502dd9a39f.png)

Wonder if #18537 is even needed anymore, now that it's possible to just click the field an see it's a Segment. Alternatively, using icons here (might be way too ugly/distracting)?

2021-11-08 14:10 UTC, ariya commented on frontend/src/metabase/icon_paths.ts
> +  function:
Many thanks to @mazameli for this icon!

2021-11-08 14:11 UTC, ariya commented
> Wonder if #18537 is even needed anymore, now that it's possible to just click the field an see it's a Segment. Alternatively, using icons here (might be way too ugly/distracting)?

Icons might be too distracting indeed, but IMO colors will be still good to have (and yes, the colors in the editor need to be consistent with the suggestions, e.g. purple for segments).

2021-11-08 19:20 UTC, mazameli requested changes
I only have 1 real change request: like the mocks show, I'd like ot have the rest of a suggestion's text be set to `color: text-medium` to further contrast it from the portion of the suggestion's text that matches what the user has typed so far:

![image](https://user-images.githubusercontent.com/2223916/140803671-ee149582-98d7-47a3-94b4-32d312a264ac.png)

Additionally, my thought had been to put functions above columns, whereas I see in the branch that this is the opposite. I don't have strong conviction on this point, however, and would love to hear @flamber's, @ariya's, and perhaps @ukritw's thoughts on the order of suggestions. (The only thing I'm pretty sure of is that "Metrics" and "Segments" in their current form aren't super useful, and I'm glad that we've put them at the bottom.)

![image](https://user-images.githubusercontent.com/2223916/140804026-8dbe948f-3417-4092-8dc5-0ebffd6f1556.png)

Also, just to say it: I noticed that the function icon is colored red rather than blue like in the mockups, but I kind of prefer the red now that I'm seeing it — but was just curious if that was an intentional choice.

2021-11-08 19:36 UTC, flamber commented
It might be a relic with the order, but something tells me that you're inputting more Fields than Functions, so it makes sense that Fields are first, though from a logical point, Functions should probably be first.

I think I've generally been annoyed no matter what, since when I have an empty expression, then I usually need a function, but inside a function I usually need a field. But it would be even worse if we tried to do some auto-guess, so consistency wins for me.

2021-11-08 19:45 UTC, ariya commented
> I only have 1 real change request: like the mocks show, I'd like ot have the rest of a suggestion's text be set to `color: text-medium` to further contrast it from the portion of the suggestion's text that matches what the user has typed so far:

That makes sense, looks like I forgot to tweak the text color.


> Additionally, my thought had been to put functions above columns, whereas I see in the branch that this is the opposite. I don't have strong conviction on this point, however, and would love to hear @flamber's, @ariya's, and perhaps @ukritw's thoughts on the order of suggestions. (The only thing I'm pretty sure of is that "Metrics" and "Segments" in their current form aren't super useful, and I'm glad that we've put them at the bottom.)

I don't have any strong preference here, I defer it to others to offer some more meaningful suggestions.

> Also, just to say it: I noticed that the function icon is colored red rather than blue like in the mockups, but I kind of prefer the red now that I'm seeing it — but was just curious if that was an intentional choice.

It was an accident, I think I picked the wrong accent.
Blue does make sense since that is the color used for the syntax highlighting (once that function name appears in the editor), so we should strive for consistency here.

2021-11-09 05:30 UTC, ariya commented
@mazameli Please check again, I've made some color tweaks.

2021-11-09 07:56 UTC, ukritw commented
I have no strong preference in the ordering either. Like @flamber said, consistency is key.

2021-11-09 18:59 UTC, mazameli commented
This is looking almost there to me. The icons in the field suggestions though are looking a bit small, particularly the Category `Aa` and the Number `#` ones. I specced them to be 14px, whereas I think they're 10px in the branch.

![image](https://user-images.githubusercontent.com/2223916/140987228-9f7ce2e5-3bbb-482c-87d6-b008daa35f69.png)

Here's the design mockup for comparison:

![image](https://user-images.githubusercontent.com/2223916/140987200-87dde77b-e25b-4b62-b72f-700101fda4da.png)

2021-11-09 19:19 UTC, ariya commented
> This is looking almost there to me. The icons in the field suggestions though are looking a bit small, particularly the Category `Aa` and the Number `#` ones. I specced them to be 14px, whereas I think they're 10px in the branch.

Good catch @mazameli!
I've changed it to 14px, but now we have some (vertical) alignment issue. Can I get some CSS help on this?

![image](https://user-images.githubusercontent.com/7288/140990240-a8ffbd46-52ee-4b38-ae71-84089a350673.png)

2021-11-09 20:12 UTC, mazameli approved these changes

2021-11-09 20:13 UTC, mazameli commented
@ariya I pushed a little CSS fix:

![image](https://user-images.githubusercontent.com/2223916/140997562-4312b2d6-9d1e-44ee-8b03-8851ad91c7a8.png)

2021-11-10 01:04 UTC, ariya commented
> I have no strong preference in the ordering either. Like @flamber said, consistency is key.

A minor consistency argument in favor of listing the functions first is making the the list a bit more _**predictable**_, e.g. there are only 3 functions that start with an `s` (sqrt, startsWith, substring), whereas the fields and others vary significantly depending on the table etc.

2021-11-10 01:12 UTC, akiselev commented
> > I have no strong preference in the ordering either. Like @flamber said, consistency is key.
> 
> A minor consistency argument in favor of listing the functions first is making the the list a bit more _**predictable**_, e.g. there are only 3 functions that start with an `s` (sqrt, startsWith, substring), whereas the fields and others vary significantly depending on the table etc.

How is autocomplete used the most and which scenario are we optimizing for? Is it for discoverability/mental unblocking the average user as they explore data or is it used by power users to autocomplete long names using muscle memory?

2021-11-10 04:29 UTC, ariya commented
> How is autocomplete used the most and which scenario are we optimizing for? Is it for discoverability/mental unblocking the average user as they explore data or is it used by power users to autocomplete long names using muscle memory?

@flamber and @mazameli  will know better, though I suspect that there won't be a lot of non-power users dropping to the custom expression editor since they can already perform a number of complex filtering and aggregation via the simpler UI.

2021-11-10 04:29 UTC, merged