Move initial user setup from hash data to env var plus token
metabase/metabase pull request #18763
Opened 2021-10-29 17:47 UTC by john-metabase

Using most of the code from the base64 approach, I tried using the env var `MB_USER_DEFAULTS` for supplying initial user details at deployment time. This avoids putting any user data in URLs. The `/setup#...` URL still uses the hash but the value should just be the configured token rather than the full encoded data.

The new `/api/setup/user_defaults` endpoint is authenticated by the `token` parameter which must match the configured value (note: this is completely separate from the runtime-generated setup token).

The structure of the env var JSON is exactly like the JSON in #18471 with the addition of a top-level `token` key, e.g.:

```
{
  user: {
    first_name: "",
    last_name: "",
    email: "",
    site_name: ""
  },
  token: "..."
}
```

2021-11-01 15:04 UTC, noahmoss reviewed
Backend parts lgtm with a couple non-blocking comments. I'll let @ranquild sign off on the frontend changes.

2021-11-01 15:06 UTC, ranquild commented on frontend/src/metabase/setup/components/Setup.jsx
> +    await this.setDefaultDetails();
trackStepSeen relies on the current `props`. Could you move `await this.setDefaultDetails` below it?

2021-11-01 15:06 UTC, ranquild commented on frontend/src/metabase/setup/components/Setup.jsx
> +    if (0 < token.length) {
nit: `if (token) {`

2021-11-01 15:08 UTC, ranquild requested changes
Waiting for `trackStepSeen` fix, apart from that lgtm

2021-11-15 15:31 UTC, ranquild approved these changes

2021-11-15 16:57 UTC, merged

2021-11-15 16:57 UTC, ranquild commented
Epic https://github.com/metabase/metabase/pull/18471