embed: call postMessage to all origins
metabase/metabase pull request #18838
Opened 2021-11-04 10:51 UTC by pawit-metabase

`embedding-app-origin` may contain multiple origins but postMessage supports only a single origin, so we need to call postMessage for each origin. The browser will quietly drop messages for other origins.

Fixes #12069

2021-11-04 16:45 UTC, daltojohnso requested changes

2021-11-04 16:45 UTC, daltojohnso commented on frontend/src/metabase/lib/embed.js
> +  const origins = MetabaseSettings.get("embedding-app-origin").split(" ");
I see in `public_settings.clj` that `embedding-app-origin` has no default value, so let's make sure we have a string here by doing something like:
```
const origins = (MetabaseSettings.get("embedding-app-origin") || "").split(" ");
```

2021-11-04 18:29 UTC, flamber reviewed
So while this would work, it would also litter the browser console with errors:
`Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://another-url.test’) does not match the recipient window’s origin (‘https://app.example.com’).`

2021-11-08 03:00 UTC, pawit-metabase commented
I was trying to avoid having to do a manual check but having that error there isn't good either. Plus `postMessage` doesn't support the `https://*.subdomain.dom` syntax.

Maybe we should just use `*` which should be relatively safe because we have iframe ancestor policy and we're not sending sensitive information.

2021-11-08 17:46 UTC, daltojohnso approved these changes

2021-11-09 02:07 UTC, merged