Add "Datasets" search filter
metabase/metabase pull request #18878
Opened 2021-11-05 17:25 UTC by kulyk

Adds "Datasets" search filter to `/search` page and renames "Tables" filter into "Raw Tables"

### To Verify

1. Follow the steps from #18702 to create a dataset
2. Use the navbar search to find a dataset
3. While being focused on the search input, hit "Enter"
4. You should appear on the `/search` page. You should see result filters on the right side
5. Click "Datasets" in the list of filters, you should only see datasets

### Demo

**Before**

<img width="1054" alt="CleanShot 2021-11-05 at 19 18 38@2x" src="https://user-images.githubusercontent.com/17258145/140552760-6a253fdc-3683-498d-80aa-f54361d07daa.png">

**After**

<img width="1090" alt="CleanShot 2021-11-05 at 19 19 42@2x" src="https://user-images.githubusercontent.com/17258145/140552785-5a992194-3d62-4033-aa07-d6f465bfa5ab.png">

2021-11-05 17:42 UTC, alxnddr approved these changes
Nice! We also need to have datasets in recents, currently they are rendered as questions:
<img width="594" alt="Screen Shot 2021-11-05 at 21 41 09" src="https://user-images.githubusercontent.com/14301985/140554840-7a7bbf8e-616d-40a8-b2eb-4bfce310c4e9.png">

2021-11-05 17:44 UTC, kulyk commented
> Nice! We also need to have datasets in recents, currently they are rendered as questions: <img alt="Screen Shot 2021-11-05 at 21 41 09" width="594" src="https://user-images.githubusercontent.com/14301985/140554840-7a7bbf8e-616d-40a8-b2eb-4bfce310c4e9.png">

Sharp eye! Thank you

2021-11-05 20:36 UTC, mazameli requested changes
Functionality seems to work great.

A very nitpicky thing I noticed was that in the sidebar, the datasets icon should be 1px to the left, and the `Datasets` string looks like it should be 2px to the left.

![image](https://user-images.githubusercontent.com/2223916/140575307-3a0d23c9-bd89-4936-8aca-1f61c8e7d934.png)

2021-11-08 18:05 UTC, mazameli approved these changes

2021-11-08 18:13 UTC, merged