Update question header breadcrumbs
metabase/metabase pull request #18903
Opened 2021-11-08 17:30 UTC by kulyk

Updates question header breadcrumbs. Most noticeable changes:

* there is a database icon in simple mode's breadcrumbs. Later, for questions built on datasets, we're going to display a dataset icon there
* the dot divider is replaced with a slash to mirror data sources nesting (e.g. database / schema / table)
* font size in simple mode is increased and is now the same as saved question's title
* breadcrumb colors are changed from `text-medium` to `text-light`
* breadcrumb links have hover effects

### Scenarios

<details>
<summary>Simple Question</summary>

**Before**

<img width="259" alt="table view : adhoc before" src="https://user-images.githubusercontent.com/17258145/140788793-7411ae71-c95f-425c-90ea-42ecf892aa01.png">

**After**

<img width="279" alt="table view : adhoc" src="https://user-images.githubusercontent.com/17258145/140788810-198fcb3a-c810-45e1-92e3-ae9a965baa0a.png">

</details>

<details>
<summary>Simple Question (with schema)</summary>

**Before**
<img width="286" alt="table view with schema before" src="https://user-images.githubusercontent.com/17258145/140789327-d375ecae-241b-491a-92df-5a1fdc6b482a.png">

**After**
<img width="312" alt="table view (with schema)" src="https://user-images.githubusercontent.com/17258145/140789335-7eb08720-fd6e-40e5-9062-cdbf80542749.png">

</details>

<details>
<summary>Saved Question (with schema)</summary>

**Before**

<img width="390" alt="saved with schema before" src="https://user-images.githubusercontent.com/17258145/140789114-30578c60-48c0-4894-bebd-5b712811f76f.png">

**After**

<img width="365" alt="saved with schema" src="https://user-images.githubusercontent.com/17258145/140789110-02ad49c8-0e2b-4dd0-a59f-f8b10e630e12.png">

</details>

<details>
<summary>Native Saved Question</summary>

**Before**

<img width="307" alt="native-saved-before" src="https://user-images.githubusercontent.com/17258145/140789188-fcb53070-7fc5-453a-8519-ad41338d6f7a.png">

**After**

<img width="302" alt="native-saved" src="https://user-images.githubusercontent.com/17258145/140789207-1a110b31-ee32-437a-8387-434d95bbfd5e.png">

</details>

<details>
<summary>Using saved question as a data source</summary>

**Before**

<img width="430" alt="based-on-question-before" src="https://user-images.githubusercontent.com/17258145/140789432-4f8151e0-8f09-4488-95bf-186e7b1f8482.png">

**After**

<img width="415" alt="based-on-question" src="https://user-images.githubusercontent.com/17258145/140789445-e51ad9fc-ec6f-49f2-ac62-124a4109a470.png">

</details>

<details>
<summary>Question started from another question</summary>

**Before**

<img width="359" alt="from-question-filters-expanded-before" src="https://user-images.githubusercontent.com/17258145/140789526-e027a11d-ca64-4e15-9078-3d53a512b61e.png">

<img width="413" alt="from-question-filters-collapsed-before" src="https://user-images.githubusercontent.com/17258145/140789534-22c4a322-0de3-41c7-9d8b-e6aba58ce60d.png">

**After**

<img width="400" alt="from-question-filters-expanded" src="https://user-images.githubusercontent.com/17258145/140789556-ce11d569-d153-466a-80cd-eeffbca76b97.png">

<img width="460" alt="from-question-filters-collapsed" src="https://user-images.githubusercontent.com/17258145/140789563-309a9824-ca27-472b-9831-455dd5928ed9.png">

</details>

<details>
<summary>Detail View</summary>

**Before**

Note: fixes missing object PK in breadcrumbs

<img width="259" alt="detail view before" src="https://user-images.githubusercontent.com/17258145/140789623-d4d8b300-8de8-4ce0-ae9d-f6ae789e5d41.png">

**After**

<img width="311" alt="detail view" src="https://user-images.githubusercontent.com/17258145/140789639-1b887acd-5af0-4120-ae92-081beb387db7.png">

</details>

2021-11-08 18:00 UTC, kulyk commented
@metabase-bot run visual tests

2021-11-08 18:20 UTC, daltojohnso approved these changes
looks solid. one nitpick in code you didn't write 🙂

2021-11-08 18:20 UTC, daltojohnso commented on frontend/src/metabase/query_builder/components/view/QuestionDataSource.jsx
> +  const isStructuredQuery = query instanceof StructuredQuery;
since we have access to the `question` here, let's go ahead and change this to `question.isStructured()` so we can avoid importing `StructuredQuery`

2021-11-08 19:36 UTC, mazameli requested changes
The Filter tokens and the breadcrumbs are colliding here:

![image](https://user-images.githubusercontent.com/2223916/140805997-b3415ce9-f46c-4816-bd82-fb3c5ffab2c2.png)

![image](https://user-images.githubusercontent.com/2223916/140806464-e2cc18f6-619c-4901-932a-c48bd9bff3fd.png)

2021-11-08 19:37 UTC, mazameli commented
I'd be keen to get @kdoh's eyes on this since he came up with this general direction. Is this looking good to you, Kyle?

2021-11-09 09:36 UTC, kulyk commented
Thanks, @mazameli! Fixed:

<img width="418" alt="CleanShot 2021-11-09 at 10 52 55@2x" src="https://user-images.githubusercontent.com/17258145/140899408-c36f71eb-4925-4102-90d5-8b3d9a5de633.png">

2021-11-09 11:28 UTC, flamber commented
I'm testing `d2b769f` and still seeing padding problem:
![image](https://user-images.githubusercontent.com/1447303/140913509-bbfa9118-7787-4637-a6c2-b53178ad1300.png)

Looks like it addresses the color issue in #17922, but don't know if the font-size is intended or not. Either way, that issue can be closed.

Also want to point out that the color is getting to a point, where it's really difficult to read - already got bad in 0.38 #14602

Totally outside the scope of this PR, but would love if 12616 and 17961 was addressed at some point.

2021-11-09 18:25 UTC, mazameli commented
@kulyk I'm still seeing this problem on saved questions:

![image](https://user-images.githubusercontent.com/2223916/140981858-06f47dbd-654d-4387-aeed-c7e46048ea9f.png)

2021-11-09 18:25 UTC, kulyk commented
Thanks, @flamber, I missed the saved question case there. Updated:

<img width="545" alt="CleanShot 2021-11-09 at 20 17 53@2x" src="https://user-images.githubusercontent.com/17258145/140982574-4b6d4c83-4b4d-486a-834b-6cd22074b57a.png">

<img width="1304" alt="CleanShot 2021-11-09 at 20 18 01@2x" src="https://user-images.githubusercontent.com/17258145/140982568-9a077188-9786-4fe5-bb44-18d7bba9598b.png">

<img width="999" alt="CleanShot 2021-11-09 at 20 18 09@2x" src="https://user-images.githubusercontent.com/17258145/140982556-e4f5616c-bbe6-487c-9527-94fd2e5093b3.png">

2021-11-09 18:26 UTC, mazameli approved these changes
Looks good to me now that the filter collisions on ad hoc and saved questions are fixed. 👍🏼 Nice work!

2021-11-09 18:35 UTC, flamber reviewed
I've been looping through a handful of questions and modes, and seems like padding is on-par :+1:

2021-11-09 19:13 UTC, merged