Progress bar static viz BE bits
metabase/metabase pull request #18945
Opened 2021-11-11 05:11 UTC by howonlee

Pursuant to #18676, also to the FE bits sasha whacked in in 18884.

Implements the backend bits to display pulses + dashboard subs for progress bar view. You need to have it as the display type for a card for it to get displayed

2021-11-15 16:10 UTC, dpsutton requested changes
You'll need to handle formatting (numeric, decimals, prefix, suffix, etc) on both the value and the goal.

But otherwise looks great!

2021-11-22 21:29 UTC, dpsutton commented
I don't see any formatting done on `value` or `goal`. In `21756f6` you added `(format-cell timezone-id (ffirst rows) (first cols) viz-settings)` to the value and then removed it in the subsequent commit. But you will need to do this same formatting to the goal in addition to the value.

2021-11-22 21:50 UTC, howonlee commented
> I don't see any formatting done on `value` or `goal`. In `21756f6` you added `(format-cell timezone-id (ffirst rows) (first cols) viz-settings)` to the value and then removed it in the subsequent commit. But you will need to do this same formatting to the goal in addition to the value.

`data` is different format in frontend than before, it just expects an unformatted int and the formatting is intended to be done by FE. `->js-viz` actually does fit in the formatting options in the JS dict passed in for the frontend but it fits it in the `x` key: I shove it into `format` key which is what the FE wants.

Result with formatting attached
![metabase_pulse_image_1326394200721437732](https://user-images.githubusercontent.com/1364952/142940161-50ba1a09-d68f-4130-ac70-267bbff125f4.png)

2021-11-23 23:34 UTC, dpsutton approved these changes

2021-11-29 01:47 UTC, merged