Dataset metadata editor UI
metabase/metabase pull request #19206
Opened 2021-12-06 13:12 UTC by kulyk

2021-12-06 20:54 UTC, daltojohnso commented
<img width="1149" alt="Screen Shot 2021-12-06 at 12 53 02 PM" src="https://user-images.githubusercontent.com/13057258/144920888-c124f416-230d-4fc3-b53b-52cef15a2dee.png">

I noticed there's quite a delay when you click on a column header in the "edit metadata" mode. Looks like a chunk of the slowness is caused by a hook in `SyncSnackbar.jsx`. Not sure what that's about.

2021-12-06 21:52 UTC, daltojohnso commented
https://user-images.githubusercontent.com/13057258/144928371-60697733-f75b-4fd3-aca3-cec8e1ccb568.mov

Also, perhaps related to the above performance problem I commented on, but it seems like the form ui on the right side is pretty slow, too. Every key press in the description input is ~60ms long and you can feel the sluggishness. Seems like some unnecessary rendering going on. Didn't dig too deep into it, however.

2021-12-06 22:04 UTC, daltojohnso requested changes
One minor thing besides some comments regarding performance -- feel free to look at performance stuff in a subsequent PR. Besides that, I noticed that custom columns don't seem to work:

https://user-images.githubusercontent.com/13057258/144929992-eb5cfcdb-3b20-4557-bd7b-5a45e17995a7.mov

2021-12-07 00:07 UTC, mazameli commented
We shouldn't discard metadata changes when you tab between the query and metadata modes: https://www.loom.com/share/de53f08706cd47d9ac435e92a9ea367d

2021-12-07 00:09 UTC, mazameli commented
> I noticed there's quite a delay when you click on a column header in the "edit metadata" mode. Looks like a chunk of the slowness is caused by a hook in SyncSnackbar.jsx. Not sure what that's about.

@daltojohnso `SyncSnackbar.jsx` is a new component that the Activation team added. It shows up in the bottom right of the app after you connect a new DB to let you know if it's done syncing yet. cc @ranquild

2021-12-07 00:11 UTC, mazameli commented
I'm just assuming the specced tabbing behavior [isn't implemented yet](https://www.loom.com/share/d51f619f79d8442c85befb723c9e77b8).

2021-12-07 00:18 UTC, mazameli commented
Is it expected that I can't yet map a foreign key field to the column it points to in the related table? https://www.loom.com/share/10a8f510f2f94b09bb9b16196964f737

2021-12-07 00:28 UTC, mazameli requested changes
Presuming this PR isn't meant to persist/save the metadata changes you make, but just add the UI, then it's looking really cool. 

Just one small chage request: the space between column headings is too tight currenty. See screenshots. 

**Desired spacing between column headings**

![image](https://user-images.githubusercontent.com/2223916/144943889-9fdbb436-74f1-4a78-9794-af410e90cee4.png)

**Current spacing is too tight**

![image](https://user-images.githubusercontent.com/2223916/144943948-2e0ffc89-e996-45c9-b984-0dd3abab4f9d.png)

2021-12-07 00:31 UTC, mazameli commented
Just noticed this, too: if I cancel my edits, my results disappear: https://www.loom.com/share/01c25e079a954a7c81c21328526eef47

2021-12-07 16:16 UTC, kulyk commented
@daltojohnso many thanks for the performance investigation, the videos and screenshots helped a lot

I did a few things and looks like the performance has improved (e.g. key press handling in metadata sidebar now takes ~20-30ms compared to 60ms before the optimization)

* query editor should not rerender now when it's hidden in "metadata" mode ([commit](url))
* some memorization in the [sidebar component](https://github.com/metabase/metabase/pull/19206/commits/0521206e24725c4fc305e647e4086973e473dec3) and the [dataset editor itself](https://github.com/metabase/metabase/pull/19206/commits/eede1b8f57f69565ffa95be649ba6eaa7adabc0b)

2021-12-07 16:18 UTC, kulyk commented on frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
> +const isSameField = (f1, f2) => {
Tried that and it seems to work good. Thanks!

2021-12-07 16:25 UTC, kulyk commented
@mazameli thanks for your review

> It seems as though this PR isn't meant to actually persist/save the metadata yet (right?)

Correct, the API isn't available yet

> I'm just assuming the specced tabbing behavior [isn't implemented yet](https://www.loom.com/share/d51f619f79d8442c85befb723c9e77b8), and will be in a different PR, which is cool by me.

Correct

> Is it expected that I can't yet map a foreign key field to the column it points to in the related table?

Yes. If you don't mind, I'd batch that together with field mapping for native datasets (working on that now, should be the next PR).

> Just one small change request: the space between column headings is too tight currently

Thanks! I also noticed it wasn't properly handling long column names. Both issues should be fixed 🙌 

> if I cancel my edits, my results disappear

Yeah, Jeff caught that during query editor bug bash. The issue is tracked, I'd prefer to issue the fix in another PR

2021-12-07 17:28 UTC, mazameli approved these changes

2021-12-08 02:53 UTC, daltojohnso approved these changes

2021-12-08 09:02 UTC, merged