Replace deprecated CircleCI image
metabase/metabase pull request #19423
Opened 2021-12-19 23:25 UTC by paoliniluis

Fixes https://github.com/metabase/metabase/issues/18650

2021-12-20 03:34 UTC, paoliniluis commented
I'm next to the finish line:
1) image is built from new Temurin JDK + Node LTS + Clojure (8, 11 and 17)
2) user profile is configured as circleci wants, so it's plug and play with the current CI
3) it's slimmer (only ~600mb compared to current circleci image)
4) it's very very upgradable (in fact I'm thinking into building one to build and other to test, so it's not a full image for every step)

but I can't get yarn to spawn a java process... but I'm sure it's a path thing somewhere that I'll have to fix

2021-12-24 18:35 UTC, paoliniluis commented
"be-tests-ee" and "be-tests-oss" are pending since those were changed "be-tests-java-8-ee" "be-tests-java-8-oss" to know which java version we're running those tests

2021-12-30 01:11 UTC, camsaul approved these changes

2021-12-31 20:01 UTC, paoliniluis commented
Now this should also be ready to merge once all tests pass

2022-03-23 15:41 UTC, diogormendes commented on .circleci/config.yml
> +          name: be-tests-java-17-<< matrix.edition >>
No need to test with 16 anymore ??

2022-03-23 15:49 UTC, ariya commented on .circleci/config.yml
> +          name: be-tests-java-17-<< matrix.edition >>
Only 8, 11, and 17 are LTS versions.

2022-03-31 20:59 UTC, diogormendes approved these changes

2022-04-16 17:02 UTC, diogormendes approved these changes

2022-04-16 17:02 UTC, diogormendes commented on Dockerfile
> +FROM --platform=linux/amd64 eclipse-temurin:11-jre-alpine as runner
🚀

2022-04-17 01:01 UTC, paoliniluis commented
Thanks @diogormendes for the approval, I'll need https://github.com/metabase/metabase-docker-ci/pull/6 approved before merging this one

2022-04-17 01:02 UTC, paoliniluis commented
Thanks @diogormendes for the approval, I'll need https://github.com/metabase/metabase-docker-ci/pull/6 approved before merging this one

2022-04-18 17:03 UTC, camsaul requested changes
We shouldn't test with Clojure 1.11.0 since we're not shipping anything with it yet.

We'll probably switch to Clojure 1.11.1 when that comes out but we're still shipping 1.10.x until then

2022-04-18 17:06 UTC, dpsutton commented
My reading of this is its just bumping the version of the clojure cli. We specify `org.clojure/clojure {:mvn/version "1.10.3"}` so we will not be testing on clojure 1.11.X at all. But we for sure want to stay away from 1.11.0 and only use 1.11.1 and above when we do switch.

2022-04-18 19:30 UTC, paoliniluis commented
Thanks @dpsutton and @camsaul, I left my comments here: https://github.com/metabase/metabase-docker-ci/pull/6#issuecomment-1101692558

2022-04-18 19:31 UTC, camsaul approved these changes
Oops you're totally right @dpsutton. Ok in that case then this looks fine

2022-05-16 15:09 UTC, merged