Add empty pinned items section banner & new empty state svg
metabase/metabase pull request #19857
Opened 2022-01-22 21:56 UTC by daltojohnso

Adds banner + new empty state svg when there are no collection items

<img width="1160" alt="Screen Shot 2022-01-22 at 1 56 05 PM" src="https://user-images.githubusercontent.com/13057258/150656704-744d9284-a1cd-48e3-900c-00e50511913e.png">
<img width="1144" alt="Screen Shot 2022-01-22 at 1 56 11 PM" src="https://user-images.githubusercontent.com/13057258/150656705-7d64cf3a-c993-449a-9943-2694b1f7459b.png">

2022-01-24 18:37 UTC, mazameli requested changes
The distance between the banner and the empty state content should ideally be a consistent ~40px to prevent awkward gaps like this (i.e., the placeholder images should align to the top I think): 

![image](https://user-images.githubusercontent.com/2223916/150843377-8e84ec94-ac38-49a5-9140-c59f1cdce2d9.png)


Also, in an ideal world I think this content would have a min-width, and then stretch wider to better fill up wide screens; but only if that's trivially easy.

![image](https://user-images.githubusercontent.com/2223916/150843068-068ba553-d00b-44c1-8103-2442717ee858.png)

2022-01-24 18:54 UTC, daltojohnso commented
@mazameli I think getting rid of the defined `width` and `height` of the SVG gets us most of the way there; how is that?

2022-01-24 21:33 UTC, mazameli commented
@daltojohnso looking now

2022-01-24 22:33 UTC, mazameli approved these changes
I pushed a commit with a reasonable maxWidth for the whole thing, and I think this is a good-enough happy medium for our purposes now.

2022-01-25 00:26 UTC, merged

2022-01-25 11:56 UTC, kulyk commented on frontend/src/metabase/collections/components/EmptyPinnedItemsBanner/EmptyPinnedItemsBanner.tsx
> +      {t`Save your questions, dashboads, and datasets in collections — and pin them to feature them at the top.`}
Please replace "datasets" with "models"

2022-01-25 11:56 UTC, kulyk commented on frontend/src/metabase/collections/components/PinnedItemOverview/PinnedItemOverview.unit.spec.js
> +      "Save your questions, dashboads, and datasets in collections — and pin them to feature them at the top.",
Please replace "datasets" with "models"