docs - instructions for running development branch
metabase/metabase pull request #19926
Opened 2022-01-25 19:44 UTC by frannietrempe

- This was a Notion doc, revised and reorganized it a bit to add to developer's guide in docs.
- Added mentions on developer's guide start page and install guide doc.

2022-01-25 20:21 UTC, ariya commented
Any particular reason why the contents in `running-dev-branch.md` not being merged into `devenv.md`? There's a lot of similarity (after all, it's about developing Metabase).

Some of the (detailed) info regarding the prerequisite (Xcode on Mac etc) can be spawned into its own `.md` file, since then it can be referred from `build.md`.

2022-01-27 22:23 UTC, jeff-bruemmer requested changes
Just some suggestions.

2022-01-27 22:23 UTC, jeff-bruemmer commented on docs/developers-guide/build.md
>  If you are developing on Windows, make sure to use Ubuntu on Windows and follow instructions for Ubuntu/Linux instead of installing ordinary Windows versions.
```suggestion
### If you're running Windows, use WSL

If you are developing on Windows, you should run Ubuntu on Windows Subsystem for Linux (WSL) and follow instructions for Ubuntu/Linux.
```

2022-01-27 22:23 UTC, jeff-bruemmer commented on docs/developers-guide/build.md
```suggestion
### Developing with VS Code in a remote container
```

2022-01-27 22:23 UTC, jeff-bruemmer commented on docs/developers-guide/build.md
> +## Copy the Metabase code to your computer
```suggestion
## Clone the Metabase repo
```

2022-01-27 22:23 UTC, jeff-bruemmer commented on docs/developers-guide/build.md
> +Once you have all that installed, you’re going to get a copy of Metabase's source code from GitHub, where it’s stored.
```suggestion
Once you've installed all the build tools, you'll need to clone the Metabase repository from GitHub.
```

2022-01-27 22:23 UTC, jeff-bruemmer commented on docs/developers-guide/build.md
> +1. Run this GitHub command to “clone” Metabase into this folder
Do they need to set up the `gh` CLI to do this? Should that be in the required tools?

https://cli.github.com/manual/

And should we provide the alternate git clone command?

2022-01-27 22:23 UTC, jeff-bruemmer commented on docs/developers-guide/build.md
> +   You should do this every time to make sure that you have all the latest Metabase branches and code on your computer. It’s also how you’ll get updates on a feature branch if the engineer make chang
```suggestion
   You should do this every time to make sure that you have all the latest Metabase branches and code on your computer. It’s also how you’ll get updates on a feature branch someone make changes to it.
```

2022-01-27 22:23 UTC, jeff-bruemmer commented on docs/developers-guide/build.md
> +   git checkout branch-name
```suggestion
   git checkout <branch-name>
```

2022-01-27 22:23 UTC, jeff-bruemmer commented on docs/developers-guide/build.md
> +6. Now we’ll start up the backend server of Metabase with:
This should be its own section, as it talks about running the code (not getting the code).

2022-01-27 22:23 UTC, jeff-bruemmer commented on docs/developers-guide/build.md
> +- If you want to make Metabase stop running, you can either quit your terminal program, or go to the tab with the backend running and hit `Ctrl+C` to stop the backend. Most of the time you don’t have
```suggestion

## Shutting down Metabase

If you want to make Metabase stop running, you can either quit your terminal program, or go to the tab with the backend running and hit `Ctrl+C` to stop the backend. Most of the time you don’t have to do this to switch branches, but there are some cases where the change or feature you’re trying to see is a change with the backend, and you may need to stop the backend with `Ctrl+C` and then restart it by completing Step 6 again.
```

2022-01-27 22:23 UTC, jeff-bruemmer commented on docs/developers-guide/build.md
>  ## Build Metabase Uberjar
```suggestion
## Building the Metabase Uberjar
```

2022-01-27 22:23 UTC, jeff-bruemmer commented on docs/developers-guide/dev-branch-docker.md
> +## Run an in development branch to test or verify features
```suggestion
## Run a development branch to test or verify features
```

2022-01-28 19:52 UTC, jeff-bruemmer approved these changes
Thanks, @frannietrempe!

2022-01-28 20:06 UTC, frannietrempe commented
a belated thank you to @ariya for pointing out that this info could be integrated into existing pages 🙏

2022-01-28 20:06 UTC, merged