Remove legacy impl to fix timezone issue
metabase/metabase pull request #20023
Opened 2022-01-28 18:07 UTC by pratikgajjar

###### Before submitting the PR, please make sure you do the following

This PR will fix [Issue](https://github.com/metabase/metabase/issues/19910) 

### Tests

- [ ] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [ ] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

2022-01-28 18:23 UTC, pratikgajjar commented
Can anyone help, why these unrelated test cases are failing. 

```bash
➜  metabase git:(fix-19910-redshift-timezone-issue) ✗ clojure -X:dev:test
Looking for test namespaces in directory test
Setting clojure.tools.logging factory to clojure.tools.logging.impl/log4j2-factory
Looking for test namespaces in directory shared/test
 ⮦ Load driver :sql took 471.4 ms
Load driver :sql-jdbc took 620.1 ms
Added test extensions for :sql/test-extensions 💯
Running 2469 tests

   0/2469     0% [                                                  ]  ETA: --:--
+---------------------+
| Initializing :db... |
+---------------------+

Setting up :h2 test DB and running migrations...
Database setup took 3.2 s
Application DB is H2 1.4.197 (2018-03-18)

+--------------------------+
| Initializing :plugins... |
+--------------------------+

   5/2469     0% [                                                  ]  ETA: 43:02Loading driver :h2 test extensions (require metabase.test.data.h2)
Added SQL test extensions for :sql-jdbc/test-extensions ✏️
Added SQL JDBC test extensions for :h2 ➕
Load :h2 test extensions took 191.2 ms
load-data for h2 test-data users (reference H2 duration: 23.8 ms) took 18.8 ms
load-data for h2 test-data categories (reference H2 duration: 10.1 ms) took 4.1 ms
load-data for h2 test-data venues (reference H2 duration: 29.4 ms) took 30.1 ms
load-data for h2 test-data checkins (reference H2 duration: 130.4 ms) took 83.3 ms
Sync :h2 Database test-data (reference H2 duration: 1.1 s) took 1.4 s
  10/2469     0% [                                                  ]  ETA: 30:17
+-----------------------------+
| Initializing :test-users... |
+-----------------------------+


+-----------------------------+
| Initializing :web-server... |
+-----------------------------+

Started test server on port 3001
  31/2469     1% [                                                  ]  ETA: 16:26
+--------------------------------------------------+
| Initializing :test-users-personal-collections... |
+--------------------------------------------------+

  43/2469     1% [                                                  ]  ETA: 14:03load-data for h2 sample-dataset products (reference H2 duration: 95.6 ms) took 30.1 ms
load-data for h2 sample-dataset people (reference H2 duration: 1.9 s) took 516.9 ms
load-data for h2 sample-dataset reviews (reference H2 duration: 292.7 ms) took 88.5 ms
load-data for h2 sample-dataset orders (reference H2 duration: 3.4 s) took 1.6 s
QUICK sync :h2 Database sample-dataset (reference H2 duration: 96.3 ms) took 187.8 ms
 194/2469     7% [===                                               ]  ETA: 07:01
+-------------------------------+
| Initializing :test-drivers... |
+-------------------------------+

Loading plugin manifest (from test_modules/drivers/driver-deprecation-test-legacy/resources/metabase-plugin.yaml) for driver as if it were a real plugin: driver-deprecation-test-legacy
Loading plugin manifest (from test_modules/drivers/driver-deprecation-test-new/resources/metabase-plugin.yaml) for driver as if it were a real plugin: driver-deprecation-test-new
Loading plugin manifest (from test_modules/drivers/secret-test-driver/resources/metabase-plugin.yaml) for driver as if it were a real plugin: secret-test-driver
 198/2469     8% [====                                              ]  ETA: 06:58Load lazy loading driver :driver-deprecation-test-legacy took 12.2 ms
 214/2469     8% [====                                              ]  ETA: 06:33[qtp379207727-45] INFO  metabase.task.sync-databases - Scheduling sync/analyze for database 68: trigger: metabase.task.sync-and-analyze.trigger.68
[qtp379207727-45] INFO  metabase.task.sync-databases - Scheduling field-values for database 68: trigger: metabase.task.update-field-values.trigger.68
 214/2469     8% [====                                              ]  ETA: 06:34[main] INFO  metabase.task.sync-databases - Scheduling sync/analyze for database 69: trigger: metabase.task.sync-and-analyze.trigger.69
[main] INFO  metabase.task.sync-databases - Scheduling field-values for database 69: trigger: metabase.task.update-field-values.trigger.69
 299/2469    12% [======                                            ]  ETA: 05:44load-data for h2 integer-coerceable t (reference H2 duration: NONE) took 783.6 µs
QUICK sync :h2 Database integer-coerceable (reference H2 duration: NONE) took 76.0 ms
 441/2469    17% [========                                          ]  ETA: 04:30load-data for h2 sad-toucan-incidents incidents (reference H2 duration: 7.3 ms) took 5.5 ms
QUICK sync :h2 Database sad-toucan-incidents (reference H2 duration: 48.6 ms) took 90.2 ms
 530/2469    21% [==========                                        ]  ETA: 05:04
+-------------------------+
| Initializing :events... |
+-------------------------+

 549/2469    22% [===========                                       ]  ETA: 05:16load-data for h2 test-data-with-time users (reference H2 duration: 15.3 ms) took 56.9 ms
QUICK sync :h2 Database test-data-with-time (reference H2 duration: 40.4 ms) took 150.3 ms
 675/2469    27% [=============                                     ]  ETA: 05:04Database setup took 1.5 s
Database setup took 1.5 s
Database setup took 350.7 ms
Database setup took 1.5 s
Database setup took 375.2 ms
Database setup took 1.5 s
Database setup took 328.4 ms
Database setup took 1.4 s
 678/2469    27% [=============                                     ]  ETA: 05:26Database setup took 372.8 ms
Database setup took 1.1 s
Database setup took 277.0 ms
Database setup took 1.3 s
 682/2469    27% [=============                                     ]  ETA: 05:32Database setup took 362.0 ms
Database setup took 1.1 s
 710/2469    28% [==============                                    ]  ETA: 05:29[main] DEBUG metabase.db.schema-migrations-test.impl - Testing migrations for driver :h2...
[main] DEBUG metabase.db.schema-migrations-test.impl - Creating empty H2 app db...
[async-dispatch-5] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-8] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-1] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-2] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-4] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-7] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-3] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-2] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-2] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-1] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-2] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-1] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-2] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-1] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-1] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-2] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-1] TRACE metabase.async.streaming-response - Checking cancelation status after waiting 1000.0 ms
[async-dispatch-8] TRACE metabase.async.streaming-response - Checking cancelation status after  [...]

2022-01-28 21:15 UTC, dpsutton commented
Hi thanks for the submission. I'm looking at the first set of failures "am" vs "AM". 

I'm seeing

2022-01-29 09:07 UTC, flamber commented
Guessing that `-Duser.country=US` would get rid of the locale specific errors - just like we're defining [-Duser.language=en](https://github.com/metabase/metabase/blob/master/deps.edn#L190)

2022-01-29 21:34 UTC, pratikgajjar commented
@flamber @dpsutton Please let me know what are the next steps for me so we can move forward and get this merged. This is very high priority issue for us because our analytics team isn't able to utilize redshift cluster to full extent as most of the analysis requires date filter which returns inconsistent data.

Test cases are failing because 

- [Circle CI] be-tests-redshift-ee -  we haven't provided correct redshift host config 

   ```bash
     :cause "In order to test redshift, you must specify the env var MB_REDSHIFT_TEST_HOST."  
   ```
- [Circle CI] Snowplow and other most of the test cases are failing due to missing env variable used by `wget`

  ```bash
  #!/bin/bash -eo pipefail
  wget --output-document=snowplow-micro.jar $SNOWPLOW_MICRO_JAR
  
  wget: missing URL
  Usage: wget [OPTION]... [URL]...
  
  Try `wget --help' for more options.
  
  Exited with code exit status 1
  ```
- [Local backend tests] Ran `clojure -X:dev:test -D user.country=US`

  ```bash
  FAIL in metabase.email.messages-test/alert-schedule-text-test (messages_test.clj:66)
  Alert schedules can be described as English strings, with the timezone included
  Setting :report-timezone = "America/Pacific"
  
  expected: "Run daily at 12 AM America/Pacific"
    actual: ("Run daily at 12 am America/Pacific")
  
  FAIL in metabase.email.messages-test/alert-schedule-text-test (messages_test.clj:69)
  Alert schedules can be described as English strings, with the timezone included
  Setting :report-timezone = "America/Pacific"
  
  expected: "Run daily at 5 AM America/Pacific"
    actual: ("Run daily at 5 am America/Pacific")
  
  FAIL in metabase.email.messages-test/alert-schedule-text-test (messages_test.clj:72)
  Alert schedules can be described as English strings, with the timezone included
  Setting :report-timezone = "America/Pacific"
  
  expected: "Run daily at 6 PM America/Pacific"
    actual: ("Run daily at 6 pm America/Pacific")
  
  FAIL in metabase.email.messages-test/alert-schedule-text-test (messages_test.clj:75)
  Alert schedules can be described as English strings, with the timezone included
  Setting :report-timezone = "America/Pacific"
  
  expected: "Run weekly on Monday at 8 AM America/Pacific"
    actual: ("Run weekly on Monday at 8 am America/Pacific")
  
  FAIL in metabase.email.messages-test/alert-schedule-text-test (messages_test.clj:81)
  If report-timezone is not set, falls back to UTC
  Setting :report-timezone = nil
  
  expected: "Run daily at 12 AM UTC"
    actual: ("Run daily at 12 am UTC")
  
  [CLI-agent-send-off-pool-9] ERROR metabase.public-settings.premium-features - Error fetching token status:
  clojure.lang.ExceptionInfo: clj-http: status 404

  ERROR in metabase.util.ssh-test/connects-with-correct-ssh-key-and-passphrase (HostConfigEntry.java:889)
  expected: (some?
             (ssh/start-ssh-tunnel!
              {:host "127.0.0.1",
               :port 1234,
               :tunnel-host "127.0.0.1",
               :tunnel-port ssh-mock-server-with-publickey-passphrase-port,
               :tunnel-private-key (slurp ssh-key-with-passphrase),
               :tunnel-private-key-passphrase ssh-key-passphrase,
               :tunnel-user ssh-username}))
    actual:
  
  Ran 2472 tests in 295.245 seconds
  12672 assertions, 6 failures, 2 errors.
  {:test 2472,
   :pass 12664,
   :fail 6,
   :error 2,
   :type :summary,
   :duration 295244.838421,
   :single-threaded 2401,
   :parallel 71}
  Ran 71 tests in parallel, 2401 single-threaded.
  Tests failed.  
  ```

2022-02-03 12:59 UTC, pratikgajjar commented
@dpsutton @flamber Do we have any updates on this ? 

If anyone else facing this issue they can use [docker image](https://hub.docker.com/layers/190198423/fampay/metabase/v0.41.5-hotfix/images/sha256-f4e217ca530639710d769455f4d5b35a5651d9af38853255ba9c4397fce4d364?context=repo) temporarily which was built from [branch](https://github.com/fampay/metabase/tree/v0.41.5-with-timezone-fix)

2022-02-03 19:11 UTC, camsaul requested changes
We'll have to verify this manually since we don't run Redshift tests for third-party PRs. 

@pratikgajjar can you write a test to verify that #19910 is resolved? We generally don't merge bug fix PRs with no tests. 

Add that test and then run the tests locally like this:

```
export MB_REDSHIFT_TEST_DB=<db name>
export MB_REDSHIFT_TEST_HOST=<whatever>.redshift.amazonaws.com
export MB_REDSHIFT_TEST_PASSOWRD=<password>
export MB_REDSHIFT_TEST_USER=<user>
export DRIVERS=redshift
clojure -X:dev:ee:ee-dev:drivers:drivers-dev:test
```

Ping us once you've written the tests and have them passing locally.

Once that's done we can run it locally to confirm and then we can merge this.

2022-03-03 18:55 UTC, pratikgajjar commented
@camsaul , Sure I will do the suggested changes. Thanks for the update and reply.

2023-04-04 21:26 UTC, paoliniluis commented
@pratikgajjar were you able to fix the changes requested?

2023-06-07 17:29 UTC, pratik-fampay commented
Working hotfix  - https://github.com/fampay/metabase/tree/hotfix/v0.46.4

2023-06-07 18:38 UTC, paoliniluis commented
@pratik-fampay let us know when this is ready to review

2024-04-30 23:37 UTC, camsaul commented
Closing since there hasn't been activity in almost a year and I have a separate fix for this.

2024-04-30 23:37 UTC, closed without merging