Models E2E tests: ensure that the dataset is loaded first
metabase/metabase pull request #20127
Opened 2022-02-01 19:35 UTC by ariya

How to test? `yarn test-visual-open` and run `models-query-editor.cy.spec.js`.

**Before this PR**

Sometimes, the following happens:

![scenarios  models query editor -- locks display to table (failed)](https://user-images.githubusercontent.com/7288/152038477-072655c2-04c7-4e6b-8a9e-ed602363cec1.png)

**After this PR**

It doesn't happen anymore.

2022-02-01 20:31 UTC, rlotun approved these changes

2022-02-02 12:58 UTC, nemanjaglumac commented on frontend/test/metabase/scenarios/models/models-query-editor.cy.spec.js
> +    cy.wait("@dataset");
I'm constantly seeing this failure:
![image](https://user-images.githubusercontent.com/31325167/152158256-8fd50326-f6ad-492a-b4f2-47c8be06759b.png)

2022-02-02 14:17 UTC, nemanjaglumac requested changes
Something's off here.
I can't get those tests to work with these changes.

Anyway, spoke to @kulyk and we agreed that these tests could be greatly simplified, to the point that we probably wouldn't need these guards.

AFAIC, feel free to close this PR and I'll take care of the rest in the separate PR, @ariya

2022-02-02 15:51 UTC, closed without merging

2022-02-02 17:09 UTC, nemanjaglumac commented
https://github.com/metabase/metabase/pull/20175