Disable model editor's "Save changes" button when there are no changes
metabase/metabase pull request #20191
Opened 2022-02-02 17:45 UTC by kulyk

2022-02-03 18:26 UTC, nemanjaglumac commented
> @kulyk I imagine this is a simple one I'm missing, but just to save confusion on my side, I'd like to know where this Save button is for a model :)
> 
> 40-odd-second video
> 
> https://www.loom.com/share/07f46517e10445138f09b42101b55f57

@gusaiani Edit metadata or Edit query.

2022-02-03 18:32 UTC, nemanjaglumac approved these changes
~~Works as described.~~

2022-02-03 18:45 UTC, nemanjaglumac requested changes
Actually, wait.
Even when I change metadata, I cannot "Save changes". The button stays disabled.

Editing the query seems to be working.

2022-02-03 19:07 UTC, kulyk commented
> Actually, wait. Even when I change metadata, I cannot "Save changes". The button stays disabled.
> 
> Editing the query seems to be working.

Can you share the repro steps, please? There can be a lag if you edit a display name. Its `onChange` handler is denounced not to mess up the results table on every new character. So there might be a small delay between adding the final character and the button becoming active

2022-02-03 19:16 UTC, gusaiani commented
Don't know if you meant to go this far in redisabling Save Changes.

In editing metadata, renaming `ID`→`IDo` enables `Save Changes`, which is expected.
Then deleting the `o` and naming it back to `ID` doesn't disable `Save Changes`.

Tbh I don't think this is necessary to happen.

https://www.loom.com/share/f4589e1b6e1c4d47a426e021b179793f?from_recorder=1&focus_title=1

2022-02-03 20:43 UTC, nemanjaglumac commented
@kulyk there are no specific repro steps. I cannot edit metadata at all:
https://share.getcloudapp.com/yAuk985v

2022-02-04 12:53 UTC, kulyk commented
> @kulyk there are no specific repro steps. I cannot edit metadata at all: https://share.getcloudapp.com/yAuk985v

I couldn't reproduce the issue with the same model locally. I pushed another thing, can you please check if the problem persists? If so, could you please take a look at the developer console, maybe there is some error happening?

2022-02-04 12:57 UTC, kulyk commented
> Don't know if you meant to go this far in redisabling Save Changes.
> 
> In editing metadata, renaming `ID`→`IDo` enables `Save Changes`, which is expected. Then deleting the `o` and naming it back to `ID` doesn't disable `Save Changes`.
> 
> Tbh I don't think this is necessary to happen.
> 
> https://www.loom.com/share/f4589e1b6e1c4d47a426e021b179793f?from_recorder=1&focus_title=1

Great catch, thanks! I've looked into it and it's a bit tricky to fix. This PR uses `metadataDiff` in redux we use for the metadata editor and it doesn't become empty when you change something and get back to the original state. The only way to fix this is to compare the modified metadata with the original one using something like `_.isEqual`, but once we enter the metadata editing mode, we don't keep the original metadata. I suppose we'd want that to be fixed properly, but I'd leave that as is to provide at least some protection from accidental saves

2022-02-04 15:49 UTC, gusaiani approved these changes
Probably worth waiting for Nemanja's confirmation that things work.
Seems to work quite all right for me and code looks good too.

2022-02-07 13:20 UTC, nemanjaglumac approved these changes
Everything's working as expected.
Great work, @kulyk ! 💪

2022-02-07 13:23 UTC, merged