Retain property file path when revisiting database edit page
metabase/metabase pull request #20199
Opened 2022-02-02 21:03 UTC by jeff303

Ensuring that the file path (if that is the secret type) is returned via the API response to the admin, so the UX on the form edit page is better

This involved a lot of refactoring to clean up some stuff:

* removed the population of inferred secret properties (ex: last updated timestamp and creator ID) from `handle-db-details-secret-prop!`, since that stores those values into the details blob, defeating some of the purpose of normalizing secrets into a separate table
* moved the logic for injecting such inferred values to a new function, `expand-inferred-secret-values`, which lives within the secret model namespace
* delegating existing calls that require such expansion to the new function
* adding a new helper function, `reduce-over-details-secret-values`, to handle some common logic that is now showing up in a few places (reducing over db-details on secret values and doing some kind of manipulation)

Adding new database API test to ensure that the file path value is, in fact, returned from the API

###### Before submitting the PR, please make sure you do the following

- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [ ] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [ ] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

2022-02-03 17:09 UTC, escherize approved these changes

2022-02-03 17:11 UTC, dpsutton commented
One thing jumps out at me glaringly: in 
```clojure
(api/defendpoint GET "/:id"
  "Get a single Database with `id`. Optionally pass `?include=tables` or `?include=tables.fields` to include the Tables
  belonging to this database, or the Tables and Fields, respectively."
  [id include]
  {include (s/maybe (s/enum "tables" "tables.fields"))}
  (-> (api/read-check Database id)
      add-expanded-schedules
      secret/admin-expand-db-details-secret-values ;; we call expand secrets in api/database/:id
      (get-database-hydrate-include include)))
```

I clicked around in the app a little bit but never saw this endpoint hit, but it is not locked behind an admin permission check so any user can curl against it and trigger a scary sounding `secret/admin-expand-db-details-secret-values`. And that sounds pretty bad. Reading the `admin-expand-db-details-secret-values` code, there are no checks against the api user or permissions so i think this would leak secrets.


```shell
curl 'http://localhost:3000/api/database/19' -H 'Cookie: metabase.DEVICE=fa3a1d05-8c26-434b-a199-75fa1e4c99ab; metabase.SESSION=f6220d55-696a-48dc-b9b7-b4189aa2c043'
{"description":null,"features":["full-join","basic-aggregations","standard-deviation-aggregations","expression-aggregations","percentile-aggregations","foreign-keys","right-join","left-join","native-parameters","nested-queries","expressions","set-timezone","regex","case-sensitivity-string-filter-options","binning","inner-join","advanced-math-expressions"],"cache_field_values_schedule":"0 0 7 * * ? *","timezone":"UTC","auto_run_queries":true,"metadata_sync_schedule":"0 14 * * * ? *","name":"pg-testing","caveats":null,"creator_id":null,"is_full_sync":true,"updated_at":"2021-10-29T15:10:02.298959Z","cache_ttl":null,"is_sample":false,"id":19,"is_on_demand":false,"options":null,"schedules":{"cache_field_values":{"schedule_minute":0,"schedule_day":null,"schedule_frame":null,"schedule_hour":7,"schedule_type":"daily"},"metadata_sync":{"schedule_minute":14,"schedule_day":null,"schedule_frame":null,"schedule_hour":null,"schedule_type":"hourly"}},"engine":"postgres","initial_sync_status":"complete","refingerprint":null,"created_at":"2021-10-29T15:10:02.000057Z","points_of_interest":null}%
```

2022-02-03 17:12 UTC, dpsutton requested changes
Need to lock down expand-secrets in `api/database/:id`

2022-02-03 17:34 UTC, dpsutton commented
So a bit more nuance, I'm not seeing the details in that curl response, but I do see them when i call from the repl:

```clojure
database=> (binding [metabase.api.common/*current-user-id* 65
                     metabase.api.common/*current-user-permissions-set* (atom (metabase.models.user/permissions-set 65))]
             (:details
              (let [id 19 include nil]
                (-> (api/read-check Database id)
                    add-expanded-schedules
                    secret/admin-expand-db-details-secret-values
                    (get-database-hydrate-include include)))))
{:additional-options nil,
 :ssl false,
 :ssl-key-source nil,
 :password "super complicated and secure password",
 :ssl-key-creator-id nil,
 :ssl-key-password-source nil,
 :port nil,
 :dbname "testing",
 :ssl-root-cert-creator-id nil,
 :host nil,
 :tunnel-enabled false,
 :ssl-key-password-creator-id nil,
 :ssl-root-cert-source nil,
 :ssl-client-cert-creator-id nil,
 :user "username",
 :ssl-client-cert-source nil}
```

2022-02-04 22:20 UTC, dpsutton approved these changes

2022-02-04 23:16 UTC, merged