Migrate query-builder from grid-styled
metabase/metabase pull request #20220
Opened 2022-02-03 17:26 UTC by ranquild

Epic: https://github.com/metabase/metabase/issues/20163

2022-02-03 17:36 UTC, ranquild commented
@kulyk @ariya I've manually tested the changes and everything seems to look the same, added you as reviewers to double check.

2022-02-03 17:52 UTC, gusaiani approved these changes
Markup is so much clearer, thank you Alexandr.

2022-02-04 08:37 UTC, kulyk requested changes
Overall looks good, I noticed a UI regression on the join step

**See how it looks on `master`**
<img width="1091" alt="notebook-joins-master" src="https://user-images.githubusercontent.com/17258145/152497524-24a8149d-2d29-4026-9f54-9f1ff9d36a57.png">

**And that's how it looks in the branch**

<img width="1093" alt="notebook-joins-now" src="https://user-images.githubusercontent.com/17258145/152497469-aa22e7f6-f2e0-4ddb-8671-e3d969950e3c.png">

2022-02-04 08:37 UTC, kulyk commented on frontend/src/metabase/query_builder/components/QueryDownloadWidget.jsx
> +      isExpanded={result.data && result.data.rows_truncated != null ? 300 : 260}
`WidgetRoot` sets `width` depending on `isExpanded`, but the ternary passes a numeric value here, so it's going to be `true` all the time

2022-02-04 08:38 UTC, kulyk commented
Also, could you please look at [this regression](https://metaboat.slack.com/archives/C02H619CJ8K/p1643922564501759) Bruno has mentioned on Slack? Seems like the icon sizes are not identical

2022-02-04 08:38 UTC, kulyk commented
@metabase-bot run visual tests

2022-02-04 13:54 UTC, ranquild commented
@kulyk Fixed these 2 issues

2022-02-04 14:07 UTC, kulyk approved these changes

2022-02-04 14:47 UTC, merged