Make sure params substitution code handles Dashboard :default values
metabase/metabase pull request #20503
Opened 2022-02-14 20:07 UTC by camsaul

Fixes #20493

2022-02-14 20:08 UTC, camsaul commented on test/metabase/driver/sql/parameters/substitute_test.clj
> -             (substitute query {"#123" (i/map->ReferencedCardQuery {:card-id 123, :query "SELECT 1 `x`"})})))))))
Unrelated to this fix but this `deftest` was actually inside of the parent test form. Fixed the parens.

2022-02-14 20:09 UTC, camsaul commented on src/metabase/driver/common/parameters/values.clj
> +                                                 (dissoc param :target)))]
This is the actual fix

2022-02-15 05:55 UTC, dpsutton approved these changes

2022-02-15 13:08 UTC, flamber requested changes
Tested `e72c729`. This changes the behavior and makes it impossible to remove dashboard defaults.

1. Setup a dashboard with default filter
2. Go to `/dashboard/:id` - it will automatically add the filter `/dashboard/:id?text=Doohickey`
3. Then when I clear the widget it changes to `/dashboard/:id?test=`, and it should now show all results, but with this PR it still applies the default value for the card
![image](https://user-images.githubusercontent.com/1447303/154068060-fcbaea48-a47d-4b35-9a2b-5b65b3393ff6.png)

2022-02-15 17:01 UTC, camsaul commented
@flamber are you **sure** that in older versions you could override the default value to somehow be nothing? If you look at the code I didn't change anything that would change that behavior and make it suddenly stop working where it had worked before.

2022-02-15 17:26 UTC, flamber commented
@camsaul Try 0.41.6 - I would not block a PR if I didn't think it would cause more problems.

2022-02-15 17:58 UTC, nemanjaglumac commented
@camsaul keep in mind that this issue was reproduced in https://github.com/metabase/metabase/pull/20495. I can update repro steps to also check for the thing Flamber found in his review https://github.com/metabase/metabase/pull/20503#pullrequestreview-882957652.

Let me know if you want me to do it in this branch (if you rebase it or include `master` in it), or do you want me to update it on the `master` first?

2022-02-15 18:25 UTC, camsaul commented
Ok I'm a little confused on how this is actually supposed to work. I can tweak the code to ignore Dashboard `:default` parameter values (because the expectation seems to be that the FE client will explicitly pass those in as `:value` if it wants to use them) but then that breaks #19494.

In #19494 it seems that the clear expectation was that we **would** take default values into account on the backend

2022-02-15 18:55 UTC, nemanjaglumac commented
@flamber can correct me because he has much better understanding, but dashboard would have the default parameter set on the visit. All good so far.

But you should also be able to remove that default filter value (set via filter widget) while exploring data and it should give you ALL results. The url changes to `/dashboard/:id?test=` as Flamber pointed out. Results on the page should reflect that.

On the next visit, the default filter would be set again.

2022-02-15 19:04 UTC, nemanjaglumac commented
In other words, this:
https://www.loom.com/share/27047a48cba2435a9b32e817fa8b5dc6

2022-02-15 20:55 UTC, camsaul commented
I think I've figured out how this is supposed to work. @flamber, can you try this out again and check #19494 as well to make sure that still works. @nemanjaglumac feel free to add more tests to this branch.

2022-02-15 20:56 UTC, flamber approved these changes
Tested `8c7a56b` and it works as expected (similar to 41.6) :tada: 
And I also re-tested #19494, which still works as expected.

EDIT: I've been testing it for the past 15 minutes, which is why the response is so fast

2022-02-15 22:00 UTC, nemanjaglumac commented
>  @nemanjaglumac feel free to add more tests to this branch.

@camsaul The repro for this has already been merged to `master` previously. But since @flamber tested this manually and can confirm, please feel free to merge it and I'll enable the repro after you do that.

Wouldn't want to keep this PR any longer and to wait for one more CI cycle.

2022-02-15 22:50 UTC, merged