data model feature permission
metabase/metabase pull request #20571
Opened 2022-02-17 00:32 UTC by alxnddr

# Feature-level data model permission

## How to verify
### Metabase OSS 
#### As an Admin
- Go to Admin -> Data model
- Ensure it behaves the same way as before, and admins can edit the data model
#### As a regular user
- Ensure you cannot go to the Admin Settings as a regular user

### Metabase EE
#### As an Admin
- Go to Admin -> Data model
- Ensure it behaves the same way as before, and admins can edit the data model

#### As a regular user without a Data model permission
- Ensure you cannot go to the Admin settings as a regular user

#### As a regular user with Data model permission enabled
- Ensure you can go to the Admin Settings and it opens the Data model
- Ensure you can only view databases/tables/schemas data model with `read` data model permission
- Ensure you can edit databases/tables/schemas data model with `write` data model permission

2022-03-25 12:50 UTC, ranquild commented on frontend/src/metabase/admin/datamodel/components/database/MetadataTableList/MetadataTableList.tsx
> +        ? new RegExp(regexpEscape(event.target.value), "i")
It seems that `regex` is not state, and should be computed and memoized from `text`

2022-03-25 12:52 UTC, ranquild commented on frontend/src/metabase/admin/datamodel/components/database/MetadataTablePicker/MetadataTablePicker.tsx
> +      tables = [],
There should be a type for `Table` too in our api types

2022-03-25 12:54 UTC, ranquild commented on frontend/src/metabase/admin/datamodel/containers/MetadataEditorApp.tsx
> +// @ts-nocheck
Can it be removed and `any` used instead where needed?

2022-03-25 12:59 UTC, ranquild commented on enterprise/frontend/src/metabase-enterprise/advanced_permissions/utils.ts
> +  entity?.data_model_permission == null ||
Why does this check for `null` exist? I couldn't figure it out

2022-03-25 12:59 UTC, ranquild commented on frontend/src/metabase-types/api/user.ts
> +  can_access_data_model?: boolean;
Is it really optional? I think that the backend will always return this field. Could you make it required and set to false in the mock creator function?

2022-03-25 13:00 UTC, ranquild commented on frontend/src/metabase-types/types/Database.ts
> +  data_model_permission?: DataAccessPermission;
The same question - is it truly optional, or will the backend always set, e.g. to `none`? If it's optional, how is it different to `none` or `write`?

2022-03-25 13:50 UTC, ranquild requested changes
It's still possible to navigate to table settings via keyboard, and some of the settings are writable 
<img width="1728" alt="Screenshot 2022-03-25 at 16 48 18" src="https://user-images.githubusercontent.com/8542534/160133122-67e4fc8c-a270-4770-8ca4-095e157fa9cc.png">
<img width="980" alt="Screenshot 2022-03-25 at 16 48 46" src="https://user-images.githubusercontent.com/8542534/160133136-85dce308-4291-4837-b11b-be83b04ca957.png">

Also it seems wrong that it's possible to discard cached values when you are effectively a read-only user
<img width="690" alt="Screenshot 2022-03-25 at 16 47 39" src="https://user-images.githubusercontent.com/8542534/160133285-27c5f141-eb76-4918-9791-676392b4ed29.png">
<img width="1728" alt="Screenshot 2022-03-25 at 16 47 50" src="https://user-images.githubusercontent.com/8542534/160133295-adec1a76-5574-47c2-8402-c97e5ed18dbe.png">

2022-04-08 03:24 UTC, alxnddr commented
Closed in favor of https://github.com/metabase/metabase/pull/20952

2022-04-08 03:24 UTC, closed without merging