Fix "Show error details" keeps showing after clicked
metabase/metabase pull request #20824
Opened 2022-03-03 13:23 UTC by WiNloSt

Fixes #19900 

## Repro steps
https://github.com/metabase/metabase/issues/19900#issuecomment-1057990108

## Before the fix
https://www.loom.com/share/948afe7f3e4b44be91d878a30890071d

## After the fix
https://www.loom.com/share/8eafeb5913f240cbb62a71b1796bd5e2

2022-03-03 13:26 UTC, WiNloSt commented on frontend/src/metabase/components/ErrorDetails/ErrorDetails.tsx
> +export default function ErrorDetails({
Move the component to TypeScript + functional components + hooks

2022-03-03 13:26 UTC, WiNloSt commented on frontend/src/metabase/components/ErrorDetails/ErrorDetails.tsx
> +          {showError ? t`Hide error details` : t`Show error details`}
Here's the changed logic.
- From setting `showError` to `true` 👉  Toggling `showError`
- From always showing `Show error details` 👉  Showing either `Hide error details` or `Show error details` based on the `showError` flag.

2022-03-03 13:26 UTC, WiNloSt commented on frontend/src/metabase/components/ErrorDetails/ErrorDetails.tsx
> +import React, { useState } from "react";
Removed `/* eslint-disable react/prop-types */` at the top of the file.

2022-03-03 19:25 UTC, daltojohnso requested changes

2022-03-03 19:25 UTC, daltojohnso commented on frontend/src/metabase/components/ErrorDetails/types.ts
> +  className: string;
Let's make `centered` and `className` optional.

And based on the usage of `details` in `ErrorDetails` around line 39, it looks like `details` is pretty loose. Maybe just make it `string | Record<string, any>` to account for the first predicate of the ternary (`typeof details === "string"`)

2022-03-04 04:10 UTC, WiNloSt commented on frontend/src/metabase/components/ErrorDetails/types.ts
> +export interface ErrorDetailsProps {
@daltojohnso Fixed https://github.com/metabase/metabase/pull/20824#discussion_r818994361

2022-03-04 20:16 UTC, daltojohnso approved these changes

2022-03-07 02:54 UTC, merged

2022-03-18 11:50 UTC, WiNloSt commented
@metabase-bot backport release-x.42.x