Show event time range in the sidebar
metabase/metabase pull request #21293
Opened 2022-03-28 19:14 UTC by ranquild

Epic: https://github.com/metabase/metabase/issues/20289

<img width="1252" alt="Screenshot 2022-03-28 at 22 12 38" src="https://user-images.githubusercontent.com/8542534/160470046-4fae9ef1-73d7-4a23-a987-4879184037a4.png">

2022-03-28 21:29 UTC, mazameli requested changes
I think this approach is sound, but just visually we can put the text in the heading of the sidebar so that it can look like @kdoh's designs:

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/2223916/160489199-a531e4d6-60f9-4205-a2cd-0cea8ae643ee.png">

In the screenshot you sent me where you tried this before, what didn't look great was that the only thing that wrapped to the second line was `2020`. We could try using the 3-letter abbreviations for months to use less space, like `Events between Jan 1, 2022 and Apr 1, 2022`.

![image](https://user-images.githubusercontent.com/2223916/160490084-700b5d9e-cbf6-4284-818f-6aa57c677c6f.png)

2022-03-29 07:49 UTC, ranquild commented
@mazameli I've put dates in the title and also increased the sidebar width to make sure it fits one line:

<img width="1728" alt="Screenshot 2022-03-29 at 10 46 57" src="https://user-images.githubusercontent.com/8542534/160560902-4bc5f470-ea88-4f35-83d4-e74bd0c16a85.png">

2022-03-29 22:49 UTC, mazameli commented
I think this is actually counterintuitively a situation where we actually want to make the sidebar _narrower_, to force it to wrap sooner so that it's far less likely to have any word or number all by itself on one line. I pushed a commit to do that, which also allows the sidebar to line up nicely with the filter and summarize buttons:

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/2223916/160719312-4d4c30f8-7878-48f6-81da-4d4b1db7142a.png">

2022-03-29 22:49 UTC, mazameli approved these changes

2022-03-30 10:32 UTC, merged