Subscriptions management permission
metabase/metabase pull request #21307
Opened 2022-03-29 02:56 UTC by alxnddr

# Subscription management permission

This PR adds new subscriptions management permission which is available in Metabase EE.

<img width="607" alt="Screenshot 2022-03-28 at 22 51 43" src="https://user-images.githubusercontent.com/14301985/160523326-86a8f9ff-be19-430b-8284-a7b281d07b43.png">

## How to verify
- Run Metabase EE
- Create "Test User"
- Login as an admin in one window, login as "Test User" in another window

### Granted
- As an admin go to [General Permissions management](http://localhost:3000/admin/permissions/general) and ensure "Subscriptions" permission for "All Users" is "Yes"
- Ensure "Test User" can create question alerts and dashboard subscriptions

### Revoked
- As an admin go to [General Permissions management](http://localhost:3000/admin/permissions/general) and ensure "Subscriptions" permission for "All Users" is "No"
- Ensure "Test User" is unable to create question alerts or dashboard subscriptions

2022-03-29 15:31 UTC, ranquild commented on frontend/src/metabase/hoc/withReducer.jsx
> +export const withReducer = (key, reducer) => Component => {
Would it be better to have a plugin for reducer instead? E.g. `PLUGIN_REDUCERS = []`, which is by default `[(state) => reducer(state)]`, and the plugin functions are reduced to get a final reducer? This approach is used in multiple places in the app.

2022-03-29 15:37 UTC, ranquild requested changes
Would be great to know your thoughts on using another approach to injecting a reducer in runtime before approving this

2022-03-30 10:59 UTC, ranquild approved these changes

2022-03-31 09:48 UTC, qnkhuat approved these changes
Works as expected 👍

2022-04-01 23:08 UTC, merged