Show xrays in the new homepage
metabase/metabase pull request #21393
Opened 2022-03-31 17:24 UTC by ranquild

Epic: https://github.com/metabase/metabase/issues/21322

How to test:
- Run a fresh Metabase instance. You should see x-rays for the sample database.
- Add another database. You copy the connection string from the sample database. You should see x-rays for that database and a link to browse it.

<img width="920" alt="Screenshot 2022-03-31 at 20 12 48" src="https://user-images.githubusercontent.com/8542534/161113734-cb6dff13-e70f-4c71-a52e-ee3ba1d287a5.png">
<img width="792" alt="Screenshot 2022-03-31 at 20 13 48" src="https://user-images.githubusercontent.com/8542534/161113756-19cdbd33-500a-495d-b11f-174667e539bd.png">

2022-03-31 18:23 UTC, ranquild commented on frontend/src/metabase/home/homepage/components/HomeContent/HomeContent.tsx
> +const HomeContent = ({ databases }: HomeContentProps): JSX.Element | null => {
This was moved to an individual component to not block rendering of `HomeLayout` until the content loads.

2022-03-31 18:25 UTC, ranquild commented on src/metabase/automagic_dashboards/core.clj
> +                    :title       (:short-name root)
`full-name` is `Orders table`, but we need only `Orders`

2022-04-01 13:42 UTC, kdoh requested changes
At the moment my biggest reaction is finding myself wanting a clearer way to also just go browse my connected database. I know there are some sidebar changes as part of this that are supposed to also make that accessible so let's maybe wait for that but I suspect we'll want an alternate CTA at the bottom of all the X-ray options.

One visual thing: It'd be nice to add a bit of padding at the bottom so when there are more options on a larger set of tables the. 
<img width="960" alt="Screen Shot 2022-04-01 at 9 39 03 AM" src="https://user-images.githubusercontent.com/5248953/161274815-d3630876-d189-4929-a5a5-ad6325dbb563.png">

I also think we might want to tighten up the spacing between the Metabot greeting and the x-rays. There's a bit too much space right now.
<img width="591" alt="Screen Shot 2022-04-01 at 9 40 38 AM" src="https://user-images.githubusercontent.com/5248953/161275286-8d047b0a-3b12-4fa6-81d8-c4321b8c3f99.png">

I couldn't tell if it's this branch or not but Metabot's greeting wasn't showing up when I hover on our pal, so that's something to figure out as well.

I also think we should make some copy changes to make it clearer just what is going on. I'll comment on those inline with suggestions.

2022-04-01 13:51 UTC, kdoh commented on frontend/src/metabase/home/homepage/components/XraySection/XraySection.tsx
> +          {t`Here are some explorations of`}
I don't have a great alternative yet but I think we might want to give a bit more context for what the heck these are and more actively frame it as a quick way to assist you getting started. Maybe "Get started quickly with some pre-built explorations of your {name} data."?

2022-04-01 13:53 UTC, kdoh commented
Ah, I see that the DB is linked to the browse URL right there in the heading, but somehow that didn't click for me the first time I went through.

2022-04-01 15:56 UTC, merged