add Sankey
metabase/metabase pull request #21421
Opened 2022-04-01 15:10 UTC by morgan12

###### Before submitting the PR, please make sure you do the following

- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [ ] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [ ] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

2022-04-04 22:47 UTC, mazameli requested changes
Hi, @morgan12! Thanks so much for working on this. I gave the branch a thorough look, and while the bones of this are there, I'm seeing some fairly large UX issues that we'll need to address before this is in a mergeable state. Please let me know if I can clarify or elaborate on any of these points of feedback, and thanks again!

---

I'm not seeing any real hover or click interaction to be able to highlight a particular flow or pathway. That seems to me to be one of the primary uses for a diagram like this. Is is expected that I should be seeing some kind of highlighting on click/hover?

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/2223916/161643381-773ce658-561a-404b-8410-6d051230cb77.png">

This is [what Highcharts does](https://www.highcharts.com/demo/sankey-diagram), for example:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/2223916/161644233-29f1a41e-1b0e-4430-8567-2fb8db6ce431.png">


---

I think it's confusing the way the "From" and "To" column pickers are currently combined, and would suggest separating them and renaming them to `Starting point` and `Destination(s)` respectively, and changing the "Add To…" button to `Add destination`:

<img width="348" alt="image" src="https://user-images.githubusercontent.com/2223916/161641237-bc6d6e63-2f2b-472f-87c8-c11df1af7ff0.png">

---

Relatedly, the way that the From and To selections affect the visualization seems backwards right now: I'd expect the first dropdown to be the first node, and the last dropdown to be the last node, but I'm observing the opposite. You can see in this screenshot that my Product column is selected in the first dropdown, and the Source column is in the third/last dropdown, but the Source is being used for the _first_ node in the viz: 

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/2223916/161642969-99baf0d3-75ac-42c2-8b06-f66c4f3fd425.png">

---

I'd expect there to be labels for the final nodes on the far right, with the labels appearing to the left of the nodes:

<img width="1448" alt="image" src="https://user-images.githubusercontent.com/2223916/161643139-53c095f4-5470-4d33-874e-01f5df2407e4.png">

---

Even when I should be able to select a Sankey diagram, the option is grayed out (I can select the viz and it displays just fine in this situation). 

We'll also need to supply you with a designed icon for this visualization.

<img width="360" alt="image" src="https://user-images.githubusercontent.com/2223916/161639279-5b80b364-a6bc-4253-85f3-3f632d44e210.png">

---

I'm finding situations like this one where I have one metric and two dimension columns in my result, and the visualization oddly assigns one of my dimensions to be a `Value`. I'd expect metric columns to be assigned to be `Values` and grouping columns to be used in the "From and To" area by default:

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/2223916/161639704-94d6f6e9-0aab-4628-b985-b5fb10b0736a.png"> 

---

We'll likely need to hide labels on this diagram in dashboards when the card size is small like this, which would even further necessitate a hover behavior to show more information.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/2223916/161643805-ddb34e39-dbd4-4ea9-bfde-e70abb75168f.png">

2022-04-05 18:24 UTC, ariya commented
Thanks for this new chart addition @morgan12!

To make it easier to review, and also for completeness, it's always a good idea to include a sample query which can product an illustrative chart. Here's the one I used to play with this PR:

```sql
select 25 as profit, 'Brazil' as A, 'Portugal' as B
union all
select 5 as profit, 'Canada' as A, 'Portugal' as B
union all
select 34 as profit, 'Canada' as A, 'Germany' as B
```
which should result in the following output:

![image](https://user-images.githubusercontent.com/7288/161824184-6e308456-6866-456f-9b66-7a09b4223ba5.png)

2022-04-05 18:25 UTC, ariya commented on frontend/src/metabase/visualizations/visualizations/Sankey.jsx
> +          "value": x[valueIndex]
For consistency with other charts, this could use the help of `formatValue` (from `metabase/lib/formatting`).

2022-04-21 13:52 UTC, morgan12 commented
I made some updates. Let me know if you all like this version.

2022-04-21 14:21 UTC, ariya commented
> I made some updates. Let me know if you all like this version.

Thanks @morgan12! While waiting for the review, can you sign the CLA? https://github.com/metabase/metabase/pull/21421/checks?check_run_id=6113091273

2022-04-26 06:22 UTC, ariya commented on frontend/src/metabase/visualizations/visualizations/Sankey.jsx
> +        <title>{this.props.name+"\n"+"Click to zoom out"}</title>
can this be made to use ttag (to support i18n)?

2022-04-26 06:23 UTC, ariya commented on frontend/src/metabase/visualizations/visualizations/Sankey.jsx
> +          "value": x[valueIndex]
@morgan12 did you try using `formatValue` here?

2022-05-07 07:09 UTC, DeanRickles commented
Hello @morgan12,

Love the new chart and really want to gve it a go.  I'm not a program develper and hoping you're able to make the requested changes so I and others can start using your chart!

Many thanks,
Dean

2022-10-23 01:47 UTC, jedashford commented
Would love to see this usable! We're evaluating other software because we need a sankey diagram for user journey visualizations.

2022-11-28 21:35 UTC, closed without merging