Fix `Metabase` name is still present despite whitelabel name existance
metabase/metabase pull request #21616
Opened 2022-04-12 13:57 UTC by WiNloSt

Fixes #17043

### Caveat
I'm not sure the implications of putting the settings inside a `t` (`ttag`). Not sure if it's gonna mess up our translation or not.

2022-04-14 06:59 UTC, WiNloSt commented on enterprise/frontend/src/metabase-enterprise/whitelabel/components/ColorSchemeWidget.jsx
> +                    {jt`${properties.description}`}
This translates the highlighted text.
![image](https://user-images.githubusercontent.com/1937582/162979447-a83ea11f-0a22-4b47-b184-78e665f4a51b.png)

2022-04-14 07:01 UTC, WiNloSt commented on frontend/src/metabase/admin/settings/components/SettingHeader/SettingHeader.jsx
> +            <strong>{jt`${setting.warningMessage}`}</strong>{" "}
Something in `setting` is probably a JSX, that's why when I used just `t` these tests failed.
- https://app.circleci.com/pipelines/github/metabase/metabase/33280/workflows/af1c70f4-a5f2-43f9-a952-1bf40ae1bf47/jobs/1715260
- https://app.circleci.com/pipelines/github/metabase/metabase/33280/workflows/af1c70f4-a5f2-43f9-a952-1bf40ae1bf47/jobs/1715201

2022-04-15 11:26 UTC, ranquild requested changes
While the fix seems to work, I found it very hard to understand, and I also had to go to `babel-plugin-ttag` docs.

I believe that the root cause is this line https://github.com/metabase/metabase/blob/6978a836dcf03a12328bd53d871513feb242f428/enterprise/frontend/src/metabase-enterprise/whitelabel/components/ColorSchemeWidget.jsx#L25 and the fact that it's initialized as a module-level constant. Could you try replacing `const COLOR_DISPLAY_PROPERTIES = ` with a function, e.g. `const getColorDisplayProperties = () => ({` and check if it solves the issue? Thanks!

2022-04-26 09:57 UTC, WiNloSt commented
@ranquild I reverted everything to master and tried using your suggestion the fix works for just the `ColorSchemeWidget`. Now I understood that there are 2 problems
1. declaring a `const` where it contains `t` won't change the text at runtime. e.g. `locale` changed or `whitelabel` is enabled for example.
2. Any `Metabase` text that's not processed by `ttag` won't change itself to the whitelabeled name this is what I originally write in the comment https://github.com/metabase/metabase/pull/21616#issue-1201894685.

So, for the fix to work I suggest keeping `SettingHeader.jsx` as is (in this PR), and I could use your suggestion for `[ColorSchemeWidget.jsx](https://github.com/metabase/metabase/pull/21616/files#diff-a79d11d3703bb952708d40f446007834e449172d0f9bca5af83f363675a3e52a)`. 

The reason I disabled `ttag` `SettingHeader.jsx` is because I'm wrapping a dynamic value in `ttag` which won't work as we have linter for it that ensure wrapped texts should be static. And I need the settings text to be wrapped within `ttag` since we wrote a plugin that replace every `Metabase` found in any given text wrapped within `ttag`. https://github.com/metabase/metabase/blob/d7223dc05d5b40296c7f58c9b6851e6da45a4e65/enterprise/frontend/src/metabase-enterprise/whitelabel/lib/whitelabel.js#L188-L190 Otherwise, I will need to duplicate `replaceApplicationName` or expose it and call it directly e.g.

```ts
    <SettingDescription>
      {setting.warningMessage && (
        <React.Fragment>
          <strong>{replaceApplicationName(setting.warningMessage)}</strong>{" "}
        </React.Fragment>
      )}
      {replaceApplicationName(setting.description)}
      {setting.note && <div>{replaceApplicationName(setting.note)}</div>}
    </SettingDescription>
``` 

which might still be less ambiguous. What do you think?

2022-04-26 12:03 UTC, ranquild commented
@WiNloSt I believe we shouldn't use unprocessed ttag literals as a way to get `Metabase` replaced. Based on my investigation `Metabase` string in settings comes from settings on the backend, like this https://github.com/metabase/metabase/blob/19beda53393ef761ef57ea7dbb5474f6f4d57dd2/src/metabase/public_settings.clj#L58. The fix would be changing `tru` declarations on the backend to use `site-name` setting instead of `Metabase` literal. 

I suggest the following
- Revert changes to `SettingHeader`, leave changes to `ColorSchemeWidget`, and merge this PR
- Fix the backend translation strings in a separate PR on the backend.

WDYT?

2022-04-26 12:04 UTC, ranquild requested changes
Comment above

2022-04-29 06:41 UTC, WiNloSt commented
@ranquild 

> I suggest the following
> 
> * Revert changes to `SettingHeader`, leave changes to `ColorSchemeWidget`, and merge this PR
> * Fix the backend translation strings in a separate PR on the backend.
> 
> WDYT?

Yeah, I start to think the fix I made is kind of hacky if I were to change the dynamic value from BE. That'd better be done on BE instead.

Sounds good for both points.

2022-04-29 08:52 UTC, ranquild approved these changes

2022-04-29 09:00 UTC, WiNloSt commented
I noticed that the unit tests failed. There's a [conversation on Slack about this](https://metaboat.slack.com/archives/C5XHN8GLW/p1651221110690589).

2022-04-29 11:21 UTC, merged