Allow users with block perms to still use the `rescan_values` APIs if they have DB details or data model perms
metabase/metabase pull request #21808
Opened 2022-04-20 16:54 UTC by noahmoss

WIP

2022-04-20 16:54 UTC, noahmoss commented on src/metabase/server/middleware/session.clj
> +          :left-join [[User :user] [:= :session.user_id :user.id]]
Unrelated formatting fix

2022-04-21 05:34 UTC, qnkhuat requested changes
Nice solution, it works for re-scan field values but still fails when I try to sync DB schema.

2022-04-21 14:08 UTC, luizarakaki commented
@qnkhuat Did you try to sync the DB schema on the DB page? Eg: http://localhost:3000/admin/databases/1?

I could both rescan values and sync the db schema, no problems.

2022-04-21 14:39 UTC, qnkhuat commented
hmmm, yea it works now...

2022-04-21 14:39 UTC, qnkhuat approved these changes

2022-04-21 21:54 UTC, merged