Prevent channging visibility_type when updating table properties
metabase/metabase pull request #22318
Opened 2022-05-02 11:05 UTC by qnkhuat

Fix #22287

2022-05-02 14:53 UTC, noahmoss approved these changes

2022-05-02 15:11 UTC, dpsutton commented
There's a subtlety that needs to be considered. We're tip-toeing around whether `:visibility_type` is present and nil and not present and got destructured as nil. When tables are hidden, we do not sync them. We someone unhides them, we are thus forced to resync them to get back up to date. 

```clojure
(defn- update-tables!
  [ids {:keys [visibility_type] :as body}]
  (let [existing-tables (db/select Table :id [:in ids])]
    (api/check-404 (= (count existing-tables) (count ids)))
    (run! api/write-check existing-tables)
    (let [updated-tables (db/transaction (mapv #(update-table!* % body) existing-tables))
          newly-unhidden (when (nil? visibility_type)
                           (into [] (filter (comp some? :visibility_type)) existing-tables))]
      (sync-unhidden-tables newly-unhidden)
      updated-tables)))
```
This will have the same bug as you are fixing here. Here it is looking for `nil` as the destructured value of `visibility_type` and it assumes then that any that are currently hidden were newly unhidden. But this is not true in this case. We'll need to change the `when`'s conditional to `(and (contains? body :visibility_type) (nil? (:visibility_type body))`. 

I recreated this issue, hiding a table called `foo`, changing its description and in the logs i see:
> 2022-05-02 15:09:12,220 INFO api.table :: Table 'foo' is now visible. Resyncing

2022-05-02 15:14 UTC, dpsutton requested changes
Update the logic of when to re-sync unhidden tables

2022-05-02 16:02 UTC, dpsutton approved these changes

2022-05-03 07:06 UTC, merged

2022-05-06 21:49 UTC, alxnddr commented
@qnkhuat why we did not backport it?