bumps outdated deps versions to be current
metabase/metabase pull request #22567
Opened 2022-05-09 23:05 UTC by escherize

The usual deps bump for a new major version.

fixes #22401 (by bumping liquibase to "4.10.0")

2022-05-09 23:55 UTC, rlotun commented
does it make sense to do the liquidbase update in a separate PR that can be backported since https://github.com/metabase/metabase/issues/22401 is a regression (that is spaces in env vars *used* to work in previous Metabase versions)

2022-05-10 15:00 UTC, dpsutton approved these changes

2022-05-10 15:03 UTC, qnkhuat commented
oh we're bumping h2 too? I think we're doing it separately in https://github.com/metabase/metabase/pull/22354

2022-05-10 15:09 UTC, flamber requested changes, later dismissed
Only upgrade Liquibase in this PR. Nothing else.
You cannot just bump core stuff like Jetty and H2 without everything exploding.

2022-05-10 17:21 UTC, camsaul commented on deps.edn
> +  kixi/stats                                {:mvn/version "0.5.5"               ; Various statistic measures implemented as transducers
I think this might have broken something last time I tried it. Just a heads up in case tests fail on X-Rays

2022-05-10 17:23 UTC, camsaul approved these changes
It seems like one of the version bumps dropped support for Java 8. Since we want to drop support for Java 8 in 44 anyway you can probably just go ahead and remove the Java 8 nodes from CI I think

2022-05-10 17:25 UTC, escherize commented
I'll keep messing with this until the tests are passing. Obviously we should upgrade as many libraries as we can.

2022-05-12 19:37 UTC, diogormendes commented
I think we can also go and remove 8 from Github like in here: https://github.com/metabase/metabase/blob/75747c1931f68d11feeb45a2aabc2e7a723af8f7/.github/workflows/uberjar.yml#L47

2022-05-12 20:41 UTC, dpsutton approved these changes
Looks good. The tests seem to be failing because we are now getting records instead of maps with revisions. That's really weird.

2022-05-18 02:32 UTC, merged