Alert to typescript
metabase/metabase pull request #22832
Opened 2022-05-19 09:42 UTC by losrebellos

Fixes #22829.

2022-05-30 18:37 UTC, npfitz approved these changes

2022-05-31 06:47 UTC, ranquild requested changes
`metabase-types/types` are deprecated, please use types from `api`

2022-05-31 09:31 UTC, ranquild approved these changes

2022-05-31 16:32 UTC, daltojohnso approved these changes

2022-05-31 16:46 UTC, merged