Allow multi-line strings using `str` in translation macros
metabase/metabase pull request #22901
Opened 2022-05-23 21:03 UTC by noahmoss

2022-05-23 21:17 UTC, noahmoss commented
@metamben Here's a potential alternative solution for some of the translation macro workarounds you're using in #22804.

2022-05-23 22:11 UTC, metamben approved these changes
If we prefer to have the text to be translated in a single chunk, then I think this solution is good. Also, my understanding is that after this change we will have the possibility to concatenate string literals where we had to write a single string literal, so this is an extension that should not break existing code.

2022-05-24 00:48 UTC, camsaul requested changes
The one line restriction isn't arbitrary, it's because the tool we use to scrape our source files doesn't support multi-line forms.

https://github.com/metabase/metabase/blob/master/bin/i18n/update-translation-template#L53-L69

IF you want to support multi-line forms you'll have to replace that tool with something more sophisticated. I would write some custom Clojure code that walks the source files without evaluating anything and then looks for the `tr*`/`deferred-tr*` forms and can handle `str` inside them

2022-05-24 01:21 UTC, noahmoss commented
@camsaul Ah, thanks for the context. I wasn't aware that's how the script worked...might try to tackle that at some point but probably not right away. Will close this PR in the meantime.

2022-06-06 20:51 UTC, dpsutton commented
@noahmoss in light of https://github.com/metabase/metabase/pull/23181, if that PR is merged can this PR be merged as-is or would I need to do anything?

2022-06-06 21:15 UTC, noahmoss commented
@dpsutton I think this PR should be good to go when that one is merged w/support for `(str ...)` forms.

2022-06-06 21:16 UTC, noahmoss commented
Or we could update this PR to add that support, if that would compartmentalize the changes better. I don't have a strong preference.

2022-06-08 16:23 UTC, dpsutton commented
So just merged the new pot creation script. I can finish this branch unless someone else wants to jump on. the fix is quite simple. In the file `bin/i18n/src/i18n/enumerate.clj` there's a function:

```clojure
(defn- form->string-for-translation
  "Function that turns a form into the translation string. At the moment
  it is just the second arg of the form. Afterwards it will need to
  concat string literals in a `(str \"foo\" \"bar\")` situation. "
  [form]
  (second form))
```

Form at this point will be a form like `(trs "Invalid foo: {0}" foo)` and right now it just takes `second`, in this case `"Invalid foo: {0}"`. We can update this to take second if second is a string, otherwise anticipate a `(str "string literal 1" "string literal 2")` and grab the literal forms and combine them.

2022-06-08 21:00 UTC, dpsutton commented
@camsaul can you mark your requested changes as completed?

```
;; the pot file
#: metabase/public_settings.clj:521
msgid ""
"Whether an introductory modal should be shown after the next database "
"connection is added. Defaults to false if any non-default database has "
"already finished syncing for this instance."
msgstr ""
```

```clojure
;; source
(defsetting show-database-syncing-modal
  (deferred-tru
    (str "Whether an introductory modal should be shown after the next database connection is added. "
         "Defaults to false if any non-default database has already finished syncing for this instance."))
  :visibility :admin
  :type       :boolean
  :getter     (fn []
                (let [v (setting/get-value-of-type :boolean :show-database-syncing-modal)]
                  (if (nil? v)
                    (not (db/exists? 'Database :is_sample false, :initial_sync_status "complete"))
                    ;; frontend should set this value to `true` after the modal has been shown once
                    v))))
```

2022-06-10 02:51 UTC, camsaul approved these changes

2022-06-10 13:37 UTC, merged