Save on AdHoc Question Title Click
metabase/metabase pull request #23470
Opened 2022-06-21 16:57 UTC by npfitz

Epic #22826 

Adds a click handler to the title of an unsaved question that will open the Save Question Modal, as well as re-locates the save button and removes the icon in the subhead data source.

![image](https://user-images.githubusercontent.com/1328979/174855840-031b883f-0393-460c-8f36-0a92155fd928.png)

2022-06-21 20:12 UTC, iethree requested changes
Works and looks great, I think there may have been an unintended CSS border added though.

2022-06-22 12:24 UTC, npfitz commented on frontend/src/metabase/query_builder/components/view/ViewHeader.styled.jsx
> +
I did (in the query builder header). Alternatively I could set up a container to put the button in that has the border/margin

2022-06-22 13:29 UTC, ranquild commented on frontend/src/metabase/query_builder/components/view/QuestionDescription.jsx
> +            .filter(x => !!x)
nit: `filter(Boolean)`

2022-06-22 13:33 UTC, ranquild commented on frontend/src/metabase/query_builder/components/view/QuestionDescription.styled.tsx
> +export const StyledSpan = styled.span`
nit: `AggregationAndBreakoutDescription`?

2022-06-22 16:21 UTC, iethree approved these changes
🎆

2022-06-22 17:03 UTC, merged