application-colors have new keys that may be added via the getter
metabase/metabase pull request #23493
Opened 2022-06-22 20:28 UTC by adam-james-v

Epic: #22816

Some colors previously had multiple usage contexts. 

For example, `accent1` was used both in charts and other parts of the summarize UI. Now, those notions are being separated, so `accent1` remains a valid key, and `summarize` is a new valid key. To make sure behaviour remains the same for existing whitelabel users who may have set these keys, when such a key exists, it is 'split' by the getter.

For example, if the existing `application-colors` json contains `accent1`, the getter will add a new key `summarize`
with the same value as `accent1`, but only if `accent1` already exists, otherwise it does nothing. This is also true
for keys `brand`, which adds `accent0`, and `accent7`, which adds `filter`

2022-06-22 20:46 UTC, escherize approved these changes

2022-06-23 10:01 UTC, ranquild requested changes
I don't think this code does what we want to do. E.g. after an upgrade to 0.44, it should be perfectly valid to have just `accent1: #f00` with a default value for `summarize`. This code would set `summarize` to the value of `accent1` in this case, and that's not what we want.

The idea was to implement this as a one-time migration. If it cannot be done as an SQL migration, we could add another setting to indicate that the colors were migrated. I.e. with the following getter:
```
if (!colorsAreMigrated) {
  setColors({ ...colors, accent0: colors["brand"], summarize: ..., filter: ... });
  setColorsAreMigrated(true);
}

return getColors();
```

2022-06-23 16:36 UTC, adam-james-v commented
> I don't think this code does what we want to do. E.g. after an upgrade to 0.44, it should be perfectly valid to have just `accent1: #f00` with a default value for `summarize`. This code would set `summarize` to the value of `accent1` in this case, and that's not what we want.

Ok, I'm confused then. I thought that setting summarize to value of accent1 was exactly what we wanted. At least, that was my understanding based on what was written in https://github.com/metabase/metabase/issues/22816 at the end.

> 
> The idea was to implement this as a one-time migration. If it cannot be done as an SQL migration, we could add another setting to indicate that the colors were migrated. I.e. with the following getter:
> 
> ```
> if (!colorsAreMigrated) {
>   setColors({ ...colors, accent0: colors["brand"], summarize: ..., filter: ... });
>   setColorsAreMigrated(true);
> }
> 
> return getColors();
> ```

Ok, I think that makes sense. The reason we can't do it as an SQL migration is because of how these settings are stored. The application colors get stored as a string of JSON in the app-db, and we don't restrict the shape of it, except through getters/setters in Clojure. We do have 'clojure land migrations', but we're deprecating usage of that, so I think for a case like this I won't use that kind of migration.

2022-06-23 18:49 UTC, ranquild approved these changes

2022-06-24 00:05 UTC, merged