Update and create crud actions work with more types + improved one-ness checking
metabase/metabase pull request #23530
Opened 2022-06-24 06:58 UTC by escherize

The way to check that 1 and only 1 record was deleted/updated was not working for more exotic types. So I've decided to use a rollback strategy if a non-1 number of rows are affected.

This doesn't cover all types but it covers quite a few. The ones listed here, as well as enums.

2022-06-27 17:29 UTC, snoe approved these changes

2022-06-27 17:30 UTC, snoe requested changes, later dismissed

2022-06-27 17:30 UTC, snoe commented on src/metabase/driver/sql_jdbc/actions.clj
> +      (do (jdbc/db-set-rollback-only! conn)
I believe this will need to be within a transaction.

2022-06-28 19:32 UTC, escherize commented on test/metabase/api/action_test.clj
> +          (is (= result-count (count (mt/rows (qp/process-query query-that-returns-more-than-one))))
Note: I added this check too to double check that the result count gets rolled back when it should.

2022-06-28 21:52 UTC, snoe approved these changes

2022-06-28 22:11 UTC, merged