docs - mysql json note
metabase/metabase pull request #23568
Opened 2022-06-27 14:34 UTC by jeff-bruemmer

- Adds note to MySQL page regarding JSON sync.
- Updates postgres page to specify 500 records (see https://github.com/metabase/metabase/pull/22662).

There is some repeated text here, but the duplication is probably okay for now. If we support JSON in more databases, we can consider creating a dedicated JSON page.

2022-06-27 16:45 UTC, nllho requested changes

2022-06-27 17:42 UTC, jeff-bruemmer commented on docs/administration-guide/databases/mysql.md
> +The problem is that if the keys in the JSON vary record to record, the first five hundred rows may not capture all the keys used by JSON objects in that JSON field. To get Metabase to infer all the J
@luizarakaki do you know the answer to @nllho's questions?

2022-07-06 18:21 UTC, luizarakaki commented on docs/administration-guide/databases/mysql.md
> +The problem is that if the keys in the JSON vary record to record, the first five hundred rows may not capture all the keys used by JSON objects in that JSON field. To get Metabase to infer all the J
The first 500 is what comes from `SELECT field FROM table LIMIT 500`. For MySQL and Postgres, this is deterministic, it always returns the same rows.

These rows are generally the first rows inserted into the table.

I'm not sure if there is ambiguity. Maybe we can explain how we get the first 500 rows, but I'm not sure if it necessary.

2022-07-06 18:34 UTC, nllho approved these changes

2022-07-07 17:32 UTC, merged