White background in pivot tables
metabase/metabase pull request #23624
Opened 2022-06-30 05:58 UTC by gitstart

###### Before submitting the PR, please make sure you do the following

- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [x] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [x] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

2022-07-11 20:06 UTC, alxnddr requested changes
@gitstart thank you for your contribution. Could you please rebase on the latest maser and format the code?

Also, it seems like your changes do not fix the issue fully:
<img width="1640" alt="Screenshot 2022-07-11 at 23 54 25" src="https://user-images.githubusercontent.com/14301985/178348179-e3f63dcf-1dcc-4529-abe9-501a2204c0c8.png">

Steps to reproduce:
- New -> Question -> Sample dataset -> Orders -> Visualize
- Summarize:
<img width="341" alt="Screenshot 2022-07-11 at 23 53 41" src="https://user-images.githubusercontent.com/14301985/178348827-126db8a4-5d94-4093-a639-ae2eb92b6607.png">
- Change the visualization type to Pivot Table with the following settings
<img width="353" alt="Screenshot 2022-07-11 at 23 53 22" src="https://user-images.githubusercontent.com/14301985/178348933-74a761d3-e6ef-4acd-9ee4-aebe585a5a33.png">
- Add it on a dashboard -> Full screen mode -> Dark mode

2022-07-19 08:38 UTC, gitstart commented
@alxnddr  Thank you for the review, pushed the full fix now. Could you please review again?

2022-07-21 10:25 UTC, alxnddr reviewed
Hey @gitstart thanks for the fixes!

In the light mode we highlight specific columns and rows:
<img width="1362" alt="Screenshot 2022-07-21 at 14 22 24" src="https://user-images.githubusercontent.com/14301985/180191668-ab2cef2e-0a7d-4a7d-b733-ca678755c8eb.png">

So it would be great to preserve it and do at least something like:
<img width="1361" alt="Screenshot 2022-07-21 at 14 22 14" src="https://user-images.githubusercontent.com/14301985/180191818-40b144cd-fc88-4168-a899-6c9378be790b.png">

To achive that instead of not applying `backgroundColor` when `isNightMode` is `true` you could add parameters to color functions like `getBgLightColor(hasCustomColors, isNightMode)`

And then use it like:
```js
const getBgLightColor = (hasCustomColors, isNightMode) => {
  if (isNightMode) {
    return lighten("bg-black", 0.3);
  }

  return hasCustomColors ? darken("white", 0.01) : lighten("brand", 0.65);
};

const getBgDarkColor = (hasCustomColors, isNightMode) => {
  if (isNightMode) {
    return lighten("bg-black", 0.1);
  }

  return hasCustomColors ? darken("white", 0.035) : lighten("brand", 0.6);
};
```

2022-07-21 21:08 UTC, alxnddr approved these changes

2022-07-21 21:08 UTC, merged