Update @testing-library/user-event to v14
metabase/metabase pull request #24087
Opened 2022-07-19 08:51 UTC by gitstart

Fixes [#23080](https://github.com/metabase/metabase/issues/23080)

###### Before submitting the PR, please make sure you do the following

- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [ ] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [ ] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).
 ### Demo

![Screen Shot 2022-07-13 at 10 32 09 AM](https://user-images.githubusercontent.com/31402501/178652754-caca3b7b-7eb7-4cb3-a358-2103471f8329.png)

2022-07-20 21:06 UTC, alxnddr requested changes
@gitstart tremendous job, thanks for your contribution! I left a few comments that would be great to address before merging

2022-07-20 21:06 UTC, alxnddr commented on frontend/src/metabase/core/components/AccordionList/AccordionList.unit.spec.js
> +      await waitFor(() => expect(screen.findByText("popover")));
This is not a correct check — there is no "popover" dom node, so seems like the test should be fixed

2022-07-27 16:48 UTC, gitstart commented
@alxnddr Tests have been updated, kindly take a look again

2023-09-27 21:41 UTC, iethree commented
closing due to massive number of conflicts. feel free to re-open with conflicts resolved.

2023-09-27 21:41 UTC, closed without merging