Filtering on empty cells by clicking on table is adding incorrect filter type
metabase/metabase pull request #24302
Opened 2022-07-26 11:13 UTC by gitstart

Fixes #23796 

###### Before submitting the PR, please make sure you do the following

- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [ ] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [ ] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

### Demo
https://www.loom.com/share/0c8c70e506324436a36c39ab41ef9174

2022-07-26 16:32 UTC, iethree requested changes

2022-07-26 16:32 UTC, iethree commented on frontend/src/metabase-lib/lib/queries/structured/Filter.ts
> +  }
We shouldn't bypass the logic of `setOperator`

2022-07-26 16:32 UTC, iethree commented on frontend/src/metabase-lib/lib/queries/structured/Filter.ts
> +        }
while we're at it, we should also handle `is-empty` and `not-empty`

2022-08-02 14:14 UTC, gitstart commented
@iethree Thank you for the review. Requested changes have been implemented, kindly look into it again

2024-06-26 09:34 UTC, nemanjaglumac commented
Already fixed.

2024-06-26 09:34 UTC, closed without merging