basic conditional formatting
metabase/metabase pull request #24930
Opened 2022-08-22 19:19 UTC by alxnddr

2022-08-25 12:06 UTC, ranquild commented on frontend/src/metabase/visualizations/visualizations/PivotTable.styled.tsx
> +const EMPHASIZED_BG_COLOR = "#F8FAFB";
Can this color be computed from existing ones?

2022-08-25 12:58 UTC, ranquild requested changes
@alxnddr I've tried using new formatting settings with a slightly different query and it doesn't seem to work for me. The result below is unexpected, is it?

<img width="1197" alt="Screenshot 2022-08-25 at 15 57 32" src="https://user-images.githubusercontent.com/8542534/186670904-5a160237-bd7d-4e36-bcc7-595e0727a831.png">

I also see some strange columns
<img width="354" alt="Screenshot 2022-08-25 at 15 59 18" src="https://user-images.githubusercontent.com/8542534/186671197-1af10528-7e92-4981-ab79-2fa99e13abe0.png">

2022-08-25 13:00 UTC, alxnddr commented
@ranquild based on your screenshots, you don't have the latest changes since the pivot table has old styling

2022-08-26 11:37 UTC, ranquild approved these changes

2022-08-26 16:16 UTC, merged

2022-09-29 19:13 UTC, mvtemple commented
hi @alxnddr - I don't see this in my UI yet, has this been released?

2022-09-29 19:29 UTC, alxnddr commented
Hey @mvtemple, this feature will be included into the upcoming x.45.0 release