Implement navigation between data app pages
metabase/metabase pull request #25366
Opened 2022-09-12 17:56 UTC by kulyk

Closes #25365, based on BE work from #25343

Implements smooth navigation between data app pages. When BE generates list and detail pages:

1. List page has a "list" dash card. It now has a [custom destination click behavior](https://www.metabase.com/learn/dashboards/custom-destinations) with `linkType: "page"` pointing to the detail page.
2. Detail page has a "Back to list" button with the same click behavior, but it points back to the list page

The "page" click behavior works almost the same as the "dashboard" click behavior, but it uses `react-router` to perform the transition, so it's absolutely smooth as opposed to a page reload.

### To Verify

1. New > App > Pick a table > Create
2. Select the "List" page in the app navigation sidebar (the detail page shouldn't be open first really, it's going to be fixed in one of the subsequent PRs)
3. Click any list item
4. Ensure you're navigated to a detail page with the item ID you clicked now passed to detail's page dashboard filter
5. Click the "Back to list" button under the ID filter
6. Ensure you're back to the list page

### Demo

https://user-images.githubusercontent.com/17258145/189723445-ef3d36a1-5a81-45e5-b829-a1857d9645a8.mp4

2022-09-12 17:59 UTC, kulyk commented on frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkedEntityPicker.tsx
> +function LinkedEntityPicker({
Renaming since it's not really a `QuestionDashboardPicker` anymore and `QuestionDashboardPagePicker` is too much for me

2022-09-12 17:59 UTC, kulyk commented on frontend/src/metabase/visualizations/hoc/WithVizSettingsData.js
> +      }),
The diff highlight is going crazy here. There are only two changes here:

1. We're now adding router `location` and `params` props to the final object here
2. The whole thing is now wrapped into `withRouter` HoC to ensure these props are available

2022-09-12 20:38 UTC, iethree requested changes
This looks great overall, a couple code nits, and I think one major bug: I can't manually create or edit a link-to-page action button because the "done" button stays disabled.

![Screen Shot 2022-09-12 at 1 04 21 PM](https://user-images.githubusercontent.com/30528226/189753764-700be1bb-366d-47a9-bfed-031c5f7b04ff.png)

Left a comment about one other bug which i think is a smaller edge case we should probably deal with separately.

2022-09-13 14:45 UTC, kulyk commented
Great catch and suggestion @iethree, fixed both 👍

2022-09-13 16:19 UTC, iethree approved these changes
👍 Looks good and works for me!

Sorry, there's one more bug I forgot to comment on yesterday, but I don't think it needs to block this merge.

If you go straight to a page with a page-nav button, it doesn't work. But, if you navigate to the target page, then back, it does work. 🤷 

![doesntWorkInitially](https://user-images.githubusercontent.com/30528226/189953992-15e7ec4e-2519-4086-b542-9791e3e717bd.gif)

2022-09-13 16:32 UTC, kulyk commented
@iethree yeah, I noticed that too. User shouldn't really land in this kind of scenario; let's see how it all works together with hidden pages support and stuff

2022-09-13 16:37 UTC, merged