Return app_id for dashboard bookmarks
metabase/metabase pull request #25419
Opened 2022-09-14 18:57 UTC by metamben

Fixes #25418.

2022-09-14 19:03 UTC, metamben commented on test/metabase/models/bookmark_test.clj
> +             (#'bookmark/normalize-bookmark-result row))))))
Although this test specifies a desirable property, it doesn't prevent us from removing the `cond->` around the `(into ...)` form at line 42 in `src/metabase/models/bookmark.clj`. It's difficult to influence the order in which the map created by `(into ...) gets walked from outside and it so happens, that at least on my machine, the name and description of the dashboard shadow the name and the description of the collection.

If you have a good idea how to cost effectively test this, please let me know.

2022-09-14 22:49 UTC, snoe approved these changes

2022-09-14 22:49 UTC, snoe commented on src/metabase/models/bookmark.clj
> +        _ (tap> (keys result))
Remove tap

2022-09-14 22:50 UTC, snoe requested changes
fix the tap and it lgtm

2022-09-20 19:55 UTC, snoe approved these changes

2022-09-20 19:55 UTC, merged