Keep "model" in URL when creating fresh model
metabase/metabase pull request #25799
Opened 2022-10-05 17:04 UTC by gusaiani

### How to Test

1. `+ New`
2. Model
3. Choose either mode

URL should be http://localhost:3000/model/query#…aHash

(before it was http://localhost:3000/*question*/query#…aHash)

2022-10-05 19:37 UTC, ranquild requested changes
I don't think that's the correct way of doing this. We should keep `dataset` flag in the serialized card state and generate a dataset card url when clicking on New -> Model. It seems that we currently don't serialize this flag https://github.com/metabase/metabase/blob/ab828e7b40dbc93316b5c32f5441bd4fc56f6e67/frontend/src/metabase/lib/card.js#L40 so this should be fixed first

2022-10-06 13:02 UTC, daltojohnso requested changes

2022-10-10 16:33 UTC, gusaiani commented
@ranquild @daltojohnso Now passing dataset from the moment a link to a new model page is serialized.

2022-10-10 16:36 UTC, ranquild commented on frontend/src/metabase-lib/lib/Question.ts
> +      dataset,
I believe it the question was the url was created correctly, we wouldn't `dataset` to `serializeUrl`

2022-10-10 16:41 UTC, ranquild requested changes
Please take a look at the comment and this loom https://www.loom.com/share/75ee5477af324c9fb5dff3713126100d

2022-10-10 17:46 UTC, gusaiani commented
@ranquild Thanks, it came down do that one-liner.

2022-10-10 17:50 UTC, ranquild approved these changes

2022-10-10 17:51 UTC, ranquild commented
@daltojohnso Please take a look to - @gusaiani won't be able to merge the PR since changes were requested

2022-10-10 18:04 UTC, daltojohnso approved these changes

2022-10-10 18:05 UTC, merged