Fix time period selector can cause blank screen under some circumstances
metabase/metabase pull request #26286
Opened 2022-11-08 10:22 UTC by swk777

Fixes: #26265

###### Before submitting the PR, please make sure you do the following

- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

### Tests

- [ ] Run the frontend and Cypress end-to-end tests with `yarn lint && yarn test`)
- [ ] If there are changes to the backend codebase, run the backend tests with `clojure -X:dev:test`
- [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
      (unless it's a tiny documentation change).

2022-11-10 10:23 UTC, ranquild requested changes
There should never be `null` or `undefined` clauses in a query. Instead of fixing it here, we should prevent adding such clauses to the query.

2022-11-10 11:03 UTC, WiNloSt reviewed
Hi @swk777 , thanks for contributing to Metabase.

While this solves the bug in #26265, I don't think it addresses the root problem.

First, let's see `Q.getFilters`'s signature

https://github.com/metabase/metabase/blob/af232cbfbc4fffdc675e8062f2be537be220b61c/frontend/src/metabase-lib/queries/utils/query.js#L46

While there's no type there, we can see the original type for this function [which was removed in this PR](https://github.com/metabase/metabase/pull/19215/files#diff-4efe49e2119a0c7af405e8234edb18453eed4629c1fa86efc7b4606f3ae6d8e7L20).
https://github.com/metabase/metabase/blob/a50fd9b898bbc67829fe4a1480398472621a9998/frontend/src/metabase/lib/query/filter.js#L20

And its return type is a list of `Filter`, and `null` isn't compatible with it

https://github.com/metabase/metabase/blob/af232cbfbc4fffdc675e8062f2be537be220b61c/frontend/src/metabase-types/types/Query.ts#L136

We can also verify that with TypeScript
![image](https://user-images.githubusercontent.com/1937582/201074560-ae9c243e-2058-4c02-8af2-071e44f02e37.png)

One of the places that I think it might make more sense to filter out `null` filter is here
https://github.com/metabase/metabase/blob/af232cbfbc4fffdc675e8062f2be537be220b61c/frontend/src/metabase-lib/queries/utils/filter.js#L14

@ranquild maybe you could confirm that.

2022-11-14 04:02 UTC, swk777 commented
I did some investigation and found it's related to the option "All Time" whose value is null. Please check @ranquild @WiNloSt

2022-11-14 05:07 UTC, WiNloSt commented
@swk777 I'd say `null` value is expected. Since you should be able to remove the filter and `All time` is kind of remove the time filter.

Here I have a filter set to `Last month`
![Screenshot 2022-11-14 at 12 01 55 PM](https://user-images.githubusercontent.com/1937582/201579483-80e738c5-71aa-4f00-8f01-105e80cfe339.png)

After setting to `All time` it removes the filter
![Screenshot 2022-11-14 at 12 02 08 PM](https://user-images.githubusercontent.com/1937582/201579584-8ebf7f68-44bd-4759-a8ed-b18895831813.png)

So, `null` isn't a problem here. The problem is like @ranquild and I indicated that the **individual** filter—not the filter clause itself—should never be `null` or `undefined`

If I remember correctly the filter clause that cause the bug looks something like:
```JS
["and", filter_1, filter_2, null]
```

And the clause should never contain nullish value. It's expected to look like this instead `["and", filter_1, filter_2]`, so the problem is what causes the `null` value to be included in the filter in the first place.

2022-11-14 08:13 UTC, swk777 commented
> 
agree
https://github.com/metabase/metabase/blob/2a9fcbf3a74702ecd2c327f8a41354e24a873c10/frontend/src/metabase/query_builder/components/filters/pickers/LegacyDatePicker/DatePicker.jsx#L180

the "All Time" init value is null, so I remove it. Maybe it should be changed to another value?

2025-02-05 01:33 UTC, closed without merging