memoize snowflake describe-database w/ 5 min ttl
metabase/metabase pull request #26810
Opened 2022-11-29 23:52 UTC by escherize

I've solved the excessive re-querying issue by putting a time to live cache on snowflake's implementation of `describe-database`.

```mermaid

graph TD
POST_:id/sync_schema --> api/write-check
POST_:id/sync_schema --> future
future --> sync-metadata/sync-db-metadata!
sync-metadata/sync-db-metadata! --> sync-operation
sync-operation --> timezone
sync-operation --> tables
sync-operation --> fields
sync-operation --> fks
sync-operation --> metabase-metadata

future --> analyze/analyze-db!

%% :private_key_value --> resolve-private-key
%% :private_key_path --> resolve-private-key
%% resolve-private-key --> private_key_file

analyze/analyze-db! --> sync-operation2[sync-operation]
sync-operation2[sync-operation] --> fingerprint-fields
sync-operation2[sync-operation] --> classify-fields
sync-operation2[sync-operation] --> classify-tables

style tables color:#f22
style metabase-metadata color:#f22
```

`sync-tables` and `metabase-metadata` both call `describe-tables`, but we should only call it once for the sync operation.

To just call it once per sync, I've memoized the snowflake describe-tables call with a time to live cache. This way it is only called once per sync. If `metabase-metadata` gets a different result from `sync-tables`, then odd things can happen. This makes that race condition very unlikely.

Note: After the ttl timeout, the value will be removed from the cache. That is to say that the ttl is not reset when calling the function. and the cache works independently of different databases.

E.g:

```
     miss   hit              hit       miss       hit
      |     |                |          |         |
      v     v                v          v         v
------[============================]----[============================]
      [ cache full ================]    [ cache full ================]

```

2022-11-29 23:56 UTC, escherize commented
Not sure if 5 minutes is right here, but this will resolve both: redundant ❄️ queries, and the race condition.

2022-11-30 20:16 UTC, metamben reviewed
Especially if consistency (i.e., that the table descriptions are equal) is important, wouldn't be better to make `sync-tables` and `metabase-metadata` get the result of `describe-tables` as input parameter? This solution feels more like a work around than a real fix.

2022-11-30 20:16 UTC, metamben commented on modules/drivers/snowflake/src/metabase/driver/snowflake.clj
> +(defn describe-database* [database]
Might make sense to keep the `driver` parameter, so that drivers inheriting from snowflake can profit from it.

2022-12-01 05:33 UTC, escherize commented
I'll reopen this tomorrow

2022-12-02 14:39 UTC, metamben approved these changes
LGTM. My only concern is that making the `.getPrimaryKeys` calls with dbname and schema might break other drivers. If the tests pass, it's good, IMO.

2022-12-02 14:39 UTC, metamben commented on src/metabase/sync/sync_metadata.clj
> +(defn ^:private make-sync-steps [db-metadata]
```suggestion
(defn- make-sync-steps [db-metadata]
```

2022-12-02 14:39 UTC, metamben commented on test/metabase/sync/util_test.clj
> +        ;; Check the number of syncs that took place. Should be 1 (just the first)
This comment is no more helpful than the actual check following it and I don't quite understand "just the first". I would remove the comment.

2022-12-02 17:42 UTC, luizarakaki requested changes
@escherize It is now running the sync only once 🙌 , but I'm getting this exception when trying to sync FK

```
[backend] 2022-12-02 14:38:51,877 INFO sync.util :: STARTING: step 'sync-fields' for snowflake Database 5 'Snowflake Dev'
[backend] 2022-12-02 14:38:52,361 WARN sync.util :: Error syncing Fields for Table 'Table 92 'PUBLIC.TIMESTAMP_TEST''
[backend] clojure.lang.ArityException: Wrong number of args (2) passed to: metabase.driver.sql-jdbc.sync.describe-table/add-table-pks
```

2022-12-05 18:37 UTC, luizarakaki approved these changes
LGTM!

2022-12-05 21:49 UTC, escherize commented
Once I get the `Oracle` test working, I'll go ahead and merge this.

2022-12-08 21:15 UTC, merged