Manual backport: datetime-diff function for SQL Server #27002
metabase/metabase pull request #27074
Opened 2022-12-08 14:33 UTC by calherries

This is a manual backport for https://github.com/metabase/metabase/pull/27002

2022-12-09 09:06 UTC, calherries commented on test/metabase/query_processor_test/date_time_zone_functions_test.clj
> +                        (filter mt/supports-time-type?))
Note snowflake coverage on this test will be added here https://github.com/metabase/metabase/pull/27068#top

2022-12-09 09:08 UTC, calherries commented on test/metabase/query_processor_test/date_time_zone_functions_test.clj
> +                            {:second 82800 :minute 1380 :hour 23 :day 0})
SQL server doesn't support set-timezone, so this change verifies that setting the report-timezone doesn't have an effect.

2022-12-10 05:41 UTC, camsaul approved these changes
I'll go ahead and 👍 since this is just a backport but I would have liked to have reviewed the original version of it

2022-12-13 23:12 UTC, camsaul requested changes
Sorry, I think I jumped the gun on approving this.

Our general policy is not to ship new features in point releases. Point releases are just for bug and security fixes. It seems unlikely, but it's possible this change can introduce new bugs, so it's best to give it bake time.

Maybe there is some really compelling reason we would want to ship this in a point release, but I haven't heard anything about doing so. Let me know if there is actually some reason to ship this in 45.x

2022-12-14 08:29 UTC, calherries commented
My bad, I was under the impression that adding driver support for existing custom expression functions was something we could do in a point release. Nobody I've talked to about this had suggested otherwise.

For transparency snowflake's datetimeDiff support was added in 0.45.1 https://github.com/metabase/metabase/pull/26746
and redshift and vertica support is geared up to go in 0.45.2. I'll revert redshift and vertica backports.

2022-12-14 08:29 UTC, closed without merging