Fix Zero Filters not loading URL Parameters
metabase/metabase pull request #27342
Opened 2022-12-19 22:43 UTC by iethree

resolves #27257

## Description

Our `TextWidget` component was not handling numeric zeroes correctly. When we load in a query parameter of zero, the `||` operator coalesced it to an empty string.  Here, I have used the null-coalescing operator `??` to only coerce `null` and `undefined` values to an empty string, which will allow numeric zeroes to populate properly in the `TextWidget` component.

![zeroPreserved](https://user-images.githubusercontent.com/30528226/208540806-a43b9b64-8af5-411e-959c-04dceeabc884.gif)

## Testing Steps

- Create a new sql query : `SELECT {{ num }}`
- fill in a `0` in the input
- refresh the page
- see that the zero populates in the numeric input

2022-12-20 02:46 UTC, alxnddr approved these changes

2022-12-20 08:50 UTC, nemanjaglumac commented
Excellent. Thank you for adding unit tests on top of this :)

One thing I don't understand: 
Why don't we want `NumberInputWidget` component here ["at all"](https://github.com/metabase/metabase/issues/27257#issuecomment-1358571381)? We're explicitly setting the widget type to be "Number" in the UI.

2022-12-20 20:00 UTC, nemanjaglumac requested changes
We need to expand tests.
This input should be able to accept (and preserve) multiple comma-separated values.

## Scenarios
1. type `1,2,3,4,5,6`
2. run query
3. refresh
4. make sure the input is preserved (spoiler alert - it's not)

- Another things to try:
    - `1,2,3,` (notice trailing comma at the end)
    - `0,1,2,3,0`
    - `0,0,0,0,0`
    - `00000,1,2,3`
    - `0000`

---

1. type `1, 2 ,3,4,5,6` (notice the whitespace)
2. query will fail with `Unparseable number: " 2 "`

- At the same time, why is it possible to parse `1,2 ,3` but not `1, 2,3` or `1, 2, 3`?
- Another things to try: `,,` | `,,,,,` | `, ,`(space) | `,      ,`
---

1. **paste** `1,2,3,4,5,6` (just to make sure we don't have [this problem](https://github.com/metabase/metabase/issues/21385))
2. run query
3. refresh
4. make sure the input is preserved

--- 

When we're already thinking about different combinations, it's worth noting that https://github.com/metabase/metabase/issues/15295 exists. Not saying you have to tackle it in this PR, but maybe you can see a solution for it as well.
Anyway, just putting it on your radar.

2022-12-21 17:33 UTC, nemanjaglumac approved these changes
This PR fixed the related issue.
It's totally fair to merge it, and we can follow up with the next issue based on [this comment](https://github.com/metabase/metabase/pull/27342#pullrequestreview-1225060680).

2022-12-21 18:54 UTC, iethree commented
I appreciate the detailed feedback @nemanjaglumac  ❤️ . It doesn't appear that we support loading comma-separated values for parameters from URLs at all in the application. Doing so would likely be a fairly major project and involve pretty serious extensions to existing UI components or the creation of new ones. In addition, we would need to rework how we handle the logic of loading URL parameters into the redux store.

Given this complexity, and  unless we here differently from users, I think persisting comma-separated query parameters through page refreshes is probably too small an issue to devote significant development time at this point.

2022-12-21 19:09 UTC, merged

2022-12-22 12:38 UTC, nemanjaglumac commented
> It doesn't appear that we support loading comma-separated values for parameters from URLs at all in the application 

@iethree see this issue https://github.com/metabase/metabase/issues/25374. It's marked as a regression so it seems there was a way to achieve this in v44.

2022-12-22 13:52 UTC, iethree commented
> > It doesn't appear that we support loading comma-separated values for parameters from URLs at all in the application
> 
> @iethree see this issue #25374. It's marked as a regression so it seems there was a way to achieve this pre v44.
> 
> Edit: I tested it on 39.3 and indeed it works `/question/1?number=1%2C2%2C3%2C4`

I'm happy to address #25374 if you think it should be escalated.