Remove hard coded minimum width from the Google button
metabase/metabase pull request #27440
Opened 2022-12-28 10:47 UTC by nemanjaglumac

Fixes #27431

This PR removes hard coded `min-width` CSS property set on the GoogleLogin button.
It was first added [in this PR](https://github.com/metabase/metabase/pull/22868/files#diff-e1888d8af8301f423f898d9d6bb24b456face8148af9cb549378f3b1ca569883R51) by @gusaiani, which is the reason I'm adding him to the reviewers. There was probably a very good reason why that minimal width was added back then. Although I tried many different screen sizes top check that this button renders correctly, I'd still be much more confident with @gusaiani 's review.

**Before**

**After**

2022-12-28 10:53 UTC, gusaiani approved these changes
I wish I had a very good reason to share for the 366.
If there ever was one, I forgot it.

2022-12-28 11:45 UTC, nemanjaglumac commented
@gusaiani I am looking at the real world scenario now and the screenshot from the original issue.

When you actually set up a provider instead of mocking it, you see how the button layout changes? There is "Sign in as..." on the left and the Google logo is on the right.
![image](https://user-images.githubusercontent.com/31325167/209807139-958df96a-daa1-41cb-a335-8e6e247abafa.png)

Could it be that you've set that minimum width to accommodate the content on the left?

2022-12-28 19:58 UTC, gusaiani requested changes
Manually testing here, which I should have done before, shows that without a width value, on desktop it will look like below.

I've cooked up a solution here, please take a look: https://github.com/metabase/metabase/pull/27446

<img width="881" alt="image" src="https://user-images.githubusercontent.com/380816/209865650-c6b11ab2-3e5e-46d9-a4bc-0962bbdfc93c.png">

2023-01-04 12:15 UTC, ranquild reviewed
Please use the solution for centerrng from the comments

2023-01-04 19:44 UTC, gusaiani commented
@nemanjaglumac, as you were OOO this week and the alternative PR was all right, I merged that one into master.

Cheers!

2023-01-04 19:44 UTC, closed without merging