Fix ParamMapping schema on dashboard
metabase/metabase pull request #27623
Opened 2023-01-11 10:09 UTC by qnkhuat

2023-01-11 10:27 UTC, qnkhuat commented on src/metabase/models/dashboard.clj
> +  {:id                    su/NonBlankStringPlumatic
the bug from 24500 is from when calling `dashboard->resolved-params*`, it expects output that has a nonblankstring name.

As described in the PR's description. Name is not required, so we will mark them as optional here.

2023-01-11 11:21 UTC, qnkhuat commented
@nemanjaglumac could you please help me with the failing Cypress test?

FYI:
- Parameter with empty name is a valid parameter, it's not corrupted
- If we create a parameter with empty name using UI, FE will automatically fill the name with `unnamed`

2023-01-12 13:11 UTC, tsmacdonald commented on test/metabase/models/dashboard_test.clj
> +  (testing "parametesr with null or empty name should works (#24500)"
```suggestion
  (testing "parameters with null or empty names should work (#24500)"
```

2023-01-12 13:11 UTC, tsmacdonald approved these changes
Does what it says on the tin :boat:

2023-01-12 17:44 UTC, nemanjaglumac requested changes
Making the schema loose leads to a different can of worms.

> Even though the bug is already fixed because FE will replace an empty name with unnamed.

See https://github.com/metabase/metabase/issues/27653 for more details.
I'll repeat the important bit here: FE uses `name` to derive a `slug`, and without a `slug` it's impossible to distinguish between multiple unnamed filters in the query parameters.

As @qnkhuat and I saw during the video chat, leaving both `name` and the `slug` empty (this is only possible using the API and bypassing FE) can have really ugly consequences.

1. query parameters will be set without a slug, and only with a value like so `?=foo`
2. on a dashboard refresh, this filter value will be dropped

Blocking the merge until we discuss how to approach this problem and whether it's worth protecting against unnamed filters in the first place.

2023-01-30 07:29 UTC, qnkhuat commented
as @nemanjaglumac pointed out, the approach of this PR does not solve the root cause.
We should make parameter's  name required and unique on both FE and BE and close it https://github.com/metabase/metabase/issues/27653 altogether.

2023-01-30 07:29 UTC, closed without merging