[Feature] Allow actions to be shared via public link: Milestone 2
metabase/metabase pull request #27845
Opened 2023-01-23 22:53 UTC by calherries

This PR targets milestone 2 of "Allow actions to be shared via public link".

Epic: https://github.com/metabase/metabase/issues/27626

2023-02-06 22:00 UTC, calherries commented on frontend/src/metabase/actions/containers/ActionCreator/ActionCreator.unit.spec.tsx
> -  queryIcon,
This was somehow unused and preventing me from committing, so I removed it.

2023-02-07 02:54 UTC, qnkhuat requested changes
I should have mentioned this in the milestone 1 PR, but application permissions should have tests in https://github.com/metabase/metabase/blob/master/enterprise/backend/test/metabase_enterprise/advanced_permissions/api/setting_test.clj

2023-02-07 08:38 UTC, calherries commented
@qnkhuat Good catch, I'll add those today

2023-02-08 05:28 UTC, qnkhuat approved these changes

2023-02-09 10:16 UTC, calherries commented
Reminder TODO: once Tim's work on https://github.com/metabase/metabase/pull/27866 is merged, I'll have to make sure the endpoint doesn't return archived actions

2023-02-14 15:59 UTC, merged