Fallback to generating action form fields from parameters
metabase/metabase pull request #28512
Opened 2023-02-21 23:01 UTC by iethree

background: https://metaboat.slack.com/archives/C04FG88HL95/p1677015835193029

### Description

- At some point, the backend stopped populating the model card and its `card.result_metadata` that we were using to build richer and more appropriate forms for implicit actions.
- In the absence of that metadata (which I hope we can get back), this allows the frontend to make some smarter form field picking decisions based on parameters alone. It's still not as good as what we could do with `card.result_metadata`, but we can at least prettify some field titles and appropriately show date/boolean inputs, etc.

Before | After
--- | ---
![Screen Shot 2023-02-21 at 3 53 46 PM](https://user-images.githubusercontent.com/30528226/220477745-613cc188-937d-4280-ab57-4835a96add9b.png) | ![Screen Shot 2023-02-21 at 3 53 26 PM](https://user-images.githubusercontent.com/30528226/220477749-f2873b76-8348-42e5-a52e-c2f079b66d78.png)
![Screen Shot 2023-02-21 at 3 58 25 PM](https://user-images.githubusercontent.com/30528226/220477968-ddb96a38-5db3-4419-bdeb-de63f1a36d86.png) | ![Screen Shot 2023-02-21 at 3 58 44 PM](https://user-images.githubusercontent.com/30528226/220477970-1c2d70ad-b7cc-4fca-9278-e9aa49c1f36e.png)

### How to verify

- enable implicit actions on a model, like the `orders` table
- see that when you preview the form, you get prettified fields and appropriate form fields for dates

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

2023-02-22 13:14 UTC, ranquild requested changes
To confirm, is this only about implicit actions?

2023-02-22 15:26 UTC, iethree commented on frontend/src/metabase/actions/utils.ts
> +          base_type: param.type,
Why do you think that? I think currently the api for action parameters is always giving us their `base_type`

![Screen Shot 2023-02-22 at 8 24 12 AM](https://user-images.githubusercontent.com/30528226/220669257-ae96b10a-53ce-4a6c-9f62-4310c25a96c5.png)

2023-02-22 15:28 UTC, iethree commented
> To confirm, is this only about implicit actions?

Currently, this code path is only used for implicit actions because we have to infer the shape of the form fields - for custom query actions, we (a) can't infer anything since we can't introspect the schema from their sql query, and (b) can build the form from the settings chosen y the user.

2023-02-23 12:31 UTC, ranquild commented on frontend/src/metabase/actions/utils.ts
> +          base_type: param.type,
I see - action parameters use a different type system than regular parameters :(((

2023-02-23 12:31 UTC, ranquild approved these changes

2023-02-24 10:22 UTC, merged