Set action.model_id to cascade on delete
metabase/metabase pull request #28518
Opened 2023-02-22 07:07 UTC by qnkhuat

2023-02-22 07:33 UTC, qnkhuat commented on resources/migrations/000_migrations.yaml
> +            onDelete: CASCADE
actually we don't need to do anything on rollback because `action.model_id` will be deleted anyway

2023-02-22 08:24 UTC, tsmacdonald approved these changes

2023-02-22 15:22 UTC, dpsutton requested changes, later dismissed
I'd love to see some tests for this.

2023-02-23 14:54 UTC, qnkhuat commented
@dpsutton I added test and it looks trivial, so I'm gonna dismiss your requested change.

2023-02-23 14:54 UTC, merged