De-crazy the expression editor function helper popover
metabase/metabase pull request #28678
Opened 2023-02-27 15:53 UTC by deniskaber

Closes https://github.com/metabase/metabase/issues/28668, check it for full details

### Description

We want to improve expression editor helper popover to make it less overwhelming and more clean and helpful.
To achieve that we want to change it's design and structure.

<table>
<tr>
<th> Before: </th>
<th> After: </th>
</tr>
<tr>
<td>

<img width="350" alt="Screenshot 2023-02-27 at 19 34 09" src="https://user-images.githubusercontent.com/7983744/221607763-7f4cd944-00e9-4b0e-9057-ce1487ce7bd1.png">

</td>
<td>

<img width="350" alt="Screenshot 2023-02-27 at 19 41 14" src="https://user-images.githubusercontent.com/7983744/221609926-ef52ac72-0e23-4190-b96b-53f5f4f5b81a.png">

</td>
</tr>
</table>

### How to verify

1. Start creating a new Question: click "New" button in the top bar -> Question.
2. Click "Custom column" in the Notebook.
3. Appeared expression editor should have new design and experience.

### Demo

https://user-images.githubusercontent.com/7983744/223769602-b2deaf75-3e47-4891-92c6-f76644abf793.mov

### Checklist

- [x] [Refactored ExpressionWidget, ClauseStep components to TS](https://github.com/metabase/metabase/pull/28687)
- [x] [Change expression editor title, Implement info tooltip](https://github.com/metabase/metabase/pull/28776) 
- [x] [Change popover structure to match proposed design](https://github.com/metabase/metabase/pull/28920)
- [x] [Add interactivity for popover parameters](https://github.com/metabase/metabase/pull/28966)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metabase/metabase/28678)

2023-03-09 00:03 UTC, mazameli requested changes
On custom filter expressions, the helper popover seems to be tethered to the bottom of the parent popover. The expectation is that it would instead appear right below the input box.

<img width="548" alt="image" src="https://user-images.githubusercontent.com/2223916/223880611-b04e25d4-403e-4487-bedc-3261bce48be7.png">

2023-03-09 00:33 UTC, mazameli commented
I did not spec this, but a thought that occurred to me is that we could try this icon so that it turns blue on hover, and would be clickable and would take you to [the documentation](https://www.metabase.com/docs/latest/questions/query-builder/expressions) on click. We could add to the tooltip the sentence, `Click for documentation.`

Could we try that?

<img width="479" alt="image" src="https://user-images.githubusercontent.com/2223916/223884162-b511e2a0-1361-4c48-bc8b-d852ef6d9f8b.png">

2023-03-09 19:07 UTC, ranquild commented
@deniskaber I think we should address this
```
I did not spec this, but a thought that occurred to me is that we could try this icon so that it turns blue on hover, and would be clickable and would take you to [the documentation](https://www.metabase.com/docs/latest/questions/query-builder/expressions) on click. We could add to the tooltip the sentence, Click for documentation.

Could we try that?
```
in the scope of this epic. This is a regression caused by this integration branch - we effectively remove the help link for expression.

We need to check whether this can be reproduced in master. If not, then we need to fix this here, too:
```
Another bug I found: updating an existing custom column will incorrectly duplicate the column. It should replace it instead. See this recording: https://www.loom.com/share/7b57e79f763e4b95ad0f28576d627c18
```

There is no rush to get this epic completed.

2023-03-14 15:18 UTC, mazameli commented
@deniskaber will do

2023-03-14 15:43 UTC, WiNloSt commented on frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx
> +              data-testid="expression-widget-info-link"
I believe this is from https://github.com/metabase/metabase/pull/29113. I've checked and seems nobody's using this anymore, so it should be removed.

2023-03-15 23:06 UTC, mazameli approved these changes
The description tooltip and link look good to me, and my understanding is that we'll fix that preexisting issue with the popover tethering in a different PR.

2023-03-16 12:15 UTC, ranquild approved these changes

2023-03-16 13:40 UTC, merged