Revert column settings changes
metabase/metabase pull request #28709
Opened 2023-02-27 21:37 UTC by alxnddr

> **Warning**
>
> If that is your first contribution to Metabase, please sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) (unless it's a tiny documentation change). Also, if you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

Closes https://github.com/metabase/metabase/issues/[issue_number]

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2023-02-27 22:50 UTC, npfitz commented
We may have reverted too much of the `ObjectDetail` stuff, as there are no longer any settings for that viz. I believe the `table.columns` prop should be the same as what we've restored to `Table.jsx`, but @iethree could confirm

2023-02-27 22:52 UTC, npfitz requested changes
Comment above about Object Detail. But the Table column settings seems to be working well

2023-02-27 22:55 UTC, iethree commented
I had object detail working with the old column settings components before

https://github.com/metabase/metabase/pull/27757/commits/ec3bcc534758cf63034f9785c52e5bd5ad1dd35a has most of the diff necessary.

2023-02-28 10:47 UTC, npfitz approved these changes

2023-02-28 13:48 UTC, merged