docs - update caching
metabase/metabase pull request #28753
Opened 2023-02-28 19:58 UTC by nllho

Add notes about caching location. Useful for people who need to adhere to data residency laws.

2023-02-28 20:01 UTC, paoliniluis commented on docs/data-modeling/models.md
> +If you're self-hosting Metabase, cached models will be saved to your [application database](../installation-and-operation/configuring-application-database.md).
Cached models are saved in the data warehouse, not on the app db :)

2023-02-28 20:01 UTC, paoliniluis commented on docs/data-modeling/models.md
> +If you're using Metabase Cloud, cached models will be saved to Metabase's servers in the United States.
same as above, it's saved on customer's data warehouse in a special schema we create

2023-02-28 20:01 UTC, paoliniluis requested changes
Just a few changes

2023-02-28 20:12 UTC, nllho commented
Should have read it more carefully -- the model caching section already mentions the schema 😅

2023-03-01 08:23 UTC, paoliniluis approved these changes

2023-03-01 14:31 UTC, merged