e2e testing framework proof of concept
metabase/metabase pull request #29059
Opened 2023-03-08 23:09 UTC by alxnddr

[RFC](https://www.notion.so/metabase/37-Use-the-page-object-pattern-for-E2E-specs-7fec75c17248439090272d5c85019fcf)

### Description

FE integration tests are nice, however, they do mock a lot, and the reality of how the application works may be different from what the author of the tests thinks. And even if mocks were correct, these tests won't catch a BE bug caused by a changed contract or the permissions model. In our reality, only good e2e tests can ensure that the application works correctly.
We should also make reading and writing e2e tests as easy as possible to encourage more people to write them.

2023-03-10 10:05 UTC, ranquild commented on e2e/pages/widgets/shared/input.js
> +  clear = value => {
Does clear accept `value`? I think not, in that case we should remove this probably

2023-03-10 10:16 UTC, ranquild approved these changes, later dismissed
@alxnddr I think it's a huge improvement over what we have for e2e tests right now. A couple of comments I'd like to address (either in this PR or the next one):
- Can we convert `e2e/pages` to TypeScript?
- Can we add `wait` to form submit methods?

2023-03-10 10:16 UTC, ranquild commented on e2e/pages/widgets/shared/input.js
> +  append = value => {
I would prefer calling it `type` to match cypress

2023-03-10 10:16 UTC, ranquild commented on e2e/pages/widgets/shared/input.js
> +    if (value !== "") {
there is probably no harm in calling `append` with an empty string

2023-03-10 10:16 UTC, ranquild commented on e2e/pages/widgets/shared/select.js
> +    popover().within(() => {
Can we add a version of `Popover` in `shared` that wraps this helper? I'd like us to avoid using old helpers directly if possible

2023-03-10 10:16 UTC, ranquild commented on e2e/pages/widgets/account-settings/profile-form.js
> +  submitButton = () => cy.button("Update");
Could we add `Button` wrapper in `shared`, too?

2023-03-10 10:16 UTC, ranquild commented on e2e/pages/account-settings-page.js
> +  profileForm = new UserProfileForm();
I'm not sure if the page contains the profile form. I think the page contains tabs, and in a specific tab there is a form.

2023-03-10 10:16 UTC, ranquild commented on e2e/pages/widgets/account-settings/profile-form.js
> +    this.submitButton().click();
I think it's important to move `cy.wait` from the test to this method. To make it scalable, I think we should use unique aliases for `wait` each time we call it. Not sure about the exact API to do this, but semantically I want something like this:

```
const requestId = _. uniqueId("updateUser");
cy.intercept("PUT", "/api/user/*").as(requestId);
this.submitButton.click();
cy.wait(`@{requestId}`);
```

2023-03-10 10:16 UTC, ranquild commented on e2e/pages/widgets/account-settings/profile-form.js
> +  submitButton = () => cy.button("Update");
This would also allow us to use it like `this.submitButton` and not `this.submitButton()`

2023-03-10 10:16 UTC, ranquild commented on e2e/pages/widgets/account-settings/profile-form.js
> +  firstNameInput = Input.byLabel("First name");
Not sure but maybe we should make these fields private

2023-03-13 15:21 UTC, nemanjaglumac requested changes
I don't think this approach moves us in a good direction. On the contrary.
It will make our E2E tests even harder to maintain and will promote practices that will further slow them down.

As I mentioned multiple times before, Page Object Model is considered an anti-pattern not just in Cypress, but in modern JS testing tooling as well.

- https://www.cypress.io/blog/2019/01/03/stop-using-page-objects-and-start-using-app-actions/
- https://dev.to/walmyrlimaesilv/why-nowadays-do-i-consider-page-objects-an-anti-pattern-in-web-test-automation-46ad
- https://gauge.org/2017/06/13/the-page-objects-anti-pattern/

--- 
We can utilize API calls to set up tests state and we should (in general) reduce the number of repetitive flows through UI.

2023-03-13 15:29 UTC, ranquild commented
@nemanjaglumac I disagree. As stated before, I think this approach is far superior to what we currently have and makes it much more straightfoward to add a new e2e test.

2023-03-14 15:29 UTC, ranquild commented on e2e/test/scenarios/onboarding/setup/user_settings.cy.spec.js
> +      .tabs.passwordForm.fill({
Probably it was better before the `tabs`. I don't have any ideas how to make it better atm, maybe we should revert to the previous version without tabs

2025-02-05 01:32 UTC, closed without merging