Users can run actions if they have access to the database
metabase/metabase pull request #29088
Opened 2023-03-09 16:16 UTC by tsmacdonald

[Fixes #28425]

2023-03-09 18:48 UTC, kulyk approved these changes
Works great, thank you! @tsmacdonald I think we need to add the "backport" label here?

2023-03-13 08:43 UTC, qnkhuat requested changes
@tsmacdonald or @kulyk I followed the reproduction steps in the original issue and successfully execute the action as Rasta user. Could you double-check if the steps are correct?

Also I'm not sure the fix makes sense, we're changing from `/db/1/` to `/db/1/schema`, isn't it supposed to be more restrictive than before?

2023-03-13 14:26 UTC, tsmacdonald commented
@qnkhuat just pushed up a new commit since apparently we're supposed to be *very* permissive. Here's the truth table that Bruno signed off on. This PR is just for the execution part. Action creation is covered by #29171 

![image](https://user-images.githubusercontent.com/784417/224730217-d1f97a06-db3c-40ef-b918-ffbff8620f1a.png)

2023-03-14 12:04 UTC, tsmacdonald commented on test/metabase/api/dashboard_test.clj
>  ;; Not relevant for 46; uncomment and make work for 47
```suggestion
```

2023-03-14 12:43 UTC, qnkhuat submitted a review, later dismissed
I think this looks great, the code and permissions table checks out.

But sorry to be the bad guy to request changes here but since we're revisiting action perms, I think we should add some low-level tests in `test/metabase/query_processor/middleware/permissions_test.clj` for `check-query-action-permissions*` too

2023-03-14 18:39 UTC, calherries approved these changes
Looks good

2023-03-14 19:02 UTC, metamben approved these changes
LGTM

2023-03-14 19:02 UTC, metamben commented on test/metabase/query_processor/middleware/permissions_test.clj
> +                       (re-pattern #"You do not have permissions to view Card [\d,]+")
```suggestion
                       #"You do not have permissions to view Card [\d,]+"
```

2023-03-14 19:05 UTC, merged