Optimize DB calls of dashboard card updates some more - 2
metabase/metabase pull request #29252
Opened 2023-03-15 21:45 UTC by calherries

This PR makes progress towards solving [Dashboard update makes too many app DB calls](https://github.com/metabase/metabase/issues/28956#top).

It builds on [Optimize DB calls of dashboard card updates some more](https://github.com/metabase/metabase/pull/29132#top) by making sure the dashcard data coming from the API is in the same format as the dashcard data coming from the database.

The previous PR meant there were still unnecessary update DB calls if a dashcards had non-nil values for `parameter_mappings` or `visualization_settings`. 

This PR makes a change to the PUT "api/dashboard/:id/cards" handler, so that the dashcard data in the request body is transformed into the right format for comparison with existing dashcards, before `update-dashcards!` is called.

2023-03-15 21:52 UTC, calherries commented on src/metabase/models/dashboard_card.clj
> +                                  (select-keys old-dashboard-card update-ks))]
just formatted differently

2023-03-16 16:06 UTC, tsmacdonald approved these changes
I'm not blocking the PR on this, but this is an ideal use case for generative tests (property-based tests)

2023-03-16 16:08 UTC, tsmacdonald commented on test/metabase/models/dashboard_card_test.clj
> +    (mt/with-temp* [Dashboard     [dash     {:name "my dashboard"   :created_at now}]
`now` is undefined

2023-03-16 16:08 UTC, tsmacdonald requested changes
:heavy_check_mark: in theory , but ping me for a new review when the tests are green

2023-03-16 17:21 UTC, tsmacdonald approved these changes

2023-03-16 17:22 UTC, tsmacdonald commented on src/metabase/models/interface.clj
> +   to modern MBQL clauses so things work correctly."
wrong order for the args / docstring

2023-03-17 14:50 UTC, merged