First try of adding Formik Cypress application actions
metabase/metabase pull request #29617
Opened 2023-03-28 18:44 UTC by WiNloSt

Closes https://github.com/metabase/metabase/issues/29428

### Description

Adding a way to fill form programmatically, so we can speed up Cypress test when using Formik forms

### How to verify

All tests are ✅

### Demo

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2023-03-29 13:02 UTC, ranquild requested changes
With this approach we're testing the internal details of how forms are implemented and not how they work from the user perspective. Both unit tests with RTL and cypress with RTL-like methods are less implementation-depend, more robust, and give more confidence.

2023-03-29 13:56 UTC, ranquild commented
@WiNloSt @nemanjaglumac does it apply to all forms or just ones with long input? Have you considered using this for long input https://github.com/metabase/metabase/blob/f71f20e18788f2997a55e8bdafb1a39843d06a13/e2e/test/scenarios/filters/reproductions/9339-clipboard-numeric-filter.cy.spec.js#L17?

2023-03-29 14:14 UTC, WiNloSt commented
Pasting text into each input looks like a good alternative IMO. I'm just not sure how that fares against directly calling Formik's function to change the form state since the focus here is to speed up the CI. Worth benchmarking them both.

2023-04-04 16:07 UTC, nemanjaglumac commented
> @WiNloSt @nemanjaglumac does it apply to all forms or just ones with long input? Have you considered using this for long input
> 
> https://github.com/metabase/metabase/blob/f71f20e18788f2997a55e8bdafb1a39843d06a13/e2e/test/scenarios/filters/reproductions/9339-clipboard-numeric-filter.cy.spec.js#L17
> 
> ?

TIL 
Thanks @ranquild 

@WiNloSt thank you for exploring this path.
I've spoken to more developers about this and the general consensus seems to be that this is not a very good idea. I'll explore some other paths, including the paste option that Alexander showed us here.

2023-04-04 16:07 UTC, closed without merging