Fixes metadata on declare in m.m.serialization
metabase/metabase pull request #29691
Opened 2023-03-30 15:45 UTC by john-metabase

Quick fix for a warning in `metabase.models.serialization`

2023-03-30 15:50 UTC, dpsutton commented
Was:
> Warning: *lookup-by-id* not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic *lookup-by-id* or change the name. (metabase/models/serialization.clj:245)

Now its:
> Warning: *lookup-by-id* not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic *lookup-by-id* or change the name. (metabase/models/serialization.clj:375)

Looks like you need it in both places.

2023-03-30 15:51 UTC, dpsutton requested changes
Need in both places it seems

2023-03-30 16:01 UTC, dpsutton approved these changes

2023-04-19 13:26 UTC, john-metabase commented
Rewriting this branch to just remove the `:dynamic` from `*lookup-by-id*` (now just `lookup-by-id`) since it's inappropriate to cache this function anyway.

2023-04-19 14:09 UTC, merged