WIP - 29598 csv status toast
metabase/metabase pull request #29757
Opened 2023-04-03 14:26 UTC by npfitz

Closes https://github.com/metabase/metabase/issues/[29598]

### Description
Adds redux state to handle showing the alert in the bottom right corner while uploading a CSV, as well as generalizes the Status Listings. Setup should handle multiple concurrent uploads happening at once, and each collection should have it's own listing. Currently the upload is mocked to take 6 seconds.

### How to verify

1. Go to any collection, and "upload" a csv
2. Alert should appear with the correct collection name in the header.

### Demo
![chrome_nA9AxjzGgb](https://user-images.githubusercontent.com/1328979/229539466-36b65926-b211-422d-8441-3cf3fe0ae5ae.gif)

### Checklist
- [ ] Tests have been added/updated to cover changes in this PR

2023-04-03 19:55 UTC, iethree requested changes
🙌  This rules

I think there's three blockers here:
1. I think we should name things to `uploads` or `fileUploads`, not uploadCSV. I realize I did this too. 🤦‍♀️ 
2. We also need this to work with the dropzone on `CollectionContent`
3. Let's just assume a sane error/success API for the backend, actually call the backend, and we can update it as needed.

2023-04-03 19:55 UTC, iethree commented on frontend/src/metabase/status/components/FileUploadStatusLarge/FileUploadStatusLarge.stories.tsx
this might be my storybook environment, but I can't get these new stories to show up 😢

2023-04-03 19:55 UTC, iethree commented on frontend/src/metabase/status/components/FileUploadStatusLarge/FileUploadStatusLarge.tsx
> +  upload.status === "complete" ? <Link to="/">Start exploring</Link> : "";
we probably want to link to a model id here? Maybe let's just assume a reasonable response payload and adjust as necessary?

2023-04-03 19:55 UTC, iethree commented on frontend/src/metabase/status/components/StatusListing/StatusListing.tsx
> +      {isAdmin && (
I think we're planning to allow uploads for anyone with write permissions on the uploads db, right? I guess this requires the settings PR to be merged to be able to check.

2023-04-04 14:03 UTC, npfitz commented on frontend/src/metabase/status/components/FileUploadStatus/FileUploadStatus.tsx
> +  console.log(uploadCollections);
🤦

2023-04-05 18:39 UTC, iethree requested changes
😍 

![Screen Shot 2023-04-05 at 11 05 44 AM](https://user-images.githubusercontent.com/30528226/230159368-3ae6a292-1af7-4fa4-afef-1c3563b663ef.png)


Looking good. There's a few type + lint errors to clear and a couple issues with creating a formData object and the net request the file upload. should be g2g after that!

2023-04-05 18:40 UTC, npfitz commented on frontend/src/metabase/redux/uploads.ts
> +      );
Sure should! I'll update that lol

2023-04-05 18:41 UTC, npfitz commented on frontend/src/metabase/redux/uploads.ts
> +      const { modelId } = await CardApi.uploadCSV({
Oh! I good point. I'll refactor

2023-04-05 18:42 UTC, npfitz commented on frontend/src/metabase/redux/uploads.ts
> +      });
🤦 Whoops. I'll get that fixed, and move the checks in `collections/upload.ts` over to the action

2023-04-11 14:46 UTC, merged