docs - update saml
metabase/metabase pull request #29846
Opened 2023-04-05 18:44 UTC by nllho

Clarify the note about editing email attributes.
See the thread here: https://metaboat.slack.com/archives/C01LQQ2UW03/p1680040000192879

2023-04-05 23:20 UTC, paoliniluis commented on src/metabase/metabot/util.clj
> +  (let [q "SELECT 1 FROM (SELECT 1 AS ONE) AS TEST"]
I'm pretty sure this is an error?

2023-04-05 23:20 UTC, paoliniluis requested changes
there's some code change

2023-04-06 12:55 UTC, jeff-bruemmer approved these changes
Approved, but see Luis's comment before merging. Looks like an errant file got committed.

2023-04-13 18:53 UTC, paoliniluis approved these changes

2023-04-13 18:53 UTC, merged