Adds list of exported settings, basic test. resolves #29837
metabase/metabase pull request #29927
Opened 2023-04-10 14:41 UTC by john-metabase

This PR adds a simple list of setting which are appropriate to export by default, and attempts to limit these to settings that affect interaction, content, and visual style. Some settings should probably be removed or added from this list after discussion.

If there are strong objections, then we can skip this or come up with a different approach. There are so many settings that maybe groups or tags would help with this. If we export all settings then someone could just edit the YAML file, but that seems like asking a lot when we can identify settings that should never be transferred.

2023-04-10 14:43 UTC, john-metabase commented on src/metabase/models/setting.clj
> +     map-tile-server-url
In many cases, e.g. a dev and prod server, someone might use the same map tile server for different Metabase instances, but in some cases they would be different between dev and prod.

2023-04-10 14:43 UTC, john-metabase commented on src/metabase/models/setting.clj
> +     persisted-models-enabled
This is another one that seems more likely be different between dev and prod than others.

2023-04-10 14:46 UTC, john-metabase commented on src/metabase/models/setting.clj
> +     site-name
This is more likely to be customized for deployments vs `application-name` above.

2023-04-11 13:38 UTC, bshepherdson requested changes
LGTM overall, but left a few remarks.

In general, I think we should err on the side of _not_ transferring settings, because it's a lot easier to just set an excluded one in both environments, than it is to fix an overzealous exported setting on every export.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29927#-:-NSkX3-h1dqzwbFbeYOS:bxe4ovg)* status: all files reviewed, 5 unresolved discussions (waiting on @john-metabase, @luizarakaki, and @paoliniluis)

___
*[`src/metabase/models/setting.clj` line 152 at r1](https://reviewable.io/reviews/metabase/metabase/29927#-NSkUQOG659kAb_EjmEN:-NSkUQOG659kAb_EjmEO:b-j3b7sn) ([raw file](https://github.com/metabase/metabase/blob/be6e0b0889bbf5a87ed3378e75c6dcc49c1896ce/src/metabase/models/setting.clj#L152)):*
> ```Clojure
> 
> (def ^:private exported-settings
>   '#{admin-email
> ```

Not sure about this one. It seems like dev and prod environments might well want different administrators. We don't transfer user accounts and all that. This seems like a setup-time concern for each environment, and not transferable.
___
*[`src/metabase/models/setting.clj` line 176 at r1](https://reviewable.io/reviews/metabase/metabase/29927#gh-1161779867:-NSkUnvvEWYJeNVySh0e:b-1psxr5) ([raw file](https://github.com/metabase/metabase/blob/be6e0b0889bbf5a87ed3378e75c6dcc49c1896ce/src/metabase/models/setting.clj#L176)):*
<details><summary><i>Previously, john-metabase wrote…</i></summary><blockquote>

In many cases, e.g. a dev and prod server, someone might use the same map tile server for different Metabase instances, but in some cases they would be different between dev and prod.
</blockquote></details>

I think unless they're pretty likely to be the same, the setting should be excluded. Otherwise we're forcing people to write a script to post-process each export.

It's a lot easier to one-time set some option that doesn't get imported (admin email, this, etc.) than to fix an over-eager export every time.
___
*[`src/metabase/models/setting.clj` line 179 at r1](https://reviewable.io/reviews/metabase/metabase/29927#gh-1161780386:-NSkVNWm5aPdOsyuSyTg:b-xclfw1) ([raw file](https://github.com/metabase/metabase/blob/be6e0b0889bbf5a87ed3378e75c6dcc49c1896ce/src/metabase/models/setting.clj#L179)):*
<details><summary><i>Previously, john-metabase wrote…</i></summary><blockquote>

This is another one that seems more likely be different between dev and prod than others.
</blockquote></details>

Eh, I'm not so sure here. This really changes how models work, and would I think be a source of dev/prod divergence if it were different. It only works on some warehouses currently though (Postgres, MySQL, Redshift) so are we concerned that a dev environment might be running on a different one that doesn't support it?


<!-- Sent from Reviewable.io -->

2023-04-13 20:32 UTC, bshepherdson approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/29927)* status: all files reviewed, 2 unresolved discussions (waiting on @luizarakaki and @paoliniluis)



<!-- Sent from Reviewable.io -->

2023-04-14 14:31 UTC, merged