Make column group functions return plain arrays in JS
metabase/metabase pull request #30097
Opened 2023-04-13 22:32 UTC by metamben

Fixes #30090.

I've also cleaned up the import in `metabase.lib.js` so that the `metabase.lib.core` version of the functions is used when it exists.

2023-04-13 23:47 UTC, camsaul approved these changes

2023-04-14 14:38 UTC, bshepherdson requested changes
LGTM aside from the question about `lib.core` usage.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30097#-:-NT-BuwhA0hQvjmHnl8w:b-4hlrc2)* status: all files reviewed, 1 unresolved discussion (waiting on @metamben)

___
*[`src/metabase/lib/js.cljs` line 14 at r1](https://reviewable.io/reviews/metabase/metabase/30097#-NT-BWA48uYz84VSdSVb:-NT-BWA48uYz84VSdSVc:bt6hokt) ([raw file](https://github.com/metabase/metabase/blob/fe8da90713d51b5e9b33cfca6153f28fb6a1deeb/src/metabase/lib/js.cljs#L14)):*
> ```Clojure
>    [metabase.lib.query :as lib.query]
>    [metabase.lib.remove-replace :as lib.remove-replace]
>    [metabase.mbql.js :as mbql.js]
> ```

I had the impression that we were treating `lib.core` as a convenience for testing/REPL usage, and that nothing under `src/metabase/lib/` should be importing it. I can see `metabase.lib.js` being an exception, though, because it's sort of a catch-all.

@camsaul thoughts?



_Code quote:_
```Clojure
   [metabase.lib.js.metadata :as js.metadata]
   [metabase.lib.metadata.calculation :as lib.metadata.calculation]
   [metabase.lib.metadata.protocols :as lib.metadata.protocols]
   [metabase.lib.normalize :as lib.normalize]
   [metabase.lib.order-by :as lib.order-by]
   [metabase.lib.query :as lib.query]
   [metabase.lib.remove-replace :as lib.remove-replace]
   [metabase.mbql.js :as mbql.js]
```


<!-- Sent from Reviewable.io -->

2023-04-14 14:52 UTC, metamben reviewed
We discussed this in [slack](https://metaboat.slack.com/archives/C04DN5VRQM6/p1681417485680629).

> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30097#-:-NT-EyfyETGQvL35xP4a:b-j47cjf)* status: all files reviewed, 1 unresolved discussion (waiting on @camsaul)

___
*[`src/metabase/lib/js.cljs` line 14 at r1](https://reviewable.io/reviews/metabase/metabase/30097#-NT-BWA48uYz84VSdSVb:-NT-FA5X6mgaXINAipGT:b-z5b4hx) ([raw file](https://github.com/metabase/metabase/blob/fe8da90713d51b5e9b33cfca6153f28fb6a1deeb/src/metabase/lib/js.cljs#L14)):*
<details><summary><i>Previously, bshepherdson (Braden Shepherdson) wrote…</i></summary><blockquote>

I had the impression that we were treating `lib.core` as a convenience for testing/REPL usage, and that nothing under `src/metabase/lib/` should be importing it. I can see `metabase.lib.js` being an exception, though, because it's sort of a catch-all.

@camsaul thoughts?
</blockquote></details>

 We discussed this in [slack](https://metaboat.slack.com/archives/C04DN5VRQM6/p1681417485680629).


<!-- Sent from Reviewable.io -->

2023-04-14 17:48 UTC, camsaul commented
Yeah, cleaning up stuff this way is cool with me. I think it makes sense. `metabase.lib.core` = public Clojure(Script) API for MLv2 `metabase.lib.js` = JS wrapper around stuff in `metabase.lib.core` (as needed)

I think there are some open questions about how the `dev` stuff plays in to things here since they don't make sense in JS (or future Clj stuff like QP or X-Ray code for that matter) but I think we can figure that out later.





<!-- Sent from Reviewable.io -->

2023-04-14 17:48 UTC, camsaul reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30097#-:-NT-sRMKB_r_68Pe7i7N:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @bshepherdson)

___
*[`src/metabase/lib/js.cljs` line 14 at r1](https://reviewable.io/reviews/metabase/metabase/30097#-NT-BWA48uYz84VSdSVb:-NT-sSKDBgKBd0LNxIW3:bzi5jh8) ([raw file](https://github.com/metabase/metabase/blob/fe8da90713d51b5e9b33cfca6153f28fb6a1deeb/src/metabase/lib/js.cljs#L14)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

 We discussed this in [slack](https://metaboat.slack.com/archives/C04DN5VRQM6/p1681417485680629).
</blockquote></details>

Mentioned above, this is cool with me 


<!-- Sent from Reviewable.io -->

2023-04-14 18:01 UTC, bshepherdson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30097#-:-NT-vOaM-BebYMHxM9HW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @metamben)



<!-- Sent from Reviewable.io -->

2023-04-14 18:01 UTC, merged