docs - update db connection troubleshooting
metabase/metabase pull request #30205
Opened 2023-04-18 20:42 UTC by nllho

2023-04-18 23:31 UTC, jeff-bruemmer approved these changes

2023-04-18 23:31 UTC, jeff-bruemmer commented on docs/troubleshooting-guide/db-connection.md
> +3. Make sure that Metabase is using a role with the correct privileges to connect to your data warehouse.
```suggestion
3. Make sure that Metabase is connecting to your database using a database user account that has a role with the privileges to query and write to the tables that you want to query or write to. If the database user account doesn't have a role with those privileges, you'll either need to grant that account a role (or roles) with the necessary privileges, or have Metabase connect using a different database account.
```

Is this more precise? Just want to clarify that, like Metabase's accounts and groups, databases typically have have users and roles.

2023-04-20 15:27 UTC, jeff-bruemmer requested changes
@nllho this is great so far.

2023-04-20 15:27 UTC, jeff-bruemmer commented on docs/databases/connecting.md
> +The easiest way to set this up in a Postgres database:
The easiest (but not recommended)?

2023-04-20 15:27 UTC, jeff-bruemmer commented on docs/databases/connecting.md
> +GRANT CONNECT ON DATABASE "your_database" TO bi_tool;
I like this second pass, but think we could go further. We should give people more complete code here, so people don't have to figure this out for themselves and can just copy/paste/modify.

In fact, we could/should recommend a cookie cutter set of SQL and roles to set up for Metabase. Like: tell them to create specific roles that have different privileges required for different Metabase features.

Something like this pseudocode:

```
-- Set up db user account that Metabase will use to connect to the database.
CREATE USER metabase;

-- Create roles with different privileges
--
-- Role with the minimum privileges for Metabase to work
CREATE ROLE connect_and_query;
GRANT CONNECT ON DATABASE "your_database" TO connect_and_query;
...

-- Role for Metabase actions and model caching to work
-- (Nat, I'm guessing on this here, we may need to split model caching and action privileges into separate roles)
CREATE ROLE actions_and_caching
GRANT CONNECT ...

-- Assign role(s) to `metabase` user account.
GRANT connect_and_query to metabase;
GRANT actions_and_caching to metabase;
```

And then, like you do below, also show how to do it for particular schema/tables.

2023-04-20 15:58 UTC, likeshumidity commented on docs/databases/connecting.md
> +```
The below should work with two roles. One for just read only analytics access and the other for analytics with writeback (CREATE access necessary for model caching):

```sql
-- create user and password for Metabase
CREATE USER metabase WITH PASSWORD 'INSERT_PASSWORD';
-- create role for read-only analytics
CREATE ROLE analytics_read_only WITH LOGIN;
-- grant SELECT access to to all tables for role
GRANT SELECT ON ALL TABLES IN SCHEMA public TO analytics_read_only;
-- grant SELECT access to to specific tables for role
GRANT SELECT ON public.model_actions_test TO analytics_read_only;
-- grant role to Metabase user
GRANT analytics_read_only TO metabase;


-- Add the below for model caching
-- create role for analytics with writeback access to database for model caching
CREATE ROLE analytics_with_writeback WITH LOGIN;
-- grant CREATE access to database
GRANT CREATE ON DATABASE "testing-20230207a" TO analytics_with_writeback;
-- grant INSERT, UPDATE, DELETE access to all tables in schema (so it has access to newly created tables)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO analytics_with_writeback;
-- grant role to Metabase user
GRANT analytics_with_writeback TO metabase;
```

2023-04-24 19:22 UTC, jeff-bruemmer approved these changes
Nice revision/expansion on this, @nllho. Approving, but see my comments before merging. 

For the larger asks, you can either tact them onto this PR or create a new PR for me to review if you like, but this is already way ahead of our current resources on this topic.

2023-04-24 19:22 UTC, jeff-bruemmer commented on docs/databases/users-roles-privileges.md
> +In order to view and query your tables in Metabase, you'll have to give Metabase's database user:
Can we get the SQL here for the lazy (following the grant to role, then grant role to user pattern)?

2023-04-24 19:22 UTC, jeff-bruemmer commented on docs/databases/users-roles-privileges.md
> +## Actions
```suggestion
## Privileges Metabase needs to run actions
```

2023-04-24 19:22 UTC, jeff-bruemmer commented on docs/databases/users-roles-privileges.md
> +## Organize database privileges with roles
Think we need one more short section, as close to the top of the page as possible, that just gives people a set-and-forget SQL code block they can copy and paste to get moving if they don't want to bother with all this reading and fine-tuning. Something like: create a role that has/lists all the privileges Metabase would need, create a metabase user, grant role to user, done. Like the "Grant all privileges" section, but more explicit about the privileges granted, i.e., this should state every privilege Metabase would need, including `TEMPORARY`, etc. Might even want to use language like "set and forget", but then encourage/recommend the more nuanced approach.

The bonus side effect of frontloading this short-but-explicit version is that the list of grants will let experienced database admins see at a glance exactly what they need, and they can run with it and set up privileges however they want.

2023-04-25 18:33 UTC, merged