Keep only visualization Percy specs
metabase/metabase pull request #30245
Opened 2023-04-19 22:46 UTC by alxnddr

### Description

Keep only visualization Percy specs since the other ones are not being useful. We run Percy tests manually when needed and they are useful for visualizations while being mostly useless for other parts since they were never executed.

This PR does two things:
- Removes non-visualizations Percy specs
- Adds a GHA workflow that assigns the `visual` label on PRs which will make Percy specs run on it

The GHA workflow uses pretty basic path matching so it is still expected in rare cases that engineers based on their judgment will run Percy tests manually by adding the `visual` on their PR.

### How to verify

Test the workflow on a fork or inspect my fork [here](https://github.com/alxnddr/metabase/pull/133)

2023-04-20 09:15 UTC, ranquild approved these changes

2023-04-20 09:29 UTC, nemanjaglumac requested changes

2023-04-20 09:29 UTC, nemanjaglumac commented on .github/workflows/require-percy-tests.yml
> +    types: [opened, synchronize, reopened, ready_for_review]
Isn't this going to create two triggers?
`pull_request` alone should be enough, unless I'm missing something.

2023-04-21 06:46 UTC, nemanjaglumac approved these changes
👌 🚀

2023-04-21 15:41 UTC, merged