[MLv2] Make aggregation references use source uuid
metabase/metabase pull request #30440
Opened 2023-04-28 17:09 UTC by snoe

Having aggregation references use indexing to point to the source is problematic for two reasons:
1. It means on removal, all references may get shifted.
2. Finding references of a source requires a lot more calculation.

It's possible we want to do the same for named `:field` references at some point, perhaps introducing a unified `:reference` tag.

2023-04-28 17:18 UTC, snoe commented on test/metabase/lib/convert_test.cljc
> -    [:aggregation 0 {:display-name "Bean Count"}]
Since we need a source uuid in pMBQL, a standalone aggregation conversion is no longer valid.

2023-04-28 20:59 UTC, metamben requested changes
> Reviewed 8 of 11 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30440)* status: all files reviewed, 14 unresolved discussions (waiting on @snoe)

___
*[`src/metabase/lib/aggregation.cljc` line 31 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8Sa2O0hxsgRqP0x0k:-NU8Sa2O0hxsgRqP0x0l:undefined) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/src/metabase/lib/aggregation.cljc#L31)):*
> ```Clojure
>    ag-uuid      :- :string]
>   (let [{aggregations :aggregation} (lib.util/query-stage query stage-number)
>         found (first (filter (comp #{ag-uuid} :lib/uuid second) aggregations))]
> ```





_Suggestion:_
```Clojure
m/find-first
```
___
*[`src/metabase/lib/aggregation.cljc` line 33 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8JHneAj-U3-iyrTaQ:-NU8JHneAj-U3-iyrTaR:b-7ex5yn) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/src/metabase/lib/aggregation.cljc#L33)):*
> ```Clojure
>         found (first (filter (comp #{ag-uuid} :lib/uuid second) aggregations))]
>     (when-not found
>       (throw (ex-info (i18n/tru "No aggregation with index {0}" ag-uuid)
> ```

Or "uuid".



_Suggestion:_
```Clojure
id
```
___
*[`src/metabase/lib/convert.cljc` line 105 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8VEfQEpMyV62m-RS6:-NU8VEfQEpMyV62m-RS7:b45h) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/src/metabase/lib/convert.cljc#L105)):*
> ```Clojure
>                                                (map-indexed (fn [idx [_tag {ag-uuid :lib/uuid}]]
>                                                               [idx ag-uuid]))
>                                                aggregations)]
> ```





_Suggestion:_
```Clojure
    (binding [*legacy-index->pMBQL-uuid* (mapv (comp :lib/uuid second) aggregations)]
```
___
*[`src/metabase/lib/convert.cljc` line 173 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8WxdP7WGT1QQ-mhVO:-NU8WxdP7WGT1QQ-mhVP:bmq0vjk) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/src/metabase/lib/convert.cljc#L173)):*
> ```Clojure
> (defmethod ->pMBQL :aggregation
>   [[tag value opts]]
>   (lib.options/ensure-uuid [tag opts (get *legacy-index->pMBQL-uuid* value)]))
> ```

Consider throwing an exception if `value` is not a valid index.
___
*[`src/metabase/lib/convert.cljc` line 304 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8Yiyi4nSOLlDxBFpe:-NU8Yiyi4nSOLlDxBFpf:bn66fzs) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/src/metabase/lib/convert.cljc#L304)):*
> ```Clojure
>   (if (map? opts)
>     (let [opts (not-empty (disqualify opts))]
>       (cond-> [:aggregation (get *pMBQL-uuid->legacy-index* agg-uuid)]
> ```

Consider throwing an exception if `agg-uuid` is not contained.
___
*[`src/metabase/lib/convert.cljc` line 306 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8XeQ77f8ZZoIayQpJ:-NU8XeQ77f8ZZoIayQpK:bol2tyu) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/src/metabase/lib/convert.cljc#L306)):*
> ```Clojure
>       (cond-> [:aggregation (get *pMBQL-uuid->legacy-index* agg-uuid)]
>         opts (conj opts)))
>     ;; Something in source_metadata that shouldn't be touched
> ```

I don't know what this means (and it sounds it's about something tricky).
___
*[`src/metabase/lib/convert.cljc` line 361 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8XyTg1rLir7F__Mm1:-NU8XyTg1rLir7F__Mm2:undefined) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/src/metabase/lib/convert.cljc#L361)):*
> ```Clojure
>                 (m/update-existing :aggregation #(mapv aggregation->legacy-MBQL %))
>                 (update-list->legacy-boolean-expression :filters :filter))
>             (remove #{:aggregation :filters} stage-keys))))
> ```





_Suggestion:_
```Clojure
disj stage-keys :aggregation :filters
```
___
*[`src/metabase/lib/dev.cljc` line 66 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8ZdwsEaK-KeMXQd4a:-NU8ZdwsEaK-KeMXQd4b:b4vrge0) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/src/metabase/lib/dev.cljc#L66)):*
> ```Clojure
>   "Returns a function that can be resolved into an expression reference for the expression with name `expr-name`.
>   Throws an exception if there is no expression with that name can be found."
>   [expression-or-aggregation :- [:enum :aggregation :expression] index-or-name :- [:or :string :int]]
> ```

We could check that it's not negative.



_Code quote:_
```Clojure
:int
```
___
*[`src/metabase/lib/dev.cljc` line 82 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8ZK8UB3ZMqmOj_pCM:-NU8ZK8V8H5PRT6pCxND:btlj75b) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/src/metabase/lib/dev.cljc#L82)):*
> ```Clojure
>                         {:aggregation-index index-or-name
>                          :query query
>                          :stage-number stage-number}))))))
> ```

I recommend implementing separate functions.
___
*[`src/metabase/lib/equality.cljc` line 78 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8aB-A6Xwq-S-CG6EB:-NU8aB-A6Xwq-S-CG6EC:bji17tj) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/src/metabase/lib/equality.cljc#L78)):*
> ```Clojure
>          (clojure.core/= (get-in *side->uuid->index* [:left (last x)] ::no-left)
>                          (get-in *side->uuid->index* [:right (last y)] ::no-right))
>          (clojure.core/= (last x) (last y)))))
> ```

Or destructure `x` and `y` in the argument list.



_Suggestion:_
```Clojure
         (clojure.core/= (get-in *side->uuid->index* [:left (peek x)] ::no-left)
                         (get-in *side->uuid->index* [:right (peek y)] ::no-right))
         (clojure.core/= (peek x) (peek y)))))
```
___
*[`src/metabase/lib/schema.cljc` line 63 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8bTzM5TiRU6BBCxLT:-NU8bTzM5TiRU6BBCxLU:bqdzy8k) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/src/metabase/lib/schema.cljc#L63)):*
> ```Clojure
>   (let [uuids (into #{} (map (comp :lib/uuid second)) (:aggregation stage))]
>     (mbql.match/match-one (dissoc stage :joins :lib/stage-metadata)
>       [:aggregation _opts (index :guard (complement uuids))]
> ```

I would `complement` in the `let`.
___
*[`src/metabase/lib/schema.cljc` line 64 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8bcGfCi5ORQeHQmjU:-NU8bcGfCi5ORQeHQmjV:b-n5hh37) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/src/metabase/lib/schema.cljc#L64)):*
> ```Clojure
>     (mbql.match/match-one (dissoc stage :joins :lib/stage-metadata)
>       [:aggregation _opts (index :guard (complement uuids))]
>       (str "Invalid :aggregation reference: no aggregation with index " index))))
> ```

Or "uuid"



_Suggestion:_
```Clojure
id
```
___
*[`test/metabase/lib/breakout_test.cljc` line 251 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8cLrT4h2xZv0_imxr:-NU8cLrT4h2xZv0_imxs:b-jrdi3l) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/test/metabase/lib/breakout_test.cljc#L251)):*
> ```Clojure
> 
> (defn- assert-breakout-column-excluded [query column]
>   (is (not (contains? (set (lib/breakoutable-columns query)) column))))
> ```

The original asserts that `column` is the only difference, I would like to keep that.
(I also have a weak preference to have the assertions inline, I find error reports easier to read that [...]

2023-05-02 20:03 UTC, snoe commented
*[`src/metabase/lib/schema.cljc` line 63 at r3](https://reviewable.io/reviews/metabase/metabase/30440#-NU8bTzM5TiRU6BBCxLT:-NUT2viS7xUm8NDqXXml:b-s3cpo2) ([raw file](https://github.com/metabase/metabase/blob/6fe9ada29965d3bfeb1e3daa3013261557c82e86/src/metabase/lib/schema.cljc#L63)):*
<details><summary><i>Previously, metamben wrote…</i></summary><blockquote>

I would `complement` in the `let`.
</blockquote></details>

I think it's harder to name that.


<!-- Sent from Reviewable.io -->

2023-05-02 22:03 UTC, metamben approved these changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30440)* status: all files reviewed, 14 unresolved discussions (waiting on @snoe)



<!-- Sent from Reviewable.io -->

2023-05-04 00:30 UTC, merged