Migrate field refs in visualization_settings.column_settings from legacy format
metabase/metabase pull request #30460
Opened 2023-05-01 14:26 UTC by calherries

This PR is a prerequisite to make https://github.com/metabase/metabase/pull/27487 easier to solve, and a trial of SQL migrations for JSON.

It includes adding UDFs to the H2 database on creating the Liquibase connection.

The SQL migrations ended up getting pretty big, our biggest yet. Most of the machinery is in getting data in and out of the JSON structure, which amounts to a (update visualization_settings :column_settings (fn [x] (map (...) x)) operation.

What's in the migration?
The migration updates the field refs in visualization_settings.column_settings from legacy formats (e.g. ["field-id",<id>] to ["field",<id>,null]). I recommend reading [the test](https://github.com/metabase/metabase/pull/27660/files#diff-41093075df90623837726c733afc60b57899a66d6e9878b4250413b74f045f67R824).

Example transformations:

(in EDN for clarity, but the transformations are still done with JSON strings in the DB)

[:field-id 12] 
-> [:field 12 null]

[:field-literal "name" :type/Text]
-> [:field "name" {:base-type :type/Text}]

[:fk-> [:field-id 12] [:field-id 11]] 
-> [:field 11 {:source-field 12}]

[:fk-> 12 11]                                   
-> [:field 11 {:source-field 12}]
Note normalizing other legacy field tags (like datetime-field or binning-strategy) is not needed here. In the past these field tags were removed to get the unwrapped field ref (aka base dimension field ref) before storing them in the database.

Why do this now?
https://github.com/metabase/metabase/pull/27487 requires another migration (probably even bigger) following this to the field refs in visualization_settings.column_settings, see https://github.com/metabase/metabase/pull/27487.
It is simpler to do that migration if the field refs are standardized in one format first.

2023-05-01 16:13 UTC, dpsutton requested changes
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30460)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @calherries)

___
*[`src/metabase/db/custom_migrations.clj` line 202 at r2](https://reviewable.io/reviews/metabase/metabase/30460#-NUN-6qI5mvhLRhSDZFB:-NUN-6qI5mvhLRhSDZFC:bnnrx07) ([raw file](https://github.com/metabase/metabase/blob/64f4229a24971617271c6879c2c446bfc1e0bd4c/src/metabase/db/custom_migrations.clj#L202)):*
> ```Clojure
>         (json/generate-string))))
> 
> (define-migration UpdateLegacyColumnSettingsFieldRefs
> ```

I like the general idea here (and big props for the PR description) but have two problems with this:
1. We shouldn't update viz settings that don't have old style refs. Let's not round trip possibly thousands of correct viz settings if only 2 (or even zero) have no changes.
2. We're loading all viz settings into memory and then `doseq`ing over them. This could lead to unacceptable memory pressure in cloud. Switching to a reducible query and keeping only viz settings that need to be updated should mean that we only keep those in memory and can GC the valid ones that don't need to be written back to the db. Using `t2/reducible-query` and filtering to just those that have deprecated refs would drastically reduce numer of items in memory and number of writes to the db that we do.
___
*[`test/metabase/db/custom_migrations_test.clj` line 58 at r2](https://reviewable.io/reviews/metabase/metabase/30460#-NUN1R_S0BFNPcJo_1jb:-NUN1R_S0BFNPcJo_1jc:b-kmpk25) ([raw file](https://github.com/metabase/metabase/blob/64f4229a24971617271c6879c2c446bfc1e0bd4c/test/metabase/db/custom_migrations_test.clj#L58)):*
> ```Clojure
>     (impl/test-migrations ["v47.00-016"] [migrate!]
>       (let [visualization-settings
>             {"column_settings" {"[\"ref\",[\"field-id\",39]]"                                 {"column_title" "ID1"}
> ```

would this look nicer as actual vectors and use cheshire to serialize them on insert? 
___
*[`test/metabase/db/custom_migrations_test.clj` line 65 at r2](https://reviewable.io/reviews/metabase/metabase/30460#-NUN4URL9cKeu6RgM009:-NUN4URL9cKeu6RgM00A:b-r1cn9r) ([raw file](https://github.com/metabase/metabase/blob/64f4229a24971617271c6879c2c446bfc1e0bd4c/test/metabase/db/custom_migrations_test.clj#L65)):*
> ```Clojure
>                                 "[\"name\",\"column_name\"]"                                  {"column_title" "ID6"}}}
>             expected
>             {"column_settings" {"[\"ref\",[\"field\",39,null]]"                                       {"column_title" "ID1"}
> ```

Do we want to assert that string representation, or perhaps that they look correct using `metabase.shared.models.visualization-settings/db->norm` or something like that? Viz settings are weird and get normed so perhaps making sure that they behave correctly under `(mb.viz/db->norm (:visualization_settings my-card))` would be an even better test?
___
*[`test/metabase/db/custom_migrations_test.clj` line 77 at r2](https://reviewable.io/reviews/metabase/metabase/30460#-NUN1KEY1AY7ZSg0pr-G:-NUN1KEY1AY7ZSg0pr-H:b-e6d4hj) ([raw file](https://github.com/metabase/metabase/blob/64f4229a24971617271c6879c2c446bfc1e0bd4c/test/metabase/db/custom_migrations_test.clj#L77)):*
> ```Clojure
>                                                         :date_joined :%now})
>             database-id (t2/insert-returning-pks! Database {:name       "DB"
>                                                      :engine     "h2"
> ```

nit: alignment
___
*[`test/metabase/db/custom_migrations_test.clj` line 81 at r2](https://reviewable.io/reviews/metabase/metabase/30460#-NUN1xLi0vayN76kP2ZF:-NUN1xLi0vayN76kP2ZG:b-j3zm6u) ([raw file](https://github.com/metabase/metabase/blob/64f4229a24971617271c6879c2c446bfc1e0bd4c/test/metabase/db/custom_migrations_test.clj#L81)):*
> ```Clojure
>                                                      :updated_at :%now
>                                                      :details    "{}"})
>             card-id     (t2/insert-returning-pks! Card {:name                   "My Saved Question"
> ```

can we just use a traditional `with-temp` and ditch the fake user and database?


<!-- Sent from Reviewable.io -->

2023-05-02 11:45 UTC, calherries reviewed
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30460)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dpsutton)

___
*[`src/metabase/db/custom_migrations.clj` line 202 at r2](https://reviewable.io/reviews/metabase/metabase/30460#-NUN-6qI5mvhLRhSDZFB:-NUR9YZz2o7d23DkWhrF:bveoidl) ([raw file](https://github.com/metabase/metabase/blob/64f4229a24971617271c6879c2c446bfc1e0bd4c/src/metabase/db/custom_migrations.clj#L202)):*
<details><summary><i>Previously, dpsutton wrote…</i></summary><blockquote>

I like the general idea here (and big props for the PR description) but have two problems with this:
1. We shouldn't update viz settings that don't have old style refs. Let's not round trip possibly thousands of correct viz settings if only 2 (or even zero) have no changes.
2. We're loading all viz settings into memory and then `doseq`ing over them. This could lead to unacceptable memory pressure in cloud. Switching to a reducible query and keeping only viz settings that need to be updated should mean that we only keep those in memory and can GC the valid ones that don't need to be written back to the db. Using `t2/reducible-query` and filtering to just those that have deprecated refs would drastically reduce numer of items in memory and number of writes to the db that we do.
</blockquote></details>

Good point, I updated to use `transduce`
___
*[`test/metabase/db/custom_migrations_test.clj` line 58 at r2](https://reviewable.io/reviews/metabase/metabase/30460#-NUN1R_S0BFNPcJo_1jb:-NUR9h_j1LLzQp-eNHT2:b-io0sk5) ([raw file](https://github.com/metabase/metabase/blob/64f4229a24971617271c6879c2c446bfc1e0bd4c/test/metabase/db/custom_migrations_test.clj#L58)):*
<details><summary><i>Previously, dpsutton wrote…</i></summary><blockquote>

would this look nicer as actual vectors and use cheshire to serialize them on insert? 
</blockquote></details>

Yes, although the keys of column_settings are serialized twice, so it's not clean to serialize them on insert. I've just used `update-keys` on them here to make this slightly more readable. 
___
*[`test/metabase/db/custom_migrations_test.clj` line 65 at r2](https://reviewable.io/reviews/metabase/metabase/30460#-NUN4URL9cKeu6RgM009:-NURCVcuDwugRzBxFCId:b-a43njj) ([raw file](https://github.com/metabase/metabase/blob/64f4229a24971617271c6879c2c446bfc1e0bd4c/test/metabase/db/custom_migrations_test.clj#L65)):*
<details><summary><i>Previously, dpsutton wrote…</i></summary><blockquote>

Do we want to assert that string representation, or perhaps that they look correct using `metabase.shared.models.visualization-settings/db->norm` or something like that? Viz settings are weird and get normed so perhaps making sure that they behave correctly under `(mb.viz/db->norm (:visualization_settings my-card))` would be an even better test?
</blockquote></details>

Good point. I realized now that we might as well update the entire `visualization_settings` map from the legacy format, and use the same transformation code as the `deftransforms` for card [here](https://github.com/metabase/metabase/blob/5b5bb78af9c982b5de6c5f1a6e3eaa9fb2b2f8cb/src/metabase/models/card.clj#L51). I added tests to show that `expected` is really the result of "normalization", and that the result has been normalized. The problem is these tests will have to be deleted if we want to remove the dead code that is no longer needed.
___
*[`test/metabase/db/custom_migrations_test.clj` line 81 at r2](https://reviewable.io/reviews/metabase/metabase/30460#-NUN1xLi0vayN76kP2ZF:-NURCCnN08zDUpmvgQ7I:b541l9w) ([raw file](https://github.com/metabase/metabase/blob/64f4229a24971617271c6879c2c446bfc1e0bd4c/test/metabase/db/custom_migrations_test.clj#L81)):*
<details><summary><i>Previously, dpsutton wrote…</i></summary><blockquote>

can we just use a traditional `with-temp` and ditch the fake user and database?
</blockquote></details>

There's a reason why no migrations use `with-temp`, and I think it's because`with-temp` exposes the migration to changes in the temp defaults.


<!-- Sent from Reviewable.io -->

2023-05-02 13:35 UTC, calherries reviewed
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30460)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dpsutton)

___
*[`test/metabase/db/custom_migrations_test.clj` line 65 at r2](https://reviewable.io/reviews/metabase/metabase/30460#-NUN4URL9cKeu6RgM009:-NURcbxk4x_l9viVOPmm:b-g0kmnl) ([raw file](https://github.com/metabase/metabase/blob/64f4229a24971617271c6879c2c446bfc1e0bd4c/test/metabase/db/custom_migrations_test.clj#L65)):*
<details><summary><i>Previously, calherries (Cal Herries) wrote…</i></summary><blockquote>

Good point. I realized now that we might as well update the entire `visualization_settings` map from the legacy format, and use the same transformation code as the `deftransforms` for card [here](https://github.com/metabase/metabase/blob/5b5bb78af9c982b5de6c5f1a6e3eaa9fb2b2f8cb/src/metabase/models/card.clj#L51). I added tests to show that `expected` is really the result of "normalization", and that the result has been normalized. The problem is these tests will have to be deleted if we want to remove the dead code that is no longer needed.
</blockquote></details>

I decided not to do update the entire `visualization_settings` map because that requires the migration depending on clojure code which might change in the future. I'll stick to updating the field refs for now. I've left the new test in though.


<!-- Sent from Reviewable.io -->

2023-05-02 13:52 UTC, dpsutton approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30460)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @calherries)

___
*[`src/metabase/db/custom_migrations.clj` line 203 at r5](https://reviewable.io/reviews/metabase/metabase/30460#-NURhTF9EutfcCDDRefv:-NURhTF9EutfcCDDRefw:b2lnttl) ([raw file](https://github.com/metabase/metabase/blob/589274d0e7f3afaad010458a0c7ac5f9a45291ca/src/metabase/db/custom_migrations.clj#L203)):*
> ```Clojure
> 
> (define-migration MigrateLegacyColumnSettingsFieldRefs
>   (transduce
> ```

I think this could be easier to read if you used `run!` as that's essentially what you've recreated:

`(run! update-viz! (eduction (keep changed?) (t2/reducible-query {})))`
___
*[`test/metabase/db/custom_migrations_test.clj` line 98 at r5](https://reviewable.io/reviews/metabase/metabase/30460#-NURhueQ5kb6C8hgHjkg:-NURhueQ5kb6C8hgHjkh:b18mzfc) ([raw file](https://github.com/metabase/metabase/blob/589274d0e7f3afaad010458a0c7ac5f9a45291ca/test/metabase/db/custom_migrations_test.clj#L98)):*
> ```Clojure
>                                     :where  [:= :id card-id]})
>                      :visualization_settings
>                      (mi/json-out-without-keywordization)))))
> ```

This is unlikely to change, but it is still using Clojure code from elsewhere. And it's essentially `json/parse-string` in a try/catch. Should we just use that?
___
*[`test/metabase/db/custom_migrations_test.clj` line 101 at r5](https://reviewable.io/reviews/metabase/metabase/30460#-NURiwcoBgs6GN4_T8Vx:-NURiwcoBgs6GN4_T8Vy:bi70k2r) ([raw file](https://github.com/metabase/metabase/blob/589274d0e7f3afaad010458a0c7ac5f9a45291ca/test/metabase/db/custom_migrations_test.clj#L101)):*
> ```Clojure
>         (testing "legacy column_settings are updated to the current format"
>           (is (= (-> visualization-settings
>                      (mi/normalize-visualization-settings)
> ```

I'm going back and forth if we should be normalizing since that code could change. Use your judgment about which is better. 


<!-- Sent from Reviewable.io -->

2023-05-02 15:10 UTC, calherries reviewed
> Dismissed @dpsutton from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/metabase/metabase/30460)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dpsutton)

___
*[`src/metabase/db/custom_migrations.clj` line 203 at r5](https://reviewable.io/reviews/metabase/metabase/30460#-NURhTF9EutfcCDDRefv:-NUS-nnR8RyHsYIX7sjr:b-896fix) ([raw file](https://github.com/metabase/metabase/blob/589274d0e7f3afaad010458a0c7ac5f9a45291ca/src/metabase/db/custom_migrations.clj#L203)):*
<details><summary><i>Previously, dpsutton wrote…</i></summary><blockquote>

I think this could be easier to read if you used `run!` as that's essentially what you've recreated:

`(run! update-viz! (eduction (keep changed?) (t2/reducible-query {})))`
</blockquote></details>

Done.
___
*[`test/metabase/db/custom_migrations_test.clj` line 98 at r5](https://reviewable.io/reviews/metabase/metabase/30460#-NURhueQ5kb6C8hgHjkg:-NURzSDj5A68qx4NB34p:b-896fix) ([raw file](https://github.com/metabase/metabase/blob/589274d0e7f3afaad010458a0c7ac5f9a45291ca/test/metabase/db/custom_migrations_test.clj#L98)):*
<details><summary><i>Previously, dpsutton wrote…</i></summary><blockquote>

This is unlikely to change, but it is still using Clojure code from elsewhere. And it's essentially `json/parse-string` in a try/catch. Should we just use that?
</blockquote></details>

Done.
___
*[`test/metabase/db/custom_migrations_test.clj` line 101 at r5](https://reviewable.io/reviews/metabase/metabase/30460#-NURiwcoBgs6GN4_T8Vx:-NURyq-SEFP1aMb6bD2o:b-1atvv4) ([raw file](https://github.com/metabase/metabase/blob/589274d0e7f3afaad010458a0c7ac5f9a45291ca/test/metabase/db/custom_migrations_test.clj#L101)):*
<details><summary><i>Previously, dpsutton wrote…</i></summary><blockquote>

I'm going back and forth if we should be normalizing since that code could change. Use your judgment about which is better. 
</blockquote></details>

I feel like if these tests can be removed in the future with little risk anyway. The migration shouldn't change and has minimal dependencies. These tests are more about making sure the migration does what it needs to do now. And the test that doesn't use `mi/normalize-visualization-settings` is a backup that doesn't rely on this code anyway.


<!-- Sent from Reviewable.io -->

2023-05-02 16:05 UTC, merged