hide dashcard when empty setting
metabase/metabase pull request #30630
Opened 2023-05-08 23:36 UTC by alxnddr

Closes https://github.com/metabase/metabase/issues/29175

### Description

Adds a new dashcard setting that defines if the card should be visible on a dashboard when results are empty.

### How to verify

1. Create a new dashboard with a few cards
2. Open the dashcards settings and toggle they should be hidden when no results
3. Connect filters to the dashcards
4. Enter filter values that lead to empty results
5. Ensure cards get hidden

### Demo

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2023-05-17 14:06 UTC, npfitz requested changes
The only thing I noticed is that we don't seem to hide native queries when there are no results. Is this intentional? And there are a few instances of `any` that are just being called out incase they were forgotten/missed

![image](https://github.com/metabase/metabase/assets/1328979/095a922a-d96f-40b4-bc6b-9bcf572f2ddb)

2023-05-17 14:06 UTC, npfitz commented on frontend/src/metabase/dashboard/utils.ts
> +export function getDatasetQueryParams(datasetQuery: any = {}) {
`any`

2023-05-17 18:43 UTC, alxnddr commented
@npfitz I could not reproduce it for native questions, can you please share more details on which param did you use? Regarding `any`s I renamed a js file to ts which contained many utils I did not change so because of that I did not refactor the entire file to add types. Anyway, I'll figure out and add types there

2023-05-17 19:18 UTC, npfitz commented
Sure thing! So, I made a native question that looks like `Select * from Orders where CREATED_AT > {{CREATEDAT}}`, where `CREATEDAT` is a text input. Then you can try adding the parameter with a format like `2020-01-01`. I added that to the dashboard, connected the filter to it, and ran it. 

I also tried a native query like `Select * from PEOPLE where REGEXP_LIKE(NAME, {{name}}, 'i')` to search for people with specific names, and it also didn't disappear when no results were returned
![image](https://github.com/metabase/metabase/assets/1328979/4b98f8de-ad2b-42c6-aa13-511c0c6ebcc2)

2023-05-17 19:22 UTC, alxnddr commented
For some reason, still works for me:
<video src="https://github.com/metabase/metabase/assets/14301985/a6571341-120a-4efd-b89f-0a9e685bdb1b" />

2023-05-17 19:27 UTC, npfitz approved these changes
Turns out my issue earlier was with the "chair to keyboard interface"... I forgot to turn the setting on for the dashcard. Looking good!

2023-05-18 15:09 UTC, luizarakaki approved these changes

2023-05-19 20:13 UTC, merged