Fix drag + drop operations on collections pages
metabase/metabase pull request #30718
Opened 2023-05-11 22:45 UTC by iethree

Closes https://github.com/metabase/metabase/issues/30614

### Description

Basically, `react-dropzone` was either swalling all drop events on the collections page, or our other libraries were swallowing them all. I looked into writing a custom hook for file drop, but there are a lot of edge cases and cross-browser complexities that I'd rather not spend weeks dealing with.  Instead, I opted to add a flag to the `react-dropzone` library that would make it only handle drag events for files, and leave non-file drag events alone. This allows all our drag + drop operations to play nicely together.

I submitted a [pull request to the main react-dropzone repo](https://github.com/react-dropzone/react-dropzone/pull/1303), but for now, I've implemented a patch on top of the library for our immediate use.

![ALLTHEDRAGS](https://github.com/metabase/metabase/assets/30528226/ff523dd3-874c-4fff-9afb-d2ad0e62cb2d)

### How to verify

Install: you may have to nuke your node modules and `yarn cache clean` to pick up the patch correctly at first.

Testing:
- enable uploads in admin settings
- visit any collection
- see that you can upload files by dragging them into the main collection item list area 🥳 
- see that you can drag items around in pinned items as well 🥳 

### Checklist

I added unit tests in the `react-dropzone` PR. I'll add some e2e tests in metabase to test that all the drag and drop operations work properly.

- [x] Tests have been added/updated to cover changes in this PR

2023-05-12 17:26 UTC, alxnddr requested changes
It would be nice to avoid patching packages because potentially we can be stuck with upgrading them in the future.

I wonder if it is possible to find another reasonable workaround. For instance, `getRootProps()` from `useDropzone` hook returns event handlers. Can we define our own dnd event handlers that will check if the event has files and only in this case call ones from `getRootProps`?

2023-05-12 19:30 UTC, iethree commented
> It would be nice to avoid patching packages because potentially we can be stuck with upgrading them in the future.
> 
> I wonder if it is possible to find another reasonable workaround. For instance, `getRootProps()` from `useDropzone` hook returns event handlers. Can we define our own dnd event handlers that will check if the event has files and only in this case call ones from `getRootProps`?

🤦  thanks @alxnddr , that's a much simpler solution

2023-05-12 20:47 UTC, alxnddr approved these changes
🚀

2023-05-12 20:51 UTC, iethree commented on e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js
> +    dragAndDrop("draggingViz", "pinnedItems");
@nemanjaglumac I wonder if you know if there's any way to test drag + drop that doesn't involve specifying which events to fire on which elements? that actually doesn't help catch bugs that are caused by events not getting fired on the intended elements when they're dragged over.

2023-05-17 19:12 UTC, iethree commented on e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js
> +    dragAndDrop("draggingViz", "pinnedItems");
I took a close look at both https://github.com/dmtrKovalenko/cypress-real-events and https://github.com/4teamwork/cypress-drag-drop and neither allow you to do what we really need here - simulate a mouse moving over a screen region - they both rely on firing events on specific elements - the bugfix here is that the events got fired on the wrong elements while hovering the right screen region - so any test where we tell it where the fire the events will not fail. 😢

2023-05-18 19:49 UTC, merged