Attempt to fix flaky history revision test
metabase/metabase pull request #30932
Opened 2023-05-23 11:31 UTC by uladzimirdev

## Description

Attempt to fix flaky history revision cypress spec. 

<img width="1019" alt="image" src="https://github.com/metabase/metabase/assets/125459446/fabcdfa9-0661-4c35-b9f0-2cec0fe0dc9a">

In flaky runs at CI ([example](https://www.deploysentinel.com/ci/runs/64639aedb34905a540a5313b)) `/api/revision` returns the only record about dashboard creating, but not about adding a card to the dashboard. The reason for it *can be* an async nature of adding revision events on BE. 

In this PR we add a retry option for requests to the `/api/revision` until BE responds with 2 events

### At CI - 1 event in response
<img width="480" alt="Screenshot 2023-05-23 at 13 38 44" src="https://github.com/metabase/metabase/assets/125459446/686231cd-0514-4130-8e2b-49eb619fd8f1">
<img width="485" alt="Screenshot 2023-05-23 at 13 38 51" src="https://github.com/metabase/metabase/assets/125459446/08b83c21-8882-4f70-bb22-d97cf76cded7">

### Locally - 2 events in response
![image (1)](https://github.com/metabase/metabase/assets/125459446/c79f2482-f706-47ce-84fe-7ebf890b5b0f)

2023-05-24 08:03 UTC, WiNloSt approved these changes
Thank you for fixing the flake 🙇

2023-05-24 08:37 UTC, nemanjaglumac requested changes
Let's not merge this until it passes a stress-test.
https://github.com/metabase/metabase/actions/workflows/e2e-stress-test-flake-fix.yml

2023-05-24 13:08 UTC, uladzimirdev commented on e2e/support/helpers/e2e-dashboard-helpers.js
> +  retryRevisionRequest({ url, condition: ({ body }) => body.length >= count })
I followed the similar concept from another file, I believe it makes sense to separate it as it checks body length, not that big abstraction, but thanks for the point. 

The nature of revision events is async in backend so I expect to see more problems like this in the future in other related tests

2023-05-24 19:18 UTC, uladzimirdev commented
https://www.deploysentinel.com/ci/runs/646e282f61b9189af3a782fe 😱

2023-05-25 11:31 UTC, nemanjaglumac commented
This is helping to a certain extent, but I'm not convinced that the test helper is the way to go. As you can see from the logs, even with this retry mechanism in place, this test will still fail quite often:
![image](https://github.com/metabase/metabase/assets/31325167/737118b4-8d25-4bfc-be10-ed1dc0ae38ee)

Something happened on FE or between FE and BE recently that made this test flake like crazy.
I think we should take a look into the root cause of it and fix it there, rather than trying to adjust the test to hide that root problem.

2023-05-25 12:00 UTC, uladzimirdev commented
> This is helping to a certain extent, but I'm not convinced that the test helper is the way to go. As you can see from the logs, even with this retry mechanism in place, this test will still fail quite often: ![image](https://user-images.githubusercontent.com/31325167/240898630-737118b4-8d25-4bfc-be10-ed1dc0ae38ee.png)
> 
> Something happened on FE or between FE and BE recently that made this test flake like crazy. I think we should take a look into the root cause of it and fix it there, rather than trying to adjust the test to hide that root problem.

true. even bigger timeout didn't help, so something is definitely went wrong and we need to find a root cause

2023-05-25 20:49 UTC, uladzimirdev commented
As we need to continue investigation (whether it's FE-BE connection or just BE problem), I'm closing this

2023-05-25 20:49 UTC, closed without merging