Fetch field icon from dimension instead of semantic_type (#28622)
metabase/metabase pull request #31016
Opened 2023-05-24 21:21 UTC by abdulazizali77

Closes https://github.com/metabase/metabase/issues/28622

### Description

Use `field.dimension().icon()` instead of `field.semantic_type`

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Click on New -> Notebook -> Accounts
2. Verify Boolean and other icons are correct 

### Demo

![image](https://github.com/metabase/metabase/assets/23547158/257e3676-fe33-434b-8c3b-35c803e6c175)

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2023-06-08 15:49 UTC, shaunlebron requested changes

2023-06-12 14:59 UTC, shaunlebron commented on frontend/src/metabase/query_builder/components/dataref/FieldList.tsx
> +              name={field.dimension().icon()}
I went ahead and made the requested changes, and rebased onto master since we have a new icon set.

2023-06-12 15:00 UTC, shaunlebron submitted a review, later dismissed

2023-06-12 21:02 UTC, closed without merging

2023-06-12 21:24 UTC, shaunlebron commented
Recreated PR here: https://github.com/metabase/metabase/pull/31538

2023-06-14 18:09 UTC, shaunlebron commented
Apologies for re-creating the PR, that was due to a mixup here about policy.

Your change was merged, thank you! 🙌

2023-06-15 01:57 UTC, abdulazizali77 commented
@shaunlebron i apologize for my delays you had to do what you had to do for the good of the project, not for me or yourself thank you