fix dashboard save failure after deleting tabs
metabase/metabase pull request #31039
Opened 2023-05-25 17:40 UTC by EmmadUsmani

Closes https://github.com/metabase/metabase/issues/30923

### Description

When we added the undo toast notification for deleting tabs in https://github.com/metabase/metabase/pull/30497, a regression was introduced where saving a dashboard could fail after deleting tabs.

This PR fixes this by updating the logic for tab deletion to understand that tabs now follow a tombstone deletion model, thus we ignore tabs that have an `isRemoved: true` attribute.

### How to verify

1. New dashboard
2. Add two new tabs
3. Delete `Page 2`
4. Delete `Page 3`
5. Add a card
6. Save

### Demo

TODO

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

2023-05-25 20:05 UTC, JesseSDevaney requested changes
This fixes the targeted issue, but accidentally introduces a regression in reverting tab deletions. I made a suggestion with a couple ideas for how to fix it. If you have a better idea, then go for it :heart:

2023-05-25 20:41 UTC, JesseSDevaney commented
Also, unrelated to this issue and I may be incorrect, but I think there is some unused code in the `deleteTab` case.
```typescript
builder.addCase(
      deleteTab,
      (state, { payload: { tabId, tabDeletionId } }) => {
        const { dashId, prevDash, prevTabs } = getPrevDashAndTabs(state);
        const tabToRemove = prevTabs.find(({ id }) => id === tabId);
        if (!dashId || !prevDash || !tabToRemove) {
          throw Error(
            `DELETE_TAB was dispatched but either dashId (${dashId}), prevDash (${prevDash}), or tabToRemove (${tabToRemove}) is null/undefined`,
          );
        }
        // 1. Select a different tab if needed
        const noTabsRemaining = prevTabs.length === 1; // **************************
        const deletingSelectedTab = state.selectedTabId === tabToRemove.id;

        if (noTabsRemaining) { // **************************
          state.selectedTabId = null; // **************************
        } else if (deletingSelectedTab) {
          const tabToRemoveIndex = prevTabs.findIndex(
            ({ id }) => id === tabToRemove.id,
          );
          const targetIndex = tabToRemoveIndex === 0 ? 1 : tabToRemoveIndex - 1;
          state.selectedTabId = prevTabs[targetIndex].id;
        }
        // 2. Mark the tab as removed
        tabToRemove.isRemoved = true;
        // 3. Mark dashcards on removed tab as removed
        const removedDashCardIds: DashCardId[] = [];
        prevDash.ordered_cards.forEach(id => {
          if (state.dashcards[id].dashboard_tab_id === tabToRemove.id) {
            state.dashcards[id].isRemoved = true;
            removedDashCardIds.push(id);
          }
        });
        // 4. Add deletion to history to allow undoing
        state.tabDeletions[tabDeletionId] = {
          id: tabDeletionId,
          tabId: tabToRemove.id,
          removedDashCardIds,
        };
      },
    );
```

I think the unused code is:
```typescript
const noTabsRemaining = prevTabs.length === 1;

if (noTabsRemaining) {
  state.selectedTabId = null;
```
Is there actually a point where there would be only one tab and we are able to delete it? Deleting a tab is disabled for dashboards with only one tab if I am not wrong?

2023-05-25 20:50 UTC, EmmadUsmani commented on frontend/src/metabase/dashboard/actions/tabs.ts
> +  const prevTabs = prevDash?.ordered_tabs?.filter(t => !t.isRemoved) ?? [];
Thanks for the thorough explanation and suggestions! I'll the code to use 2

2023-05-25 20:52 UTC, EmmadUsmani commented
> Also, unrelated to this issue and I may be incorrect, but I think there is some unused code in the deleteTab case.

@JesseSDevaney Nice catch! The original behavior was that you could delete the last tab, I forgot to remove this code when we changed it. I'll update this as well.

2023-05-30 15:22 UTC, alxnddr approved these changes

2023-05-30 15:36 UTC, JesseSDevaney approved these changes

2023-05-30 17:53 UTC, merged