Refreshing page in some unedited questions triggers browser warning
metabase/metabase pull request #31080
Opened 2023-05-26 15:17 UTC by oisincoveney

Closes https://github.com/metabase/metabase/issues/30905

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2023-05-29 14:43 UTC, ranquild approved these changes

2023-05-29 17:34 UTC, mazameli requested changes
In my testing this seems to introduce a regression: https://www.loom.com/share/7c709ccacbd544ad9e28894f8a68e07c

2023-05-31 17:33 UTC, cdeweyx approved these changes
Works as expected for me.

2023-05-31 22:21 UTC, mazameli approved these changes

2023-06-02 13:24 UTC, merged