Release script: exclude EBS artifact publish from manual steps
metabase/metabase pull request #31444
Opened 2023-06-08 19:03 UTC by ariya

After PR #28516 is merge, there is no need anymore for the release manager to create and publish EBS (Elastic Beanstalk) artifacts, as it is now is taken care automatically (see `.github/workflow/release.yml`), once the release tag (e.g. `v1.x.y` and `v0.x.y`, for the EE and OSS respectively) is pushed to this repository.

### Before this PR

The release manager manually runs a release script when doing a release. One step in that release script is to build and publish EBS artifacts.

### After this PR

The step in publish EBS artifacts gone. Instead, the process is replaced by the release workflow (`release.yml`).

Example of such a run: https://github.com/metabase/metabase/actions/runs/5071492376/jobs/9108071086

2023-06-08 20:10 UTC, nemanjaglumac requested changes
I don't think we can remove this step without extracting `:update-version-info` step first.
Otherwise `:update-version-info` will almost certainly fail as part of the manual release process.

2023-06-09 01:27 UTC, ariya commented
> Otherwise `:update-version-info` will almost certainly fail as part of the manual release process.

Hmm, not clear to me why that will fail, as the function `release.version-info/update-version-info!*` seems to be independent from anything related to EBS. Care to elaborate?

2023-06-09 15:36 UTC, nemanjaglumac commented
> Hmm, not clear to me why that will fail, as the function `release.version-info/update-version-info!*` seems to be independent from anything related to EBS. Care to elaborate?

I was under the impression that the second cloudfront invalidation we're doing immediately after "push to EBS" step is related to the EBS?

The first time we're doing cloudfront invalidation is after we push JARs to S3 (`downloads.metabase.com`). The second cloudfront invalidation happens after we push to EBS.

Are they not related?

2023-06-09 20:13 UTC, nemanjaglumac approved these changes

2023-06-10 06:22 UTC, merged