[Milestone] Add action edit in action execute modal (#31171)
metabase/metabase pull request #31478
Opened 2023-06-09 16:26 UTC by deniskaber

Milestone of https://github.com/metabase/metabase/issues/29866

### Description

I should be able to update / edit the action definition, (or do anything else I could normally do in that modal) and hit Update. I’m then sent back. 

### Demo

https://github.com/metabase/metabase/assets/7983744/7a84466e-477a-43e5-bc7d-31df9264cf9e

2023-06-12 13:16 UTC, kdoh requested changes
Overall looking solid. Just one small item. I think we're going to want a `Tooltip` on the pencil icon in the modal that says `Edit this action.`

<img width="342" alt="Screen Shot 2023-06-12 at 9 16 23 AM" src="https://github.com/metabase/metabase/assets/5248953/0940910b-fac0-4777-97de-36a82b28fe62">

2023-06-12 15:24 UTC, cdeweyx approved these changes
Pending tooltip comment above, working as expected 👌

2023-06-12 16:12 UTC, kdoh approved these changes

2023-06-13 13:48 UTC, ranquild approved these changes

2023-06-13 23:13 UTC, merged