moving instance analytics logic to enterprise
metabase/metabase pull request #31484
Opened 2023-06-09 19:25 UTC by npfitz

Closes https://github.com/metabase/metabase/issues/31212

### Description
Moves logic to determine collection Icon to enterprise plugins

### How to verify
Verify that collections in the nav bar show the correct icons, and that the collection header also shows the beaker icon

### Demo
![image](https://github.com/metabase/metabase/assets/1328979/657b0f3c-4d03-4893-b57b-9a45b052b8ea)

### Checklist
- [ ] Tests have been added/updated to cover changes in this PR

2023-06-12 20:18 UTC, iethree requested changes
Approach looks good, I think we just need to move one other function as well. 👍

2023-06-12 20:18 UTC, iethree commented on enterprise/frontend/src/metabase-enterprise/collections/utils.ts
we should probably move the `getCollectionTooltip` function from `entities/collections/utils` into this file as well.

2023-06-13 22:59 UTC, iethree approved these changes
Nice. thanks for doing this rather tedious and boring bit of moving stuff around.

I think there's a couple unit tests that just need

```js
beforeEach(() => {
    setupEnterpriseTest();
});
```

2023-06-14 15:23 UTC, oisincoveney approved these changes
Just here for the `DashboardHeader` unit test changes, looks good 😄

2023-07-03 13:38 UTC, merged