add collection_type to search results
metabase/metabase pull request #31565
Opened 2023-06-13 18:33 UTC by escherize

I am not sure where these _should_ go. But they are going here.
 
<img width="775" alt="Screen Shot 2023-06-13 at 12 33 27 PM" src="https://github.com/metabase/metabase/assets/343288/6ef91fbf-f817-437a-8523-a5bcbdad9be0">

Can you check that that is where it's expected, @iethree ?

2023-06-13 20:03 UTC, noahmoss approved these changes

2023-06-13 23:45 UTC, iethree commented
can you put the type inside the collection object  as a `type` property, instead of its own top-level property as `collection_type`? That way it will "just work" on the front end.
![Screen Shot 2023-06-13 at 5 44 04 PM](https://github.com/metabase/metabase/assets/30528226/e20d1f62-b9e7-42fb-bf61-25cfdc497279)

Otherwise, I have to do something stupid like this to move it around on the frontend


![Screen Shot 2023-06-13 at 5 43 24 PM](https://github.com/metabase/metabase/assets/30528226/921f51ed-6475-4446-a40a-f4f8c0d1aedd)

2023-06-22 16:48 UTC, iethree requested changes
I think it's best if we keep the collection properties inside the collection object if feasible

2023-10-06 20:30 UTC, escherize commented
closed, this moving to #34451

2023-10-06 20:30 UTC, closed without merging