docs - upload size capped at 50 mbs
metabase/metabase pull request #31828
Opened 2023-06-23 19:08 UTC by jeff-bruemmer

Updates upload limit in docs from 200 to 50 MB.

2023-06-24 00:32 UTC, iethree requested changes

2023-06-24 00:32 UTC, iethree commented on docs/databases/uploads.md
> +> While Metabase limits uploads to 50 MB, the server you use to run your Metabase may impose a lower limit. For example, the default client upload limit for [NGINX is 1 MB](https://nginx.org/en/docs/
There's another reference to 200 in the second paragraph

2023-06-24 12:52 UTC, jeff-bruemmer commented on docs/databases/uploads.md
> +> While Metabase limits uploads to 50 MB, the server you use to run your Metabase may impose a lower limit. For example, the default client upload limit for [NGINX is 1 MB](https://nginx.org/en/docs/
```suggestion
> While Metabase limits uploads to 50 MB, the server you use to run your Metabase may impose a lower limit. For example, the default client upload limit for [NGINX is 1 MB](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size). So you may need to change your server settings to allow uploads up to 50 MB. People on Metabase Cloud don't have to worry about this.
```

2023-06-26 16:26 UTC, iethree approved these changes
🥳

2023-06-26 16:26 UTC, merged