Prevent returning implicitly joined fields for saved questions
metabase/metabase pull request #31883
Opened 2023-06-26 23:02 UTC by metamben

Fixes #30950.

2023-06-27 20:13 UTC, snoe requested changes
I can see it works but it looks like magic.

2023-06-27 20:13 UTC, snoe commented on src/metabase/lib/stage.cljc
> +           not-empty))))
I could not figure out why this works, maybe updating the comment would be helpful?

1. With `:include-implicitly-joinable? false` I would not expect any implicitly joinable columns, and am surprised the `dissoc` is necessary.
2. Doing this `dissoc` would seem to mark columns as not implicitly joinable but somehow this causes removal of implicitly joinable columns somewhere else.

2023-06-27 23:04 UTC, snoe approved these changes

2023-06-28 15:37 UTC, merged

2023-08-16 21:52 UTC, metamben commented on test/metabase/lib/stage_test.cljc
>                  (lib.metadata.calculation/visible-columns query)))))))
@camsaul Reverting this test is questionable, but required for this PR to work. In this case at least I know that issue I fixed in #30950 by removing implicitly joinable fields everywhere is fixed in this PR differently (i.e., only for orderable and breakoutable columns).