Fix loading values for virtual fields
metabase/metabase pull request #31906
Opened 2023-06-27 16:19 UTC by ranquild

Fixes https://github.com/metabase/metabase/issues/30562

2023-06-28 11:41 UTC, ranquild commented on frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.unit.spec.js
> +    it("should not call fetchFieldValues", () => {
Follows the same pattern used in other tests in this file

2023-06-30 07:21 UTC, kamilmielnik requested changes
This change breaks code that follows it

2023-06-30 07:21 UTC, kamilmielnik commented on frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.jsx
> +          .filter(field => !field.isVirtual())
:x: 

I tried the branch locally and while reproducing it (just followed the steps) I noticed that there's a JS error coming from `dedupeValues` call right in the next line (192). It also happens afterwards, when trying to edit the filter.
The error is caused by this change.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at FieldValuesWidget.jsx:458:1
    at Array.map (<anonymous>)
    at dedupeValues (FieldValuesWidget.jsx:458:1)
    at _callee$ (FieldValuesWidget.jsx:184:1)
    at tryCatch (runtime.js:63:1)
    at Generator.invoke [as _invoke] (runtime.js:293:1)
    at Generator.next (runtime.js:118:1)
    at asyncGeneratorStep (index.jsx:1:1)
    at _next (index.jsx:1:1)
```

![image](https://github.com/metabase/metabase/assets/6830683/eefade83-755d-4652-8190-547e7dab3e4a)

2023-06-30 13:11 UTC, ranquild commented
@kamilmielnik fixed, please take a look

2023-06-30 13:17 UTC, kamilmielnik approved these changes
LGTM :+1:

2023-06-30 17:39 UTC, merged