Remove CSS re-writing with whitelabel
metabase/metabase pull request #32478
Opened 2023-07-18 16:48 UTC by ranquild

Related to https://github.com/metabase/metabase-private/issues/73

Removes rewriting CSS on the fly to support whitelabeling. When the integration branch would be ready for merging, all whitelabeled colors would set using `color` function and not css.

2023-07-18 19:25 UTC, uladzimirdev commented
@ranquild what about broken e2e tests?

2023-07-19 08:51 UTC, WiNloSt requested changes
The change itself makes sense. I think the JS color updated logic is 1:1 to the previous version.

Only the `applicationName()` needs to be fixed though.

2023-07-19 08:53 UTC, WiNloSt commented
@uladzimirdev 
>  what about broken e2e tests?

I believe that's because the application failed to run. See https://github.com/metabase/metabase/pull/32478#discussion_r1267750767.

2023-07-19 09:06 UTC, ranquild commented
@uladzimirdev ignore failing e2e tests for now

2023-07-19 09:08 UTC, ranquild commented
@WiNloSt fixed applicationName

2023-07-19 10:07 UTC, WiNloSt approved these changes
Awesome! The lastest commit works now. As stated earlier, this refactor is 1:1 to the previous implementation but only remove the CSS updater part.

2023-07-19 11:55 UTC, merged