Update snowplow schema to include new feature flags
metabase/metabase pull request #32619
Opened 2023-07-25 03:46 UTC by qnkhuat

2023-07-25 06:37 UTC, ranquild requested changes
@qnkhuat we should still allow old flags in the schema otherwise events from old instances would be rejected

2023-07-25 06:44 UTC, qnkhuat commented
@ranquild good point. added back with a deprecated note.

2023-07-25 06:57 UTC, ranquild commented on snowplow/iglu-client-embedded/schemas/com.metabase/instance/jsonschema/1-1-2
> +    "version": "1-1-1"
@qnkhuat please also update version here

2023-07-25 13:46 UTC, qnkhuat commented on snowplow/iglu-client-embedded/schemas/com.metabase/instance/jsonschema/1-1-2
> +    "version": "1-1-1"
updated [f8aea41](https://github.com/metabase/metabase/pull/32619/commits/f8aea41b03f49a0d339193261c75ffa2a9ecac2e)

2023-07-26 14:39 UTC, ranquild approved these changes

2023-07-27 05:38 UTC, merged