Add `lib.field/add-field` and `remove-field`
metabase/metabase pull request #32679
Opened 2023-07-26 19:21 UTC by bshepherdson

These are "porcelain" APIs to make FE management of the set of selected
columns for a query much easier.

`add-field` and `remove-field` will handle regular table fields,
explicit join fields, and custom expressions correctly.

DO NOT SUBMIT - remove isn't actually implemented yet.

2023-07-27 17:38 UTC, metamben requested changes
I would like to see some tests with multi-stage queries with columns coming from aggregates, breakouts, etc.

I would use `cond->` in many places, just ignore these suggestions if you don't like it.

2023-07-27 17:38 UTC, metamben commented on src/metabase/lib/field.cljc
> +(defn- remove-top-field
What should I associate `top` with?

2023-07-27 17:38 UTC, metamben commented on src/metabase/lib/field.cljc
> +          (lib.remove-replace/replace-join query stage-number join (lib.join/with-join-fields join removed)))))))
Another `cond->`. (In my reading that would correspond to the "Return the query unchanged" part of the comment.)

2023-07-27 17:38 UTC, metamben commented on src/metabase/lib/field.cljc
> +                                    query)
And another `cond->`.

2023-07-28 18:17 UTC, bshepherdson commented on src/metabase/lib/field.cljc
> +      ;; returned and cannot be selected off and on.
Added and tested.

2023-08-01 13:58 UTC, metamben approved these changes
Awesome!

2023-08-01 13:58 UTC, metamben commented on src/metabase/lib/field.cljc
> +      ;; Default case - for columns from a card, from a native query, from a custom expression - these are always
This looks outdated.

2023-08-01 13:58 UTC, metamben commented on src/metabase/lib/field.cljc
> +                     (not (:fields (lib.util/query-stage query stage-number))) (populate-fields-for-stage stage-number)
I suggest introducing `query-with-fields`.

2023-08-01 13:58 UTC, metamben commented on src/metabase/lib/field.cljc
> +      - If `:fields` is missing, it's implicitly `:all` - populate it with all the columns except the removed one.
Update?

2023-08-01 13:58 UTC, metamben commented on src/metabase/lib/js.cljs
> +      - If `:fields` is missing, it's implicitly `:all`, so do nothing.
Update?

2023-08-01 13:58 UTC, metamben commented on src/metabase/lib/js.cljs
> +      - If `:fields` is missing, it's implicitly `:all` - populate it with all the columns except the given one.
Update?

2023-08-02 10:06 UTC, merged