[WIP] Handle breakout detection in multistage queries
metabase/metabase pull request #32872
Opened 2023-08-02 20:11 UTC by iethree

> **Warning**
> WIP checking CI

Closes https://github.com/metabase/metabase/issues/22563

### Description

The reproduction is complex in the issue, but the essence of this bug is that when you have both aggregations and custom columns in a query, the column settings ignore logic that should be in effect for aggregated queries. Thus, when you hide columns, for some reason the query updates to add a fields clause to the query. 

Before | After
--- | ---
![beforebreakoutsfix](https://github.com/metabase/metabase/assets/30528226/57eb739d-59e0-4a87-8d54-8871555f5e35) | ![afteraggfix](https://github.com/metabase/metabase/assets/30528226/d695179a-d7b8-42e4-89f2-b5e98492026d)

The cause I found was that we produce `additionalFieldOptions` for this query when we shouldn't. Those options are behind a "hasBreakouts" check, but when we have a custom column, the query becomes multi-stage, and we only check for aggregations on the last stage of the query.  I simply updated the `hasBreakouts()` function to check all stages of the query.

I have serious misgivings about whether this change is safe. Running CI to see what happens. I suspect that even if this is a "correct" implementation, other parts of the codebase might rely on the incorrect implementation that appears to not have been touched for 4 years.

### How to verify

Follow Flamber's repro steps.

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2023-08-04 09:12 UTC, kamilmielnik commented on frontend/src/metabase-lib/queries/StructuredQuery.ts
> +    if (this.isBareRows() && !this.hasAnyBreakouts()) {
This line did not change semantically but behavior did.
It's not possible to guess/tell the difference between `hasBreakouts()` and `hasAnyBreakouts()` without looking at their code. I suggest to make the name more specific:


```suggestion
    if (this.isBareRows() && !this.anySourceQueryHasBreakouts()) {
```

2023-08-04 09:12 UTC, kamilmielnik commented on frontend/src/metabase-lib/queries/StructuredQuery.ts
> +    return this.queries().some(query => query.hasBreakouts());
Should we also check `this.query()` here?

I mean

```suggestion
    return [this.query(), ...this.queries()].some(query => query.hasBreakouts());
```

or

```suggestion
    return this.hasBreakouts() || this.queries().some(query => query.hasBreakouts());
```

----

If that's the case, then I'd call this function `anyQueryHasBreakouts`.

2023-08-07 11:16 UTC, ranquild requested changes
@iethree We're currently migrating this part of the app to MLv2 here https://github.com/metabase/metabase/pull/32698. I think it would make sense for the MLv2 PR to land and then fix the issue on the clojure side if it exists. Wdyt?

2023-08-07 13:55 UTC, iethree commented
> @iethree We're currently migrating this part of the app to MLv2 here #32698. I think it would make sense for the MLv2 PR to land and then fix the issue on the clojure side if it exists. Wdyt?

how about i change this PR to just have the skipped repro then?

2023-08-09 05:53 UTC, kamilmielnik approved these changes
:+1:

2023-08-09 14:57 UTC, ranquild approved these changes

2023-08-09 14:58 UTC, merged