Collapse temporal units list
metabase/metabase pull request #32953
Opened 2023-08-04 17:41 UTC by kulyk

A few people ran into a similar UX hiccup: when picking a temporal unit for a column (e.g. for a breakout), it's not obvious there're more options. The popover has a fixed height and there's no hint it's scrollable. This PR implements @mazameli's solution: we'd only display the first seven items and show a "More" icon that can expand the picker.

A few behavior nuances:

* we shouldn't display the "More" button if there're fewer than seven options (e.g. for binning strategies because the picker component is shared)
* we shouldn't collapse the list if a selected temporal unit is one of the "advanced" options
* (I assume) we should collapse the list again after a unit is selected

### How to verify

1. New > Question > Raw Data > Sample Database > Orders
2. Click "Pick a column to group by"
3. Hover the "Total" column, click the "Auto-binned" label on the right
4. Ensure you can see all the options and there's no "More" button
5. Hover the "Created At" column, click the "by month" label on the right
6. Ensure you can only see the first seven opts (from Minute to Year) and the "More" button
7. Click the More button, ensure you can see all the units
8. Pick a unit from the end of the list, open that popover for the "Created At" column again, and ensure the list is expanded
9. Pick a unit from the beginning of the list, open that popover for the "Created At" column again, and ensure the list is collapsed again

### Demo

**Before**

https://github.com/metabase/metabase/assets/17258145/01ae1366-16ae-446a-aa91-8c24a581a35f

**After**

https://github.com/metabase/metabase/assets/17258145/b816c2c7-e2aa-45fa-bfd8-82ad6cd38a91

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

2023-08-04 18:40 UTC, mazameli requested changes
I didn't consider this state, where you've selected one of the granularities that are beneath the More click, and you reopen the granularity picker: 
<img width="479" alt="image" src="https://github.com/metabase/metabase/assets/2223916/d28c1055-0e00-4a31-9503-69290fabd8cf">

I think we need to do this, i.e. display the correct chosen granularity in the column picker, and then expand the items that would be inside the More if the chosen granularity is one of them:
<img width="1212" alt="image" src="https://github.com/metabase/metabase/assets/2223916/82cf054c-552d-418e-b0ef-4aa1ccee897b">

2023-08-04 18:46 UTC, mazameli commented
I'd also suggest:
- Make the `min-width` of the popover 160px, so that the width doesn't change so dramatically when clicking "More"
- Reduce the left-margin or padding on the text in the popover by 8px, because it appears to me like there's too much space to the left right now

Mucking around in the inspector, I got this, which I think looks nicer:
<img width="510" alt="image" src="https://github.com/metabase/metabase/assets/2223916/efb9a214-d62a-4cd8-9b37-23bb73e42dbb">

2023-08-08 04:17 UTC, shaunlebron approved these changes

2023-08-08 06:21 UTC, kamilmielnik approved these changes
Looks good :+1: 
Left some minor comments.

2023-08-08 12:51 UTC, kulyk commented on frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx
> +              style={{ padding: "8px 16px" }}
Ouch, totally forgot about that one. Thanks!

2023-08-08 12:53 UTC, kulyk commented on frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BucketPickerPopover.unit.spec.tsx
> +    expect(screen.getAllByRole("menuitem")).toHaveLength(buckets.length + 1);
Woah, I really like that idea, thanks!

2023-08-09 10:57 UTC, kulyk commented
@mazameli fyi, auto-expanding the list if the selected unit is at the latter part of the list should work, I think we have an issue with figuring out which unit is actually displayed. I'll let you know once it's fixed, so you could take another look. Just wanted to let you know what's going on

2023-10-12 18:30 UTC, mazameli reviewed
This all looks good to me — but I realized I didn't spec a hover state for the "More" item. If we can add that then I can approve!

<img width="395" alt="image" src="https://github.com/metabase/metabase/assets/2223916/865fadf9-3dce-480d-adbb-1435ec70b43a">

2023-10-13 16:27 UTC, mazameli approved these changes
Works for me! Ideally the `More` link would not have the CSS transition effect on hover since the other items in the popover don't, but if that's an annoying exception then it doesn't bother me a ton.

![hover-transition](https://github.com/metabase/metabase/assets/2223916/0e46acaf-ec43-42b8-9c35-39d2e9857e35)

2023-10-13 18:15 UTC, merged