Mantine menu
metabase/metabase pull request #33097
Opened 2023-08-10 16:45 UTC by ranquild

Closes https://github.com/metabase/metabase/issues/32273

2023-08-11 14:32 UTC, kdoh requested changes
Looking good in general. I do think it would be worthwhile to add more "realistic" data in the previews to better sense how things are working. I provided some examples as suggestions.

I'd like Dawei to take a look as well and confirm that he's happy with the spacing and sizing since he was in charge of the spec for this one. One thing I noticed was that the hover color felt a little bit too dark compared to what's in product in spots like the `New` menu. I know it matches "what's in Figma" but curious if we have any different feelings seeing it in its native habitat.

2023-08-11 14:32 UTC, kdoh commented on frontend/src/metabase/ui/components/layovers/Menu/Menu.stories.mdx
> +<Meta title="Layovers/Menu" component={Menu} args={args} argTypes={argTypes} />
```suggestion
<Meta title="Overlays/Menu" component={Menu} args={args} argTypes={argTypes} />
```
Would tweak this so it matches our Figma structure.

2023-08-11 14:32 UTC, kdoh commented on frontend/src/metabase/ui/components/layovers/Menu/Menu.stories.mdx
> +        <Menu.Item>Text</Menu.Item>
```suggestion
        <Menu.Item>Option 1</Menu.Item>
```

2023-08-11 14:32 UTC, kdoh commented on frontend/src/metabase/ui/components/layovers/Menu/Menu.stories.mdx
> +        <Menu.Item>Text</Menu.Item>
```suggestion
        <Menu.Item>Option 2 - Electric Boogaloo</Menu.Item>
```

2023-08-11 14:32 UTC, kdoh commented on frontend/src/metabase/ui/components/layovers/Menu/Menu.stories.mdx
> +        <Menu.Item>Text</Menu.Item>
```suggestion
        <Menu.Item>Option 3</Menu.Item>
```

2023-08-11 14:32 UTC, kdoh commented on frontend/src/metabase/ui/components/layovers/Menu/Menu.stories.mdx
> +          Text
```suggestion
          Keyboard option
```

2023-08-11 14:32 UTC, kdoh commented on frontend/src/metabase/ui/components/layovers/Menu/Menu.stories.mdx
> +        <Menu.Item>Text</Menu.Item>
```suggestion
        <Menu.Item>Option 5</Menu.Item>
```

2023-08-11 14:32 UTC, kdoh commented on frontend/src/metabase/ui/components/layovers/Menu/Menu.stories.mdx
> +        <Menu.Item icon={<Icon name="dashboard" />}>Text</Menu.Item>
```suggestion
        <Menu.Item icon={<Icon name="question" />}>Question</Menu.Item>
```

2023-08-11 14:32 UTC, kdoh commented on frontend/src/metabase/ui/components/layovers/Menu/Menu.stories.mdx
> +        <Menu.Item icon={<Icon name="dashboard" />}>Text</Menu.Item>
```suggestion
        <Menu.Item icon={<Icon name="dashboard" />}>SQL Query</Menu.Item>
```

2023-08-11 14:32 UTC, kdoh commented on frontend/src/metabase/ui/components/layovers/Menu/Menu.stories.mdx
> +        <Menu.Item icon={<Icon name="dashboard" />}>Text</Menu.Item>
```suggestion
        <Menu.Item icon={<Icon name="dashboard" />}>Dashboard</Menu.Item>
```

2023-08-11 14:32 UTC, kdoh commented on frontend/src/metabase/ui/components/layovers/Menu/Menu.stories.mdx
> +        <Menu.Item icon={<Icon name="dashboard" />}>Text</Menu.Item>
```suggestion
        <Menu.Item icon={<Icon name="dashboard" />}>Collection</Menu.Item>
```

2023-08-11 14:32 UTC, kdoh commented on frontend/src/metabase/ui/components/layovers/Menu/Menu.stories.mdx
> +        <Menu.Item icon={<Icon name="dashboard" />}>Text</Menu.Item>
```suggestion
        <Menu.Item icon={<Icon name="dashboard" />}>Action</Menu.Item>
```

2023-08-14 19:22 UTC, dhuniverse commented
Looking good in general. A couple of small udpates to consider. 

1.  On the docs tab / General section, the [Toggle menu] was inside a bounding div. Clicking on it won't be able to show the entire menu list. I would suggest showing the menu popup totally via moving the [Toggle menu] out of the bounding area, or remove the bounding constraints.
2. On the docs tab / General section, the sub-sections are identical. Suggestion adding a sub-header to differentiate the sub-sections.
3. For the top sections on the docs tab, I have written a draft content for each. Please see those in [Figma](https://www.figma.com/file/MZhwfwmOaa8HeCBBUCeq7R/Menu?type=design&node-id=442%3A676&mode=design&t=SggFFFXFkpkiTfBA-1).

2023-08-14 21:06 UTC, kdoh reviewed
Happy to move forward once Dawei's happy with things.

2023-08-15 09:35 UTC, ranquild commented
@dhuniverse I've updated the docs, all the mentioned issues should be fixed. Please take a look

<img width="1067" alt="Screenshot 2023-08-15 at 12 33 28" src="https://github.com/metabase/metabase/assets/8542534/0b17fc48-d20d-4fa8-b57f-e64e3a7f2614">

2023-08-15 13:02 UTC, oisincoveney reviewed
Looks really good from my side, love that you broke out the styles as well! I'm happy if the others are happy

2023-08-15 14:05 UTC, kdoh approved these changes
Nice work. I'm happy. Let's ship it. 🥇  (Also very into the extracted overrides).

2023-08-15 15:40 UTC, merged