Fix null series title
metabase/metabase pull request #33331
Opened 2023-08-18 12:32 UTC by iethree

Closes https://github.com/metabase/metabase/issues/32107

### Description

When we had empty series breakouts, we didn't show the label. Also updated the series settings to use the localized `(empty)` instead of unlocalized `UNKNOWN`

It seems a little strange to show an empty series breakout, but I think it's the correct behavior, the only problem was the label not showing up. See discussion in #32959 as well as issues: https://github.com/metabase/metabase/issues/12782 and https://github.com/metabase/metabase/issues/4995

![Screen Shot 2023-08-18 at 6 29 46 AM](https://github.com/metabase/metabase/assets/30528226/65a9b8b0-e0fe-4cf6-8726-10c5226bfeb6)

### How to verify

- sample query

```
select 1 id, 50 val1, null val2
union all select 2, 75, null
union all select 3, 175, null
union all select 4, 200, null
union all select 5, 280, null
```
- choose a line chart
- update column settings like this:
![Screen Shot 2023-08-18 at 6 29 46 AM](https://github.com/metabase/metabase/assets/30528226/c9f3257e-3e53-4161-877c-5e49875af84b)

- see that (empty) appears in the chart legend now

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

2023-08-19 19:08 UTC, JesseSDevaney requested changes
:+1: The fix worked for me. 

There is just one discrepancy between **Row Charts** and the other charts - the label for **Row Charts** changes to `null` instead of `(empty)`. If it does not require a lot of work, we should fix that so the labels do not have different names across different charts.

2023-08-21 14:16 UTC, iethree commented on frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx
> +          ),
wow. great catch @JesseSDevaney

2023-08-22 21:44 UTC, JesseSDevaney requested changes
:tada: It is now showing `(empty)` instead of null

But alas, I found another thing :cry:. Sorry for being the bearer of bad (good that we will fix it) news :heart: 

---
Row Chart legend disappears when the filtered column has cardinality one
- e.g. only nulls in the column, only 1s in the column, ...

![legend-now-missing-on-null-column](https://github.com/metabase/metabase/assets/22608765/b85c11e1-edbf-4982-a73e-6144c5110ccb)

---
**Issue Location**

Upon a quick investigation, the issue is located in [RowChart.tsx](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx#L268). The fix might be checking whether [chartColumns](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx#L118) has a breakout property instead of the current `series.length > 1` check - but there are also may be a better solution.

2023-08-22 22:40 UTC, iethree commented
> 🎉 It is now showing `(empty)` instead of null
> 
> But alas, I found another thing 😢. Sorry for being the bearer of bad (good that we will fix it) news ❤️
> 
> Row Chart legend disappears when the filtered column has cardinality one

Huh. interesting find. It's not entirely clear to me that this is a bug, or what the right behavior is, but it is interesting how row and column charts behave differently.  I wonder if @dhuniverse or @luizarakaki could weigh in on what the desired behavior is here.

https://www.loom.com/share/7d8dcd94ee8b4336ba808f6c25f10192

2023-08-23 17:55 UTC, luizarakaki commented
If the chart is a line chart, the legend is hidden if there is only one series.

I think we should remove the legend everytime there is only one series... it takes space and doesn't add any information

2023-08-23 19:06 UTC, JesseSDevaney commented
> Huh. interesting find. It's not entirely clear to me that this is a bug, or what the right behavior is, but it is interesting how row and column charts behave differently. I wonder if @dhuniverse or @luizarakaki could weigh in on what the desired behavior is here.
> 
> https://www.loom.com/share/7d8dcd94ee8b4336ba808f6c25f10192
> \- Ryan

> If the chart is a line chart, the legend is hidden if there is only one series.
> 
> I think we should remove the legend everytime there is only one series... it takes space and doesn't add any information
> \- Luiz

@luizarakaki The issue here is not that the legend is shown/hidden with only one series. The issue is that when there are multiple series and the breakout series has only cardinality one - only one 'group' of values - it hides the legend on RowCharts, whereas it does not do that on other charts (Bar, Line, Area, Combo, ...).

---
## Example

**Visualization Settings**

_Without Filter_
![image](https://github.com/metabase/metabase/assets/22608765/fc6af985-28c0-48f3-8fae-677351e92f61)

_With Filter_
![image](https://github.com/metabase/metabase/assets/22608765/759aee77-10d4-4750-9b64-e38f69b3b398)

**Chart Legends** (with filter applied)
_Row Charts are missing the legend when breakout series has cardinality one_

https://github.com/metabase/metabase/assets/22608765/42c0f59c-27cd-40ec-9e3d-f4229e427ce9

2023-08-23 19:31 UTC, luizarakaki commented
Yeah I understand that... A 1-cardinality breakout is effectively one series. I don't see much value in keeping the legend.

I'm trying to find a case when it would be useful, but most of the times this happens if the user is already filtering a single category (so the legend is not useful). The breakout also appears on hover if necessary...

Maybe we are trying to be too smart to save space, but I think it is reasonable to hide the legend on this case

2023-08-23 20:14 UTC, JesseSDevaney commented
I think hiding it decreases the context and therefore value of the charts.

---
**1. Filters can be hidden**

_With legend_
![image](https://github.com/metabase/metabase/assets/22608765/8561f65c-c1d9-481a-bae2-441365ffac81)

_Without legend_
![image](https://github.com/metabase/metabase/assets/22608765/565986ae-3fef-4118-81a6-bc85433394f7)


---
**2. On a dashboard, filters are not explicit for individual questions**

_With legend_
![image](https://github.com/metabase/metabase/assets/22608765/d718693b-da74-4b13-aeac-b4036d59b054)

_Without legend_
![image](https://github.com/metabase/metabase/assets/22608765/5a530913-f242-4ec3-aafd-865ce260b630)


---
**3. In dashboard subscriptions, the filter is not explicit**
_If the title were not explicit, this would be confusing because we would think we are looking at all data when in reality we are looking at filtered data_

_With legend_
![image](https://github.com/metabase/metabase/assets/22608765/7444df70-4cee-46b3-8fc3-c456df697b54)

_Without legend_
![image](https://github.com/metabase/metabase/assets/22608765/b13c04e6-a512-434f-87b9-a82c6327e21d)

- Note: if we actually want to show legends with breakout series with cardinality one, we need to update dashboard subscriptions as they do not currently show the legend when breakout has cardinality one

2023-08-24 13:42 UTC, iethree commented
> I think hiding it decreases the context and therefore value of the charts.
> 
> **1. Filters can be hidden**
> 
> **2. On a dashboard, filters are not explicit for individual questions**
> 
> 
> **3. In dashboard subscriptions, the filter is not explicit** _If the title were not explicit, this would be confusing because we would think we are looking at all data when in reality we are looking at filtered data_
> 
> 
> * Note: if we actually want to show legends with breakout series with cardinality one, we need to update dashboard subscriptions as they do not currently show the legend when breakout has cardinality one

@JesseSDevaney this is a really good explanation. I also originally thought, with @luizarakaki that we should hide legends on any single-series charts, but I think we actually should show breakout series with cardinality 1 because it makes explicit what metabase "magic" we're doing, and without it, we lose some of the meaning of the chart, because, unlike non-breakout-single-series charts, the axis label doesn't provide all the necessary context.

2023-08-24 13:44 UTC, luizarakaki commented
Yeah, I'm converging to this path. I created a thread on product to get feedback from others, but I think we should follow this route of showing the legend when there are breakouts regardless of cardinality
https://metaboat.slack.com/archives/C02H619CJ8K/p1692882715932179

2023-08-24 17:27 UTC, JesseSDevaney commented
So, how do we want to resolve this PR?

---
**Option 1 =** :+1:
When the breakout group contains empty values (`null`), just implement the showing `(empty)` label in the legend and visualization settings. Then after consensus, synchronize the legends display logic across charts in a separate PR.

**Steps to Complete:**
1. Revert the RowChart legend "cardinality" commit
2. Review and merge

---
**Option 2 =** :heart: 
Wait until consensus, then synchronize the legends display logic across charts in this PR.

**Steps to Complete:**
1. Wait until consensus and then synchronize the desired behavior of legends across all of the charts in this PR

2023-08-27 17:34 UTC, JesseSDevaney approved these changes
:rocket: LGTM

I just realized on my last check through that dashboard subscriptions still use `null` and some charts just completely freak out at `null` values, so I will create an issue to track those problems separately as they seem to be more involved than this small fix.

---
**Row Chart**

![image](https://github.com/metabase/metabase/assets/22608765/eb3f169f-2217-4df9-a284-ce972d573a08)

---
**Line Chart** (same data as row chart)

![image](https://github.com/metabase/metabase/assets/22608765/b1f12ec8-c76d-483d-a274-eaf0060ca953)

2023-08-28 14:05 UTC, merged