Updates to FE `external_op`
metabase/metabase pull request #33410
Opened 2023-08-22 17:22 UTC by kulyk

`external_op` doesn't communicate enough meaning to FE engs and we expect that having a `ColumnMetadata` in external op's `args` would lead to a lot of duplicate code unpacking it. This PR does three things:

* renames `external_op`'s TypeScript wrapper to `filterParts` (and `ExternalOp` type to `FilterParts`)
* extends `filterParts` TypeScript wrapper to unpack a `column` from external op's `args` (a column is always the first arg)
* updates typings in `filter` and `join`, so `FilterParts` can't be used to build new filters or join conditions. Let's keep things consistent on the FE and always pass around `FilterClause` or `JoinConditionClause` and keep the `FilterParts` only for visualizing filters

2023-08-22 17:46 UTC, iethree requested changes
nice. love this change. 

Found one typo, one organization suggestion, and one readability improvement.

2023-08-22 17:46 UTC, iethree commented on frontend/src/metabase-lib/common.ts
>  }
how would you feel about moving this puppy to `filter.ts` ? If i'm looking for a list of filter related functions, that's where i would look.

2023-08-22 17:46 UTC, iethree commented on frontend/src/metabase-lib/filter.ts
> +  return ML.filter(query, stageIndex, filter);
```suggestion
  return ML.filter(query, stageIndex, filterClause);
```

2023-08-22 19:44 UTC, iethree commented
see https://github.com/metabase/metabase/pull/33419 before merging this

2023-08-23 11:51 UTC, kulyk commented
Thanks @iethree. I think we should better close this PR in favor of #33419 and remove `externalOp` from the FE entirely

2023-08-31 10:18 UTC, closed without merging