Add find-visible-column-for-legacy-ref
metabase/metabase pull request #33447
Opened 2023-08-23 19:57 UTC by metamben

Part of #33022.

2023-08-23 20:02 UTC, bshepherdson requested changes
This feels over-specialized to me. I think this should be a TS helper that calls `Lib.visible_columns` and `Lib.find_column_indexes_from_legacy_refs`.

I see on reflection that `Lib.visible_columns` doesn't exist in master, only the [escalation branch](https://github.com/metabase/metabase/blob/mblib-column-settings-round-trip/src/metabase/lib/js.cljs#L437).

That would be easy to split out into a separate PR along with the TS helper I propose - should I do that now?

2023-08-23 20:23 UTC, metamben commented
> That would be easy to split out into a separate PR along with the TS helper I propose - should I do that now?

Yes, please.

2023-08-24 04:14 UTC, bshepherdson approved these changes
Extracting enough of #32698 to support this is taking longer than I'd hoped.

If this is blocking other work, go ahead and submit it. I'll keep working on breaking up that mega-PR in any case; it's way too big and splitting out some pieces is a good idea anyway.

2023-08-24 17:49 UTC, merged

2023-08-24 20:16 UTC, iethree commented on frontend/src/metabase-lib/fields.ts
> +): ColumnMetadata | null {
I think we need a `ColumnWithOperators` from this, or maybe even more helpfully a way to turn a `ColumnMetadata` column into a `ColumnWithOperators` ?