Implement #33646
metabase/metabase pull request #33865
Opened 2023-09-12 10:36 UTC by camsaul

Start setting `unreturnedConnectionTimeout` for data warehouse connections. This uses the same timeout as the query timeout by default (20 minutes), but is configurable by setting `JDBC_DATA_WAREHOUSE_UNRETURNED_CONNECTION_TIMEOUT_SECONDS`

2023-09-12 12:41 UTC, bshepherdson approved these changes

2023-09-12 14:42 UTC, bshepherdson requested changes
Luis tested this and I don't think this can actually be overridden? It seems like this is always pinned at the same as the query timeout. That's a fine default, but it seems it can't be `set!` nor overridden with an env var or config file.

Do we support late-bound `:default` values with `delay` or a function?

2023-09-13 07:57 UTC, paoliniluis submitted a review, later dismissed
I tested it with both the env var as it is and prepending MB_... and both didn't work, the connections will still be kept in the queue

2023-09-27 13:06 UTC, bshepherdson approved these changes

2023-10-04 19:12 UTC, merged

2023-10-08 16:23 UTC, paoliniluis commented
LOVE IT!!! it works!!!