show columns added after the dashcard as been created in the viz settings
metabase/metabase pull request #33886
Opened 2023-09-13 16:04 UTC by npretto

closes https://github.com/metabase/metabase/issues/25592

### Description

TODO

### How to verify

TODO
### Demo

TODO

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

2023-09-18 08:31 UTC, ranquild requested changes
Several things:
1. Comparing columns via `name` is incorrect. There are functions that handle it https://github.com/metabase/metabase/blob/ed6c220b670fdea3dfe702a14d09c13b2b927d0e/frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/utils.ts#L87
2. I'd prefer fixing this case in the settings abstraction here https://github.com/metabase/metabase/blob/ed6c220b670fdea3dfe702a14d09c13b2b927d0e/frontend/src/metabase/visualizations/lib/settings/column.js#L503 to make all consumers operate on the same setting value. There should be a way to pre-process the setting value, most likely by adding `getValue` method

2023-09-22 10:01 UTC, npretto commented on frontend/src/metabase/visualizations/lib/settings/column.unit.spec.js
> +  it("table should should generate default columns when table.columns entries do not match data.cols (metabase#28304)", () => {
I trasformed `e2e/test/scenarios/visualizations/reproductions/28304-table-columns-unknown.cy.spec.js` into a unit test to make it run faster

2023-09-22 10:07 UTC, npretto commented on frontend/src/metabase/visualizations/lib/settings/column.js
> +    const enabledColumns = columns.filter(column => column.enabled);
here the main change is that I trasnformed
```
const columns = card.visualization_settings["table.columns"];
```
into
```
const columns = settings["table.columns"] || [];
```
As far as I understand this shouldn't change anything, but worth noting the change

2023-09-22 10:08 UTC, npretto commented on frontend/src/metabase/visualizations/lib/settings/column.js
> +  const isValid = ([{ card, data }], settings) => {
I extracted isValid/getDefault/getValue as const outside of the big returned object because I needed to call getDefault/isValid from getValue

2023-09-25 07:37 UTC, ranquild approved these changes
@npretto great work!

2023-09-25 08:08 UTC, merged