Drop unused form widgets depended on entities to avoid circular deps problem
metabase/metabase pull request #33978
Opened 2023-09-20 07:33 UTC by uladzimirdev

> [!IMPORTANT]
> If you are merging into master, please add either a `backport` or a `no-backport` label to this PR. You will not be able to merge until you do this step. Refer to the section [Do I need to backport this PR?](https://www.notion.so/metabase/Metabase-Branching-Strategy-6eb577d5f61142aa960a626d6bbdfeb3?pvs=4#89f80d6f17714a0198aeb66c0efd1b71) in the Metabase Branching Strategy document for more details.

> **Warning**
>
> If that is your first contribution to Metabase, please sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) (unless it's a tiny documentation change). Also, if you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

Closes https://github.com/metabase/metabase/issues/[issue_number]

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2023-09-21 09:06 UTC, kamilmielnik reviewed
> double check widgets were not used

But they are, aren't they? That's why we keep them?

2023-09-21 09:06 UTC, kamilmielnik commented on frontend/src/metabase/components/form/FormWidget.jsx
> +    <Suspense fallback={<LoadingAndErrorWrapper loading />}>
Does this cause a content layout shift (a flicker)?
A recording of how it behaves now would be nice, or at least steps to verify that these widgets work.

2023-09-21 09:26 UTC, uladzimirdev commented
> > double check widgets were not used
> 
> But they are, aren't they? That's why we keep them?

right, I forgot to update steps to verify, I'll add demo and clear steps, thanks for heads up

2023-09-22 13:50 UTC, kamilmielnik approved these changes
Very nice :+1:

2023-09-22 13:50 UTC, kamilmielnik commented on frontend/src/metabase/entities/containers/EntityForm.jsx
> +const Form = lazy(() => import("metabase/containers/FormikForm"));
Nit: it's easier to find usages when the reference name matches the file name

```suggestion
const FormikForm = lazy(() => import("metabase/containers/FormikForm"));
```

2023-09-25 07:31 UTC, ranquild requested changes
We don't do code splitting atm with Suspense and I'm not sure if that's the best place to start doing it. Could you add a `require` call to import the component inside the function? It should solve the circular dep issue

2023-09-25 09:47 UTC, uladzimirdev commented
@ranquild alright, I changed it to `require`

2023-09-25 10:17 UTC, ranquild approved these changes
@uladzimirdev could you add a comment about a circular dep issue?

2023-09-25 14:16 UTC, merged