Enable ClojureScript REPL and hot reloading of CLJS code
metabase/metabase pull request #34007
Opened 2023-09-20 22:55 UTC by bshepherdson

Requiring the shadow-cljs browser REPL components in
metabase.util.devtools is all that was needed to get the REPL working.

But that exposed a problem - the REPL kept disconnecting when edits were
made to CLJS files. The webpack HotModuleReload plugin does not know
how to handle these changes, so it falls back to the safe thing: full
reload.

Therefore this commit adds HMR integration to metabase.lib.js so that
HMR will know that it's safe to simply reload the CLJS code.

Work remaining:
- The attempt to rerender the entire React component tree doesn't seem
  to be working. I'd be glad to know if that's the wrong component, or
  if it somehow only reaches the outer containers and not into the heart
  of the UI.
- Really the HMR integration should be a build-time hook in shadow-cljs
  that does similar integration to each of the `:entries` that are
  exposed to JS. Currently, editing CLJS code outside `src/metabase/lib`
  won't hot reload.

2023-09-21 21:21 UTC, metamben reviewed
It's an interesting read, someone with more knowledge should review.

2023-09-21 21:21 UTC, metamben commented on src/metabase/lib/js.cljs
> +;; state held anywhere here, just library, code, there's no further action needed.
```suggestion
;; state held anywhere here, just library code, there's no further action needed.
```

2023-09-21 21:21 UTC, metamben commented on src/metabase/lib/js.cljs
> +;; - Even if it did work, I could find a way to tell webpack's HMR to allow a hot reload (ie. don't refresh the page)
```suggestion
;; - Even if it did work, I could find no way to tell webpack's HMR to allow a hot reload (ie. don't refresh the page)
```

2023-09-22 07:42 UTC, shaunlebron commented
Awesome, great stuff!

For the work remaining:

1. I’m not sure what is being missed in the whole App re-render, but maybe we can find some way to call the top-level init, which will re-render App with the updated reducers and routes: https://github.com/metabase/metabase/blob/76b54609e5f8f51857e354f2dda58f70ab564e47/frontend/src/metabase/app.js#L65-L89

2. I think we can do a `:shadow.build/stage :compile-prepare` hook that:
   * only runs if `:shadow.build/mode` is `:dev`
   * gets the sources in `(:sources build-state)` associated with `(:entries (:config build-state))`
   * return `(update-in build-state [:sources entry :source] add-hmr)` for each `entry`, where `add-hmr` is a function which appends the hrm cljs code to the source string

2023-09-22 16:21 UTC, shaunlebron requested changes
Awesome, great stuff!

For the work remaining:

1. I’m not sure what is being missed in the whole App re-render, but maybe we can find some way to call the top-level init, which will re-render App with the updated reducers and routes: https://github.com/metabase/metabase/blob/76b54609e5f8f51857e354f2dda58f70ab564e47/frontend/src/metabase/app.js#L65-L89

2. I think we can do a `:shadow.build/stage :compile-prepare` hook that:
   * only runs if `:shadow.build/mode` is `:dev`
   * gets the sources in `(:sources build-state)` associated with `(:entries (:config build-state))`
   * return `(update-in build-state [:sources entry :source] add-hmr)` for each `entry`, where `add-hmr` is a function which appends the hrm cljs code to the source string

2023-09-26 20:52 UTC, metamben approved these changes
Nice!

2023-10-02 15:57 UTC, shaunlebron approved these changes
Really nice job on this.  I tried it out in Conjure, and it worked well and verified that hot reloading still works on JS files. 🎉

2023-10-02 21:52 UTC, merged