Set empty parameter names and slugs to "unnamed" as they come out of the database
metabase/metabase pull request #34311
Opened 2023-10-03 12:04 UTC by calherries

Fixes 24500

2023-10-03 13:56 UTC, calherries commented on e2e/test/scenarios/dashboard-filters/reproductions/24500-gracefully-deal-with-corrupted-filter.cy.spec.js
> +    cy.findByTestId("edit-dashboard-parameters-widget-container")
`filterWidget` doesn't get the filter widget in edit mode. Maybe it worked before, but it doesn't now.

2023-10-03 13:57 UTC, calherries commented on e2e/test/scenarios/dashboard-filters/reproductions/24500-gracefully-deal-with-corrupted-filter.cy.spec.js
> +describe("issues 15279 and 24500", () => {
This is the repro that was created for https://github.com/metabase/metabase/issues/24500

2023-10-04 08:25 UTC, qnkhuat requested changes
I don't think this is gonna fix #24500.

One problem from the issue is that if you have 2 filters without a name, then setting value for one parameter will populate the value to both filters after refresh. It's probably because FE gets the value from URL `?unamed={{some_value}}`.

I think we need to make sure that the name and slug we assoc in the after-select is unique to fix that.

2023-10-04 09:38 UTC, ranquild approved these changes
FE changes ok

2023-10-04 10:14 UTC, calherries commented
@qnkhuat 

> I don't think this is gonna fix https://github.com/metabase/metabase/issues/24500.

Tell me why. It fixes the repro.

> One problem from the issue is that if you have 2 filters without a name, then setting value for one parameter will populate the value to both filters after refresh. It's probably because FE gets the value from URL ?unamed={{some_value}}.

That's a different issue. I'm solving it with [this](https://github.com/metabase/metabase/issues/27653#issuecomment-1746565164) approach.

2023-10-05 04:12 UTC, qnkhuat approved these changes
I guess the expected behavior of #24500 is unclear, but okay I think it's an improvement to not error out from BE.

and I'm okay with solving the issue of unique parameter names separately.

2023-10-05 07:15 UTC, merged