Migrate storybook to a subfolder
metabase/metabase pull request #34571
Opened 2023-10-11 15:35 UTC by uladzimirdev

2023-10-12 12:52 UTC, uladzimirdev commented on frontend/src/metabase/.eslintrc
> +        "import/no-unresolved": [2, {"ignore": ["@storybook"]}]
allow unresolved imports to `@storybook/something` in stories. Stories are located near components, but storybook is a part of different package

2023-10-12 12:53 UTC, uladzimirdev commented on frontend/src/metabase/core/components/FormFileInput/FormFileInput.stories.tsx
> -// eslint-disable-next-line import/no-default-export -- deprecated usage
This story had a typo in the name

2023-10-12 12:54 UTC, uladzimirdev commented on jest.config.json
> +    "<rootDir>/node_modules/(?!(rehype-external-links|unist-util-visit|unist-util-visit-parents|space-separated-tokens|is-absolute-url)/)"
packages were upgraded after removal of storybook from package.json, they all are in ESM, so we have to transpile them

2023-10-12 12:54 UTC, uladzimirdev commented on package.json
> -    "build-storybook": "yarn build:cljs && NODE_OPTIONS=--max-old-space-size=8196 build-storybook",
scripts are defined in the `storybook` folder package.json, so I we explicitly say it should be started there

2023-10-12 12:55 UTC, uladzimirdev commented on storybook/.storybook/main.js
> +        ...webpackConfig.resolve.modules,
adding `storybook/node_modules` to the list of modules where webpack will look for modules

2023-10-12 12:55 UTC, uladzimirdev commented on tsconfig.json
> +      "@storybook/*": ["./storybook/node_modules/@storybook/*"]
this is needed for typecheck

2023-10-12 14:06 UTC, uladzimirdev commented on storybook/package.json
> +    "build": "NODE_OPTIONS=--max-old-space-size=8196 build-storybook -o ../storybook-static"
never change `-o` to something like `../`, it's `rm -rf`

2023-10-12 14:07 UTC, uladzimirdev commented on storybook/.storybook/main.js
> +  babel: () => ({
added our babel config instead of one from storybook

2023-10-13 12:02 UTC, kamilmielnik reviewed
LGTM :+1: Left some comments inline.

I'll let others approve as I'm not sure about the workflows changes (do we need them?).

2023-10-13 13:30 UTC, uladzimirdev commented on storybook/package.json
> +    "build": "NODE_OPTIONS=--max-old-space-size=8196 build-storybook -o ../storybook-static"
I think this way chromatic expects storybook to be built, but I'm not 100% sure, I tried to keep the old behaviour

2023-10-13 13:59 UTC, nemanjaglumac commented
Thank you for doing this.
I'll remove myself from the reviewers because I don't know enough about the Storybook ecosystem.

2023-10-16 09:09 UTC, ranquild requested changes
This approach considerably increases complexity of our project setup. I believe we should upgrade our mdx stories instead.

2024-01-03 08:41 UTC, closed without merging