Fix entities fetch caching
metabase/metabase pull request #34661
Opened 2023-10-13 14:57 UTC by deniskaber

Relates to https://github.com/metabase/metabase/issues/31905

### Description

This is additional fix for https://github.com/metabase/metabase/pull/33898 
More context - https://metaboat.slack.com/archives/C057T1QTB3L/p1697183111294489

There is a race condition: 
Let's say we have two fetch requests to load entities list (e.g. databases), 
The second request waits for the first one to be loaded, 
and then for the second request we waited extra 10ms to make sure state gets recalculated.

https://github.com/metabase/metabase/blob/ed00657b6807960b31c386175426bcfad5fb456f/frontend/src/metabase/lib/redux/utils.js#L327-L333

But as soon as first request get loaded, it updated request state to be "loaded"

https://github.com/metabase/metabase/blob/ed00657b6807960b31c386175426bcfad5fb456f/frontend/src/metabase/lib/redux/utils.js#L246-L253

For this 10ms period we are in the incorrect state due to different request states.

### How to verify

1. Create a new question or model, save it.
2. Refresh the page.
3. You should not see 2 same api requests to load your question/model.
4. You should see a collection where your question/model is saved to as selected in the left menu.

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2023-10-25 08:07 UTC, kamilmielnik requested changes
New test does not pass

2023-10-25 08:07 UTC, kamilmielnik commented on frontend/src/metabase/components/LoadingAndErrorWrapper/LoadingAndErrorWrapper.jsx
> +        style={this.props.style}
While we're at it, we can use destructuring for `className` and `style` like for all the other props.

2023-10-25 08:07 UTC, kamilmielnik commented on frontend/src/metabase/common/hooks/use-entity-list-query/use-entity-list-query.unit.spec.tsx
> +    expect(screen.queryByTestId("loading-spinner")).not.toBeInTheDocument();
Is this needed? Because we already `await delay(100)` above, which should be enough for request(s) to start/finish.

2023-10-26 06:25 UTC, kamilmielnik approved these changes
Looks good, works well and fixes [the race condition I encountered in tests](https://metaboat.slack.com/archives/C057T1QTB3L/p1697183111294489) :+1:

2023-10-26 10:25 UTC, ranquild approved these changes

2023-10-26 20:14 UTC, merged