[Auditv2/default save location
metabase/metabase pull request #35172
Opened 2023-10-27 17:25 UTC by iethree

Closes https://github.com/metabase/metabase/issues/34086

### Description

Defaults to saving copied instance analytics questions, models, and dashboards to the "Custom Reports" sub-collection.

![Screen Shot 2023-10-27 at 11 23 52 AM](https://github.com/metabase/metabase/assets/30528226/31c24a72-8689-4e4b-af36-25ff302167c9)

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2023-10-30 22:13 UTC, iethree commented on e2e/test/scenarios/collections/instance-analytics.cy.spec.js
> +    it.skip("should not allow moving or archiving custom reports collection", () => {
this is a test for https://github.com/metabase/metabase/pull/35230, will unskip it when that merges

2023-11-01 17:14 UTC, npfitz requested changes
Found a small issue where we show an error if we save a question, then try to duplicate it immediately.
![chrome_6O9ddjgqOQ](https://github.com/metabase/metabase/assets/1328979/10f86420-69aa-48b5-8e0d-5bd1d09660ef)

2023-11-01 22:26 UTC, iethree commented
> Found a small issue where we show an error if we save a question, then try to duplicate it immediately. This doesn't happen if you save the question, go back home, then re-open the question, so I'm not sure what's going on here.

Collections loading state issue. Good catch! 👍

2023-11-06 16:56 UTC, npfitz approved these changes
Looks Good 🔥

2023-11-08 00:05 UTC, merged