Only create one revision per request to PUT /api/dashboard/:id
metabase/metabase pull request #35413
Opened 2023-11-06 11:43 UTC by calherries

Epic: https://github.com/metabase/metabase/issues/35209

This is the 3rd PR in a series of 3 PRs to change the way dashboards are saved to use `PUT /api/dashboard/:id`.

2023-11-06 16:47 UTC, markbastian approved these changes
LGTM

2023-11-07 02:15 UTC, qnkhuat requested changes, later dismissed
I'm fine with cleaning this up, but could check with the auditv2 teams on whether or not removing these events is ok?

looks like we'll eventually remove `activity_feed` but we added a new `audit_log` table that has similar purpose.

I found this code that use those events https://github.com/metabase/metabase/pull/35434/files#diff-961e100cdcd88e4f74341ab90f9776a3a11a565dc8bb29cea31110d8cd5bb74b

cc @noahmoss

2023-11-07 05:25 UTC, calherries commented
Good idea. Having a look their [audit_log](https://github.com/metabase/metabase/pull/35434/files#diff-961e100cdcd88e4f74341ab90f9776a3a11a565dc8bb29cea31110d8cd5bb74bR59-R62) code, it seems audit v2 does not use any of the removed events.

2023-11-07 05:37 UTC, calherries commented
@qnkhuat I posed the question [here](https://metaboat.slack.com/archives/C064EB1UE5P/p1699335250046449)

2023-11-07 16:13 UTC, merged