Adding Stacked Checkbox component
metabase/metabase pull request #35448
Opened 2023-11-07 13:29 UTC by npfitz

### Description
Adds a Stacked Checkbox component, which is just a specifically styled Mantine checkbox. Styled using static CSS selectors to hopefully make the migration to v7 easier in the future. This new checkbox is also set to be used in add / remove columns.

### How to verify
New Checkbox can be viewed in the Add / Remove columns panel (create a structured question and view viz settings) or found in storybook.

### Demo
![chrome_ummuyQYUD4](https://github.com/metabase/metabase/assets/1328979/2bea3f04-f389-4540-9da9-fd926aa79298)

2023-11-07 13:30 UTC, npfitz commented on .storybook/preview.tsx
> +  renderStory => (
The static class prefix by default is `mantine`. However, when using an emotion cache, it changes to the key of the emotion cache. By default our storybook previews didn't have a cache set, so the prefixes were different between storybook and the metabase app ('css' and 'emotion') respectively. This change brings those back in line.

2023-11-07 13:40 UTC, ranquild requested changes
We could introduce another Checkbox "variant" and put all styles properly in `Checkbox`. This would allow us to not override anything using static CSS selectors.

2023-11-07 14:39 UTC, npfitz commented
Updated. Awesome Suggestion @ranquild

2023-11-07 14:47 UTC, ranquild commented on frontend/src/metabase/ui/components/inputs/Checkbox/Checkbox.styled.tsx
> +            border: `2px solid ${color("brand")}`,
`theme.colors.brand[1]`

2023-11-07 14:47 UTC, ranquild commented on frontend/src/metabase/ui/components/inputs/Checkbox/Checkbox.styled.tsx
> +            left: "4px",
theme.spacing.xs

2023-11-07 17:49 UTC, mazameli commented
Nice! This is looking good to me so far. 

Detail question: why in storybook is the `size` param a string input rather than a list of discrete options like `sm`, `md`, `lg`?

2023-11-07 17:52 UTC, npfitz commented
> why in storybook is the size param a string input rather than a list of discrete options like sm, md, lg?
It should probably be a radio list, but that param will also accept an int as a number of pixels. Not sure how to make Storybook understand that, but I'll at least make the change you're suggesting here

2023-11-07 18:52 UTC, ranquild reviewed
Code LGTM, there is one lint error

2023-11-07 18:52 UTC, ranquild approved these changes

2023-11-07 18:53 UTC, ranquild commented
@npfitz we use a radio for other components for `size`, we could do it here as well. Howerver I don't think that the component supports it right now

2023-11-07 20:01 UTC, npfitz commented
Updated to use radio component for size 👍

2023-11-07 21:10 UTC, mazameli commented
This may've been a preexisting issue with the `checkbox` component before this PR, and if so, I think we could solve it separately if we have to — but, when you add a description, the box is getting aligned incorrectly relative to the label. Here it is in Storybook, with the label on left and right:

<img width="204" alt="image" src="https://github.com/metabase/metabase/assets/2223916/0f27b331-a7af-47bf-ab34-91fd75aa99e1">

<img width="201" alt="image" src="https://github.com/metabase/metabase/assets/2223916/3a8f2e5b-0fdb-4d8b-8d4f-b8cf9356aa82">


And here it is in Mantine, with the label on both left and right. This is the desired alignment IMO:

<img width="230" alt="image" src="https://github.com/metabase/metabase/assets/2223916/46c0684a-8e94-442e-bc52-ec842dd16189">

<img width="226" alt="image" src="https://github.com/metabase/metabase/assets/2223916/2c57f18a-87d5-4012-98e7-5f3b3b1471de">

2023-11-07 21:10 UTC, mazameli commented
Beyond that, this PR looks good to me.

2023-11-08 00:33 UTC, npfitz commented
Ohh, yeah. That was something I probably did in this PR. I'll see if I can get that fixed.

2023-11-08 21:30 UTC, kdoh approved these changes

2023-11-09 13:39 UTC, merged