[MLv2] Include the `:column` in `display-info` on column filter drills
metabase/metabase pull request #35878
Opened 2023-11-16 18:19 UTC by bshepherdson

2023-11-16 18:20 UTC, bshepherdson commented
Current dependencies on/for this PR:
* master
  * **PR #35878** <a href="https://app.graphite.dev/github/pr/metabase/metabase/35878?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/metabase/metabase/35878?utm_source=stack-comment).

2023-11-16 18:23 UTC, ranquild approved these changes

2023-11-16 18:51 UTC, camsaul approved these changes
No context as to what this is for but I trust your judgement. Next time a PR description would be nice tho 💪

2023-11-16 20:07 UTC, bshepherdson commented
@camsaul good call. The code ended up getting completely replaced, so PTAL. Now the commit message and PR title are clearer what is going on, and I've added some context to the description.

2023-11-16 20:08 UTC, ranquild approved these changes

2023-11-20 11:50 UTC, ranquild requested changes
aggregation columns seem to be handled correctly, but I also need this column to be `filterable`, i.e. coming from `filterableColumns`. Currently no filter functions work on the `column` instance out of the box.

2023-11-20 21:29 UTC, bshepherdson commented
> aggregation columns seem to be handled correctly, but I also need this column to be `filterable`, i.e. coming from `filterableColumns`. Currently no filter functions work on the `column` instance out of the box.
> 
> 

See the comment in the code; the returned column is coming from `filterable-columns` and there's nothing extra in the `lib.js/filterable-columns` wrapper either - the `column` coming back from these should be filter-ready.

2023-11-20 21:29 UTC, bshepherdson commented on src/metabase/lib/drill_thru/column_filter.cljc
> +            (assoc base :column (->> (lib.filter/filterable-columns (:query base) (:stage-number base))
@ranquild Here's the code where the returned column is coming from `filterable-columns`.

2023-11-20 21:48 UTC, metamben approved these changes

2023-11-20 21:48 UTC, metamben commented on src/metabase/lib/drill_thru/column_filter.cljc
> +                ;; next-stage is nil if there's no stage after the current one, so add one and bump the stage-number.
```suggestion
                ;; next-stage is nil if there's no stage after the current one, so add one and reference the last stage.
```

2023-11-21 14:37 UTC, ranquild commented
@bshepherdson it still doesn't work 
![Uploading Screenshot 2023-11-21 at 16.36.58.png…]()

2023-11-21 18:04 UTC, ranquild requested changes
Still doesn't work, check last comment

2023-11-22 15:34 UTC, ranquild approved these changes

2023-11-22 15:59 UTC, merged