Fix modal copy when changing table permissions
metabase/metabase pull request #36243
Opened 2023-11-30 17:51 UTC by shaunlebron

Fixes #34911 

## TODO 

I have to look around more to understand the following:
1. are we sure this modal is only triggered for table entity types? or whole database types too?  (found `isTableEntityId` to determine if it’s a table, but not sure what else it could be)
2. the second part of the user’s expected behavior is to change “limited” to either “sandboxed” or “unrestricted”.  `getSchemasPermission` has returned only “controlled” or “all” in my examples, not yet sure how to surmise “sandboxed” from it instead of “no self-service”.

2023-12-01 16:40 UTC, iethree requested changes
I think we need a little more logic to make this correct, as far as I can tell, this modal can pop up for both schema and tables.

![schemaChange](https://github.com/metabase/metabase/assets/30528226/f892242c-c971-41d5-92b9-f828e3d2ec7a)

I wasn't able to trigger it for databases, but I'm not 100% sure whether or not we also need to handle that.

Probably out of scope of this change, but I noted that we also get this warning when we _loosen_ permissions on a table, which is a bit of a head-scratcher.
![increase access](https://github.com/metabase/metabase/assets/30528226/a1ac9ca0-3acd-43b5-a2f1-0b8b2133124e)

2023-12-01 20:22 UTC, shaunlebron commented
I was able to verify that both `TableEntityId`s and `SchemaEntityId`s are passed to this function, so I rewrote it to name it correctly in the copy: e961210

The head-scratcher will be a bigger fix.  Notes here: https://github.com/metabase/metabase/issues/34911#issuecomment-1836421574

2023-12-01 20:33 UTC, alxnddr reviewed
The idea behind this warning is to give heads up to user that the **database** level permission implicitly will change when they modify table or schema permission. The wording is quite wrong, I would replace "Limited" with "Granular":
`Change access to this database to granular?`

As Ryan pointed out, on this branch if you have "No self-service" level on a DB and you change a single table permission to "Unrestricted" the modal will say "Change access to this table to limited?" which is not correct

2023-12-01 20:35 UTC, alxnddr commented
> I wasn't able to trigger it for databases, but I'm not 100% sure whether or not we also need to handle that.

Yep, that seems intentional. When users modifying a DB-level permission it is clear what it will be. But if they change schema/table level permissions, they may not understand the DB-level permission implicitly changes to "granular"

2023-12-06 20:10 UTC, alxnddr approved these changes

2023-12-06 20:39 UTC, iethree requested changes
Let's use the updated copy that @jeff-bruemmer proposed to make this a lot more explanatory:

https://metaboat.slack.com/archives/C064EB1UE5P/p1701885966932019?thread_ts=1701883832.195089&cid=C064EB1UE5P

> Just letting you know that changing the permission setting on this (table|schema) will also update the database permission setting to “Granular” to reflect that some of the database’s (schemas|tables) have different permission settings.

2023-12-20 22:19 UTC, iethree approved these changes
✨

2023-12-20 22:19 UTC, iethree commented on frontend/src/metabase/admin/permissions/selectors/confirmations.ts
> +      : [t`entity`, t`entities`];
this is perfectly fine, but we also have a `pluralize` function in metabase/lib/formatting/strings.js`

2023-12-20 23:23 UTC, merged