Update appearance.md
metabase/metabase pull request #36538
Opened 2023-12-07 17:47 UTC by Tony-metabase

Adding information about how colors are selected by Metabase because there is the confusion that the order in which you select colors is the order you get on the chart

> [!IMPORTANT]
> If you are merging into master, please add either a `backport` or a `no-backport` label to this PR. You will not be able to merge until you do this step. Refer to the section [Do I need to backport this PR?](https://www.notion.so/metabase/Metabase-Branching-Strategy-6eb577d5f61142aa960a626d6bbdfeb3?pvs=4#89f80d6f17714a0198aeb66c0efd1b71) in the Metabase Branching Strategy document for more details.

> **Warning**
>
> If that is your first contribution to Metabase, please sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) (unless it's a tiny documentation change). Also, if you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

Closes https://github.com/metabase/metabase/issues/[issue_number]

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2023-12-07 18:33 UTC, paoliniluis commented on docs/configuring-metabase/appearance.md
> +For chart colors, there’s this function [getColorsForValues](https://github.com/metabase/metabase/blob/b4d8ae8a8b1c77e78984eee2d4bea1f79bdae039/frontend/src/metabase/lib/colors/charts.ts#L5) , where
I would remove all references to code, and try to explain this in very simple words

2023-12-07 18:34 UTC, paoliniluis commented on docs/configuring-metabase/appearance.md
> +Also the reason why the color order is not respected is because you define the colors and Metabase generates a lighter and darker variation, but in a chart with series Metabase checks the colors and
same comment as above here

2023-12-07 18:34 UTC, paoliniluis requested changes
we should remove all references to code, and try to explain this in simple terms

2023-12-11 12:40 UTC, Tony-metabase commented
Removed code reference

2023-12-20 17:09 UTC, jeff-bruemmer approved these changes

2023-12-20 17:09 UTC, jeff-bruemmer commented on docs/configuring-metabase/appearance.md
> +Metabase will use the color palette you have selected but not in the order it was selected. For example in a chart with series Metabase checks the colors and sees if colors are similar to each other
```suggestion
You can choose up to 24 hex values. If you choose fewer than 24 colors, Metabase will auto-generate colors to fill in the rest of the values. And don't bother ordering the colors here, as their order doesn't apply to the order of colors for series on charts. When building a chart, Metabase will select colors to make each series easy to distinguish.
```

2023-12-21 14:12 UTC, jeff-bruemmer approved these changes

2024-01-26 00:37 UTC, paoliniluis approved these changes

2024-08-26 19:50 UTC, camsaul approved these changes

2024-08-26 19:50 UTC, merged