WIP: Auth with API Key
metabase/metabase pull request #36593
Opened 2023-12-08 19:25 UTC by johnswanson

In terms of the actual application code, things are pretty straightforward: if an API key is passed, find the associated user, check the hash against the passed API key, and attach the user if everything went well.

The hackiest bit of this is in the test code. Our HTTP client function takes a lot of positional arguments, many of which are optional, so adding in a header to an arbitrary call is not easy. Luckily, it's easy to parse the args, change what we want, and then unparse them before actually calling the client - but I'm not sure how I feel about this. Part of me thinks it might be better to have a new HTTP client function that takes a map instead of all these positional args...

I do want to rename the existing functions related to API keys, e.g. `mw.auth/wrap-api-key`. We should be careful about overloading the term "API Key", both internally and externally.

The External "API Key" is a static key defined by an env var that allows you to require a particular header *in addition to regular authentication* (on some endpoints).

It's probably too painful to change the actual setting name, but we can change what we call it in the code.

I also need to add more/better tests.

2023-12-18 23:01 UTC, noahmoss requested changes

2023-12-18 23:01 UTC, noahmoss commented on test/metabase/api/api_key_test.clj
> +(deftest api-keys-work-e2e
Could you add a test that all of the session-level dynamic vars (like `api/is-superuser?`, etc) are bound correctly for API users?

2023-12-18 23:01 UTC, noahmoss commented on src/metabase/server/middleware/session.clj
> +  ;; a useless hash, *then* return `false`.
awesome

2023-12-18 23:01 UTC, noahmoss commented on test/metabase/server/middleware/session_test.clj
> +                               :unhashed_key "mb_foobar"})
Can you use `t2.with-temp` here instead?

2023-12-19 15:15 UTC, johnswanson commented on src/metabase/server/middleware/session.clj
> +                 [:user.locale :user-locale]]
Good point - this actually raises a question: can API key users become group managers, and if so, how? My thinking was that API key users will be excluded from the users you get back from normal user API endpoints, so you wouldn't be able to go through the normal flow for making them a group manager. But, that's maybe orthogonal to the question of "if a API key user _is_ a group manager, do we respect that?" - which I think the answer is yes, we should. I'll change this.

(And then maybe at some point down the road we'll add the UI/API necessary to actually make an API key into a group manager.)

2023-12-19 19:31 UTC, noahmoss approved these changes

2023-12-19 19:54 UTC, johnswanson commented on src/metabase/server/middleware/session.clj
> +  (when api-key
Good call, done!

2023-12-19 19:54 UTC, johnswanson commented on src/metabase/server/middleware/session.clj
> +   (current-user-info-for-api-key x-api-key)
Good idea, done - I used an `or` so we'll merge with the first non-nil user-info, if any (with the session taking precedence over the API key).

2023-12-19 20:40 UTC, merged