Clean up sticky filters container code
metabase/metabase pull request #36814
Opened 2023-12-14 18:27 UTC by kulyk

Fixes two things about the dashboard filters panel:

* adds a vertical space between the dashboard grid and the dashboard filters bottom border
* makes the dashboard filters bottom border only show up on scroll

I also cleaned up some code in the area, I think reviewing changes by commit would be more convenient:

* [clean up sticky filters container code](https://github.com/metabase/metabase/commit/5e2c1340a0af38750babbdcd32eefe4bfb9903ab) — we used to have way more code to manage filter panel's "stickiness" before it was mostly migrated to CSS. The PR removes most of the code in favor of a [single function](https://github.com/metabase/metabase/blob/5e2c1340a0af38750babbdcd32eefe4bfb9903ab/frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx#L398)
* [Hide parameters container border until scrolling](https://github.com/metabase/metabase/commit/d5f0e03c3a4dfe8e227e1961a596d9157a2cb060) — I suppose we lost this bit of logic when migrating it to CSS
* [Add margin between grid and parameter list bottom border](https://github.com/metabase/metabase/commit/9d06c14dbe59e75b303b70ff15c088b12563ddab) — adds the margin ✨ 

### Demo

| Before | After  |
|--------|-------|
| <img width="636" alt="before" src="https://github.com/metabase/metabase/assets/17258145/e996c4ff-790a-4cc5-b3e1-8850054d9c3e">            | <img width="615" alt="after" src="https://github.com/metabase/metabase/assets/17258145/09ea6117-ae0d-487c-872b-d1d0a23ad4a4">          |

2023-12-14 21:56 UTC, kdoh requested changes
Looking good. Couple things I noticed.

Things are also very tight when there aren't filters. I think if we're fixing the filter panel we also need to fix this same problem here when you don't have filters.
![Screenshot 2023-12-14 at 4 54 02 PM](https://github.com/metabase/metabase/assets/5248953/6e57c68c-3d2a-47b2-a09d-a96917c219ed)

It'd be nice to even out the top and bottom padding here.
![Screenshot 2023-12-14 at 4 55 58 PM](https://github.com/metabase/metabase/assets/5248953/70f07269-7cb9-4766-979b-7b1be3ccc011)

2023-12-15 12:41 UTC, kulyk commented
Appreciate a thorough review, @kdoh 🙏 Please take another look:

<details>
<summary>With filters</summary>

<img width="684" alt="filters" src="https://github.com/metabase/metabase/assets/17258145/7ea2bde3-968a-45c8-9382-d5bbde8f4246">

</details>

<details>
<summary>With tabs</summary>

<img width="786" alt="tabs" src="https://github.com/metabase/metabase/assets/17258145/b9ce9cbd-2b12-4ec8-a65f-412aa60b23db">

</details>

<details>
<summary>No tabs or filters</summary>

<img width="785" alt="none" src="https://github.com/metabase/metabase/assets/17258145/1d27143c-853a-406a-b3df-89cedbd1ba7e">

</details>

2023-12-15 13:32 UTC, kdoh approved these changes
LGTM outcome wise. Didn't do a thorough code review though.

2023-12-18 15:31 UTC, ranquild approved these changes

2023-12-18 15:52 UTC, merged