[#35961 M3] Add Interactive Embedding CTA to Embed Modal
metabase/metabase pull request #36890
Opened 2023-12-18 09:17 UTC by oisincoveney

Epic #35961 

### Description

Adds the interactive embedding CTA to the new embed modal

### How to verify

As a Pro/EE user: clicking this banner should redirect you to the interactive embedding settings page
<img width="1509" alt="image" src="https://github.com/metabase/metabase/assets/25306947/d1548565-ad25-4e38-b565-6bb8e55e3e34">

As an OSS user: clicking this banner should redirect you to the Embedded Analytics product page

<img width="1508" alt="image" src="https://github.com/metabase/metabase/assets/25306947/38fa38ee-d24e-4413-9a76-694289ec3da1">

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2023-12-19 10:16 UTC, oisincoveney commented on frontend/src/metabase/public/components/widgets/SharingPane/InteractiveEmbeddingCTA/InteractiveEmbeddingCTA.tsx
> +    // TODO: Check padding because design keeps using non-mantine-standard units
Just need to make sure on the spacing, maybe there's another component we can use that has these paddings. I'd use `Badge` but it doesn't seem to be ready yet

2023-12-19 10:17 UTC, oisincoveney commented on frontend/src/metabase/public/components/widgets/SharingPane/SharingPane.tsx
> +    <Stack p="lg">
The diff looks weird but I just nested everything into the `Stack` here and added the `InteractiveEmbeddingCTA` at the bottom

2023-12-19 14:05 UTC, deniskaber requested changes
Left inline comments. Most important one is that implementation differs from the design

2023-12-19 15:48 UTC, oisincoveney commented on frontend/src/metabase/public/components/widgets/SharingPane/InteractiveEmbeddingCTA/InteractiveEmbeddingCTA.unit.spec.tsx
> +describe("InteractiveEmbeddingCTA", () => {
Yep, good call. I'll add those to the existing tests in the embed modal

2023-12-19 15:49 UTC, oisincoveney commented on frontend/src/metabase/public/components/widgets/SharingPane/InteractiveEmbeddingCTA/InteractiveEmbeddingCTA.styled.tsx
> +    color: ${({ theme }) => theme.colors.brand[1]};
Yeah, it's a weird one but the `theme` refers to the Mantine color scheme that we're trying to migrate to, so we basically just have to deal with it unfortunately

2023-12-19 16:13 UTC, oisincoveney commented on frontend/src/metabase/public/components/widgets/SharingPane/InteractiveEmbeddingCTA/InteractiveEmbeddingCTA.tsx
> +  return (
Wow, I didn't realize how far I strayed away from the designs. Thanks for the callout, I'll make sure it matches.

2023-12-19 16:22 UTC, oisincoveney commented on frontend/src/metabase/public/components/widgets/SharingPane/InteractiveEmbeddingCTA/InteractiveEmbeddingCTA.tsx
> +    linkTarget: "https://www.metabase.com/product/embedded-analytics",
I don't think we can actually use `getDocsUrl` here - the `/product/embedded-analytics` page isn't a doc URL, but rather a marketing page

2023-12-19 16:35 UTC, oisincoveney commented on frontend/src/metabase/public/components/widgets/SharingPane/InteractiveEmbeddingCTA/InteractiveEmbeddingCTA.tsx
> +  return (
@deniskaber let me know if this matches your expectations a little better 😄

2023-12-20 09:56 UTC, albertoperdomo requested changes
I think it looks very close, but not quite like the design. What I notice is some issue with vertical alignment of icon and text.

Screenshots below

Design: 
![image](https://github.com/metabase/metabase/assets/24216/f81d3e03-844f-484f-85e3-df3b766d988f)

Implementation:
![image](https://github.com/metabase/metabase/assets/24216/62683310-4e71-4d2e-a22e-c0ce378a68a8)

2023-12-20 13:01 UTC, albertoperdomo approved these changes

2023-12-20 13:48 UTC, deniskaber approved these changes
Approve. But I also found one more issue while testing this - 
<img width="1346" alt="Screenshot 2023-12-20 at 20 28 09" src="https://github.com/metabase/metabase/assets/7983744/4ef29a9b-8d28-492f-bf03-8fdb9ec222ec">

Sharing / Embedding popover has scrollbars

2023-12-21 22:47 UTC, vbenedetti approved these changes

2023-12-22 17:18 UTC, merged