CSV appends: Use a transaction for inserting data
metabase/metabase pull request #36995
Opened 2023-12-20 16:54 UTC by calherries

This PR replaces the logic I created for handling insertion errors to fake transactions with real transactions. 

Originally I wanted to use `_mb_row_id` for deleting inserted rows if there was a failure, because I thought the reason we weren't using transactions before was performance. Turns out I was wrong, using a transaction is actually slightly faster because each commit adds overhead.

2023-12-21 04:50 UTC, qnkhuat commented
What's your thought on memory usage?

2023-12-21 14:05 UTC, calherries commented
Are you referring to the memory footprint on the JVM, or the database? 

Memory usage of the JVM should be independent of whether transactions are used or not, because the objects can be garbage collected after they are inserted.

As for the database, MySQL and Postgres are smart enough to write large files of data to disk, so memory isn't an issue there either. Otherwise large transactions would be impossible to execute.

2023-12-22 02:53 UTC, qnkhuat commented
I was thinking about database memory usage.

> MySQL and Postgres are smart enough to write large files of data to disk

Cool, that's good to know, in that case we don't need to worry about blowing the dataware house up.

2023-12-22 02:57 UTC, qnkhuat commented on src/metabase/driver/mysql.clj
> +                (.write writer (str value))))
this should be done outside of transaction

2023-12-22 02:59 UTC, qnkhuat commented on src/metabase/driver/sql_jdbc.clj
> +                          chunks)]
let's move this preparation outside of the transaction.

2023-12-22 03:04 UTC, qnkhuat requested changes
Some preparation steps should be done outside of transaction, other than that this looks good.

2023-12-22 09:03 UTC, qnkhuat commented on src/metabase/upload.clj
> +
```suggestion
```

2023-12-22 09:04 UTC, qnkhuat approved these changes
LGTM

2023-12-22 10:27 UTC, merged