Fix external landing page urls locking users out of Metabase
metabase/metabase pull request #37322
Opened 2024-01-05 19:42 UTC by sloansparger

### Description

If users customize the `Landing Page` setting in the `Settings -> Appearances` with an external URL, Metabase will fail to load and display an error page.

This PR prevents users from being able to input an external absolute url and warns them the input is invalid. All internal absolute urls are converted to relative in the case users serve their instance from multiple domains.

This is a front-end only improvement, we still need to validate inputs on the back-end and potentially resolve any instances that have already saved an absolute url.

### How to verify

- enable enterprise edition
- login as an admin
- go to "Admin settings"
- navigate to the "Appearance" tab
- locate the landing page input
- test various inputs (exiting/blurring the input will trigger the validation)

### Demo

![Kapture 2024-01-05 at 13 27 27](https://github.com/metabase/metabase/assets/7104357/3765497b-7049-487b-a848-7daf93e0623a)

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

2024-01-05 19:51 UTC, iethree commented on enterprise/frontend/src/metabase-enterprise/whitelabel/components/LandingPageWidget/LandingPageWidget.tsx
> +    const url = new URL(value, location.origin);
check if `isMetabaseUrl` does what you need here.

not entirely sure if it matters here, but be aware that some people host metabase on a subpath like `https://example.com/metabase/`

2024-01-09 16:02 UTC, iethree requested changes
Very nice job discerning our weird settings definition + widget situation. 

Before we merge this, can you
- handle the leading `/` input validation
- make the requested test changes that also test the actual landing page loading

2024-01-09 16:02 UTC, iethree commented on enterprise/frontend/src/metabase-enterprise/whitelabel/components/LandingPageWidget/index.tsx
> +export { LandingPageWidget } from "./LandingPageWidget";
this is fine, though often we just do `export * from` to handle the possible future where there are multiple exports.

2024-01-09 16:05 UTC, iethree commented on e2e/test/scenarios/admin/settings/settings.cy.spec.js
> -    cy.visit("/admin/settings/whitelabel");
🤔 why didn't this test catch that it breaks the instance?

2024-01-09 19:10 UTC, rafpaf reviewed
Looking great! Some questions below

2024-01-09 19:30 UTC, rafpaf commented on frontend/src/metabase/lib/dom.js
> +export function isMetabaseUrl(url) {
Here's a [screencast (no audio)](https://www.loom.com/share/aa7a047c14ff46bcb3650eb94ec1899d?sid=ca8a7b26-1fd9-46cf-a109-1984ae7f6afb) of me entering that SMS URL into the input.

The interface tries to remove the `sms:` scheme from the input, but I found it doesn't succeed if I paste the URL and immediately blur.

2024-01-09 19:52 UTC, rafpaf commented on frontend/src/metabase/lib/dom.js
> +export function isMetabaseUrl(url) {
Here's a [screencast](https://www.loom.com/share/aa7a047c14ff46bcb3650eb94ec1899d?sid=2c829acd-9dff-4f92-aa3d-cf48a4e64031) (there's no audio) of me entering that URL into the input by pasting and immediately blurring.

2024-01-09 21:11 UTC, sloansparger commented on frontend/src/metabase/lib/dom.js
> +export function isMetabaseUrl(url) {
Good catch. @iethree i fixed this by reverting the isMetabaseUrl suggestion from earlier. My previous approach made sure it was the same origin (host + protocol) so this wouldn't happen.

2024-01-09 21:32 UTC, rafpaf commented on frontend/src/metabase/lib/dom.js
> +export function isMetabaseUrl(url) {
Sorry about the double comment, btw. Github was being wonky

2024-01-10 17:50 UTC, iethree approved these changes
🏆

2024-01-10 17:50 UTC, iethree commented on enterprise/frontend/src/metabase-enterprise/whitelabel/components/LandingPageWidget/utils.unit.spec.ts
❤️

2024-01-10 17:50 UTC, iethree commented on enterprise/frontend/src/metabase-enterprise/whitelabel/components/LandingPageWidget/LandingPageWidget.tsx
> +      }
works for me now! I think the changes to getRelativeLandingPageUrl handle it. 👍

2024-01-10 23:11 UTC, merged