Druid Math Aggregations (Part 1)
metabase/metabase pull request #3798
Opened 2016-11-22 20:24 UTC by camsaul

This part is ready to be merged. Support expressions inside aggregations, e.g. MBQL

```clojure
{:aggregation [:sum [:+ [:field-id 1] [:field-id 2]]]}
```

Currently Druid-only.

2016-11-22 22:33 UTC, camsaul commented
Ok, this is all done. Expressions inside aggregations (e.g. `sum(x/y)`), expressions comprised of aggregations (e.g. `avg(x) + sum(y)`), and any combination thereof, are now fully-supported by the Druid driver. Tests included.

I think it makes sense to merge this so on the off chance anything unrelated is broken by the necessary changes to the query parser we can fix them sooner rather than later.

@metabase/core-developers review?

2016-11-23 01:48 UTC, salsakran requested changes
I'm 👎  on the replacement of built-in aggregations with javascript functions as that's a significant performance regression.

The JS function construction code looks solid.

2016-11-23 01:48 UTC, salsakran commented on src/metabase/driver/druid/js.clj
> +  "Interpose artihmetic OPERATOR between ARGS, and wrap the entire expression in parens."
"artihmetic" is mispelled.

2016-11-23 01:48 UTC, salsakran commented on src/metabase/driver/druid/query_processor.clj
> +(defn- ag:doubleSum:expression [{operator :operator,  :as expression} output-name]
For aggregations which have analogs in http://druid.io/docs/latest/querying/aggregations.html, we should use them directly, as JS aggregators are significantly slower than  builtins.

2016-11-23 02:07 UTC, camsaul commented
@salsakran we're not replacing anything that already exists, so there are no regressions.

2016-11-23 02:11 UTC, salsakran commented
I think I misread that bit. Let me go over it again, minus derping.

2016-11-23 02:14 UTC, salsakran approved these changes
Disregard my previous statement. I mis-read the section in question.

2016-11-23 02:16 UTC, camsaul commented
the Druid built-in aggregators only work on a single field so we have to use javascript ones if you're doing things like `min(x + y)` or w/e

We still use built-in ones wherever possible

2016-11-23 02:33 UTC, merged

2016-11-23 13:06 UTC, tlrobinson commented on src/metabase/driver/druid/query_processor.clj
> +
`0` is falsely so it will always be replaced with the `default-value`, is that intended
?