Include filters when exporting dashboard to PDF
metabase/metabase pull request #38231
Opened 2024-01-29 16:29 UTC by perivamsi

Closes https://github.com/metabase/metabase/issues/35475

Give the overall dashboard container that contains filters a name and use that in the html2canvas library.

2024-01-29 16:37 UTC, perivamsi commented
PDF without this change
<img width="1125" alt="Screenshot 2024-01-29 at 11 36 30 AM" src="https://github.com/metabase/metabase/assets/127636/4adc5c34-79e0-44fe-adc1-d27da22fea7b">

PDF with this change (and no filter values selected)
<img width="1124" alt="Screenshot 2024-01-29 at 11 36 41 AM" src="https://github.com/metabase/metabase/assets/127636/eb411de9-5959-43e7-8172-a2e44f11ad3b">


PDF with this change (and with filter values selected)
<img width="1089" alt="Screenshot 2024-01-29 at 11 36 50 AM" src="https://github.com/metabase/metabase/assets/127636/10d056e8-4ef0-46e8-aa57-8d71a0450ffb">

2024-01-29 16:38 UTC, perivamsi commented
The filter labels look funky, they overlap with the filter control.

2024-01-31 00:28 UTC, EmmadUsmani requested changes
I think there's a couple of things that still need to be fixed visually
- The padding to the left of the title is missing
- Dashcard outlines are no longer visible

2024-02-22 14:11 UTC, kulyk commented on frontend/src/metabase/dashboard/components/Dashboard/Dashboard.styled.tsx
> +    }
Workaround: `html2canvas` doesn't handle `fieldset` + `legend` elements we're using for filters
https://github.com/niklasvh/html2canvas/issues/2418

![cleanshot_2024-02-21_at_17 03 30_2x](https://github.com/metabase/metabase/assets/17258145/c1dbc3c2-273e-424a-887f-153f517e01d2)

2024-02-22 15:09 UTC, cdeweyx approved these changes

2024-02-22 15:43 UTC, alxnddr approved these changes

2024-02-22 17:55 UTC, EmmadUsmani approved these changes

2024-02-22 17:55 UTC, EmmadUsmani commented on frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
> +    const cardNodeSelector = "#Dashboard-Parameters-And-Cards-Container";
Nit: extracting this to a single constant that we share between this component and `Dashboard.tsx` would be nice

2024-02-22 20:42 UTC, merged

2024-02-23 13:28 UTC, kulyk commented
@metabase-bot backport release-x.49.x

2024-03-19 11:05 UTC, kulyk commented
@metabase-bot backport release-x.48.x