Prevent categorizing extraction of/truncation to year as temporal-extraction
metabase/metabase pull request #38358
Opened 2024-02-01 15:18 UTC by metamben

Fixes #37172.

Getting the year is both a truncation and extraction operation, but the FE traditionally doesn't see it as extraction. This PR leaves `:year` as an extraction unit, but when generating the display-info, it returns false in `:is-temporal-extraction`.

2024-02-02 14:25 UTC, kamilmielnik requested changes

2024-02-02 19:20 UTC, bshepherdson approved these changes
LGTM code-wise, but there may be a broken case to fix.

2024-02-05 07:49 UTC, kamilmielnik commented on src/metabase/lib/temporal_bucket.cljc
> +          :is-temporal-extraction (let [bucket (raw-temporal-bucket option)]
It works now :+1:

2024-02-05 07:50 UTC, kamilmielnik approved these changes
I confirm it fixes #38253 :+1:

2024-02-05 15:22 UTC, merged