Improve tooltips in navigation
metabase/metabase pull request #38588
Opened 2024-02-08 22:55 UTC by sloansparger

### Description

This PR does two things

1. Makes the sidebar navigation tooltips consistent with the one used by the main navigation
<img width="497" alt="Screenshot 2024-02-08 at 4 50 49 PM" src="https://github.com/metabase/metabase/assets/7104357/f5b85121-23b1-41d2-a347-7cbeab0db419">

2. Adds a delay for showing the open/close sidebar tooltip in the main navbar
![Kapture 2024-02-08 at 17 52 45](https://github.com/metabase/metabase/assets/7104357/dbd916a6-1868-4083-9f83-81ed6a7e010b)

2024-02-09 15:48 UTC, naatz-co commented
it's looking nice!

2024-02-09 15:49 UTC, naatz-co approved these changes

2024-02-09 20:54 UTC, sloansparger commented
@naatz-co done and done! you can see what I implemented in this loom link: https://www.loom.com/share/2c0aca6a734b46099d3ce0ebd7ae9285?sid=aecc093b-534c-4805-a791-445a1444d405

2024-02-09 23:15 UTC, rafpaf commented
@sloansparger This is how it looks on my end: https://www.loom.com/share/06a7b396ad134cf786075c8dc58aaf1a?sid=ddd4d367-f696-49f0-bf45-4dccb317d257

2024-02-09 23:16 UTC, rafpaf commented on frontend/src/metabase/nav/components/AppBar/AppBarToggle.tsx
> +    onToggleClick?.();
I darest not coalesce so boldly

2024-02-09 23:21 UTC, rafpaf requested changes
See https://github.com/metabase/metabase/pull/38588#issuecomment-1936726126

Perhaps I'm not loading the branch correctly, but it seems like the tooltip is being disobedient

2024-02-12 17:08 UTC, iethree commented
check out: https://github.com/metabase/metabase/pull/38678

2024-02-14 04:09 UTC, sloansparger commented
@rafpaf I've tested it again locally and it appears to work for me 🤔

2024-02-14 16:52 UTC, rafpaf approved these changes
Looks good now!

2024-02-14 16:52 UTC, rafpaf approved these changes
Looks good now!

2024-02-15 15:27 UTC, iethree approved these changes
🌴

2024-02-15 15:45 UTC, merged