WIP flow :semantic-type through QP for aggregations
metabase/metabase pull request #38829
Opened 2024-02-15 19:40 UTC by adam-james-v

Fixes: #38022

WIP need to add and fix some tests and confirm if this is the most correct place to fix the problem. Seems like it's a good spot to put things though.

2024-02-16 16:27 UTC, markbastian commented on test/metabase/query_processor_test/aggregation_test.clj
> +(deftest semantic-type-for-aggregate-fields-test
Might want to put a ticket number for https://github.com/metabase/metabase/issues/38022 in the test name or the testing string.

2024-02-16 16:28 UTC, markbastian approved these changes
Left one nonblocking comment, but looks good.

2024-02-16 17:02 UTC, bshepherdson reviewed
I think there's some more test cases to exercise here.

The argument to an aggregation and the aggregation's own result don't necessarily have the same semantic type. On the other hand I see that `metadata-method ::aggregation` is what you're editing, and they all use that except `:count-where`, which overrides `:semantic-type :type/Quantity`.

You'll want to check all the aggregation operators - if they take an argument, make sure they either share the `:semantic-type` of the first argument (eg. `sum`, `avg`, `min`, `max`), or that there's a specific `metadata-method` (eg. `:count-where`).

I think this might already be broken for `distinct`, which should be a `:type/Quantity` rather than blank (now) or copied from the column (your PR).

Does this make sense?

2024-02-22 16:56 UTC, bshepherdson commented
Yes, that's all the aggregations.

I think individually these changes are good, but I think we should take advantage of multimethod dispatch to reduce duplication here, like is done elsewhere in this file. There's really only three cases: always a `:type/Quantity` (eg. `:count`), keep the inner `:semantic-type` (eg. `SUM`), and drop `:semantic-type` for the unit-less `:var`.

See the [docs](https://clojure.org/reference/multimethods) if you're not familiar with `derive` and hierarchies. There's a few existing ones in this namespace; I think we can reuse `::count-aggregation`.

```clojure
(lib.hierarchy/derive ::count-aggregation ::quantity-aggregation)
(lib.hierarchy/derive :distinct ::quantity-aggregation)

(doseq [tag [:percentile :var]]
  (lib.hierarchy/derive tag ::no-semantic-type))

(defmethod lib.metadata.calculation/metadata-method
  ::quantity-aggregation
  ; ...
 (assoc ... :semantic-type :type/Quantity))

;; The default preserves the semantic type.

;; But for ::no-semantic-type we should drop it.
(defmethod lib.metadata.calculation/metadata-method
  ::no-semantic-type
  ; ...
(dissoc ... :semantic-type))
```

2024-02-22 16:56 UTC, bshepherdson requested changes
Sorry to send this back, but hopefully this is a modest edit to reduce duplication.

2024-02-22 22:09 UTC, bshepherdson approved these changes

2024-02-22 22:09 UTC, bshepherdson approved these changes
Good stuff!

2024-02-22 23:20 UTC, merged