allow timezone setting on read-only postgres
metabase/metabase pull request #4062
Opened 2017-01-04 15:37 UTC by parisholley

Fixes #1699

2017-01-04 21:35 UTC, salsakran commented
Hey @parisholley , thanks for the contribution. 

Can you please add some tests that verify this works?

2017-01-04 21:41 UTC, camsaul commented
Replacing all occurrences of the `?` in the SQL sounds like it would be a SQL injection issue since we don't verify that the value of the `timezone` setting.

2017-01-04 21:42 UTC, camsaul commented on src/metabase/driver/generic_sql/query_processor.clj
> +        replaced (clojure.string/replace sql "?" (str "'" (re-matches #"[A-z\/_]+" timezone) "'"))]
https://github.com/metabase/metabase/wiki/Metabase-Clojure-Style-Guide#require-namespaces-you-use

2017-01-04 22:49 UTC, parisholley commented
@camsaul correct, but no good way around this. the regex is a simple attempt to make it injection safe

2017-04-24 18:55 UTC, camsaul requested changes
There's a couple things I think need to be addressed here:

1.  I think it's hacky and misleading to have all the various drivers specify a string like

```sql
SET SESSION TIMEZONE TO ?
```

only to have that `?` replaced with a string literal before it gets executed anyway. Someone could be forgiven for thinking the timezone is actually passed as a prepared statement param.

It would make more sense just to make `set-timezone-sql` a plain format string, e.g.

```sql
SET SESSION TIMEZONE TO %s
```

So it's at least obvious `%s` is going to get replaced with a string literal before the statement is executed. Then we can just have a Clojure call to format like

```clojure
(format sql timezone)
```

2. If there is no timezone or the timezone is invalid we shouldn't execute the statement at all, rather than running something like

```sql
SET SESSION TIMEZONE TO ''
```

3.  A regex with a range of `A-z` is definitely not what we want. What we want here is `A-Za-z`. `A-z` means any character point between `A` and `z` is considered valid, which includes all sorts of nasty things like `[`, `\`, `^`, etc.

2017-04-26 17:24 UTC, camsaul commented
@parisholley thanks for your contribution. Since we want to get this merged for our next release I went ahead and opened a new PR, #4872, based off of this one with the changes requested. I'm expecting to merge that shortly. Thanks again!

2017-04-26 17:24 UTC, closed without merging