Add invalidate now button
metabase/metabase pull request #40972
Opened 2024-04-03 15:50 UTC by rafpaf

<img width="541" alt="image" src="https://github.com/metabase/metabase/assets/130925/13276a67-8d1a-4fed-a7a9-367f2b032404">

2024-04-03 18:41 UTC, rafpaf commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/metabase/metabase/40972?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#40972** <a href="https://app.graphite.dev/github/pr/metabase/metabase/40972?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#40980** <a href="https://app.graphite.dev/github/pr/metabase/metabase/40980?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-16 17:01 UTC, iethree requested changes
1) the strategy name changes look good, if they were in their own pr, that would be easy to approve
1) functionality also looks and works great
2) I really don't think the invalidation button should be its own form, all the ref passing and portaling are smells that this is a hack and there is a better way. it should just be a button within the form. yes, we'll need a status-updating button that's separate from formik, but i think that is a generally worthwhile endeavor, not just for this bit of UI.

2024-04-16 17:26 UTC, rafpaf commented on enterprise/frontend/src/metabase-enterprise/caching/components/StrategyEditorForDatabases.unit.spec.tsx
> -      await screen.findByLabelText("Edit default policy (currently: Duration)"),
yes but there are further changes here not included in that PR

2024-04-16 17:26 UTC, rafpaf commented on frontend/src/metabase/admin/performance/components/StrategyForm.tsx
> +  shouldAllowInvalidation &&= targetId !== rootId;
good call

2024-04-18 14:33 UTC, iethree approved these changes
looks good!

one little thing: should the "done" state of the invalidation button be clickable?

2024-04-18 18:26 UTC, merged