docs - drop note on sandboxes
metabase/metabase pull request #41220
Opened 2024-04-09 21:25 UTC by jeff-bruemmer

Caching is compatible with data sandboxing.

See https://github.com/metabase/metabase/pull/14388.

2024-04-09 21:30 UTC, luizarakaki requested changes

2024-04-09 21:30 UTC, luizarakaki commented on docs/data-modeling/models.md
> -> Model caching doesn't work with [data sandboxing](../configuring-metabase/caching.md#caching-doesnt-work-with-data-sandboxing).
This is actually true.

Only question cache works

2024-04-10 13:28 UTC, luizarakaki approved these changes

2024-04-11 08:06 UTC, piranha commented
Caching is indeed compatible with data sandboxing - there is some code designed to specifically be careful around that, see `middleware/cache.clj`:

```
  ;; Query will already have `info.hash` if it's a userland query. It's not the same hash, because this is calculated
  ;; after normalization, instead of before. This is necessary to make caching work properly with sandboxed users, see
  ;; #14388.
  (let [query-hash      (qp.util/query-hash query)
```

2024-04-11 16:24 UTC, merged