fix invalid series names in tooltip
metabase/metabase pull request #41711
Opened 2024-04-23 03:53 UTC by alxnddr

### Description

Fixes invalid tooltip series names. Previously we used series name for columns that are used by the series in tooltips. However, series names (what we show in legends) may differ from what we need to show in tooltips:

Here is a break down of what we need to show when cards are combined.
**For a single metric card**
Series name: `card name`
Tooltip name: `column name`
When series name is overriden in settings both series name and tooltip name should use the specified value.

**For a multiple metric card**
Series name: `card name: column name`
Tooltip name: `column name`
When series name is overriden in settings both series name and tooltip name should use the specified value.

**For a breakout card**
Series name: `card name: breakout value`
Tooltip name: `column name`
When series name is overriden in settings both series name and tooltip name should use the specified value.

### How to verify

Verify cases above and/or ensure `e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js` and `e2e/test/scenarios/visualizations-charts/line_chart.cy.spec.js` are green

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

2024-04-23 19:20 UTC, JesseSDevaney approved these changes
LGTM!

2024-04-23 20:45 UTC, JesseSDevaney requested changes
Upon reviewing the E2E tests, waterfall charts just started breaking. I think the import in `frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts` of `getCardSeriesModels` needs to be updated to `getCardsSeriesModels`, right?

![Screenshot from 2024-04-23 16-41-27](https://github.com/metabase/metabase/assets/22608765/99bc20d0-215a-4656-9bbd-65cd1b666727)

- Relevant files:
  - https://github.com/metabase/metabase/blob/fix-invalid-tooltip-series-names/frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts#L9
  - https://github.com/metabase/metabase/blob/fix-invalid-tooltip-series-names/frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts#L94
- Relevant tests: 
  - https://github.com/metabase/metabase/blob/fix-invalid-tooltip-series-names/e2e/test/scenarios/dashboard-cards/dashboard-card-resizing.cy.spec.js#L256-L257
  - https://github.com/metabase/metabase/blob/fix-invalid-tooltip-series-names/e2e/test/scenarios/visualizations-charts/waterfall.cy.spec.js

2024-04-23 21:22 UTC, alxnddr commented
@JesseSDevaney thanks, I fixed it

2024-04-24 15:00 UTC, kulyk approved these changes

2024-04-24 19:10 UTC, JesseSDevaney approved these changes

2024-04-24 19:13 UTC, merged