fix combined cards crash when some cards do not have metrics and dimensions settings
metabase/metabase pull request #41710
Opened 2024-04-23 01:09 UTC by alxnddr

Closes https://github.com/metabase/metabase/issues/41290

### Description

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2024-04-23 18:53 UTC, JesseSDevaney requested changes
Thank you for fixing dash-cards with added series, Sasha! 

I checked the tests that were blocked by the corresponding issue and all of them are no longer failing because of added series errors - they are still failing but for other reasons. 

But, there is still one chart listed in that issue that is still crashing, see below.

---

The chart from https://github.com/metabase/metabase/issues/41290, shown below, is still erroring out.

![Screenshot from 2024-04-22 15-20-19](https://github.com/metabase/metabase/assets/22608765/02dc91b3-f1a8-4463-8649-923404114ed9)
![image](https://github.com/metabase/metabase/assets/22608765/ba5c4aca-4478-4ebe-8d34-3834b2ade20c)

- Relevant test: https://github.com/metabase/metabase/blob/echarts/e2e/test/scenarios/visualizations-charts/bar_chart.cy.spec.js#L406

2024-04-23 18:53 UTC, JesseSDevaney commented on e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js
- https://github.com/metabase/metabase/blob/fix-combined-cards-crash/e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js#L363

This test was also one the ones failing, but I noticed you did not update that one as well. Would you update that one as well to account for new selectors?

2024-04-23 21:17 UTC, alxnddr commented
@JesseSDevaney nice catch, thanks! I fixed the problem

2024-04-23 21:18 UTC, alxnddr commented on e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js
I fixed them here https://github.com/metabase/metabase/pull/41711 and now I'll address your feedback there

2024-04-24 19:07 UTC, JesseSDevaney approved these changes
Thank you for fixing the broken charts! :heart:

2024-04-24 19:10 UTC, merged