[Metrics V2] Query processor handle no join strategy
metabase/metabase pull request #42666
Opened 2024-05-14 22:22 UTC by snoe

Fixes #42462

Make QP preprocessor handle queries referencing metrics in the style of legacy metrics. Enforce various compatibility checks.

2024-05-15 18:05 UTC, metamben requested changes
LGTM, but I have a few questions. Also, I would prefer to have test cases explicitly testing and named for the multi-stage metric execution. I would like to see test showing what happens when expression names in a metric clash with the expression names in the host query.

2024-05-16 15:37 UTC, snoe commented on src/metabase/query_processor/middleware/metrics.clj
> +                               :aggregation (first (lib/aggregations metric-query))
I'm not sure it should be possible.

2024-05-16 15:40 UTC, snoe commented on src/metabase/query_processor/middleware/metrics.clj
> +  (lib/expression query 0 expression-name expression))
As per slack convo, I'll address this in a followup #42782

2024-05-16 15:45 UTC, snoe commented on src/metabase/query_processor/middleware/metrics.clj
> +      (recur query path (update-metric-transition-stages expanded-stages idx metric-metadata))
Added tests to check this, but metrics based on metrics based on metrics would run into this.

2024-05-16 15:49 UTC, metamben commented on src/metabase/query_processor/middleware/metrics.clj
> +                               :aggregation (first (lib/aggregations metric-query))
I meant, if it should throw. Maybe the > 1 case shouldn't, but then it should log, I guess.

2024-05-16 15:51 UTC, metamben approved these changes
This is good, any remaining issues can be addressed in a follow up PR.

2024-05-16 23:56 UTC, merged