[WIP]: Fix timeseries chrome overflow
metabase/metabase pull request #42761
Opened 2024-05-16 12:22 UTC by romeovs

Closes https://github.com/metabase/metabase/issues/42760

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Browse data -> Accounts
2. Add an aggregation on a time column and pick a bucket
3. Open the View ... by ... dropdown underneath the visualization

### Demo

<img width="436" alt="Screenshot 2024-05-16 at 14 21 57" src="https://github.com/metabase/metabase/assets/1250185/3f44bed2-257c-4327-b0e9-f80faa1894dc">

2024-05-16 20:44 UTC, mazameli requested changes
Minor, but ideally the `More…` would be `text-brand` in color to distinguish it from the selectable items, and to match what we do in the summarize sidebar and notebook group-by popovers.

2024-05-17 14:21 UTC, ranquild commented on frontend/src/metabase/querying/components/TimeseriesChrome/TimeseriesBucketPicker/TimeseriesBucketPicker.unit.spec.tsx
> +  it("should allow to show more binning options", async () => {
Please also add tests for the selected item - when it's within the initial expanded list or not

2024-05-17 14:22 UTC, ranquild approved these changes
Looks good, minor comments

2024-05-30 03:42 UTC, ranquild commented
@mazameli could you take a look?

2024-05-30 17:57 UTC, mazameli approved these changes

2024-05-30 19:23 UTC, merged