temporarily removes the SameSite=None suggestion box
metabase/metabase pull request #43524
Opened 2024-06-03 16:02 UTC by npretto

### Description

[Slack thread](https://metaboat.slack.com/archives/C063Q3F1HPF/p1717429725205379?thread_ts=1717422303.389629&cid=C063Q3F1HPF).

The box is suggesting to use SameSite=None even when that will not work.
We're temporarily removing the suggestion box until we come up with a proper solution.

I created https://github.com/metabase/metabase/issues/43523 to not forget about it and to leave a reference in the code

2024-06-03 17:56 UTC, albertoperdomo requested changes
LGTM.
Can we please also adjust this copy as it's misleading?

Before:

> If you set this to None, you'll have to use HTTPS (unless you're just embedding locally), or browsers will reject the request.

After:

>If you set this to None, you'll have to use HTTPS, or browsers will reject the request.

2024-06-04 07:46 UTC, npretto commented
> LGTM. Can we please also adjust this copy as it's misleading?
> 
> Before:
> 
> > If you set this to None, you'll have to use HTTPS (unless you're just embedding locally), or browsers will reject the request.
> 
> After:
> 
> > If you set this to None, you'll have to use HTTPS, or browsers will reject the request.

Done in https://github.com/metabase/metabase/pull/43524/commits/bd9f776e281a81ac63f7ad44394074fc377cb3d3

2024-06-04 10:58 UTC, albertoperdomo approved these changes

2024-06-04 11:03 UTC, oisincoveney approved these changes

2024-06-04 11:05 UTC, merged

2024-06-05 10:37 UTC, npretto commented
@metabase-bot backport release-x.49.x