add kubernetes deployment template
metabase/metabase pull request #4364
Opened 2017-02-12 20:48 UTC by VikramTiwari

- For #4363

###### TODO 
-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

2017-02-13 19:09 UTC, tlrobinson commented
FYI we don't currently support horizontal scaling yet, see #1446 and #2754

2017-02-13 19:42 UTC, VikramTiwari commented
Gotach! I will make necessary adjustments.

2017-02-14 13:42 UTC, allansene commented
Just deployed on my cluster. All seems ok... :+1:

2017-02-14 20:52 UTC, VikramTiwari commented
Thanks for the feedback @allansene 
I think we can improve this by adding a secrets volume to store all of the Postgress/MySQL connection details. I will be looking into that later today.

2017-02-19 07:38 UTC, VikramTiwari commented
I updated with notes on scaling and secrets. Secrets are kind of overkill right now, especially since they are gonna be used for just one instance and not shared.

@tlrobinson let me know if this looks good. I have tested the deployment and so did @allansene (thanks for review).

2017-03-28 00:10 UTC, salsakran requested changes
One thing I don't see here is any persistence of the application database. 

There should either be a well defined place for the image to store its embedded database files or a database image spun up with backing persistent storage.

2017-03-28 00:10 UTC, salsakran commented on bin/kubernetes/ingress.yaml
> +    - metabase.vikramtiwari.com
Does this need to be used as a template (where each deployment fills in its host name) or can this be generalized?

2017-03-28 00:10 UTC, salsakran commented on bin/kubernetes/ingress.yaml
> +  - host: metabase.vikramtiwari.com
see above

2017-03-28 02:38 UTC, VikramTiwari commented
This can not be merged until https://github.com/metabase/metabase/issues/4617 is fixed since HTTPs with Load Balancer is causing issues.

2017-03-28 02:39 UTC, VikramTiwari commented on bin/kubernetes/ingress.yaml
> +    - metabase.vikramtiwari.com
I should have put in proper templating. I was testing this for my website. For your question, yes, this will be used as a template.

2017-07-11 23:29 UTC, philipithomas requested changes

2017-07-11 23:29 UTC, philipithomas commented on bin/kubernetes/service.yaml
> +  type: NodePort
These are invalid nodeport values, right? Shouldn't it be 300XX range?

2017-09-22 04:53 UTC, VikramTiwari commented
Closing this in favor of #5736 https://github.com/kubernetes/charts/tree/master/stable/metabase Go helm charts!

2017-09-22 04:53 UTC, closed without merging