Add ellipsified for table header and rows (see issue #4370)
metabase/metabase pull request #4383
Opened 2017-02-15 00:27 UTC by joannekoong

Addresses issue #4370 (for both table header and table rows -- see pics)

2017-02-15 00:27 UTC, joannekoong commented
![header_ellipsified](https://cloud.githubusercontent.com/assets/13632558/22955710/a35a08b0-f2eb-11e6-96d6-eb3a6018d783.png)

2017-02-15 00:32 UTC, joannekoong commented
![header_ellipsified](https://cloud.githubusercontent.com/assets/13632558/22955804/40df98b6-f2ec-11e6-947d-0b7ed28a9bc6.png)

2017-02-15 00:33 UTC, joannekoong commented
![row_ellipsified](https://cloud.githubusercontent.com/assets/13632558/22955839/779b8eaa-f2ec-11e6-9823-cafa9150143b.png)

2017-02-15 00:57 UTC, kdoh requested changes
Hey there @joannekoong. Thanks for this! A couple quick bits of feedback.

- It looks like something is causing the sort indicator icon to wrap onto a new line (compared to master)
- The tooltips seem to be lacking padding in this instance.

2017-02-15 01:24 UTC, kdoh requested changes

2017-02-15 01:24 UTC, kdoh commented on frontend/src/metabase/visualizations/components/TableInteractive.jsx
> +                    <Ellipsified> {columnTitle} </Ellipsified>
One other small thing would be removing the extra spaces in between the components here and on line 285.

2017-02-15 03:08 UTC, joannekoong commented
Hi @kdoh, thanks for the comments. Great catch -- didn't realize the sort icon got kicked onto a new line. New pics are: 

![header_ellipsified](https://cloud.githubusercontent.com/assets/13632558/22959165/0757bdc4-f302-11e6-8da5-12b1491fcd1b.png)

![row_ellipsified](https://cloud.githubusercontent.com/assets/13632558/22959169/0aa60d50-f302-11e6-902e-6751d8dd6ba8.png)

2017-02-15 17:13 UTC, kdoh requested changes
A couple small stylistic details and then I think this is good to go.

2017-02-15 17:13 UTC, kdoh commented on frontend/src/metabase/visualizations/components/TableInteractive.jsx
> +                    <Ellipsified><span>
We'll want to keep the nesting consistent so It'd be great to wrap the spans onto their own line and then indent the children accordingly just like normal HTML.

2017-02-17 19:24 UTC, tlrobinson requested changes

2017-02-17 19:24 UTC, tlrobinson commented on frontend/src/metabase/css/components/popover.css
> +	padding: 0.8em;
This is going to add extra padding to every existing tooltip. Please remove it and wrap `<Value>` in `<div className="p1">` (or maybe `p2`, see how it looks)

2017-02-17 19:24 UTC, tlrobinson commented on frontend/src/metabase/visualizations/components/TableInteractive.jsx
> +                    <Ellipsified><Value value={cellData} column={column} onResize={this.onCellResize.bind(this, columnIndex)} /></Ellipsified>
This line is getting long, could you put `<Value>` on it's own line (and indent like the rest)

2017-02-18 20:35 UTC, joannekoong commented
Pictures for "584688d: Incorporate tlrobinson's comments -- fix padding and add line breaks"

![f](https://cloud.githubusercontent.com/assets/13632558/23096697/d58fa25c-f5ef-11e6-8c9e-c164d2fca534.png)
![s](https://cloud.githubusercontent.com/assets/13632558/23096698/d7ae26c6-f5ef-11e6-910d-19c01b7f96c5.png)

2017-02-20 20:14 UTC, kdoh approved these changes

2017-02-21 01:14 UTC, tlrobinson commented
Unfortunately my advice was bad... adding the `<div>` with padding broke the ellipsification and vertical center alignment.

Ellipsified takes a `tooltip` prop. I think this is a workable solution:

```diff
diff --git a/frontend/src/metabase/visualizations/components/TableInteractive.jsx b/frontend/src/metabase/visualizations/components/TableInteractive.jsx
index 60ea357..e6c5d22 100644
--- a/frontend/src/metabase/visualizations/components/TableInteractive.jsx
+++ b/frontend/src/metabase/visualizations/components/TableInteractive.jsx
@@ -282,10 +282,8 @@ export default class TableInteractive extends Component<*, Props, State> {
                     })}
                     onClick={isFilterable && this.showPopover.bind(this, rowIndex, columnIndex)}
                 >
-                    <Ellipsified>
-                        <div className="p1">
-                            <Value value={cellData} column={column} onResize={this.onCellResize.bind(this, columnIndex)} />
-                        </div>
+                    <Ellipsified tooltip={<div className="p1"><Value value={cellData} column={column} /></div>}>
+                        <Value value={cellData} column={column} onResize={this.onCellResize.bind(this, columnIndex)} />
                     </Ellipsified>
                     { popover && popover.rowIndex === rowIndex && popover.columnIndex === columnIndex &&
                         <QuickFilterPopover
@@ -325,8 +323,8 @@ export default class TableInteractive extends Component<*, Props, State> {
                     className={cx("cellData", { "cursor-pointer": isSortable })}
                     onClick={isSortable && this.setSort.bind(this, column)}
                 >
-                    <Ellipsified>
-                        <div className="p1">
+                    <Ellipsified tooltip={columnTitle}>
+                        <span>
                             {columnTitle}
                             {isSortable &&
                                 <Icon
@@ -335,7 +333,7 @@ export default class TableInteractive extends Component<*, Props, State> {
                                     size={8}
                                 />
                             }
-                        </div>
+                        </span>
                     </Ellipsified>
                 </div>
                 <Draggable
```

2017-03-21 19:19 UTC, kdoh commented
Hey there @joannekoong. Wanted to check in and see if you're still interested in finishing off this PR by making the changes @tlrobinson requested above.

2017-03-23 19:39 UTC, joannekoong commented
Hi @kdoh, thanks for checking in -- I'm definitely interested in finishing this PR. Sorry for the delay, am swamped with school right now. I'll try my best to get this in by the end of the weekend!

2017-04-18 17:48 UTC, kdoh commented
@tlrobinson mind giving this another look? looks like @joannekoong updated things.

2017-07-10 23:25 UTC, salsakran commented
@tlrobinson + @kdoh how do you two want to proceed with this PR?

2018-12-03 20:56 UTC, tlrobinson commented
I've opened a new PR with this merged with `master` here: https://github.com/metabase/metabase/pull/9067

2019-01-10 01:01 UTC, kdoh commented
Implemented and merged in #9067

2019-01-10 01:01 UTC, closed without merging