Bring files over from fix-adaptive-policy-bug
metabase/metabase pull request #44280
Opened 2024-06-17 10:59 UTC by rafpaf

> [!IMPORTANT]
> For those employed by Metabase: if you are merging into master, please add either a `backport` or a `no-backport` label
> to this PR. You will not be able to merge until you do this step. Refer to the section [Do I need to backport this
> PR?](https://www.notion.so/metabase/Metabase-Branching-Strategy-6eb577d5f61142aa960a626d6bbdfeb3?pvs=4#89f80d6f17714a0198aeb66c0efd1b71)
> in the Metabase Branching Strategy document for more details. If you're not employed by Metabase, this section does not
> apply to you, and the label will be taken care of by your reviewer.

> **Warning**
>
> If that is your first contribution to Metabase, please sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) (unless it's a tiny documentation change). Also, if you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

Closes https://github.com/metabase/metabase/issues/[issue_number]

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2024-06-17 10:59 UTC, rafpaf commented
* **#44280** <a href="https://app.graphite.dev/github/pr/metabase/metabase/44280?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-17 15:10 UTC, sloansparger approved these changes

2024-06-19 23:05 UTC, sloansparger commented
Approved, and will be merged after @piranha can make a related BE fix.

Internal discussion here: https://metaboat.slack.com/archives/C06KX7QECN4/p1718640617606289?thread_ts=1718624152.579009&cid=C06KX7QECN4

2024-06-25 12:51 UTC, piranha requested changes
So the thing is that it was looking at `result.updated_at`, which is not present in backend responses right now - I'm not sure why though. But `card.updated_at` is also not a good place to look for the indication when query was ran the last time, since it indicates when card was changed the last time.

I'm adding `updated_at` to backend results, which will contain time the query was ran last time, if you are getting this query from the cache. If not, it'll be `null`, which will render "Updated a few seconds ago" (seems fine to me).

2024-07-24 16:46 UTC, rafpaf commented
There's no need to fix the message now

2024-07-24 16:46 UTC, closed without merging