[MBQL lib] Map dashboard filters to last stage w/aggregations
metabase/metabase pull request #44571
Opened 2024-06-21 20:25 UTC by bshepherdson

Originally we used the last stage's columns for dashboard filters, but
then if you eg. use a custom expression to clean up the results of the
aggregation, then you can't filter at the most useful spot - before the
aggregations.

Fixes #19744. Related to #26244, #33958.

2024-07-02 16:58 UTC, bshepherdson commented
* **#44571** <a href="https://app.graphite.dev/github/pr/metabase/metabase/44571?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bshepherdson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-02 20:15 UTC, ranquild commented
@bshepherdson We discussed this with @mngr several times and I thought that we want to have columns from 2 last stages so match the filter modal behavior. Worth checking with product first.

2024-07-03 21:25 UTC, snoe approved these changes

2024-07-03 21:25 UTC, snoe commented on src/metabase/lib/js.cljs
> +(defn ^:export dashboard-filter-stage-index
This should be tested, and it seems that the implementation should be in fe-utils.

2024-07-03 21:25 UTC, snoe commented on src/metabase/query_processor/middleware/parameters/mbql.clj
> +            query         (mbql.u/add-filter-clause query (:stage-number opts) filter-clause)]
I think seeing a full test in `qp/parameters` with the expected parameter with `:stage-number` in opts would be useful to see how it's all expected to work together.

2024-07-16 13:33 UTC, ranquild requested changes
This shouldn't be merged because it conflicts with the product doc.

2024-08-15 18:59 UTC, metamben commented on src/metabase/query_processor/middleware/parameters/mbql.clj
> +            [_ _ opts]    target
In fact, this seems to be taking the opts from the dimension clause, not from the field clause, which is good.

2025-03-30 01:31 UTC, closed without merging