[wip] fix cross-version tests
metabase/metabase pull request #44691
Opened 2024-06-25 15:32 UTC by iethree

closes https://github.com/metabase/metabase/issues/44661 as a bandaid

the real fix will be https://github.com/metabase/metabase/issues/44662

## Description

These tests broke because people updated them as if they would be run on the branch they are in, like any other test. Since we run these so infrequently, it wasn't obvious when/what/why they broke.

2024-07-02 07:38 UTC, iethree commented on .github/workflows/e2e-cross-version.yml
> +    - cron: '0 9 * * 1-5'
these test are actually really fast since we're not building metabase. I'd rather run them daily than wonder how they broke in the past week.

2024-07-02 07:39 UTC, iethree commented on .github/workflows/e2e-cross-version.yml
> +    types: [opened, synchronize, reopened, ready_for_review]
we want to run these on any pull request that touches the cross-version tests so that people know if they broke them

2024-07-02 07:39 UTC, iethree commented on .github/workflows/e2e-cross-version.yml
> +    timeout-minutes: 20
these typically run in about 5 minutes

2024-07-02 07:40 UTC, iethree commented on .github/workflows/e2e-cross-version.yml
> +    if: ${{ always() && contains(needs.*.result, 'failure') && github.ref_name == 'master' }}
don't ping slack anytime a pull request test fails

2024-07-03 12:33 UTC, nemanjaglumac requested changes
The actual fix looks good.
It just seems that the file-paths logic is reversed, and should be updated.

2024-07-03 12:33 UTC, nemanjaglumac commented on .github/file-paths.yaml
> +  - ".github/workflows/e2e-cross-version.yml"
Why are we running ALL e2e tests whenever we change the cross-version yaml?
Unless I'm missing something, this doesn't make sense to me.

What you want instead is to run only cross-version tests whenever this file changes.

2024-07-03 12:33 UTC, nemanjaglumac commented on .github/file-paths.yaml
> +
You can add more triggers here, but these two should be the bare minimum.

```suggestion
e2e_cross_version: &e2e_cross_version
  - ".github/workflows/e2e-cross-version.yml"
  - "e2e/test/scenarios/cross-version/**"

```

2024-07-10 11:13 UTC, nemanjaglumac commented on .github/file-paths.yaml
> +
```suggestion
```

2024-07-10 11:29 UTC, nemanjaglumac approved these changes
Awesome!
Thank you

2024-07-10 11:57 UTC, merged