E2E test for no run button for nodata users
metabase/metabase pull request #44693
Opened 2024-06-25 16:11 UTC by ranquild

Closes https://github.com/metabase/metabase/issues/37374

Makes sure that there is no button for ad-hoc queries for users without data permissions.

2024-06-26 08:28 UTC, kamilmielnik requested changes

2024-06-26 08:28 UTC, kamilmielnik commented on e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
> +describe("issue 37374", () => {
I managed to sort of reproduce the bug (the refresh button is not shown, but query gets auto-refreshed and ends up in a non-recoverable permission error state, like in original report)

https://github.com/metabase/metabase/assets/6830683/e78a2fce-c494-4cf0-9da4-546acdf1d0c9

2024-06-27 16:07 UTC, ranquild commented on e2e/test/scenarios/models/models-revision-history.cy.spec.js
> -    cy.wait("@modelQuery" + ORDERS_BY_YEAR_QUESTION_ID);
No query changes - no query requests. Previous we re-run the query every time the viz settings changed

2024-06-28 10:03 UTC, kamilmielnik approved these changes

2024-06-28 12:49 UTC, merged