Async coll perm graph revision
metabase/metabase pull request #45258
Opened 2024-07-08 23:06 UTC by escherize

Pursuant to https://github.com/metabase/metabase/issues/39997

Improves collection graph update performance, especially on problematic instances that have 1000+ collections and perm groups, by making the costly process of writing the potentially gigantic revision json blob to the db into an async process.

2024-07-09 17:36 UTC, escherize commented on src/metabase/models/collection/graph.clj
> -     (data-perms.graph/log-permissions-changes diff-old changes)
We were logging before checking that the revision numbers were correct. That seems wrong, so I change the order that this happens too.

2024-07-09 18:22 UTC, johnswanson requested changes
This makes me a bit nervous - it doesn't provide the same concurrency guarantees as before.

Say `save-perms-revision!` takes 60s to complete. We'll update the permissions graph, but the revision won't be updated for a minute. So e.g. say I am on revision 47 and make a change. The endpoint returns quickly. At this moment, someone else makes a different change to permissions - also with revision 47. `check-revision-numbers` won't throw because as far as it knows we're still on revision 47. It'll successfully change the permissions graph - then sometime in the future we'll get an exception when we try to insert two revisions with the same ID (one will be lost).

In the end we'll have a single new revision (48) and I think it'll have the wrong diff.

One option would be to decouple the revision number from the actual revision write itself (maybe we could insert it and then fill it in later?) but I'm not really sure.

2024-07-09 19:37 UTC, escherize commented
Good call, I will decouple incrementing the revision number (fast, and should be sync) from writing the perm-graph (slow and will be async).

2024-07-09 19:57 UTC, escherize commented on src/metabase/models/collection/graph.clj
> +                                           :after ""))))
I almost wrote a migration here, but was swayed by: https://github.com/metabase/metabase/blob/async-coll-perm-graph-revision/resources/migrations/001_update_migrations.yaml#L8267

2024-07-10 12:09 UTC, johnswanson approved these changes
Nice, LGTM!

2024-07-10 16:00 UTC, noahmoss reviewed
Filling in the before/after async makes sense to me. For testing, I wonder if we can just deref the future returned from `update-graph!` so that the test blocks until the data is written? Is there anything that requires the wait-until approach? Hard-coded sleeps in tests just make me nervous.

2024-07-10 16:00 UTC, noahmoss commented on src/metabase/models/collection/graph.clj
> +                                           :id      (inc current-revision-number)
nit
```suggestion
                                           :id (inc current-revision-number)
```

2024-07-10 22:36 UTC, merged