[WIP] Fix `useIsTruncated`
metabase/metabase pull request #45347
Opened 2024-07-10 09:50 UTC by kamilmielnik

Closes https://github.com/metabase/metabase/issues/[issue_number]

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2024-07-10 13:00 UTC, kamilmielnik commented on frontend/src/metabase/hooks/use-is-truncated.ts
> -  tolerance = 0,
`tolerance` was never used

2024-07-11 13:19 UTC, ranquild requested changes
Very complex fix. Causes DOM read/write loops. There should be another way of doing this.

2024-07-12 09:39 UTC, kamilmielnik commented
> Very complex fix. Causes DOM read/write loops. There should be another way of doing this.

I see 4 options:
1. KISS - just always show tooltips, even when text is not truncated
2. What this PR does.
3. Use Canvas to measure text (arguably more complex than what's in this PR right now - especially when `line-clamp > 1`). Something like:
    - https://github.com/Igfig/react-use-text-measurer
    - https://github.com/fabiospampinato/fast-string-truncated-width
    - https://github.com/qq15725/modern-text
4. Use programmatic text truncation instead of CSS. Something like:
    - https://github.com/pablosichert/react-truncate
    - https://github.com/ShinyChang/react-text-truncate
    - https://github.com/Irene-24/react-truncatable

@ranquild WDYT?

2024-07-15 13:15 UTC, ranquild commented
@kamilmielnik can we add 1-2px to the original logic and accept that it would show tooltips in some edge cases?

2024-07-15 13:20 UTC, kamilmielnik commented
> @kamilmielnik can we add 1-2px to the original logic and accept that it would show tooltips in some edge cases?

@ranquild Adding 1px would mean we'd always show tooltips, not only in edge cases. So it's [option (1)](https://github.com/metabase/metabase/pull/45347#issuecomment-2225204872). Would this be acceptable?

2024-07-16 12:32 UTC, kamilmielnik commented
Closing in favor of #45625

2024-07-16 12:32 UTC, closed without merging