Floating filter labels
metabase/metabase pull request #4543
Opened 2017-03-18 01:59 UTC by salsakran

Fixed #4328

2017-03-18 18:34 UTC, attekei commented
Will fix #2963 as well. Created based on this design by @mazameli:

<img width="1001" alt="screen shot 2017-03-18 at 11 05 03" src="https://cloud.githubusercontent.com/assets/6034928/24074708/fca3c2b0-0bca-11e7-832b-eba9b624bdcd.png">

My thoughts:

- I haven't added field type icons next to field names yet, but currently I'm in favour of adding them. They reduce ambiguity about the field type and thus make it more clear what happens after you click a field.

- Full screen has had its own UI elements for showing active filters, but in this PR it uses the same filter field UI element as other parts of dashboard. It feels pretty big and bold in the full-screen mode, maybe we should keep using the same element but apply some extra styling when in full-screen mode?

- For simple text fields (when editing value of an ID filter, when editing the name of a filter) I'm not totally confident is it clear enough that the only way to save a value is to press Return. Losing the focus of a text field discards its value.

- Is implementing [an animation like this](https://codepen.io/simoberny/pen/gpddYQ) worth the effort?

2017-03-20 16:40 UTC, mazameli commented
> For simple text fields (when editing value of an ID filter, when editing the name of a filter) I'm not totally confident is it clear enough that the only way to save a value is to press Return. Losing the focus of a text field discards its value.

I agree that we can improve this. Atte and I spoke and thought we could implement a little hint icon like this:

![screen shot 2017-03-20 at 9 39 22 am](https://cloud.githubusercontent.com/assets/2223916/24110633/2b2148ba-0d51-11e7-8ae1-5cdb02da7cd3.png)

Ideally the icon itself could be a button that would commit the input, but that's an enhancement.

2017-03-20 17:38 UTC, tlrobinson commented
BTW in #4335 it was suggested that parameters should commit on blur as well. Did we come to a conclusion on that?

2017-03-20 23:29 UTC, mazameli commented
> BTW in #4335 it was suggested that parameters should commit on blur as well. Did we come to a conclusion on that?

A few considerations: 
1. we're adding in a little enter icon to help communicate how to commit the input, which should hopefully make the need to hit return clearer
2. Commit-on-blur is potentially dangerous if your dashboard cards take a long time to load. (The latter isn't a consideration for SQL params; they don't auto-reload on commit.) 
3. The best argument I've heard is that commit-on-blur would make tabbing between several filter input boxes feasible, but this is possibly edge-casey? (i.e. how often are users going to have several input box filters in a row?)
4. I don't think commit-on-blur feels quite right from an interaction perspective. That's not how search boxes anywhere else in the world behave, and these input filters are sort of search boxes in that they don't live-update.

So, I thought I was in favor of commit-on-blur, but I think I'm against it again/still.

2017-03-21 01:18 UTC, attekei commented
I added the icons indicating filter type (time/location/id/category) as in the original design. Next I will finish the animations and make sure that the filter widgets look sane also in the template tag editor of SQL query builder.

I will leave the commit-on-blur logic as it is.

2017-03-21 18:48 UTC, tlrobinson requested changes
Looking good. The only issues I've noticed (besides code style) are

1. input has a white background. I think we can make the TextWidget <input> background transparent

2. The default picker in SQL variables pane is missing a border and background. Try matching the other elements on the pane (`AdminSelect p1 text-bold text-grey-4 bordered border-med rounded` or similar)

2017-03-21 18:48 UTC, tlrobinson commented on frontend/src/metabase/dashboard/components/parameters/ParameterValueWidget.jsx
> +    constructor(props) {
FYI I just discovered you can replace the whole constructor with `state = { isFocused: false }` if all you're doing is setting initial state.

2017-03-21 18:48 UTC, tlrobinson commented on frontend/src/metabase/dashboard/components/parameters/ParameterValueWidget.jsx
> +        const self = this;
`self = this` tends to be unnecessary with in ES6 with arrow functions.

2017-03-21 18:48 UTC, tlrobinson commented on frontend/src/metabase/dashboard/components/parameters/ParameterValueWidget.jsx
> +            if (parentFocusChanged) parentFocusChanged(isFocused);
Prefer always including brackets and newlines even if it's a little longer.

2017-03-21 18:48 UTC, tlrobinson commented on frontend/src/metabase/dashboard/components/Dashboard.jsx
> +                    className=""
Should be able to just remove this.

2017-03-21 18:48 UTC, tlrobinson commented on frontend/src/metabase/dashboard/components/parameters/widgets/TextWidget.jsx
>              <input
I think we could make this `<input>` have a transparent background so it looks better in full screen etc

2017-03-21 18:48 UTC, tlrobinson commented on frontend/src/metabase/dashboard/containers/ParameterWidget.jsx
> +        const self = this;
No need for `self = this`

2017-03-21 18:48 UTC, tlrobinson commented on frontend/src/metabase/dashboard/containers/ParameterWidget.jsx
> +        const containerClassName = cx(S.container);
This is sort of redundant. I'd just inline `S.container` below.

2017-03-21 19:37 UTC, attekei commented
Thanks @tlrobinson! I just noticed that clicking the removal button of default picker in SQL variables pane causes an error, will fix that too.

2017-03-21 21:25 UTC, tlrobinson approved these changes

2017-03-21 21:36 UTC, merged