Add SDK storybook PoC
metabase/metabase pull request #45512
Opened 2024-07-12 21:08 UTC by deniskaber

Relates to https://www.notion.so/metabase/Embedding-SDK-e2e-tests-c3c652dd4c5b452a9a243266ae434bb3

### Description

This adds storybook and e2e tests for Embedding SDK.
Storybook acts as an example host app to show Embedding SDK components.
Then we run e2e tests to open storybook story and automate a user flow.

### How to verify

Storybook:
- `yarn dev-ee` to run Metabase.
- Go to `http://localhost:3000/admin/settings/authentication/jwt` and setup JWT secret to be "0000000000000000000000000000000000000000000000000000000000000000"
- So to `http://localhost:3000/admin/settings/embedding-in-other-applications/full-app` and set AUTHORIZED ORIGINS to "`*`"
- `yarn storybook-embedding-sdk`
- Open `http://localhost:6006/?path=/story/embeddingsdk-staticdashboard--default`

e2e tests:
Local:
- Run storybook from the previous step
- Run tests locally with `yarn test-cypress-open-sdk`
- `e2e/test/scenarios/embedding-sdk/static-dashboard.cy.spec.js` scenario should pass

<img width="1150" alt="Screenshot 2024-07-19 at 20 09 55" src="https://github.com/user-attachments/assets/59944fb9-4c28-442c-be23-b9334835816a">

CI:
`e2e-tests-embedding-sdk-ee` CI job should pass

### Demo

<img width="1150" alt="Screenshot 2024-07-13 at 00 06 41" src="https://github.com/user-attachments/assets/543ac714-c6bf-4036-8c61-294ad7891fbf">

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2024-07-19 18:44 UTC, heypoom approved these changes
Nice work! Implementation looks good to me.

2024-07-22 16:28 UTC, nemanjaglumac requested changes
Left a lot of inline comments, but I assume this might be faster resolved in a quick call.

2024-07-24 06:36 UTC, nemanjaglumac commented on .github/actions/run-embedding-sdk-storybook/action.yml
> +name: Run Embedding SDK Storybook
NIt: I would rename this workflow (both its name and file on disk) to `prepare-embedding-sdk-environment`.

1. we're not actually running tests in this action
2. we might find some solution other than the Storybook in the future

2024-07-24 06:37 UTC, nemanjaglumac commented on .github/actions/run-embedding-sdk-storybook/action.yml
> +        m2-cache-key: "cljs"
What was the issue without prepare-frontend and prepare-backend in here?

2024-07-24 06:45 UTC, nemanjaglumac commented on e2e/test/scenarios/embedding-sdk/static-dashboard.cy.spec.js
> +          window.METABASE_INSTANCE_URL = "http://localhost:4000";
Please do not hard code Cypress url.

```suggestion
          window.METABASE_INSTANCE_URL = Cypress.config().baseUrl;
```

2024-07-24 06:46 UTC, nemanjaglumac commented on e2e/test/scenarios/embedding-sdk/static-dashboard.cy.spec.js
> +        cy.findByText("Text card").should("be.visible"); // text card content
If card's test-id is available, can we please scope this to that?
I'm afraid simply finding the text "Orders" will backfire in the future.

2024-07-24 06:50 UTC, nemanjaglumac commented on enterprise/frontend/src/embedding-sdk/test/common-stories-utils.tsx
> +        last_name: DEFAULT_SDK_USER.lastName,
Two questions:

1. Couldn't we reuse the `normal` user from `cypress_data.js`?
2. What happens if first_name and/or last_name are not present? They are NOT the requirement in the main application - only email is.

2024-07-24 06:54 UTC, nemanjaglumac approved these changes
Added a few more comments.
Please address https://github.com/metabase/metabase/pull/45512/files#r1689230096 before merging.

Great work! 🚀

2024-07-24 13:58 UTC, nemanjaglumac commented on .github/actions/run-embedding-sdk-storybook/action.yml
> +        m2-cache-key: "cljs"
I understand that part, but we already prepare both frontend and backend in this job.

2024-07-24 16:16 UTC, merged