commit filter on enter [WIP]
metabase/metabase pull request #4574
Opened 2017-03-21 22:45 UTC by kdoh

addresses #4510

2017-03-21 23:05 UTC, attekei commented on frontend/src/metabase/query_builder/components/filters/FilterPopover.jsx
> +    componentWillMount() {
I had to add `this.commitOnEnter = this.commitOnEnter.bind(this);` here to make this work

2017-03-22 00:05 UTC, attekei commented
Linked to #4577. Currently it might be an undesired action that pressing Return always commits if there are multiple input fields for multiple filter values. If we decide to go with the comma separation, then there's no problem.

2017-03-23 00:12 UTC, tlrobinson approved these changes
Seems reasonable, as long as we're sure it won't conflict with anything else in the filter popover. I don't think it does currently.

2017-03-23 00:14 UTC, tlrobinson requested changes

2017-03-23 00:14 UTC, tlrobinson commented on frontend/src/metabase/query_builder/components/filters/FilterPopover.jsx
> +        window.addEventListener('keydown', this.commitOnEnter.bind(this));
Need to remove `.bind(this)` otherwise you're a passing different versions of `commitOnEnter` to `removeEventListener` and it won't be removed.

2017-03-23 00:14 UTC, attekei commented
Agreed! You could still merge master and double-check that this plays well with the latest multiple value number/string filter implementation.

2017-03-23 00:14 UTC, tlrobinson commented on frontend/src/metabase/query_builder/components/filters/FilterPopover.jsx
> +    commitOnEnter(event: Object) {
And change this to `commitOnEnter = (event: Object) => {`

2017-03-23 18:22 UTC, tlrobinson approved these changes

2017-03-23 18:29 UTC, merged

2017-03-30 23:28 UTC, cyberhorse commented
Thank you @kdoh :)

2017-03-30 23:33 UTC, kdoh commented
@cyberhorse 👍