fix(admin/performance): Fix bug where leaving the hour at its default value (8am) would result in a cron expression with a wildcard for the hour
metabase/metabase pull request #45915
Opened 2024-07-22 13:01 UTC by rafpaf

> [!IMPORTANT]
> For those employed by Metabase: if you are merging into master, please add either a `backport` or a `no-backport` label to this PR. You will not be able to merge until you do this step. Refer to the section [Do I need to backport this PR?](https://www.notion.so/metabase/Metabase-Branching-Strategy-6eb577d5f61142aa960a626d6bbdfeb3?pvs=4#89f80d6f17714a0198aeb66c0efd1b71) in the Metabase Branching Strategy document for more details. If you're not employed by Metabase, this section does not apply to you, and the label will be taken care of by your reviewer.

> **Warning**
>
> If that is your first contribution to Metabase, please sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) (unless it's a tiny documentation change). Also, if you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

Closes https://github.com/metabase/metabase/issues/[issue_number]

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2024-07-22 13:01 UTC, rafpaf commented
* **#45915** <a href="https://app.graphite.dev/github/pr/metabase/metabase/45915?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rafpaf and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-22 18:25 UTC, iethree requested changes
Looks good, but we shouldn't merge this without the e2e tests in this branch. It's ok to take some more time to package it up nicely so we can be sure it stays fixed.

2024-07-24 02:47 UTC, rafpaf commented on e2e/test/scenarios/admin/performance/performance.cy.spec.ts
I've moved these helper functions to a separate file and changed them a bit, so these tests need to change a bit

2024-07-24 12:49 UTC, rafpaf commented on e2e/test/scenarios/admin/performance/schedule.cy.spec.ts
These are the main e2e tests added in this Pr

2024-07-24 12:52 UTC, rafpaf commented on e2e/test/scenarios/dashboard/dashboard.cy.spec.js
A small refactoring of the sidebar code to facilitate testing required a change to this file

2024-07-24 12:53 UTC, rafpaf commented on frontend/src/metabase/components/Schedule/components.tsx
I moved this function here to be next to the other `Select*` components

2024-07-25 13:00 UTC, rafpaf commented on e2e/support/config.js
> +};
This fix was added by @uladzimirdev due to Cypress build issue

2024-07-25 13:01 UTC, rafpaf commented on e2e/test/scenarios/admin/performance/schedule.cy.spec.ts
> +        }
We can't use ts-pattern here because this needs to get backported :-(

2024-07-25 20:08 UTC, iethree approved these changes
Looks good! thanks for adding the tests 💪 

take a look at the note re unnecessary test cases.

2024-07-25 20:08 UTC, iethree commented on e2e/test/scenarios/admin/performance/schedule.cy.spec.ts
> +  ];
I'll let you be the judge but keep in mind that with e2e tests:
- they take a long time
- so we try to use them sparingly to cover complex UI cases
- that can't easily be covered by much faster unit tests

You know this code better than I do, but it looks to me that we're exercising most of this functionality multiple times, and some of the more granular testing can be handled in unit tests. (e.g. it's probably not worth it to have a test for every day of the week, probably a single hourly/daily/weekly/monthly test is enough for e2e, and you can drill down in more detail in unit tests)

2024-07-25 20:37 UTC, merged