🚧  [WIP] Update the Query Editor Button
metabase/metabase pull request #46097
Opened 2024-07-24 20:38 UTC by iethree

Closes https://github.com/metabase/metabase/issues/46096

lotsa tests gonna break 😬 

### Description

Before | After
---|---
![Screen Shot 2024-07-24 at 2 37 33 PM](https://github.com/user-attachments/assets/6e56c540-d492-4389-8ac6-1179a0631a3c) | ![Screen Shot 2024-07-24 at 2 36 57 PM](https://github.com/user-attachments/assets/bd36e179-9aa7-4e48-a33b-eb304057513e)

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

2024-07-29 14:16 UTC, iethree commented on frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionNotebookButton/QuestionNotebookButton.tsx
this is the only non-test file changed

2024-07-29 15:46 UTC, sloansparger approved these changes

2024-07-29 15:46 UTC, sloansparger commented on frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionNotebookButton/QuestionNotebookButton.tsx
> +      // leftIcon={<Icon size={14} name="notebook" />}
not sure if this comment is needed

2024-07-29 21:42 UTC, mazameli requested changes
1. I'd love it if these buttons could all look the same. The Show Editor button's height and borders are currently different.

<img width="330" alt="image" src="https://github.com/user-attachments/assets/1724364e-d03b-45a0-ba36-f26ec87e0518">

2. I don't love that the Show Visualization button is present from a totally new GUI question, and would prefer that it only appears for saved questions, or for cases where you've arrived in the editor via the Show Editor button. If that's unavoidable or costlier than we're willing to spend right now, I think I can live with it.

2024-07-29 21:47 UTC, iethree commented
> 1. I'd love it if these buttons could all look the same. The Show Editor button's height and borders are currently different.

I have now rebased this branch off of master to pull in recent changes to those buttons, they should now be perfectly identical in this branch as well.

![Screen Shot 2024-07-29 at 3 45 35 PM](https://github.com/user-attachments/assets/6f475176-9516-4409-a799-c4136ae488a8)

> 2. I don't love that the Show Visualization button is present from a totally new GUI question, and would prefer that it only appears for saved questions, or for cases where you've arrived in the editor via the Show Editor button. If that's unavoidable or costlier than we're willing to spend right now, I think I can live with it.

I will make this change in another branch since it's essentially a new feature: context-sensitive notebook button, and not just a simple visual change.

2024-08-02 20:22 UTC, mazameli requested changes
I'm on `771855b792b2e6ee178a822dc146758ec22706ae` and I'm not seeing the behavior from https://github.com/metabase/metabase/pull/46350 incorporated in this branch. 

https://www.loom.com/share/fe34aa25597f455bb1d061d45f190541

2024-08-02 21:30 UTC, mazameli approved these changes
Works now 🤷🏼‍♂️

2024-08-02 22:18 UTC, merged