Cleanup routes
metabase/metabase pull request #4623
Opened 2017-03-27 18:30 UTC by tlrobinson

@metabase/core-developers Any objections to this? I think the URL is the only user-facing place we use the "card" terminology. This also matches the public/embed URLs.

* Move `/q` to `/question`
* Move `/card/:cardId` to `/question/:cardId`
* Move `/dash/:dashId` to `/dashboard/:dashId`

Resolves #1157

2017-03-27 18:37 UTC, salsakran approved these changes
Works for me. 

This will break old pulses and bookmarks, etc,  so this should going in master/a new major release (0.24) vs 0.23.1 makes sense 👍

2017-03-27 18:37 UTC, salsakran commented on frontend/src/metabase/lib/card.js
> +// TODO: move to redux
Do we actually want to do this? =)

2017-03-27 18:37 UTC, salsakran commented on frontend/src/metabase/query_builder/actions.js
> +
stray newline?

2017-03-27 18:45 UTC, tlrobinson commented
There are redirects for the old style URLs so it won't break old URLs. But regardless I think this should go in 0.24.

Also, that reminds me I need to change the Pulses URL formatting.

2017-03-27 18:45 UTC, tlrobinson commented
@salsakran @camsaul Does the backend emit any other frontend URLs?

2017-03-27 20:00 UTC, camsaul commented
@tlrobinson you should update `src/metabase/util/urls.clj` because there's a few utility functions there that need to be tweaked for this change

2017-04-03 21:37 UTC, camsaul requested changes
update `src/metabase/util/urls.clj` because there's a few utility functions there that need to be tweaked for this change

2017-04-04 16:02 UTC, kdoh approved these changes

2017-04-05 19:14 UTC, tlrobinson commented
Updated the backend.

2017-04-05 19:29 UTC, camsaul commented on src/metabase/util/urls.clj
>       (dashboard-url 10) -> \"http://localhost:3000/dash/10\""
mind updating the docstring too? :D

2017-04-05 19:30 UTC, camsaul commented on src/metabase/util/urls.clj
>       (card-url 10) -> \"http://localhost:3000/card/10\""
docstring

2017-04-05 19:32 UTC, camsaul requested changes
looks like there's a couple docstrings in the backend that weren't updated

after those are fixed this LGTM

2017-04-05 19:32 UTC, tlrobinson commented on src/metabase/util/urls.clj
>       (card-url 10) -> \"http://localhost:3000/card/10\""
done

2017-04-05 19:32 UTC, tlrobinson commented on src/metabase/util/urls.clj
>       (dashboard-url 10) -> \"http://localhost:3000/dash/10\""
done

2017-04-05 19:33 UTC, camsaul reviewed
great LGTM

2017-04-05 19:33 UTC, camsaul approved these changes
great LGTM

2017-04-05 23:08 UTC, merged