FE - Cover Unit of Time in `getParameterColumns` with tests
metabase/metabase pull request #46529
Opened 2024-08-06 14:30 UTC by kamilmielnik

Closes #46526

### Description

Part of testing plan: #46520

2024-08-07 14:36 UTC, kamilmielnik commented on frontend/src/metabase-lib/v1/parameters/utils/targets.unit.spec.ts
> +    describe("date parameter", () => {
Just 1 sanity test for any other parameter than unit of time.
Tests for other parameters will come when this behavior changes.

2024-08-07 14:42 UTC, kamilmielnik commented on frontend/src/metabase-lib/v1/parameters/utils/targets.unit.spec.ts
> +  }
It took me a while to figure out why one of the model tests was failing, so I'm leaving this here.
It can cause false positives too.

2024-08-07 22:11 UTC, ranquild requested changes
We should not use raw MBQL and instead generate queries with MBQL lib. This is important - we're changing MBQL in some cases.

2024-08-08 11:08 UTC, kamilmielnik commented
> We should not use raw MBQL and instead generate queries with MBQL lib. This is important - we're changing MBQL in some cases.

55d631ad16644434b2fe4ff8ec75eceb3d0d1a1e

2024-08-08 12:59 UTC, ranquild approved these changes
One nit

2024-08-08 13:05 UTC, kamilmielnik commented on frontend/src/metabase-lib/v1/parameters/utils/targets.unit.spec.ts
> +  const card = createSavedStructuredCard({
fe853a1673f28d8abe932533199f05005dd1a980

2024-08-08 13:25 UTC, merged