handle display of 0 in the number picker
metabase/metabase pull request #4689
Opened 2017-04-04 17:59 UTC by kdoh

fixes #4373 

Turns out `String(0 || "")`(which is what we were passing to the textfield to display the selected value) will always return an empty string which is why even though a value was selected it was showing up blank. This is due to javascript being `neat and cool`. This is a "dumb" fix. Dunno if @attekei or @tlrobinson have a more elegant way to handle the checking here.

2017-04-04 18:04 UTC, attekei commented
The `isEmpty` of Ramda/Lodash treat this scenario correctly but Underscore.js which we are currently using doesn't, so I don't have a direct answer.

Why are we showing empty text instead of explicitly indicating that something is wrong with the value?

2017-04-04 18:23 UTC, kdoh commented
@attekei I think the original intent was to return an empty string in cases where there is no value which happens when you're creating a new filter since we reuse this component for new and existing filters.

2017-04-05 04:37 UTC, tlrobinson requested changes

2017-04-05 04:37 UTC, tlrobinson commented on frontend/src/metabase/query_builder/components/filters/pickers/NumberPicker.jsx
> +                return String(v || "")}
brace should go on the next line.

also I'd probably do 

```
if (typeof v === "number") {
  return String(v);
} else {
  return String(v || ");
}
```

2017-04-05 16:44 UTC, attekei approved these changes

2017-04-07 16:36 UTC, merged