Parameters enhancements [WIP]
metabase/metabase pull request #4715
Opened 2017-04-07 05:27 UTC by tlrobinson

Resolves #4655
Resolves #4663
Resolves #4653

2017-04-07 18:58 UTC, salsakran commented
👍  on moving param code out of the dashboard components

2017-04-07 23:07 UTC, tlrobinson commented
@salsakran @camsaul thoughts on the remaining TODO above? It will need a little backend work to return `param_values` like we do for dashboards.

2017-04-07 23:09 UTC, salsakran commented
I think it's important that widgets work the same regardless of where they are. 

I also think that making end users manually enter strings for parameters is completely un-zen. Any situation where FieldValues are available we should use them.

2017-04-07 23:10 UTC, tlrobinson commented
Ok, @camsaul can you handle that on the backend?

There's a little frontend work as well but I can do that once the backend is done.

2017-04-07 23:39 UTC, camsaul commented
yeah, i'll take a look at it 

Right now trying to get Druid 0.9.2 set up for CI is giving me a huge headache so it will be a while.

2017-04-10 17:57 UTC, attekei requested changes
After working for a while with the backend I realized that the parts of frontend involving heavy business logic should ideally have comments and/or examples demonstrating how they work. The comments above are on methods I found most obscure to me.

SQL parameters in query builder seem to be broken in the current state of this PR.

2017-04-10 17:57 UTC, attekei commented on frontend/src/metabase/dashboard/selectors.js
> +export const getParameters = createSelector(
Would be nice to have a comment about the behavior

2017-04-10 17:57 UTC, attekei commented on frontend/src/metabase/lib/query/field.js
> +export function getFieldValues(field: ?Field): any[] {
Would be nice to have a comment about the behavior, not only a link to GitHub issue

2017-04-10 17:57 UTC, attekei commented on frontend/src/metabase/meta/Parameter.js
> +export function getParameterTargetFieldId(target: ?ParameterTarget, datasetQuery: DatasetQuery): ?FieldId {
Again, rather hard-to-read logic so short comment explaining the behavior would be nice

2017-04-10 21:59 UTC, attekei commented
Also typing with Flow would have a really nice self-documenting effect – even if you have to use many `// $FlowFixMe` annotations  that isn't IMHO that big offence.

2017-04-11 18:19 UTC, tlrobinson commented
In general I add Flow types to new files and smaller existing files when modifying them, but big ones can take a lot of time so I don't always do them. I try to avoid `$FlowFixMe` but I suppose it's not as bad as using `any` types so maybe I'll be more aggressive about adding Flow types.

2017-04-11 23:50 UTC, tlrobinson commented
@camsaul Are you able to do the backend portion of this soon? @attekei has a branch he'd like to merge with this one sooner rather than later.

2017-04-11 23:52 UTC, camsaul commented
@tlrobinson what specific endpoint(s) do you need

2017-04-12 00:01 UTC, tlrobinson commented
@camsaul embed/public link card API endpoints, like we have for `/api/public/dashboard/:uuid`. So `/api/public/card/:uuid` and `/api/embed/card/:token` I think.

2017-04-12 00:02 UTC, camsaul commented
ooook

2017-04-12 00:45 UTC, camsaul commented
@tlrobinson do you know where should these params come from? For dashboards we just look at the values of `:parameter_mappings` for each DashboardCard, but Cards don't have anything like that

2017-04-12 17:21 UTC, tlrobinson commented
There's a function called `template-tag-parameters` and `add-implicit-card-parameters` in `metabase/api/embed.clj` that generates the parameters from the SQL `template_tags`. Currently only used on `GET /api/embed/card/:id` I believe.

2017-04-12 17:32 UTC, camsaul commented
@tlrobinson there is no `GET /api/embed/card/:id` endpoint. `GET /api/embed/card/:token` is already calling `add-implict-card-parameters`, so I'm guessing you only need that added to `/api/public/card/:uuid`, right?

2017-04-12 17:41 UTC, tlrobinson commented
@camsaul I need `param_values` like we have for dashboards.

2017-04-12 18:48 UTC, camsaul commented
ok @tlrobinson changes are done let me know if they work for you

2017-04-15 01:05 UTC, tlrobinson commented
I think this is ready, but might be a good candidate for an E2E test

2017-04-15 01:06 UTC, salsakran commented
tests would be nifty.

2017-04-18 03:24 UTC, salsakran commented
can we un-muck the section that papers over #3417 as part of this?

2017-04-18 03:35 UTC, salsakran approved these changes
Overall, looks reasonable. The parameters code in general is pretty dense and hard to follow, but this doesn't regress in any way.

Some frontend tests for the parameters code would be ideal, but not a blocker.

2017-04-18 21:45 UTC, attekei approved these changes

2017-04-26 16:17 UTC, tlrobinson commented
@attekei I got all the E2E tests passing except your 2 dashboard tests. I've disabled them for now so we can get stats and metabase-head building/updating again (its been 2 weeks). Feel free to fix those and re-enable them at your convenience.

2017-04-26 16:17 UTC, merged