🤖 backported "Improve Clear cache button text and question refresh button tooltip"
metabase/metabase pull request #47321
Opened 2024-08-27 18:17 UTC by github-automation-metabase

#46791
  > [!IMPORTANT]
  > Manual conflict resolution is required.
  Checkout the branch and run `./backport.sh` script. Force push your changes after cherry-picking.

2024-08-27 21:53 UTC, rafpaf commented on enterprise/frontend/src/metabase-enterprise/caching/components/InvalidateNowButton.tsx
> +  }, [targetModel]);
ts-pattern isn't available on v50 :-)

2024-09-10 19:30 UTC, iethree requested changes

2024-09-10 19:30 UTC, iethree commented on yarn.lock
I don't think this lockfile change should be in the backport if we're not modifying the package.json

2024-09-10 20:08 UTC, iethree approved these changes

2024-09-11 12:59 UTC, merged