Getting Started Guide fixes
metabase/metabase pull request #4733
Opened 2017-04-08 00:39 UTC by tlrobinson

* Fix metrics and misc other logic in GSG frontend #4635
* Fix incorrect API validation
* Preserve whitespace in GSG content. Resolves #3943

2017-04-08 00:43 UTC, salsakran requested changes

2017-04-08 00:43 UTC, salsakran commented on src/metabase/api/dashboard.clj
> +   caveats                 (s/maybe s/Str)
Can we have a test for this?

2017-04-08 00:43 UTC, salsakran commented on frontend/src/metabase/reference/containers/ReferenceGettingStartedGuide.jsx
> +                            { Object.keys(metrics).length > 0  && (
Is there anyway to catch this sort of stuff?  Seems like a basic type error.

2017-04-10 16:54 UTC, tlrobinson commented on frontend/src/metabase/reference/containers/ReferenceGettingStartedGuide.jsx
> +                            { Object.keys(metrics).length > 0  && (
Flow would catch it. I've been adding annotations for most new code and as I come across things, but it's a fair amount of work.

2017-04-10 17:58 UTC, kdoh commented on frontend/src/metabase/reference/containers/ReferenceGettingStartedGuide.jsx
> +                                    { Object.keys(segments).length > 0 ? 'Segments and tables' : 'Tables' }
Can we use the same `has` logic check here?

2017-04-10 22:41 UTC, tlrobinson commented on frontend/src/metabase/reference/containers/ReferenceGettingStartedGuide.jsx
> +                                    { Object.keys(segments).length > 0 ? 'Segments and tables' : 'Tables' }
`has` looks like it's different: `export const has = (entity) => entity && entity.length > 0;`

2017-04-12 17:16 UTC, tlrobinson commented on src/metabase/api/dashboard.clj
> +   caveats                 (s/maybe s/Str)
Done

2017-04-12 18:02 UTC, kdoh approved these changes

2017-04-13 19:34 UTC, merged