Add starttls smtp authentication
metabase/metabase pull request #4793
Opened 2017-04-14 23:01 UTC by thearthur

for https://github.com/metabase/metabase/issues/4272

Adds the starttls authentication option, and more importantly, attempts to detect when to use it.
If the initial connection to an outgoing mail server fails, then it will try each of the available security settings in order of security. The current preference order is: TLS, STARTTLS,SSL. It will not silently downgrade to a plaintext connection.

2017-04-14 23:30 UTC, salsakran commented on src/metabase/email.clj
> +  (loop [[security-type & more-to-try] email-security-order]
Can we add a comment to this function describing our approach here?

2017-04-15 00:07 UTC, thearthur commented on src/metabase/email.clj
> +  (loop [[security-type & more-to-try] email-security-order]
done

2017-04-15 00:11 UTC, thearthur commented
Resolves #4272

2017-04-15 00:21 UTC, tlrobinson commented
@thearthur I think the "resolves" need to go in the top description

2017-04-15 01:25 UTC, salsakran requested changes
Other than whitespace nitpicking, looks good to me! I don't have enough smtp accounts lying around to properly test it however.

2017-04-15 01:39 UTC, merged