bump snowflake for java 17+
metabase/metabase pull request #47997
Opened 2024-09-18 16:27 UTC by dpsutton

bump snowflake

2024-09-19 16:04 UTC, camsaul commented on modules/drivers/snowflake/deps.edn
> + {net.snowflake/snowflake-jdbc {:mvn/version "3.17.0"}}}
[They say 3.19 is out now](https://docs.snowflake.com/en/release-notes/clients-drivers/jdbc-2024), any reason not to bump to latest?

```suggestion
 {net.snowflake/snowflake-jdbc {:mvn/version "3.19.0"}}}
```

2024-09-19 16:05 UTC, camsaul approved these changes
Omg finally lol. LFGGGGG

2024-10-03 17:44 UTC, paoliniluis commented
You can't even add the db...
![image](https://github.com/user-attachments/assets/bb9eece9-2ff7-4e79-b5d1-557a6386a5f1)

2024-10-03 17:59 UTC, paoliniluis requested changes
I know this is just a driver bump, but we did it to test java 17+ and snowflake driver, which doesn't work. We need to think about "--add-opens java.base/java.nio=ALL-UNNAMED" and evaluate the consequences
https://community.snowflake.com/s/article/JDBC-Driver-Compatibility-Issue-With-JDK-16-and-Later

UPDATE: approving since this is a driver bump

2024-10-04 08:44 UTC, paoliniluis approved these changes

2024-10-17 18:11 UTC, camsaul commented
The changelog seems to suggest that 3.17.0+ supports Java 21 but I guess that might or might not be true

https://docs.snowflake.com/en/release-notes/clients-drivers/jdbc-2024

> Added support for Java version 21.

2024-11-01 15:44 UTC, merged