Remove CLJS_SRC_PATH_DEV from ignored watch dirs
metabase/metabase pull request #48063
Opened 2024-09-23 21:37 UTC by lbrdnk

Shadow cljs live reload is broken. This change makes the page reload always, when the compiled cljs changes.

Before this PR shadow's live reload worked when file was saved. On page reload however the stale compiled cljs was used.

2024-09-24 11:56 UTC, uladzimirdev approved these changes
I'd wait for @bshepherdson to approve this change. Based on my testing, live reload (or hot module replacement) didn't work properly with webpack, but if you can confirm, it would be nice. webpack config is still there.

moreover we've discussed during FE guild live reload and as its broken almost always for cljs files, we wanted to drop it by default

2024-09-24 11:56 UTC, uladzimirdev requested changes
oops

2024-09-24 13:22 UTC, bshepherdson approved these changes
Live reload is working fine for me; I'm not sure what could be different. Maybe I'm just behind master.

The `/invalidate` hack to refresh the CLJS is definitely not working. I'm fine with this change in the meantime, since it's less broken to reload too much than to load stale code.

2024-09-25 06:49 UTC, uladzimirdev approved these changes

2024-09-25 06:50 UTC, merged