Improve display of icons in the 'Saved in' section of question&dashboard sidesheets
metabase/metabase pull request #48313
Opened 2024-10-03 17:59 UTC by rafpaf

> [!IMPORTANT]
> For those employed by Metabase: if you are merging into master, please add either a `backport` or a `no-backport` label to this PR. You will not be able to merge until you do this step. Refer to the section [Do I need to backport this PR?](https://www.notion.so/metabase/Metabase-Branching-Strategy-6eb577d5f61142aa960a626d6bbdfeb3?pvs=4#89f80d6f17714a0198aeb66c0efd1b71) in the Metabase Branching Strategy document for more details. If you're not employed by Metabase, this section does not apply to you, and the label will be taken care of by your reviewer.

> **Warning**
>
> If that is your first contribution to Metabase, please sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) (unless it's a tiny documentation change). Also, if you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

Closes https://github.com/metabase/metabase/issues/[issue_number]

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2024-10-03 19:51 UTC, iethree requested changes
looks good overall
1) can you remove the unused code? it's confusing to have it in this branch
2) please add tests for the authority icons in QuestionDetails and DashboardDetails.

2024-10-03 19:51 UTC, iethree commented on enterprise/frontend/src/metabase-enterprise/collections/index.ts
> +          title: t`Make official`,
I just noticed we have inconsistent Official/official casing here

![Screen Shot 2024-10-03 at 1 40 44 PM](https://github.com/user-attachments/assets/d9208597-bb38-40e1-8681-6f6e44b03de3) ![Screen Shot 2024-10-03 at 1 40 38 PM](https://github.com/user-attachments/assets/63a79180-8303-42fe-a771-e583632589a4)

2024-10-03 19:51 UTC, iethree commented on enterprise/frontend/src/metabase-enterprise/collections/components/CollectionAuthorityLevelIcon.unit.spec.tsx
> +      return screen.getByLabelText("verified_collection icon");
i think this depends on https://github.com/metabase/metabase/pull/48082

2024-10-03 19:51 UTC, iethree commented on enterprise/frontend/src/metabase-enterprise/collections/components/CollectionAuthorityLevelDisplay.tsx
I think this component is not used in this PR, right? but will be used by https://github.com/metabase/metabase/pull/48082 ?

2024-10-07 19:33 UTC, iethree approved these changes

2024-10-07 19:33 UTC, iethree commented on frontend/src/metabase/plugins/index.ts
> +  route?: Route;
I don't think this is supposed to be here?

2024-10-08 18:28 UTC, vbenedetti requested changes
Good to go with ONE change:
the reverse action of making the collection official should read
`Remove official status` instead of _badge_. 
Slack [thread](https://metaboat.slack.com/archives/C02H619CJ8K/p1728411554361369)

2024-10-08 23:42 UTC, merged