docs - mention SDK and some other embedding updates
metabase/metabase pull request #48530
Opened 2024-10-09 17:49 UTC by jeff-bruemmer

- Mention of SDK, link to existing docs.
- Updates static embedding parameters.
- Updates screenshots to reflect UI updates.

2024-10-17 11:47 UTC, albertoperdomo requested changes
I left a few comments for what stood out the most.
In addition, I am surprised we go with JWT and Pro for the Quickstart. This makes it less accessible for people to start with the SDK.

We made it possible to use the SDK with API keys so anyone could try it out w/o having to get a license, an EE binary or have to implement JWT. I think having both makes sense. Or having API keys be the starting point and then JWT be the next, more advanced step.

2024-10-20 09:26 UTC, albertoperdomo commented on docs/embedding/sdk/introduction.md
> +- Message the team on Slack. If you don't have a Slack channel set up, please reach out to us at [sdk-feedback@metabase.com](mailto:sdk-feedback@metabase.com).
Actually, let's leave it for now.

2024-10-21 13:09 UTC, jeff-bruemmer commented
> I left a few comments for what stood out the most. In addition, I am surprised we go with JWT and Pro for the Quickstart. This makes it less accessible for people to start with the SDK.
> 
> We made it possible to use the SDK with API keys so anyone could try it out w/o having to get a license, an EE binary or have to implement JWT. I think having both makes sense. Or having API keys be the starting point and then JWT be the next, more advanced step.

Mentioned on Slack, but commenting here for posterity; I haven't really started documenting the SDK yet; this is essentially a port of the existing docs. And there are some key pieces still in flux (e.g., ModifyQuestion) to handle.

I did the JWT quick start to take advantage of the sample app, and the setup is actually pretty easy, but we'll do an API keys quickstart too so people can try without a license. As we discussed a while back, we may want to pluck out that JWT setup later on so that it can be used in both interactive and SDK quickstarts, but I don't want to start optimizing until we have everything documented first.

2024-10-21 13:10 UTC, jeff-bruemmer commented on docs/embedding/sdk/dashboards.md
> +You can embed an interactive or static dashboard.
Just noting that it's likely we'll remove the "editable" question to simplify things.

2024-10-21 15:47 UTC, albertoperdomo commented on docs/embedding/sdk/development.md
> +title: "Embedded analytics SDK - development
I would keep this only on GH.

2024-10-23 16:28 UTC, albertoperdomo approved these changes

2024-10-24 11:11 UTC, jeff-bruemmer commented on docs/embedding/sdk/version.md
> +So, for example, if you're on Metabase version `1.51.0`, you should use the SDK `1.51.0`.
```suggestion
So, for example, if you're on Metabase version `1.51.1`, you should use the SDK `1.51` or higher.
```

2024-10-24 11:12 UTC, jeff-bruemmer commented on docs/embedding/sdk/version.md
> +So, for example, if you're on Metabase version `1.51.1`, you should use the SDK `1.51` or higher.
```suggestion
So, for example, if you're on Metabase version `1.51.1`, you should use the SDK `1.51`.
```

2024-10-24 16:59 UTC, merged