Direct export to excel format
metabase/metabase pull request #4866
Opened 2017-04-25 12:38 UTC by stefano

Implements https://github.com/metabase/metabase/issues/4417

Adds docjure (https://github.com/mjul/docjure) as a dependency to write excel files.

As part of the PR I refactored CSV/JSON exports to reduce code duplication and make it easier to add more export formats in the future.

Question: is the API documentation automatically generated or should I update it manually?

2017-04-25 18:01 UTC, tlrobinson reviewed
Cool thanks for doing this! I'll let @camsaul review the backend more thoroughly but it's looking good.

2017-04-25 18:01 UTC, tlrobinson commented on project.clj
> +                 [dk.ative/docjure "1.11.0"]]                         ; Excel export
Could you put this between `crypto-random` and `environ` so it's alphabetical?

2017-04-25 18:01 UTC, tlrobinson commented on src/metabase/api/card.clj
> +(defendpoint POST "/:card-id/query/:export-format-name"
We could probably shorten `export-format-name` to `export-format`.

2017-04-26 17:53 UTC, camsaul commented on src/metabase/api/card.clj
>    {parameters (s/maybe su/JSONString)}
I would also add a schema here to validate `export-format`

```clojure
{parameters    (s/maybe su/JSONString)
 export-format (s/enum "csv" "json" "xlsx")}
```

2017-04-26 17:54 UTC, camsaul commented on src/metabase/api/dataset.clj
> +(defn ^:private export-to-csv
Just do `defn-` instead of `defn ^:private`

2017-04-26 17:56 UTC, camsaul commented on src/metabase/api/embed.clj
> +  [token export-format-name & query-params]
same thing, probably just shorten this to `export-format` and add a schema validation here

2017-04-26 17:57 UTC, camsaul commented on src/metabase/api/public.clj
> +(api/defendpoint GET "/card/:uuid/query/:export-format-name"
same thing, probably just shorten this to `export-format` and add a schema validation here

2017-04-26 17:57 UTC, camsaul commented on src/metabase/models/query_execution.clj
> -          :json-download
@salsakran do we want to stop differentiating between whether a query is downloaded as CSV/JSON/Excel? Seems like it might be useful for usage stats

2017-04-26 17:58 UTC, camsaul commented on test/metabase/api/card_test.clj
> +  #(> (.length %1) 0)
Just use `count` to get the length of something

```clojure
#(> (count %) 0)
```

2017-04-26 18:00 UTC, camsaul commented
I'm not convinced that a test just to make sure the endpoint returns a string with at least one byte is really a good enough test. Can `docjure` be used to parse the file that comes back and transform it to some sort of raw (perhaps CSV) output that we can verify?

2017-04-26 18:01 UTC, camsaul requested changes
Code cleanup and better tests

2017-04-26 18:13 UTC, salsakran commented on src/metabase/models/query_execution.clj
> -          :json-download
strong 👎 
we should add an excel download option.

2017-04-26 19:00 UTC, stefano commented
> Can docjure be used to parse the file that comes back and transform it to some sort of raw (perhaps CSV) output that we can verify?

I can use docjure to parse back the excel file and check the cell contents, but the tests http client returns the binary excel file as a string, which corrupts the file (because it converts it to utf8 and bytes that can't be converted get corrupted). I need to see if the http client has an option to return a byte stream or a byte array.

2017-04-27 16:14 UTC, stefano commented
@camsaul I've addressed all the code review issues.

2017-05-01 20:56 UTC, camsaul commented
Looks good @stefano. There were a couple of linter issues I needed to fix so I opened PR #4922 based on this one so I can make the last few changes. Once CI passes I'll merge that one in.

2017-05-01 21:23 UTC, merged