Dashboard list filters & favouriting [WIP]
metabase/metabase pull request #4868
Opened 2017-04-25 18:10 UTC by attekei

TODO
- [x] Add filter widget
- [x] Add "Saved by me" filter
- [ ] Add "Favorites" filter (requires the backend to actually work)
- [ ] Add "Recently viewed" filter (how to implement? check if the backend has everything set)
- [ ] Add "Most popular" filter (same as previous)
- [ ] Add actual favouriting (requires backend but I can mock API calls first if needed)

2017-04-25 18:11 UTC, salsakran commented
@attekei for things like `most popular` let's just skip that option for now

2017-04-25 18:12 UTC, attekei commented
roger

2017-04-26 00:23 UTC, attekei commented
Ready for first UI review cycle, please note that: 
- anything isn't persisted yet, so page refresh will remove favorites / archived dashboards (waiting for #4855)
- empty states are missing for "Favorites" + "Saved by me" filters and "Archive". I could recycle the same empty states that are in Questions list with slightly modified texts. Questions archive doesn't currently have an empty state but imho both question and dashboard archives don't have one.
- archive page doesn't have a separate url yet but I will implement it when doing refactoring for current code
- dashboard deletion in the single dashboard editing view has to still be changed to dashboard archival

2017-04-26 21:47 UTC, mazameli commented
Looking good. Here are some things I noticed:

- We never explicitly talked about this, but I didn't necessarily expect dashboards to have their own archive page as opposed to questions — though I think it makes sense now that I see it. Only reason it gave me pause was because archived collections and archived questions go in the same archive bucket.
- I think that the list of dashboards in the archive should look visually like the question archive page. We intentionally made that archive page a bit more stripped down to make it feel more like a recycling bin type view.
- When the archive button appears on hover with a dashboard with a long name, the ellipsified state of the title is still too close to the archive icon. I'd like it to have padding-right == to the space between the archive icon and the star. Ellipsified titles are actually also too close to the star icon even when not in the hover state.
- In the filter dropdown, I think the `all dashboards` icon should be our dashboard icon instead of the stack/collections icon.
-

2017-04-28 01:43 UTC, salsakran approved these changes

2017-04-28 18:32 UTC, kdoh requested changes
Just a couple small class usage things but after those are fixed this looks good.

2017-04-28 18:32 UTC, kdoh commented on frontend/src/metabase/dashboards/containers/Dashboards.jsx
> +                                  className="mr2 text-brand-hover Icon Icon-viewArchive"
I think the Icon element should get these `Icon` classes automatically based on the name so no need to duplicate them here.

2017-04-28 18:32 UTC, kdoh commented on frontend/src/metabase/dashboards/containers/Dashboards.jsx
> +                              className="text-brand-hover Icon Icon-add"
Same deal here r.e. `Icon` classes.

2017-04-28 18:32 UTC, kdoh commented on frontend/src/metabase/dashboards/components/DashboardList.jsx
> +                      className={cx(
Don't actually need to use `cx` here since there aren't any conditional classes on this element.

2017-04-28 18:34 UTC, attekei commented on frontend/src/metabase/dashboards/containers/Dashboards.jsx
> +                                  className="mr2 text-brand-hover Icon Icon-viewArchive"
`Icon` class  doesn't currently merge them to the provided `className` parameter but I will make it do that :-)

2017-04-28 19:45 UTC, merged