clean up HeaderBar component [WIP]
metabase/metabase pull request #4892
Opened 2017-04-27 00:20 UTC by kdoh

addresses #4885 

adds tests and refactors the markup for the HeaderBar component.

Todos: 

- [ ] handle breadcrumbs and add test
- [ ] check mobile rendering

2017-05-03 19:34 UTC, tlrobinson approved these changes

2017-05-03 19:34 UTC, tlrobinson commented on frontend/src/metabase/components/HeaderBar.jsx
> +export default class HeaderBar extends Component {
FYI, not sure if it was your intention but props/state don't get typechecked by flow unless you do `Component<*, Props, State>`

2017-05-03 20:14 UTC, attekei requested changes

2017-05-03 20:14 UTC, attekei commented on frontend/src/metabase/components/HeaderBar.jsx
> +export default class HeaderBar extends Component {
Actually that is not needed anymore in Flow, and for instance `defaultProps` is automatically inferred. This component could still have `props: {...}` [as described in React docs](https://flow.org/en/docs/frameworks/react/#toc-adding-types-for-react-component-props).

2017-10-09 17:51 UTC, kdoh commented
I think things have drifted enough to where this is no longer relevant. Closing.

2017-10-09 17:51 UTC, closed without merging