Fix: Workaround for translations of Date picker (of type all).
metabase/metabase pull request #48980
Opened 2024-10-22 09:44 UTC by antonhedstrom

> [!IMPORTANT]
> For those employed by Metabase: if you are merging into master, please add either a `backport` or a `no-backport` label to this PR. You will not be able to merge until you do this step. Refer to the section [Do I need to backport this PR?](https://www.notion.so/metabase/Metabase-Branching-Strategy-6eb577d5f61142aa960a626d6bbdfeb3?pvs=4#89f80d6f17714a0198aeb66c0efd1b71) in the Metabase Branching Strategy document for more details. If you're not employed by Metabase, this section does not apply to you, and the label will be taken care of by your reviewer.

> **Warning**
>
> If that is your first contribution to Metabase, please sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) (unless it's a tiny documentation change). Also, if you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

Work around, but:
Closes https://github.com/metabase/metabase/issues/48978

### Description

Currently, for non English users, the button label is incorrectly translated (half translated, halv english). This "solution" discards the first part of the translation (scetchy) from `Lib.describeTemporalInterval` and pass the rest to be translated by Metabase (using prefix).

### How to verify

This solves the bug being described in #48978 (see reproduce steps there). 

### Demo

Before:
<img width="300" alt="Screenshot 2024-10-22 at 11 42 03" src="https://github.com/user-attachments/assets/80a97aff-6e54-4795-aeef-3ea2a8545b17">

After:
<img width="300" alt="Screenshot 2024-10-22 at 11 44 07" src="https://github.com/user-attachments/assets/9d71091b-5afc-4f4c-8dd5-64ccc9fa641f">

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2024-12-17 16:41 UTC, uladzimirdev commented
hey @antonhedstrom, thanks for your contribution! we need to run CI against your PR, we'll get back to you once CI run is done

2024-12-17 18:48 UTC, uladzimirdev commented
@antonhedstrom many tests are broken atm, could you please start with `frontend/test/metabase/lib/query_time.unit.spec.js`? it's a jest test, just `yarn build:cljs && yarn jest frontend/test/metabase/lib/query_time.unit.spec.js` should be enough

2024-12-23 15:22 UTC, ranquild requested changes
This is a workaround. Please fix `Lib.describeTemporalInterval` in clojure instead.

2025-02-26 08:24 UTC, antonhedstrom commented
Sorry for late response.
This seems to be fixed in [Metabase 53](https://github.com/metabase/metabase/releases/tag/v0.53.1) so it can be closed.

2025-02-26 08:24 UTC, closed without merging