Docker: set timezone to UTC
metabase/metabase pull request #4904
Opened 2017-04-27 21:55 UTC by mattes

I believe the `Report Timezone` field needs clarification. Here it says "Defaults to __system timezone__."

<img width="532" alt="screen shot 2017-04-27 at 2 43 49 pm" src="https://cloud.githubusercontent.com/assets/1240531/25505837/7ffcf364-2b58-11e7-9238-d88d2cf825d0.png">

... while the select field then says __Database default__.

<img width="252" alt="screen shot 2017-04-27 at 2 44 09 pm" src="https://cloud.githubusercontent.com/assets/1240531/25505840/8210af38-2b58-11e7-8c21-ab17f88d2c93.png">

The database timezone and the system timezone are two different things. I *believe* metabase in this context actually uses the system timezone but means database default? This needs to be addressed on its own.

---

I opened this PR to set the default system's timezone to `UTC` when metabase is run inside Docker. As of today, the Java Runtime doesn't take the underlying OS' timezone into account. Metabase, when run with Docker, defaults to GMT and I think UTC is the better default here.

2017-05-30 10:24 UTC, mattes commented
cc @camsaul

2017-05-30 10:50 UTC, mattes commented
I just saw this: https://github.com/metabase/metabase/commit/b2b57ef994b90086158956354b283712b05527de

2017-06-27 21:10 UTC, thearthur commented
I suspect you may want to also make that change to `metabase/bin/docker/Dockerfile` which is the one used to build the public docker images.

2017-06-27 21:29 UTC, thearthur commented
I think we should also change the label from "Database Default" to either "Metabase Default" or "Server Default" since this is an admin setting and makes less sense if you have two DBs attached that are in different timezones.

2019-05-07 06:11 UTC, camsaul commented
@tlrobinson thoughts?

2019-05-21 22:06 UTC, tlrobinson commented
Seems reasonable, but we should do it in both Dockerfiles.

2019-08-29 01:08 UTC, camsaul requested changes
make changes in `./bin/docker/Dockerfile` as well

2019-09-02 19:02 UTC, mazameli commented
@mattes Would you still like to make the requested changes to this PR and have it be merged? I Know it's been over two years since you originally opened this and the changes were requested.

2020-01-27 21:09 UTC, closed without merging