49586 adjust the diagnostics dialog towards filing a bug vs downloading diagnostics
metabase/metabase pull request #50277
Opened 2024-11-20 14:11 UTC by filiphric

Closes https://github.com/metabase/metabase/issues/49586

### Description

Design updates to diagnostic window. When slack bug reporting channel is set, modal is shows a "description" field. Modal now shows a "bug report submitted" state too.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. enable `MB_BUG_REPORTING_ENABLED` env setting
2. hit F1 or choose any other way of showing bug report modal

### Demo

![Screenshot 2024-11-20 at 15 10 30](https://github.com/user-attachments/assets/96426cf9-d2d2-4804-916f-337610352379)
![Screenshot 2024-11-20 at 15 10 27](https://github.com/user-attachments/assets/8402c3fe-27fb-4ec7-9369-7af45874c6ba)
![Screenshot 2024-11-20 at 15 09 18](https://github.com/user-attachments/assets/343a76fb-b520-4eb5-bc0c-243bf636cf4d)
![Screenshot 2024-11-20 at 15 05 43](https://github.com/user-attachments/assets/ccae3e7f-d95f-4fd9-aeaf-59606bf127f6)

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

2024-11-21 16:11 UTC, iethree requested changes
Looking good! I like how this is shaping up. Some comments inline, but higher level:

1. This was a little hard to review, because this PR seems to be based on top off https://github.com/metabase/metabase/pull/49875 and https://github.com/metabase/metabase/pull/49954, so it's hard to tell which parts of the diff are actually part of this PR. 
2. The backend seems to be dropping fields on their way to slack 😞

2024-11-21 16:11 UTC, iethree commented on frontend/src/metabase/components/ErrorPages/ErrorDiagnosticModal.tsx
> +                    style={{ fontSize: "17px", width: "50px" }}
there are [mantine style props](https://v6.mantine.dev/styles/style-props/) for these! `fz` and `w`

I don't think, though that you necessarily want to set a fixed width, it causes weird ellipsification on some screen sizes, and will probably truncate other languages strangely.


![Screen Shot 2024-11-21 at 8 11 59 AM](https://github.com/user-attachments/assets/23eca058-d32d-45a1-b27d-e6363ccc131e)

2024-11-21 23:40 UTC, mazameli commented
@filiphric, could you help @romnitt to give this a close UX review (if he needs help getting this to run locally, or seeing an ephemeral PR env with this branch etc)?

2024-11-27 00:59 UTC, iethree requested changes
Thanks for restructuring those modals, they're much easier to understand now. I still think there's a problem with sending the `description` field to slack. This is the test I just ran


![Screen Shot 2024-11-26 at 5 47 21 PM](https://github.com/user-attachments/assets/e4d47868-dba9-4179-ab6f-a7e10882fed8)
![Screen Shot 2024-11-26 at 5 47 13 PM](https://github.com/user-attachments/assets/ab1224aa-068c-4319-9c17-5754327aa4fe)

I also don't seen any messages in the bot-testing or bug-reports-internal slack channels that actually have a description. they're all `N/A`

2024-11-28 11:15 UTC, uladzimirdev approved these changes
FE part LGTM, can we get an approval from @romnitt as @mazameli asked?

2024-12-03 00:01 UTC, johnswanson approved these changes

2024-12-03 01:00 UTC, escherize approved these changes

2024-12-03 20:05 UTC, iethree approved these changes

2024-12-04 11:02 UTC, closed without merging