`if` MBQL function
metabase/metabase pull request #50702
Opened 2024-11-29 19:13 UTC by ranquild

Epic https://github.com/metabase/metabase/issues/50698

2024-11-29 20:08 UTC, mngr requested changes
Let's add `Alias for case(). ` text to the description of if() and `Alias for if(). ` text to the description of case()

2024-11-29 20:08 UTC, mngr commented on frontend/src/metabase-lib/v1/expressions/helper-text-strings.ts
> +      t`Tests an expression against a list of cases and returns the corresponding value of the first matching case, with an optional default value if nothing else is met.`,
```suggestion
      t`Alias for case(). Tests an expression against a list of cases and returns the corresponding value of the first matching case, with an optional default value if nothing else is met.`,
```

2024-11-29 20:11 UTC, ranquild commented
@mngr updated description

2024-12-10 06:21 UTC, romeovs commented on frontend/src/metabase-lib/v1/expressions/recursive-parser.js
> +      if (isCaseOrIfOperator(node[0])) {
Not sure if it was an intentional change but the new code does not accommodate for cases where `node` is nullish.

2024-12-10 06:23 UTC, romeovs approved these changes
Just one issue in the comments

2024-12-10 12:19 UTC, mngr approved these changes

2024-12-10 14:02 UTC, ranquild commented on frontend/src/metabase-lib/v1/expressions/recursive-parser.js
> +      if (isCaseOrIfOperator(node[0])) {
This is within `Array.isArray` block so `node`  should not be `null` or `undefined`

2024-12-10 15:15 UTC, merged