Show an appropriate message if a user tries to access an archived dashboard/question
metabase/metabase pull request #5078
Opened 2017-05-10 23:07 UTC by attekei

Addresses #5025.

For questions this was really straightforward as `api/card/XX` returns the `archived` state. For dashboards I had to check the error message value (`The object has been archived.`) and I'm not sure if that is a good approach.

2017-05-11 00:42 UTC, attekei commented
Ready for review.

2017-05-11 17:53 UTC, mazameli submitted a review, later dismissed
The one thing we didn't think about was accessing a public link for a question or dashboard that has been archived. Currently you get a message that says "an error occurred," but I think we should give the new "this question/dashboard has been archived" message instead (but without the link to the archive.

2017-05-11 19:44 UTC, mazameli approved these changes

2017-05-12 18:19 UTC, tlrobinson commented on test/metabase/api/card_test.clj
> +  {:message "The object has been archived.", :error_code "archived"}
I don't think `error_code` is a pattern we've used before in any endpoints. I'm not opposed to it or similar, but we should run it by @camsaul.

2017-05-12 18:20 UTC, tlrobinson commented on test/metabase/api/card_test.clj
> +  {:message "The object has been archived.", :error_code "archived"}
If there's a suitable HTTP status code that would probably be ideal.

2017-05-12 18:22 UTC, tlrobinson requested changes
I think it would be better to handle this using the existing `setErrorPage` and a new case in `App.jsx` like we do for `Unauthorized` and `NotFound`, so we can reuse it for other archived objects.

2017-05-12 18:23 UTC, camsaul commented on test/metabase/api/card_test.clj
> +  {:message "The object has been archived.", :error_code "archived"}
@tlrobinson I added that after talking with @attekei about it. There're no HTTP status codes that seemed appropriate and we wanted a way to differentiate different kinds of 404s so this is what we came up with.

2017-05-12 18:24 UTC, tlrobinson commented on test/metabase/api/card_test.clj
> +  {:message "The object has been archived.", :error_code "archived"}
👍

2017-05-12 19:16 UTC, attekei commented
I think that I could handle the dashboard archive page in `App.jsx` but I'm a little afraid to generalize the archived empty state too much (different "this item has been archived" items have different icons and links).

2017-05-12 22:05 UTC, attekei commented
could you take a look again @tlrobinson? now `setErrorPage` is used in both cases

2017-05-16 17:26 UTC, tlrobinson commented on frontend/src/metabase/App.jsx
> -import React, { Component } from "react";
FYI there's no point in changing minor formatting like this, it will just get changed back when we enable `prettier`

2017-05-16 17:28 UTC, tlrobinson approved these changes

2017-05-16 17:31 UTC, attekei commented on frontend/src/metabase/App.jsx
> -import React, { Component } from "react";
oh that has been unintentional

2017-05-16 21:01 UTC, merged