chore: rework dataref to css modules
metabase/metabase pull request #50911
Opened 2024-12-04 21:42 UTC by uladzimirdev

> [!IMPORTANT]
> For those employed by Metabase: if you are merging into master, please add either a `backport` or a `no-backport` label to this PR. You will not be able to merge until you do this step. Refer to the section [Do I need to backport this PR?](https://www.notion.so/metabase/Metabase-Branching-Strategy-6eb577d5f61142aa960a626d6bbdfeb3?pvs=4#89f80d6f17714a0198aeb66c0efd1b71) in the Metabase Branching Strategy document for more details. If you're not employed by Metabase, this section does not apply to you, and the label will be taken care of by your reviewer.

> **Warning**
>
> If that is your first contribution to Metabase, please sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) (unless it's a tiny documentation change). Also, if you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

Closes https://github.com/metabase/metabase/issues/[issue_number]

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2024-12-09 09:38 UTC, kamilmielnik requested changes
Looks good. I found 1 small visual regression.

2024-12-09 09:38 UTC, kamilmielnik commented on frontend/src/metabase/query_builder/components/SidebarContent/SidebarContent.tsx
> +  return <Box pl="lg" pr="lg" {...props} />;
```suggestion
  return <Box px="lg" {...props} />;
```

2024-12-09 09:38 UTC, kamilmielnik commented on frontend/src/metabase/query_builder/components/dataref/NodeList.tsx
> +  QuestionId,
nit: it looks like a name of a type

```suggestion
  NodeListItemId,
```

2024-12-09 13:12 UTC, uladzimirdev commented on frontend/src/metabase/query_builder/components/dataref/NodeList.tsx
> +  QuestionId,
fixed

2024-12-09 20:19 UTC, uladzimirdev commented on frontend/src/metabase/query_builder/components/dataref/NodeList.tsx
> +      color="var(--mb-color-text-medium)"
<img width="919" alt="image" src="https://github.com/user-attachments/assets/48c27827-6817-40c0-a165-d24b66203054">
should be fixed in [8addc69](https://github.com/metabase/metabase/pull/50911/commits/8addc693b17416fa1b96a1bfbf54ec962fbc5495)

2024-12-10 08:27 UTC, kamilmielnik approved these changes

2024-12-10 09:47 UTC, merged