adjusting webhook test response ui
metabase/metabase pull request #51043
Opened 2024-12-09 13:49 UTC by npfitz

### Description
Small adjustment to how the "Test Response" UI looks for webhook notifications

### How to verify
Go to an existing webhook (or set up a new one), and hit "Send Test". The box with the background should not contain the header, and the padding should be in line with the rest of the form

### Demo
Before:
![image](https://github.com/user-attachments/assets/ca2cb38f-e5b9-42c7-88ea-6940c3c1fb1b)

After: 
![image](https://github.com/user-attachments/assets/fb47c220-b05e-4aee-8641-b56640250c0e)

### Checklist
Purely visual. No tests added
- [ ] ~Tests have been added/updated to cover changes in this PR~

2024-12-09 16:09 UTC, sloansparger approved these changes

2024-12-09 16:10 UTC, rafpaf commented on frontend/src/metabase/admin/settings/notifications/WebhookForm.tsx
> +                  Test Response
Does this need to be localized?

2024-12-09 16:11 UTC, rafpaf requested changes
See comment about i18n

2024-12-10 05:26 UTC, qnkhuat commented
when I use a webhook that returns error, I don't see UI show the error response and error status.
![Screenshot 2024-12-10 at 12 24 51](https://github.com/user-attachments/assets/70384654-8463-4b12-9614-a77b3264bfc3)

Also, the `{:ok true}` is from Metabase, I don't think we want to show a response for success cases right? if yes, I'll need to change BE to keep the response in that case.

2024-12-10 16:19 UTC, npfitz commented
@qnkhuat Updated 👍

2024-12-11 04:07 UTC, qnkhuat commented
@npfitz did you push? :D didn't see any new commits

2024-12-11 13:55 UTC, npfitz commented
Ah geez. Sorry, I was rushing out the door for an appointment. Pushed now

2024-12-13 03:55 UTC, qnkhuat commented
@npfitz I pushed a commit to parse the request data as json to make it nicer on the eyes.
![Screenshot 2024-12-13 at 10 49 55](https://github.com/user-attachments/assets/56758e02-d6d9-48e3-a4dd-3d80fe99dd22)

2024-12-16 21:41 UTC, rafpaf approved these changes

2024-12-17 12:52 UTC, merged