fix(sdk): update define function names in Next.js compat
metabase/metabase pull request #51071
Opened 2024-12-09 19:32 UTC by heypoom

We renamed the type helper functions to `defineMetabaseTheme` and `defineMetabaseAuthConfig` in https://github.com/metabase/metabase/pull/50585. This PR updates the compat generation script to use the same naming.

2024-12-12 10:30 UTC, npretto approved these changes

2024-12-12 14:30 UTC, npretto requested changes
I was testing this locally, it wasn't working because we also renamed `config` -> `authConfig`

2024-12-12 14:30 UTC, npretto commented on enterprise/frontend/src/embedding-sdk/bin/generate-nextjs-compat.ts
>    config,
We also need to update these

2024-12-18 13:15 UTC, npretto approved these changes
Tested locally, works as expected

2024-12-18 13:21 UTC, merged

2024-12-18 13:23 UTC, heypoom commented
@metabase-bot backport release-x.51.x