Fix: Create api token modal now shows error from backend (i.e. name is taken).
metabase/metabase pull request #51395
Opened 2024-12-17 14:43 UTC by rafpaf

Running CI for external contribution #47616

2024-12-17 17:59 UTC, sloansparger requested changes, later dismissed
Could we add a small test? 🥺

2024-12-20 15:00 UTC, npfitz approved these changes

2024-12-20 15:01 UTC, iethree approved these changes

2024-12-20 15:02 UTC, npfitz commented
Looks good. I haven't seen the pattern of looking at the response object to render different modals. Also, a bit wary of wrapping the error in the div. We should ensure that it doesn't affect positioning

2024-12-20 15:36 UTC, merged