Google Sheets Integration - Feature Branch
metabase/metabase pull request #51436
Opened 2024-12-18 03:08 UTC by escherize

2025-02-13 10:22 UTC, rafpaf commented on enterprise/frontend/src/metabase-enterprise/google_sheets/GoogleSheetManagement.tsx
> +    !FIXME_TEST_BOOLEAN &&
^

2025-02-13 10:23 UTC, rafpaf commented on enterprise/frontend/src/metabase-enterprise/google_sheets/GoogleSheetManagement.tsx
> +    !FIXME_TEST_BOOLEAN &&
^

2025-02-13 10:23 UTC, rafpaf commented on enterprise/frontend/src/metabase-enterprise/google_sheets/GoogleSheetManagement.tsx
> +    !FIXME_TEST_BOOLEAN &&
^

2025-02-13 10:32 UTC, rafpaf reviewed
Note that the FE code still has some FIXMEs and some (easily fixed) security issues pointed out by Github's automated tool

2025-02-13 10:32 UTC, rafpaf commented on enterprise/frontend/src/metabase-enterprise/google_sheets/GoogleSheetManagement.tsx
> +          t`Share the Google Drive folder that contains your Google Sheets with Metabase`
Maybe: `Share with Metabase the Google Drive folder that contains your Google Sheets`?

2025-02-13 10:32 UTC, rafpaf commented on enterprise/frontend/src/metabase-enterprise/upload_management/index.ts
> +  FIXME_TEST_BOOLEAN
^

2025-02-13 10:32 UTC, rafpaf commented on frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
> +  const showUploadCSVButton = true; // FIXME for testing
^

2025-02-13 10:32 UTC, rafpaf commented on frontend/src/metabase/status/components/StatusListing/StatusListing.tsx
> +// FIXME: setup an enterprise plugin
^

2025-02-13 17:04 UTC, noahmoss commented on enterprise/backend/src/metabase_enterprise/gsheets.clj
> +    (hm-delete-conn id))
What happens here if these get out of sync? i.e. we reset the gsheets state in Metabase but HM fails to delete all the connections? Is that a recoverable state?

2025-02-13 17:39 UTC, escherize commented on src/metabase/sync/sync_metadata/tables.clj
> +    (do   #p (t2/select-one :model/Table existing-id)
fixed, thank you.

2025-02-13 17:41 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/advanced_config/file/databases.clj
> +     ;; _'s because this is validated first then normalized later
Thanks, I'll expand on it.

2025-02-13 17:52 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets.clj
> +(mu/defn- hm-delete-conn :- ::hm.client/http-reply
Done (not taking the commit because I renamed it inside the file).

2025-02-13 17:55 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets.clj
> +    (hm-delete-conn id))
That is the only way we will leak connections. It is still a possibility if hm fails to delete it, but I think this is good enough.

I am deleting all gdrive conns (though we use 1 and only 1) so that we don't leak connections.

If a user is disconnecting/reconnecting their drive folders then every time they disconnect (or hit an error), we try to clean up orphanted gdrive conns.

2025-02-13 18:03 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets.clj
> +                  (some-> (t2/select-one :model/Setting :key "gsheets") :value json/decode+kw)
We observed this while running as a cluster during an inner-loop trial.

When running on a cluster, if instance A gets the `:post /folder` request, and 5 seconds later instance B gets the `:get /folder` request, instance B will likely not have the (: I got bit by the settings cache for a couple hours. The ttl for refreshing the settings cache [is 1 minute](https://github.com/metabase/metabase/blob/gsheets_integration/src/metabase/models/setting/cache.clj#L132). 

I see that there's a binding I can set that will go around the cache, too.

We _do_ return gsheets in the system/properties response. It may be worth looking into exactly when we need to get the db-value and do it only there. I will check with @iethree about exactly when he needs the gsheets setting to be 100% reliable.

2025-02-13 23:41 UTC, noahmoss commented on enterprise/backend/src/metabase_enterprise/gsheets.clj
> +(comment
want to remove this or are you including intentionally?

2025-02-13 23:41 UTC, noahmoss commented on enterprise/backend/src/metabase_enterprise/gsheets.clj
> +  ;; TODO add api/+check-superuser +auth and +check-setting
Is this still needed?

2025-02-13 23:41 UTC, noahmoss commented on src/metabase/sync/sync_metadata/tables.clj
> +                                             :pattern-strings (some-> database :settings :auto-cruft-tables)})]
It might be slightly cleaner for this API to just take a set regexes? And combine them all into one set before passing them in?

2025-02-13 23:41 UTC, noahmoss commented on src/metabase/sync/sync_metadata/tables.clj
> +                            is-crufty?              "complete"
does this actually work? if so I'm slightly surprised, I thought the sync status was just to power the UI

2025-02-14 17:17 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets.clj
> +(comment
fixed

2025-02-14 17:18 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets.clj
> +  ;; TODO add api/+check-superuser +auth and +check-setting
fixed

2025-02-14 20:27 UTC, escherize commented on src/metabase/sync/sync_metadata/tables.clj
> +                            is-crufty?              "complete"
Hmm, I believed this comment, but maybe it's no longer true (or never was). I dug around to see where the comment came from originally. [it is from this commit](https://github.com/metabase/metabase/blob/ffbb526e5deabbb668cc62cf363af2f4ecaac720/src/metabase/sync/sync_metadata/tables.clj#L99). I don't see anywhere that we are filtering for a table's initial sync status in the sync steps. 

So: I think it does get synced, but just marked crufty (hidden) which is fine for this since we want to allow admins to unhide tables that get marked crufty incidentally.

2025-02-14 20:27 UTC, escherize commented on src/metabase/sync/sync_metadata/tables.clj
> +                            is-crufty?              "complete"
I'll cleanup the comment

2025-02-14 22:52 UTC, escherize commented on src/metabase/sync/sync_metadata/tables.clj
> +                                             :pattern-strings (some-> database :settings :auto-cruft-tables)})]
good idea, done

2025-02-28 22:02 UTC, escherize commented on src/metabase/sync/sync_metadata/crufty.clj
> +  (-> pattern u/lower-case-en re-pattern))
Thanks, I can see the confusion here. The intent is to make cruftyness regexes case insenstive so they work between table or column names that are upper and or lower case.

2025-03-04 17:34 UTC, npfitz approved these changes
Looks good to me!

2025-03-05 17:41 UTC, escherize commented on enterprise/backend/test/metabase_enterprise/api/gsheets_test.clj
> +(def happy-responses (read-string (slurp (io/resource "gsheets/mock_hm_responses.edn"))))
gsheets/mock_hm_responses.edn is an edn map from {:method _ :url "" :body _} to the response observed from HM.

I've added a few functions like +syncing that overwrite pieces of the map with other observed responses.

2025-03-05 17:44 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/api/routes.clj
> +                                     (premium-handler :etl-connections))
all gsheets routes are gated behind these 2 token features.

2025-03-05 17:44 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets/settings.clj
> +(mr/def :gsheets/gsheets
This isn't actually used, but it is good for docs

2025-03-05 17:46 UTC, escherize commented on src/metabase/api/auth.clj
> +        When it matches, the request continues; otherwise it’s blocked with a 403 Forbidden response.")
this got moved for modularity's sake

2025-03-06 18:41 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets/api.clj
> +;;   - MB loops over all gdrive connection ids and deletes them
You'd think there could only 1, but it's possible for there to be more in rare cases.

2025-03-06 20:15 UTC, noahmoss commented on enterprise/backend/src/metabase_enterprise/harbormaster/client.clj
> +(mu/defn make-request :- :hm-client/http-reply
wdyt of splitting this function up a bit? could have separate functions for `construct request`, `make-request`, and `handle-response`, or something like that? just an idea, not blocking

2025-03-06 20:15 UTC, noahmoss commented on enterprise/backend/src/metabase_enterprise/harbormaster/client.clj
> +  (let [store-api-url (setting/get-value-of-type :string :store-api-url)
any reason to use `get-value-of-type` and not just `(store-api-url)`? same with the other setting

2025-03-06 20:15 UTC, noahmoss commented on enterprise/backend/src/metabase_enterprise/harbormaster/client.clj
> +        api-key (setting/get-value-of-type :string :api-key)
also asked on Slack — but just want to check that we're intentionally overloading this `api-key` setting for this use case. I thought it's supposed to be a legacy env var specifically for the `/notify` endpoints

2025-03-06 20:23 UTC, noahmoss requested changes
Left a bunch of comments — mostly nits/style things but my biggest question is around the use of the `api-key` setting. I thought we would deprecate that eventually so I'm surprised that it's being used for a very different use case here. If this is an intentional decision I'll stamp 👍

2025-03-06 20:23 UTC, noahmoss commented on enterprise/backend/test/metabase_enterprise/harbormaster/client_test.clj
> +    ;; api-key is blank or nil, and mt/with-temporary-setting-values will not allow us to set the api-key to blank
would `mt/with-temporary-raw-setting-values` work here?

2025-03-06 20:23 UTC, noahmoss commented on enterprise/backend/test/metabase_enterprise/api/gsheets_test.clj
> +  "<gdrive-link>")
is this supposed to be an actual link?

2025-03-06 20:23 UTC, noahmoss commented on enterprise/backend/test/metabase_enterprise/api/gsheets_test.clj
> +  "<gdrive-link>")
oh, I guess it's just the value in the mocked response? maybe calling it `expected-gdrive-link` or something like that would be clearer

2025-03-06 20:33 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets/api.clj
> +(mu/defn- hm-service-account-email :- [:or [:= false] :string]
nope, good catch

2025-03-06 20:42 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets/api.clj
> +  (let [[_status {:keys [body] :as _response}] (hm.client/make-request :get "/api/v2/mb/connections-google/service-account")]
That's sensible, let's.

2025-03-06 20:43 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets/api.clj
> +                            :gdrive/conn-id))
👍

2025-03-06 20:43 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets/api.clj
> +        [sstatus {conn :body}] (try (hm-get-gdrive-conn conn-id)
it's intended. I didn't want to shadow `status` on line 247

2025-03-06 20:44 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets/api.clj
> +                                        ;; sending a stuats code will ellide the message from the response.
fixed

2025-03-06 20:44 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets/api.clj
> +;; inside of those folders, and make them avaliable to the user in their attached data warehouse. This integration is
:+1:

2025-03-06 20:46 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets/api.clj
> +(comment
done

2025-03-06 20:57 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/harbormaster/client.clj
> +        api-key (setting/get-value-of-type :string :api-key)
It is that, but we also are using it to allow harbormaster to identify which metabase instance (or cluster, really) is setting up their ghsheets.

2025-03-06 20:58 UTC, noahmoss approved these changes
Clarified `api-key` usage on Slack

2025-03-06 21:01 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/harbormaster/client.clj
> +  (let [store-api-url (setting/get-value-of-type :string :store-api-url)
requiring store-api-url is a module violation, This only skirts the issue. I will require them directly and update the module linter config.

2025-03-06 21:24 UTC, escherize commented on enterprise/backend/test/metabase_enterprise/harbormaster/client_test.clj
> +    ;; api-key is blank or nil, and mt/with-temporary-setting-values will not allow us to set the api-key to blank
works for "", fails for nil. 🫠  I'll replace the "" case

2025-03-06 22:26 UTC, escherize commented on enterprise/backend/src/metabase_enterprise/gsheets/settings.clj
> +(mr/def :gsheets/gsheets
I think the comment is good enough. I put a stub for "add malli schemas to defsetting?" to the march 20th guild sync

2025-03-10 14:41 UTC, merged