WIP: Use CodeMirror in the custom expression editor
metabase/metabase pull request #51494
Opened 2024-12-19 10:00 UTC by romeovs

WIP

2025-02-07 08:40 UTC, filiphric approved these changes

2025-02-07 08:40 UTC, filiphric commented on e2e/test/scenarios/metrics/metrics-editing.cy.spec.js
> +      H.popover().button("Update").should("not.be.disabled").click();
this should not be needed as `.click()` checks for this implicitly, [see docs](https://docs.cypress.io/app/core-concepts/interacting-with-elements#Actionability)

2025-02-07 08:40 UTC, filiphric commented on e2e/support/helpers/e2e-custom-column-helpers.ts
>   */
I think adding jsdoc for "allowFastSet" would be helpful here

2025-02-07 08:40 UTC, filiphric commented on e2e/support/helpers/e2e-custom-column-helpers.ts
> +      CustomExpressionEditor.get().findByRole("textbox").invoke("text", text);
you can achieve the same thing by `.type("text", {timeout: 0})` the advantage of this is that you’ll get slightly smaller chance of flakiness, because `.type()` will check if the element is not disabled, etc.

2025-02-07 08:40 UTC, filiphric commented on e2e/support/helpers/e2e-custom-column-helpers.ts
> +      CustomExpressionEditor.get().findByRole("textbox").invoke("text", text);
nevermind, I misread the comment

2025-02-10 14:40 UTC, ranquild requested changes
https://metaboat.slack.com/archives/C0645JP1W81/p1739198343959709

2025-02-14 16:13 UTC, romeovs commented
Superceded by https://github.com/metabase/metabase/pull/53761

2025-02-14 16:13 UTC, closed without merging