docs - note on upgrading to pro
metabase/metabase pull request #51585
Opened 2024-12-20 17:18 UTC by jeff-bruemmer

Reassure people that switching JARs will preserve their work.

2024-12-23 16:17 UTC, trinya requested changes

2024-12-23 16:17 UTC, trinya commented on docs/paid-features/activating-the-enterprise-edition.md
> +The upgrade to an Enterprise Edition will keep all of your questions, dashboards, people, settings---everything in your existing Metabase.
The only thing you need to do is to replace an open source JAR file with an Enterprise Edition JAR, or <what to do if they are on Docker?>, and enter your license token in the Admin Settings -> License section.

2025-01-20 18:51 UTC, alexyarosh approved these changes

2025-01-20 18:51 UTC, alexyarosh commented on docs/paid-features/activating-the-enterprise-edition.md
> +- [Enterprise Docker image](https://hub.docker.com/r/metabase/metabase-enterprise/) at `metabase/metabase-enterprise:latest`.
I'm not sure about pointing directly to latest. In general (not necessarily in this article, but overall) we should suggest that people pin the versions instead of always pulling latest... 
Also, do the versions of OSS vs EE have to match? Can someone go from v50 OSS to v52 EE?

2025-01-20 19:00 UTC, alexyarosh approved these changes

2025-01-20 19:00 UTC, alexyarosh commented on docs/paid-features/activating-the-enterprise-edition.md
> +Upgrading to the Enterprise Edition will keep all of your questions, dashboards, people, settings---everything in your existing Metabase.
```suggestion
Upgrading to the Enterprise Edition will keep all of your questions, dashboards, people, settings — everything in your existing Metabase.

```
Our style guide says to put spaces around em dashes which is the Correct Opinion that I feel Very Strongly about 😅

2025-02-05 23:01 UTC, jeff-bruemmer commented on docs/installation-and-operation/activating-the-enterprise-edition.md
> +
```suggestion
```

2025-02-05 23:02 UTC, merged