Instant test updates
metabase/metabase pull request #51605
Opened 2024-12-20 23:19 UTC by iethree

Create and/or update a PR comment as soon as any e2e tests fails to enable faster feedback loops.

2025-01-07 15:46 UTC, iethree commented
## e2e tests failed on `undefined`

  File | Test Name
  ---- | ---------
  `undefined` | `undefined`

2025-01-07 15:59 UTC, iethree commented
## e2e tests failed on `hash`

  File | Test Name
  ---- | ---------
  `undefined` | `undefined`

2025-01-07 16:08 UTC, iethree commented
## e2e tests failed on `hash`

  File | Test Name
  ---- | ---------
  `clock.cy.spec.ts` | `server clock > server clock remains stopped once manually set`

2025-01-07 16:09 UTC, iethree commented
## e2e tests failed on `hash`

  File | Test Name
  ---- | ---------
  `clock.cy.spec.ts` | `server clock > server clock remains stopped once manually set`

2025-01-07 16:10 UTC, iethree commented
## e2e tests failed on `hash`

  File | Test Name
  ---- | ---------
  `clock.cy.spec.ts` | `server clock > can advance the server clock by one day`

2025-01-07 16:10 UTC, iethree commented
## e2e tests failed on `hash`

  File | Test Name
  ---- | ---------
  `clock.cy.spec.ts` | `server clock > server clock remains stopped once manually set`

2025-01-07 16:11 UTC, iethree commented
## e2e tests failed on `hash`

  File | Test Name
  ---- | ---------
  `clock.cy.spec.ts` | `server clock > can advance the server clock by one day`

2025-01-07 16:11 UTC, iethree commented
## e2e tests failed on `hash`

  File | Test Name
  ---- | ---------
  `clock.cy.spec.ts` | `server clock > server clock remains stopped once manually set`

2025-01-07 16:38 UTC, iethree commented
## e2e tests failed on `abc456`

  File | Test Name
  ---- | ---------
  `clock.cy.spec.ts` | `server clock > can advance the server clock by one day`

2025-01-08 12:33 UTC, filiphric requested changes
this is really cool! 👍 you forgot to remove the intentional test failures though 😅

2025-01-08 15:59 UTC, nemanjaglumac commented on .github/workflows/e2e-tests.yml
> +            }).catch((console.error));
Should this be 
```suggestion
            }).catch(console.error);
```

?

2025-01-08 17:15 UTC, nemanjaglumac commented on e2e/support/cypress.js
> +    const testInfo = Cypress.mocha.getRunner().suite.ctx.currentTest;
Nit: but couldn't we avoid repeating the whole `Cypress.mocha.getRunner().suite.ctx.currentTest` by getting the `state` out of the `testInfo`?

2025-01-08 17:16 UTC, iethree commented on e2e/support/cypress.js
> +    const testInfo = Cypress.mocha.getRunner().suite.ctx.currentTest;
https://github.com/metabase/metabase/pull/51605/commits/8902d4a394d287fe0c2ecd7ce98fb879c059475b

2025-01-08 17:17 UTC, nemanjaglumac commented on e2e/support/cypress.js
> +        test: Cypress.currentTest,
Out of curiosity - is `Cypress.currentTest` different from `Cypress.mocha.getRunner().suite.ctx.currentTest`?

2025-01-08 17:18 UTC, iethree commented on e2e/support/cypress.js
> +        test: Cypress.currentTest,
yes 🥴

2025-01-10 08:01 UTC, filiphric approved these changes

2025-01-17 21:49 UTC, merged