50766 Alerts new ux
metabase/metabase pull request #51647
Opened 2024-12-23 22:06 UTC by deniskaber

Part of  https://github.com/metabase/metabase/issues/50766

### Description

We want to migrate Question alerts to use new API and prepare UI for multiple delivery channels.

Check [this epic](https://github.com/metabase/metabase/issues/50766) for more details.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. Open existing question
2. Click "Share" icon button, then "Create an alert" or "Edit alerts"
3. Modals should have new UI. It should use the new API.

1. Go to Settings > Account Settings > Notifications
2. Check list of notifications you're subscribed to. It should use the new API.

### Demo

https://www.loom.com/share/51a553e617d84b26974999fe4d5455e2

### Checklist

- [x] Tests have been added/updated to cover changes in this PR

2025-01-30 08:41 UTC, filiphric requested changes

2025-01-30 08:41 UTC, filiphric commented on e2e/test/scenarios/sharing/sharing-reproductions.cy.spec.js
> +    cy.findByText("PM").click();
I’d be nice to get rid of the eslint warning here

2025-02-20 13:43 UTC, filiphric approved these changes

2025-02-20 17:19 UTC, uladzimirdev approved these changes
LGTM overall, left some comments

2025-02-20 17:19 UTC, uladzimirdev commented on frontend/src/metabase/account/notifications/containers/NotificationsApp/NotificationsApp.tsx
> +export const NotificationsApp = _.compose(
do we need compose here?

2025-02-20 17:19 UTC, uladzimirdev commented on frontend/src/metabase/notifications/channels/SlackChannelFieldNew.tsx
> +    <div>
do you need a div wrapper here? can we drop it?

2025-02-20 17:19 UTC, uladzimirdev commented on frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/AlertToastContent.tsx
> +// TODO: use for notifications create / edit notifications
can we either use it or remove a comment?

2025-02-20 17:19 UTC, uladzimirdev commented on frontend/src/metabase/notifications/modals/components/NotificationChannelsAddMenu.tsx
> +// eslint-disable-next-line no-restricted-imports
if you really need this type, please re-export it from metabase/ui

2025-02-20 17:19 UTC, uladzimirdev commented on frontend/src/metabase/notifications/modals/components/NotificationChannelsAddMenu.tsx
> +const ManageDestinationsButton = ({ size }: { size?: MantineSize }) => (
can it be `ButtonProps['size']`?

2025-02-21 20:26 UTC, merged