chore(QB): show small Join and CC icons for aggregation without breakout
metabase/metabase pull request #51655
Opened 2024-12-24 17:55 UTC by uladzimirdev

> [!IMPORTANT]
> For those employed by Metabase: if you are merging into master, please add either a `backport` or a `no-backport` label to this PR. You will not be able to merge until you do this step. Refer to the section [Do I need to backport this PR?](https://www.notion.so/metabase/Metabase-Branching-Strategy-6eb577d5f61142aa960a626d6bbdfeb3?pvs=4#89f80d6f17714a0198aeb66c0efd1b71) in the Metabase Branching Strategy document for more details. If you're not employed by Metabase, this section does not apply to you, and the label will be taken care of by your reviewer.

> **Warning**
>
> If that is your first contribution to Metabase, please sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) (unless it's a tiny documentation change). Also, if you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

Closes https://github.com/metabase/metabase/issues/[issue_number]

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2025-01-02 15:47 UTC, mngr approved these changes

2025-01-06 14:06 UTC, AlessioLaiso approved these changes

2025-01-06 15:52 UTC, ranquild requested changes
Blocking this to re-review carefully.

2025-01-06 18:53 UTC, ranquild commented on frontend/src/metabase/querying/notebook/components/NotebookStep/NotebookStep.tsx
> +    const { query, stageIndex } = step;
@uladzimirdev it seems that you could set `compact: true` for both `expression` and `join` steps and this change would not be needed. I think it would be cleaner this way 
<img width="1378" alt="Screenshot 2025-01-06 at 13 52 48" src="https://github.com/user-attachments/assets/a4a2040d-9772-463b-9f9b-af4866108945" />
<img width="1378" alt="Screenshot 2025-01-06 at 13 52 54" src="https://github.com/user-attachments/assets/d6706ec7-93e2-4de0-b731-daeff443635f" />

2025-01-06 18:56 UTC, ranquild reviewed
Approach is fine, left a few comments.

2025-01-06 18:56 UTC, ranquild commented on frontend/src/metabase/querying/notebook/utils/steps.ts
> +    if (hasAggregations && !hasBreakouts) {
`return hasAggregations && !hasBreakouts`

2025-01-06 18:56 UTC, ranquild commented on frontend/src/metabase/querying/notebook/utils/steps.ts
> +    valid: (query, stageIndex) => {
This is fine, good approach. Please add tests for this. I'd add unit tests in `steps.unit.spec.ts`

2025-01-06 18:56 UTC, ranquild commented on frontend/src/metabase/querying/notebook/components/NotebookStepList/NotebookStepList.unit.spec.tsx
> +describe("NotebookStepList", () => {
You could instead add tests to the existing spec `steps.unit.spec.ts`

2025-01-08 09:58 UTC, uladzimirdev commented on frontend/src/metabase/querying/notebook/components/NotebookStepList/NotebookStepList.unit.spec.tsx
> +describe("NotebookStepList", () => {
I'm not 100% sure we can drop this test. `steps.unit.spec.ts` checks the result of calling `getQuestionSteps` and not actual rendered content on the screen

2025-01-08 09:59 UTC, uladzimirdev commented on frontend/src/metabase/querying/notebook/components/NotebookStepList/NotebookStepList.unit.spec.tsx
> +describe("NotebookStepList", () => {
I added a similar test to `steps.unit.spec.ts` though

2025-01-08 10:00 UTC, uladzimirdev commented on frontend/src/metabase/querying/notebook/utils/steps.ts
> +    if (hasAggregations && !hasBreakouts) {
fixed 028e3cbeac9511e278a1de5de5b2a070757212e4

2025-01-08 10:00 UTC, uladzimirdev commented on frontend/src/metabase/querying/notebook/components/NotebookStep/NotebookStep.tsx
> +    const { query, stageIndex } = step;
fixed 028e3cbeac9511e278a1de5de5b2a070757212e4

2025-01-08 10:00 UTC, uladzimirdev commented on frontend/src/metabase/querying/notebook/utils/steps.ts
> +    valid: (query, stageIndex) => {
added a test 028e3cbeac9511e278a1de5de5b2a070757212e4

2025-01-08 18:59 UTC, ranquild commented on frontend/test/__support__/ui.tsx
> +  withNotebook?: boolean;
Let's not put it here. This is rather specific to querying.

2025-01-08 18:59 UTC, ranquild approved these changes
Please remove `withNotebook` and use it where neded

2025-01-09 11:15 UTC, merged