chore(QB): change visual style of the buttons so that they all look active
metabase/metabase pull request #51666
Opened 2024-12-26 12:36 UTC by uladzimirdev

> [!IMPORTANT]
> For those employed by Metabase: if you are merging into master, please add either a `backport` or a `no-backport` label to this PR. You will not be able to merge until you do this step. Refer to the section [Do I need to backport this PR?](https://www.notion.so/metabase/Metabase-Branching-Strategy-6eb577d5f61142aa960a626d6bbdfeb3?pvs=4#89f80d6f17714a0198aeb66c0efd1b71) in the Metabase Branching Strategy document for more details. If you're not employed by Metabase, this section does not apply to you, and the label will be taken care of by your reviewer.

> **Warning**
>
> If that is your first contribution to Metabase, please sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) (unless it's a tiny documentation change). Also, if you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

Closes https://github.com/metabase/metabase/issues/[issue_number]

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2025-01-02 15:50 UTC, mngr approved these changes

2025-01-06 14:21 UTC, AlessioLaiso requested changes
The contrast here isn't enough to really communicate that these buttons aren't disabled. The fact that we use grey for disabled buttons and text field contributes to this. Let's tweak this to get more contrast by using the following colors from the new palette:
- Background → orion-10 (this will need a semantic name for this application)
- Text and icons → text-secondary

2025-01-06 15:52 UTC, ranquild requested changes
Rejecting per UX comment

2025-01-06 18:58 UTC, ranquild approved these changes
actually I don't want to block this PR on color changes

2025-01-08 11:21 UTC, uladzimirdev commented
> * Background → orion-10

@AlessioLaiso I just realized that in figma we use `orion-5`

2025-01-08 12:46 UTC, uladzimirdev commented
@AlessioLaiso does it look better? 


https://github.com/user-attachments/assets/2ac56b9b-bd54-41a5-9980-8124ce4c7eda

2025-01-08 14:57 UTC, AlessioLaiso commented
@uladzimirdev Yes, better!

2025-01-08 21:09 UTC, merged