feat(QB): combine chart type selector with viz settings sidebar
metabase/metabase pull request #51671
Opened 2024-12-26 19:33 UTC by uladzimirdev

> [!IMPORTANT]
> For those employed by Metabase: if you are merging into master, please add either a `backport` or a `no-backport` label to this PR. You will not be able to merge until you do this step. Refer to the section [Do I need to backport this PR?](https://www.notion.so/metabase/Metabase-Branching-Strategy-6eb577d5f61142aa960a626d6bbdfeb3?pvs=4#89f80d6f17714a0198aeb66c0efd1b71) in the Metabase Branching Strategy document for more details. If you're not employed by Metabase, this section does not apply to you, and the label will be taken care of by your reviewer.

> **Warning**
>
> If that is your first contribution to Metabase, please sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) (unless it's a tiny documentation change). Also, if you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

Closes https://github.com/metabase/metabase/issues/[issue_number]

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2024-12-30 20:58 UTC, mngr commented
[localhost-1735592169372.log](https://github.com/user-attachments/files/18277713/localhost-1735592169372.log)
A lot of errors in the js console in this branch, not sure if it relates to the changes

2024-12-30 21:50 UTC, mngr approved these changes

2025-01-06 15:41 UTC, AlessioLaiso approved these changes

2025-01-06 15:53 UTC, ranquild requested changes
Rejecting until there is a clear approval

2025-01-06 16:32 UTC, alxnddr commented on frontend/src/metabase/query_builder/components/view/View/ViewLeftSidebarContainer/ViewLeftSidebarContainer.jsx
> +  if (isShowingChartTypeSidebar) {
Where is this still used?

2025-01-06 16:34 UTC, alxnddr commented on frontend/src/metabase/query_builder/components/view/View/ViewLeftSidebarContainer/ViewLeftSidebarContainer.jsx
> +/* eslint-disable react/prop-types */
This is a small enough component that just passes props to already typed components so adding types to it would be nice

2025-01-06 16:34 UTC, alxnddr approved these changes
Tested locally, looks good! Left a couple of minor comments

2025-01-06 21:52 UTC, cdeweyx approved these changes
This looks good. For some reason a part of me feels that this amplifies the badness of our "ghost chart" states, but I won't block on that. We have been meaning to pull that work forward on the DashViz side.

2025-01-08 07:39 UTC, uladzimirdev commented on frontend/src/metabase/query_builder/components/view/View/ViewLeftSidebarContainer/ViewLeftSidebarContainer.jsx
> +  if (isShowingChartTypeSidebar) {
not used afaik, but I wasn't brave enough to drop it

2025-01-08 07:39 UTC, uladzimirdev commented on frontend/src/metabase/query_builder/components/view/View/ViewLeftSidebarContainer/ViewLeftSidebarContainer.jsx
> +/* eslint-disable react/prop-types */
true, I wanted to keep this diff cleaner

2025-01-08 21:04 UTC, ranquild approved these changes

2025-01-09 11:20 UTC, uladzimirdev commented on frontend/src/metabase/query_builder/components/view/View/ViewLeftSidebarContainer/ViewLeftSidebarContainer.jsx
> +  if (isShowingChartTypeSidebar) {
I'll address it in a separate PR

2025-01-09 11:20 UTC, uladzimirdev commented on frontend/src/metabase/query_builder/components/view/View/ViewLeftSidebarContainer/ViewLeftSidebarContainer.jsx
> +/* eslint-disable react/prop-types */
I'll address it in a separate PR

2025-01-09 11:52 UTC, uladzimirdev commented on frontend/src/metabase/query_builder/components/view/View/ViewLeftSidebarContainer/ViewLeftSidebarContainer.jsx
> +/* eslint-disable react/prop-types */
https://github.com/metabase/metabase/pull/51903

2025-01-09 11:53 UTC, uladzimirdev commented on frontend/src/metabase/query_builder/components/view/View/ViewLeftSidebarContainer/ViewLeftSidebarContainer.jsx
> +  if (isShowingChartTypeSidebar) {
https://github.com/metabase/metabase/pull/51903

2025-01-09 12:10 UTC, merged