Preemptive caching FE
metabase/metabase pull request #51684
Opened 2024-12-27 20:44 UTC by noahmoss

> [!IMPORTANT]
> For those employed by Metabase: if you are merging into master, please add either a `backport` or a `no-backport` label to this PR. You will not be able to merge until you do this step. Refer to the section [Do I need to backport this PR?](https://www.notion.so/metabase/Metabase-Branching-Strategy-6eb577d5f61142aa960a626d6bbdfeb3?pvs=4#89f80d6f17714a0198aeb66c0efd1b71) in the Metabase Branching Strategy document for more details. If you're not employed by Metabase, this section does not apply to you, and the label will be taken care of by your reviewer.

> **Warning**
>
> If that is your first contribution to Metabase, please sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform) (unless it's a tiny documentation change). Also, if you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.

Closes https://github.com/metabase/metabase/issues/[issue_number]

### Description

Describe the overall approach and the problem being solved.

### How to verify

Describe the steps to verify that the changes are working as expected.

1. New question -> Sample Dataset -> ...
2. ...

### Demo

_Upload a demo video or before/after screenshots if sensible or remove the section_

### Checklist

- [ ] Tests have been added/updated to cover changes in this PR

2024-12-27 20:45 UTC, noahmoss commented
* **#51684** <a href="https://app.graphite.dev/github/pr/metabase/metabase/51684?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/metabase/metabase/51684?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-03 11:18 UTC, piranha commented
everything's fine in backend code, but I don't think it warrants a check, hehe :)

2025-01-03 22:33 UTC, iethree commented on frontend/src/metabase/admin/performance/components/StrategyForm.tsx
> +      the results and refresh the cache."
need to localize these strings with ttag

2025-01-03 23:20 UTC, iethree requested changes

2025-01-03 23:20 UTC, iethree commented on frontend/src/metabase/admin/performance/components/StrategyForm.tsx
> +        description: { fontWeight: "normal" },
I don't think this line does anything

2025-01-03 23:20 UTC, iethree commented on frontend/src/metabase/admin/performance/components/StrategyForm.tsx
> +        label: { fontWeight: "bold" },
@kdoh I wonder if this is a case where we should revisit the defaults for this switch. again this seems like a pretty "standard" switch

without styling | withstyling
---|---
![Screen Shot 2025-01-03 at 4 17 52 PM](https://github.com/user-attachments/assets/130acebf-13a7-4229-b69e-f4ba153e74ae) | ![Screen Shot 2025-01-03 at 4 17 41 PM](https://github.com/user-attachments/assets/b6ec307e-5052-4771-986f-a18a9a86f233)

@noahmoss , nothing for you to change here

2025-01-06 15:56 UTC, noahmoss commented on frontend/src/metabase/admin/performance/components/StrategyForm.tsx
> +  };
Good call, I think it's because I had written `useFormikContext<CacheStrategy>()` but I can actually scope that just to `useFormikContext<DurationStrategy | ScheduleStrategy>()`

2025-01-06 15:57 UTC, noahmoss commented on frontend/src/metabase/admin/performance/components/StrategyForm.tsx
> +  }, [enabled, currentRefreshValue, handleSwitchToggle, values]);
Honestly, not sure. I was hitting issues getting the state hooked up to Formik and somehow that helped make it work. But I just removed it and it's still working fine so 🤷

2025-01-06 15:59 UTC, iethree commented on frontend/src/metabase/admin/performance/components/StrategyForm.tsx
> +  enabled?: boolean;
I think we can 🪓  this too now

2025-01-06 15:59 UTC, iethree approved these changes

2025-01-06 21:29 UTC, merged