Fix cases where empty schema metadata property wasn't converted to an…
metabase/metabase pull request #5178
Opened 2017-05-23 20:17 UTC by attekei

Fixes two issues:

- #5158 Can't save table permission changes if the database doesn't have schemas
- If your user group has full data access to a table, and you then try to revoke an access to a single table, then the access to every table is revoked instead. This applies only if the database doesn't have schemas.

I won't merge this before I've written tests for both issues.

2017-05-23 20:27 UTC, tlrobinson requested changes

2017-05-23 20:27 UTC, tlrobinson commented on frontend/src/metabase/lib/permissions.js
> +    const schemaNamesOrNoSchema = schemaNames.length > 0 ? schemaNames : [""];
schemaNames could be null

2017-05-23 20:40 UTC, attekei commented on frontend/src/metabase/lib/permissions.js
> +    const schemaNamesOrNoSchema = schemaNames.length > 0 ? schemaNames : [""];
Nulls are filtered out in https://github.com/metabase/metabase/blob/afb6230312d44413de01124ace1b2b143362f802/frontend/src/metabase/meta/metadata/Database.js#L38

2017-05-25 00:27 UTC, attekei commented
Tests are now in place for both schemaless and multi-schema databases. I decided to test against Redux selectors as that is the API that the React components consume.

Ready for a second round of code reviews.

2017-05-25 00:45 UTC, camsaul approved these changes
lgtm

2017-05-31 21:29 UTC, tlrobinson approved these changes

2017-05-31 21:38 UTC, merged