Fix #4768: Parameter resolution via DashboardCardSeries in embedded multiline series
metabase/metabase pull request #5652
Opened 2017-08-01 18:10 UTC by alex-mcleod

Proposed fix for #4768. Pretty new to Clojure and Metabase so there may be a more sensible way to do this. Cheers for any feedback.

2017-09-14 21:45 UTC, camsaul commented on src/metabase/api/embed.clj
> +              [db :as mdb]]
this indentation is off

2017-09-14 21:45 UTC, camsaul commented on src/metabase/api/embed.clj
> +              [db :as mdb]]
also we try to keep all our requirements ordered, as you can see. So this should go further up in the file. It should just be `[metabase.db :as mdb`]

2017-09-14 21:47 UTC, camsaul commented on src/metabase/api/embed.clj
> +)
Hanging parens on their own lines is a Lisp no-no. Take a look at the rest of the file to get a sense of how the code should be styled

2017-09-14 21:49 UTC, camsaul requested changes
this fix might work. The code style could use some work however; as-is it makes reading/reviewing the code a bit difficult. Either way we'd want to add a test for this before merging

2017-09-14 21:51 UTC, camsaul commented on src/metabase/api/embed.clj
> +)
it doesn't look like you actually changed the last line so what's the reason behind changing all the parens like that?

2017-09-14 21:54 UTC, camsaul commented
Thanks for your contribution @alex-mcleod. This fix looks like it might work so I'll look into it a bit more and see it that is indeed the case.

2017-09-15 19:52 UTC, camsaul commented
Hey @alex-mcleod, I opened a new PR, #5985, which uses an approach similar to yours and adds a test as well. Thanks for the help investigating this issue. 🎉

2017-09-15 19:52 UTC, closed without merging

2017-09-16 00:03 UTC, alex-mcleod commented
@camsaul no worries, thanks for taking a look!