In new question flow, apply appropriate filter and breakout for metrics automatically
metabase/metabase pull request #6074
Opened 2017-09-29 13:35 UTC by attekei

Wanted to create a separate PR for this, earlier this was part of https://github.com/metabase/metabase/pull/5997.

---

Currently this has one potential performance problem that we need to solve if we want to merge this to production. A brief description of the problem:
- List items in Metrics search view are question links which contain the hashed questions.
- We want that clicking the link opens the question with breakouts/filters applied
- The problem is that in order to generate the link, we have to know which breakouts/filters to apply. We want to choose the fields for breakouts/filters so we have to know the fields for generating the links.
- The current solution is that we fetch the detailed metadata for every single table. 

Just realized that the fix is maybe pretty simple – just load the detailed metadata for those tables that have metrics attached. If there are metrics in >10 tables then the page load might be a little slow but probably still tolerable?

2017-10-02 19:36 UTC, salsakran commented
"The current solution is that we fetch the detailed metadata for every single table so that we can be sure that we have fields available when we need them." 
is a non-starter.

It's ok to do an additional call when the metric is selected to get dimensions, or otherwise do the conversion from a metric ID to the appropriate query dictionary on the backend. I'd have a preference for the later.

2017-10-02 19:37 UTC, salsakran requested changes
We need to stop digging the whole of needing detailed metadata for every single interaction.

2017-10-02 19:57 UTC, attekei commented
Yeah, actually adding an intermediate url could also work (and doesn't require loading any additional metadata before entering that url). So an url for a metric would be something like
```
http://localhost:3000/question/new/metric/:metric_id
```
which would then get the metadata for that metric and redirect to the query builder. That would still let people command-click / copy the link to the metric question.

2017-10-05 09:35 UTC, attekei commented
Now there is an intermediate url. Although this is already mergeable, I think that adding the backend endpoint for constructing the query dictionary for a metric makes sense (so that we can later apply some intelligent logic on which filters/groupings to use).

I don't know if there are any similar endpoints yet, but it could be simply something like
```
GET /api/metric/:metricId/query
```

which would return a MBQL query which
- is a structured query which uses the metric's database and table
- uses the metric as the aggregation
- filters by past 365 days using the first found date field
- groups by day using the first found date field
- if no date field is available, then doesn't apply filters/groupings

Could you @camsaul or @senior add that endpoint?

2017-10-11 23:41 UTC, salsakran commented
would also add: uses the primary dimension for that metric if it has one (eg like in the getting started guide)

2019-08-28 22:58 UTC, camsaul commented
Closing this and other old POC or WIP PRs for now to help clear the PR backlog. I'll leave the branch open in case we want to revisit this

2019-08-28 22:58 UTC, closed without merging