i18n(QB) translating strings
metabase/metabase pull request #6374
Opened 2017-11-13 23:09 UTC by joebordes

2017-11-13 23:25 UTC, joebordes commented
Hi @kdoh ,

Here is another directory of changes.

I don't know how to translate these two blocks:

https://github.com/metabase/metabase/pull/6374/files#diff-6a19a8788c93235b7a1d182a660096feL53

https://github.com/metabase/metabase/pull/6374/files#diff-ce3ecc7c4b390728fd6a81b319ab37feL30

Please have a look in general and get back to me when you can.

2017-11-14 16:43 UTC, kdoh reviewed
Looks pretty good! I tried to address a couple of your questions. Let me know if those solutions work. Thanks for all your help on help on getting Metabase ready to translate @joebordes!

2017-11-14 16:43 UTC, kdoh commented on frontend/src/metabase/qb/components/TimeseriesFilterWidget.jsx
> +                currentDescription = t`After`+ " " + currentDescription;
I realize this was this way before you added the t tag but to make things a little cleaner I might convert these over to something like
```jsx
t`After ${currentDescription}`
```
just to keep things a bit more maintainable. Having to do `+ " "` to add an extra space could get a little fragile.

2017-11-14 16:43 UTC, kdoh commented on frontend/src/metabase/qb/components/actions/CommonMetricsAction.jsx
> +        title: <span>{t`View  ${ mname }`}</span>,
You can convert this to a variable but you can also use `jt` to handle jsx tags. It looks something like this

```jsx
<span>{ jt`View ${<span>{metric.name}</span>}`}</span>
```

[Here's an example](https://github.com/metabase/metabase/pull/6278/files#diff-9881a49f8bf82cd653f982fbb650c80bR181) from our alerts feature branch.

2017-11-14 16:43 UTC, kdoh commented on frontend/src/metabase/qb/components/actions/PivotByAction.jsx
> +        const breakoutname = <span className="text-dark">{name.toLowerCase()}</span>
Same thing here r.e. use of `jt` over creating a variable.

2017-11-14 16:43 UTC, kdoh commented on frontend/src/metabase/qb/components/actions/UnderlyingRecordsAction.jsx
> +    const dname = <span className="text-dark">{query.table().display_name}</span>
Same here r.e. var.

2017-11-14 16:43 UTC, kdoh commented on frontend/src/metabase/qb/components/drill/QuickFilterDrill.jsx
> +                        {t`View this`}
I *think* you can do something like this to make this more contextual.

```jsx
<span>{ jt`View this ${singularize(stripId(column.display_name))}'s` }</span>
```

2017-11-14 16:43 UTC, kdoh commented on frontend/src/metabase/qb/components/drill/UnderlyingRecordsDrill.jsx
> +            title: t`View` + " " +
For this one I think the following should work. I suppose there's a chance for something like this that the broken up words could create some slightly unnatural sentences in certain languages if the proper context / tense isn't presented to the translator but I'm not sure of a way around this.

```jsx
title: t`View ${inflect(t`these`, count, t`this`, t`these`)} ${inflect(query.table().display_name, count}`
```

2017-11-14 18:59 UTC, joebordes commented
Ok, I think I got it. Thanks!!

Have a look and let me know if you need me to change anything else. I will fix the pulse changes and try to find some time to get at another directory.

2017-11-14 19:34 UTC, kdoh approved these changes
👍

2017-11-14 19:52 UTC, kdoh requested changes
Hey @joebordes. Just tried this locally and it looks like the webpack build doesn't actually build. You'll need to  import `jt` explicitly in the files that use it and I believe and there's also a lint error in one or two places. Mind running `yarn run lint` and `yarn run test` to make sure everything is working as intended?

2017-11-15 09:40 UTC, joebordes commented
Hi @kdoh 
I passed lint and test and fixed all the errors except one which I do not know how to fix:

```
LINT
/space/reps/metabase/frontend/src/metabase/query_builder/containers/ArchiveQuestionModal.jsx
  3:19  error  Unable to resolve path to module 'c-3po'  import/no-unresolved

TEST
 FAIL  frontend/test/modes/drills/PivotByCategoryDrill.integ.spec.js
  ● Test suite failed to run

    Cannot find module 'c-3po' from 'AggregationPopover.jsx'
```

Let me know what you want me to do.

2017-11-21 20:56 UTC, kdoh commented
Closing in favor of #6442

2017-11-21 20:56 UTC, closed without merging