Fix issues with `type/PK` + `type/DateTime`  fields
metabase/metabase pull request #6726
Opened 2018-01-19 09:06 UTC by tlrobinson

- [x] if drilling into a `type/PK` + `type/DateTime` field use `["datetime-field", ..., "default"]` to disable implicit bucketing by day
- [x] `getMode` shouldn't detect `type/PK` + `type/DateTime` fields as PKs (and thus `ObjectMode`) unless `["datetime-field", ..., "default"]` is used
- [x] `getMode` shouldn't detect results as `ObjectMode` if results have more than one row.
- [ ] tests

Resolves #6290

2018-01-22 07:12 UTC, tlrobinson commented
By the way, the original issue can be reproduced on any database by marking a `DateTime` field as "Entity Key" (i.e. `PK`)

2018-01-22 11:52 UTC, attekei commented
I reviewed the source code earlier today and it looks good to me

2018-01-23 21:23 UTC, camsaul approved these changes
LGTM

2018-01-24 21:17 UTC, salsakran commented
Ok, so I'm really late to the party -- 
do we need to mark the druid timestamp as a PK at all? I.e. are we just adding a weird bandaid for the type system being incorrect here? 

I don't think a time bucket should be considered a pk personally, but I haven't thought deeply about this.

2018-01-24 21:18 UTC, camsaul commented
Yeah I don't think timestamps should be PKs. I don't remember why they were in the first place but it doesn't sound like it makes sense now

2018-01-24 21:22 UTC, salsakran commented
imo this entire PR can be replaced by removing that assignment in the druid driver (?) and forcing a re-classification in the next version.

2018-01-25 06:33 UTC, tlrobinson commented
Do you think there are ever cases where a date/time field would be considered a PK? If so I think this PR is still useful.

2018-01-29 04:57 UTC, tlrobinson commented
@salsakran ^

2018-01-29 05:21 UTC, salsakran commented
I don't really know of any case where you'd want a binned time dimension to be a primary key.

2018-01-30 16:02 UTC, senior reviewed
@salsakran I've added a note [here](https://github.com/metabase/metabase/issues/6290#issuecomment-361640643) with the fix you've suggested. Should we close this?

2018-01-30 16:14 UTC, tlrobinson commented
@salsakran How should a `id TIMESTAMP PRIMARY KEY` (in postgres, for example) field behave? Currently it's detected as both a `DateTime` and `PK` so clicking the "View Details" drilldown bins the `=` filter by day (because it's a `DateTime`) and silently just shows the first row in the results in the object detail (because it's a `PK`).

Also this (ensuring rows.length == 1 for object detail) fixes another edge case where someone accidentally marks a field as `PK` but it's not actually unique and we show the object detail even if multiple rows are returned.

2018-02-12 05:47 UTC, tlrobinson commented
@salsakran ping ^

2018-04-09 22:01 UTC, camsaul commented
Are we still planning on merging this?

2018-05-08 18:14 UTC, tlrobinson commented
I think we should, but still waiting to hear @salsakran's thoughts

2018-05-08 18:37 UTC, salsakran commented
I think we should close this and fix the backend marking druid timestamps as PKs.

A timestamp is most certainly not a PK as classically defined and I don't see a need to expand the definition in this case.

I can be convinced otherwise, but that's my ~80% conviction belief.

2018-05-08 18:47 UTC, tlrobinson commented
None of the code in this PR should be merged? It addresses multiple issues.

2018-05-08 19:16 UTC, salsakran requested changes
@cam what does "default" do on a `datatime-field` clause? Is it the minimum resolution or day?

2018-05-08 19:17 UTC, salsakran commented on src/metabase/driver/druid/query_processor.clj
> +                                                  (if (= unit :default)
@camsaul

2018-05-08 19:17 UTC, salsakran commented
also @camsaul how can we do an exact filter (i.e. without any binning) on a datatime column?

2018-05-08 19:25 UTC, camsaul commented
@salsakran in answer to both questions see https://github.com/metabase/metabase/wiki/Query-Language-'98#datetime-units. `:default` means don't do any bucketing and use whatever resolution the column is at (e.g. millisecond)

2018-05-08 19:27 UTC, tlrobinson commented
The MBQL documentation doesn't match what we actually do. It says 

> Datetime fields used without being wrapped in a datetime-field form are automatically converted to datetime-field forms with :default bucketing.

https://github.com/metabase/metabase/wiki/Query-Language-'98#datetime-fields

> default | N/A | 2016-02-01 21:59:20 | No bucketing should take place -- use the default resolution of the column in question, such as seconds or milliseconds.

https://github.com/metabase/metabase/wiki/Query-Language-'98#datetime-units

However, in many (most? all?) of our drivers if you don't wrap a date time field in a `datetime-field` we bucket by day, which contradicts at least on of those statements.

2018-05-08 19:28 UTC, camsaul commented
Oh yeah the first statement is wrong it should say `:day` and not `:default`

2018-05-08 20:08 UTC, camsaul commented on src/metabase/driver/druid/query_processor.clj
> +                                                  (if (= unit :default)
done

2019-05-07 05:59 UTC, camsaul commented
This is way out of date motion to close

2019-08-28 21:54 UTC, camsaul commented
Closing this and other old POC or WIP PRs for now to help clear the PR backlog. I'll leave the branch open in case we want to revisit this

2019-08-28 21:54 UTC, closed without merging