Ia/feature/pdf export
metabase/metabase pull request #7206
Opened 2018-03-27 03:23 UTC by andhdo

Simple export-to-pdf functionality using clj-pdf

###### Before submitting the PR, please make sure you do the following 
-  [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [x] Run the frontend and integration tests with  `yarn && yarn run prettier && yarn run lint && yarn run flow && ./bin/build version uberjar && yarn run test`)
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

2018-03-27 18:58 UTC, salsakran commented
@andhdo Thank you for hour help!

The pull request template includes a few things we need from you, specifically making sure that tests pass, that linting passes and that you have signed our CLA.

Also, this PR is missing tests. Please add a few so future code changes don't break this.

2018-03-28 01:45 UTC, salsakran requested changes
Thanks @andhdo for the PR.

However, for us to accept this PR we need you to 
1. Sign the CLA
2. Add tests for this functionality
3. Verify that this doesn't break any other functionality by running the full test suite. 

We include these instructions in the PR template, and can not accept any PR that doesn't include the above steps.

2018-03-29 02:11 UTC, andhdo commented
Added modifications for testing & lint purposes.

2018-04-02 18:25 UTC, tlrobinson commented
@salsakran @kdoh @mazameli Currently the PDF output is essentially unstyled. Do we want to give it a little Metabase design love? I'm not sure how difficult that will be, as I haven't looked closely at [clj-pdf](https://github.com/clj-pdf/clj-pdf)

e.x.

<img width="856" alt="screen shot 2018-04-02 at 11 10 14 am" src="https://user-images.githubusercontent.com/18193/38208650-99c3763c-3666-11e8-926e-2ab9c8511299.png">

2018-04-02 18:27 UTC, tlrobinson commented
The download popover is also getting a bit wide:

![screen shot 2018-04-02 at 11 26 53 am](https://user-images.githubusercontent.com/18193/38209313-c3a82676-3668-11e8-9bd5-3b85c0f8fc25.png)

2018-04-02 18:42 UTC, mazameli commented
Looks like this is how you do styling: https://github.com/clj-pdf/clj-pdf#stylesheets Would it make more sense to merge this and do the styling after in a follow-up PR, or try to do styling in this PR?

And yeah, for the download menu we probably want to stack them vertically for now. We'll be moving the download actions when we implement [entity menus](https://github.com/metabase/metabase/issues/6217) in entity pages.

2018-04-02 19:02 UTC, salsakran commented
Strong 👎 on an unstyled pdf download.

What's the underlying use case for this PR @andhdo ? Are you using this yourself internally?

2018-04-02 19:04 UTC, salsakran commented on test/metabase/api/public_test.clj
> +      (http/client :get 200 (str "public/card/" uuid "/query/pdf")))))
Is there a way to check that the pdf contains what you think it contains?

2018-04-03 00:39 UTC, andhdo commented
Hi; some answers. I apologize the inconveniences. 
1. @tlrobinson - about the popover: it was a way to show the option, because with a fixed size, the link cannot be seen.
2. @tlrobinson, @salsakran  - about unstyled: it was the most basic way that i'd found to generate the output.
3. @salsakran - about internal usage: it is used to save some evidence or snapshot about the result.
4. @salsakran - about the test: unfortulately i couldn't found an example inside the clj-pdf test to verify the presence of a table inside the generated report.

I'll gonna try to modify the 2nd and 5th points. I hope to collaborate with the few hours left for this and learn a little bit of clojure, language that I did not previously know.

2018-04-19 19:05 UTC, andhdo commented
@salsakran ; i made some changes according the assestments made by you and coworkers; Please, let me know if anything else is required.

2018-06-03 16:44 UTC, BaelishLord commented
Is this feature now available?
how can i run metabase to get this feature?

2018-06-06 02:26 UTC, andhdo commented
@BaelishLord: you can do a manual merge of the  [ia/feature/pdf-export](https://github.com/in-action/metabase/tree/ia/feature/pdf-export) branch with the metabase master, then compile and run it.

2019-09-04 22:30 UTC, kdoh commented
Sorry for the long wait on this @andhdo. As soon as we start getting into any sort of rich export option like a PDF, the user expectation will most likely be that formatting settings present in the Metabase UI for those results would apply to the exported PDF. Give all that, I don't think we'll be able to take this PR in its current form and given the complexities involved I think it is probably something the core team should tackle unless you're willing to sign up for a lot of back and forth and design review. I'm not sure that a PDF of a table without that, even with minimal styling is enough of a lift to be worth the additional code or cruft to the user experience and so I'm going to close this. Thanks again for looking into this and raising the issue.

2019-09-04 22:30 UTC, closed without merging