Fix query builder scroll
metabase/metabase pull request #7281
Opened 2018-04-05 17:46 UTC by sapansanu

###### Before submitting the PR, please make sure you do the following 
-  [ ] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [ ] Run the frontend and integration tests with  `yarn && yarn run prettier && yarn run lint && yarn run flow && ./bin/build version uberjar && yarn run test`)
-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

2018-04-05 17:49 UTC, sapansanu commented
## Query Builder - View and GroupBy are scrollable / FilterBy elements are contained within query builder container

I have made the view and groupby sections scrollable.

The filterby section which was overflowing outside the query builder container is now contained within.

The selection model for filterby opens to the left side and does not overflow from page width.

TODO:
The '+' button for View and GroupBy sections is not static right now. I need suggestions on how to make the '+' button for View and groupBy sections dynamic like FilterBy section.

![image](https://user-images.githubusercontent.com/14345483/38382487-f7b8cb98-38be-11e8-99fe-a39f8d46a670.png)

2018-05-08 18:33 UTC, tlrobinson commented
Thanks for working on this, however this changes the layout of the query builder bar pretty significantly, such that each section always takes an equal amount of space:

![screenshot 2018-05-08 11 22 42](https://user-images.githubusercontent.com/18193/39775264-3635e7f4-52b2-11e8-9b41-c621fbdd0a70.png)

It also disables the "extended options" section, which we obviously don't want to do.

It looks like at some point the 2 row layout for narrow screens broke, which makes the lack of scrolling worse.

I think @mazameli and/or @kdoh should probably chime in with a better thought out solution.

2018-05-08 18:35 UTC, tlrobinson requested changes
* Need design direction from @mazameli and/or @kdoh 
* Shouldn't have each section take equal amount of space
* Should probably fix the broken 2 row layout
* Shouldn't disable extended options

2018-05-08 18:35 UTC, tlrobinson commented on frontend/src/metabase/query_builder/components/GuiQueryEditor.jsx
> +          {/* <ExtendedOptions {...this.props} /> */}
This definitely shouldn't be commented out.

2019-01-10 01:50 UTC, kdoh commented
I'm going to go ahead and close this. We're going to be making some changes soon that should remove the need for this less than ideal UX situation in the first place, and I don't think the specific implementation here is how we'd want to handle this regardless. Thanks for the effort @sapansanu.

2019-01-10 01:50 UTC, closed without merging