Docs for 0.29 (WIP)
metabase/metabase pull request #7382
Opened 2018-04-19 16:28 UTC by mazameli

2018-04-20 00:24 UTC, salsakran commented on docs/users-guide/08-dashboard-filters.md
> +As of Metabase 0.29, we've greatly improved how filtering works with fields that have lots of values. If the field you're using for a filter has more than 100 unique values, you'll now automatically
Not sure we should call out a specific version in the docs? I.e. I should be able to read a given versions docs and get info on that version.

2018-04-20 00:25 UTC, salsakran commented on docs/users-guide/10-pulses.md
> +The Pulses feature in Metabase gives you the ability to automatically send regular updates to your teammates to help everyone keep track of changes to the metrics that matter to you most. You can del
`ulse` got a `p` dropped somewhere

2018-04-20 00:25 UTC, salsakran commented on docs/users-guide/10-pulses.md
> +As of Metabase 0.29, you can now include tables in your pulses. They'll be capped to 10 columns and 20 rows, and for emailed pulses the rest of the results will be included automatically as a file at
I don't think calling out a specific version is a good idea.

2018-04-20 00:26 UTC, salsakran requested changes
Minor changes, see comments.

2018-04-20 00:38 UTC, mazameli commented
Thanks Sameer. Fixed those comments. I need to add a couple of x-ray images and then this should be good to go.

2018-04-30 20:10 UTC, mazameli commented
Any objections to me merging this?

2018-04-30 20:11 UTC, salsakran approved these changes

2018-04-30 20:11 UTC, salsakran commented
go fer it.

2018-04-30 20:11 UTC, merged