xray: better field analysis
metabase/metabase pull request #7795
Opened 2018-06-04 22:44 UTC by sbelak

This adds:
1) An overview row for all field dashboards:
<img width="1060" alt="screenshot 2018-06-05 00 40 56" src="https://user-images.githubusercontent.com/178038/40945496-62e9fc10-6859-11e8-8e69-6499fd529d25.png">
2) "crosstab" for category-vs-category breakdown
<img width="567" alt="screenshot 2018-06-05 00 40 49" src="https://user-images.githubusercontent.com/178038/40945515-78911012-6859-11e8-83fa-70b36e5271ff.png">
3) Number field heuristic
<img width="1440" alt="screenshot 2018-06-05 00 39 10" src="https://user-images.githubusercontent.com/178038/40945531-89e0ed38-6859-11e8-994e-89e95e262fa0.png">

2018-06-04 22:52 UTC, sbelak commented
@mazameli can you throw an eye on copy

2018-06-04 22:53 UTC, mazameli commented
@sbelak Yep, should be able to grab that first thing tomorrow morning once I'm done with some immediately pressing items.

2018-06-08 17:36 UTC, salsakran requested changes
Getting a brutal performance regression when looking at sample dataset people table automatic dashboards. These are taking >15s to load that api endpoint for me.

2018-06-08 21:43 UTC, salsakran approved these changes

2018-06-08 21:46 UTC, salsakran commented
Disregard, ended up being due to a not having an index on `FK_TARGET_FIELD_ID`.

We should probably index this, but that's outside the context of this PR, and don't think that app db select was even introduced in this PR

2018-06-08 23:00 UTC, merged