Documentation improvement about Running Metabase on Debian as a service with nginx
metabase/metabase pull request #7858
Opened 2018-06-12 15:09 UTC by MrCirca

Hello,
I have added a newer - modern practice to create metabase service with systemd unit file, that is preferred using systemd.

Thank you

2018-07-25 14:22 UTC, omegadeep10 commented
Should there be some text about using `systemctl enable <servicename>` to ensure metabase starts on boot?

2018-07-25 15:50 UTC, MrCirca commented
Is it ok;

2018-07-25 15:52 UTC, omegadeep10 requested changes
metabase is slightly misspelled after `systemctl enable` I think

2018-07-25 15:56 UTC, MrCirca commented
Ok i am sorry. Resolved

2018-07-25 15:56 UTC, omegadeep10 commented
Oh also, I'd recommend `Type=oneshot` instead of `Type=simple`. https://stackoverflow.com/questions/39032100/what-is-the-difference-between-systemd-service-type-oneshot-and-simple

What do you think? Perhaps there are reasons for type simple I'm unaware of, let me know.

2018-07-25 15:58 UTC, MrCirca commented
I have to try it another time....Maybe tommorow! The current unit file, works fine for me

2018-07-25 16:00 UTC, omegadeep10 commented
Yep, makes sense. This looks good to me. I have Metabase running using Debian and Systemd as well. I'll have to check what I set `Type` to :)

2018-08-01 06:54 UTC, wvengen commented on docs/operations-guide/running-metabase-on-debian.md
> +#### Create a service  systemd unit file
I think this sentence could be improved, e.g. _Create a systemd service_. There's also a double space now.

2020-01-28 13:56 UTC, walterl commented
Closed due to inactivity, overlap with merged #9037.

2020-01-28 13:56 UTC, closed without merging