Use CollectionMoveModal in query builder
metabase/metabase pull request #7888
Opened 2018-06-14 23:07 UTC by tlrobinson

Resolves #7709

2018-06-18 20:06 UTC, salsakran commented
this looks a little off visually to me.
![screen shot 2018-06-18 at 1 06 10 pm](https://user-images.githubusercontent.com/107439/41559278-6fb243d6-72f8-11e8-8bc0-72d1b4319ef4.png)

2018-06-18 20:43 UTC, mazameli commented
Yeah, I think at the very least we'd want to slap a max-width of ~550px on that. That's what the existing full-screen modal does:

![screen shot 2018-06-18 at 1 41 21 pm](https://user-images.githubusercontent.com/2223916/41560893-54cc94ea-72fd-11e8-8067-745b886c57db.png)

Another thing I'll add to my to-do list, though, is inventorying our use of full-screen vs. overlay modals. We've gotten ourselves into a weird place where it doesn't feel super predictable what kind of modal will be shown in any given part of the product.

2018-06-18 21:35 UTC, kdoh requested changes

2018-06-18 21:35 UTC, kdoh commented on frontend/src/metabase/query_builder/components/QueryHeader.jsx
>              full
We should remove the full here to keep the experience for moving items the same throughout the product.

2018-06-19 17:52 UTC, tlrobinson commented
Fixed ![screenshot 2018-06-19 10 51 51](https://user-images.githubusercontent.com/18193/41614978-e24d6856-73ae-11e8-8bd1-20c4928166ed.png)

2018-06-19 17:55 UTC, kdoh approved these changes

2018-06-19 17:56 UTC, tlrobinson commented
One thing that's not ideal is the scroll behavior of the `CollectionMoveModal`. Currently the whole modal scrolls but we probably want a fixed header/footer with just the list scrolling. I tried adding `scroll-y` to the `CollectionPicker` but that didn't work. @kdoh ideas?

2018-06-19 19:55 UTC, merged