Simple admin string spacing fix
metabase/metabase pull request #7944
Opened 2018-06-26 18:33 UTC by dv321

Adds spaces after periods in the table name humanization text, so

Metabase can attempt to transform your table and field names into more sensible, human-readable versions, e.g. "somehorriblename" becomes "Some Horrible Name".This doesn’t work all that well if the names are in a language other than English, however.Do you want us to take a guess?

becomes

Metabase can attempt to transform your table and field names into more sensible, human-readable versions, e.g. "somehorriblename" becomes "Some Horrible Name". This doesn’t work all that well if the names are in a language other than English, however. Do you want us to take a guess?

I feel like a bad contributor but due to my current setup and environment I'm unable to test this myself, but dare I say testing it won't be hard?

###### Before submitting the PR, please make sure you do the following 
-  [ ] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [ ] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

2018-07-02 23:13 UTC, salsakran commented
Thanks @dv321 !

@camsaul @senior clojure style wise, is this ok, or should we separate out the spaces from the translatable strings?

2018-07-06 16:54 UTC, camsaul commented
I think it would make more sense just to put the whitespace in between the i18n'ed strings. It would be super easy for a translator to forget them or think they're a mistake in the first place and not include them

e.g.

```clj
(str (trs ...)
     " "
     (trs ...))
```

2018-07-09 17:47 UTC, salsakran requested changes
@dv321 can you pull the spaces strings outside of translatable strings?

2018-07-10 18:57 UTC, dv321 commented
@salsakran all done, definitely cleaner this way :+1:

2018-07-24 18:53 UTC, camsaul approved these changes
Cool this should be g2g now

2018-07-24 18:53 UTC, camsaul commented
lgtm going to go ahead and merge

2018-07-24 18:53 UTC, merged