Add fuzzy search for categories filters with a list
metabase/metabase pull request #7951
Opened 2018-06-28 04:08 UTC by agindre

Hi, 

For a list of values in a categories filter, when you have 20+ categories available in the list, it's handy to have a fuzzy search instead of an order dependent search.

The idea is to help the user to find faster what they are looking for even if they are typing a part of the categorie's name.

2018-07-09 17:47 UTC, salsakran commented
@tlrobinson mind reviewing this?

2018-07-09 17:57 UTC, tlrobinson approved these changes

2018-07-09 17:58 UTC, tlrobinson commented
@salsakran Code looks fine. I assume we actually want this change?

2018-07-31 00:07 UTC, agindre commented
Hi guys!
Any timeline for the merge of this pull request? 
Can I help in any way? 

Cheers,

2018-08-06 23:27 UTC, mazameli commented
The UX problem I see with this is that it behaves differently for `lists` than for `search` widgets, which is confusing. I can search for a substring in a _list_ of possible options, but not when I have a search box widget.

List of values:

![screen shot 2018-08-06 at 4 24 52 pm](https://user-images.githubusercontent.com/2223916/43745749-4fc60f62-9995-11e8-823a-be6f1bf1ab84.png)

…but if I have a lot of values and I try to find e.g. this value by searching the word `group` instead of `blake` (or `blak`, heh), I don't get any results:

![screen shot 2018-08-06 at 4 21 02 pm](https://user-images.githubusercontent.com/2223916/43745673-f254632e-9994-11e8-8d08-feb1f94fc1dd.png)

![screen shot 2018-08-06 at 4 21 14 pm](https://user-images.githubusercontent.com/2223916/43745703-0feeaee4-9995-11e8-9b3c-6f23c60d39ad.png)

2018-12-17 20:48 UTC, mazameli requested changes
I would like the UX between lists and the search widget to be the same, i.e. I should be able to search on a substring regardless if my widget is a list of values or the type-to-search box.

2018-12-24 08:57 UTC, jbrooksuk commented
Any chance we could push this forward? We have over 100 unique values in some of our category lists and with some of the results containing a prefix, it's easy to miss them.

Thanks!

2018-12-24 15:36 UTC, MarkRx commented
There is a technical gotcha for fuzzy searches on type-ahead boxes - they will (depending on the underlying database) probably result in a full table scan. While I agree type-ahead should support fuzzy search it does mean indexes on the textual data may be moot. Hence performance should be tested on datasets of various sizes before pushing a change. I'd be interesting in knowing how well it operates with say 10 million records.

2018-12-27 08:07 UTC, jbrooksuk commented
I can't tell from the changes, but is this not filtering a list already, rather than hitting the DB again?

2019-01-09 12:02 UTC, jbrooksuk commented
Ping @tlrobinson and @kdoh. This would drastically improve UX.

2020-01-30 00:06 UTC, walterl commented
Closed due to inactivity.

2020-01-30 00:06 UTC, closed without merging

2020-01-30 16:32 UTC, MarkRx commented
Please reopen this issue. It would be a great UX improvement.

2020-01-30 16:43 UTC, walterl commented
@MarkRx I agree that it would be great to have. It's just not quite in line with the direction that the core team is heading in at the moment, so we don't have spare cycles to spend on this. If anyone wants to pick it up and push it over the line, we'd be happy to take another look at it. :slightly_smiling_face:

2020-12-12 12:01 UTC, Olaktal commented
Hello ! Can you please re-open this improvement