Fixing a problem with manual migrations
metabase/metabase pull request #8513
Opened 2018-09-13 14:42 UTC by cgimenes

Hi, I found a problem with manual migrations: It asks for a migration execution but it only contains some SQL instructions for locking purposes.
Looking at the logs and source code, I saw that it wasn't checking this `has-unrun-migrations?` function. So I just did some modifications to use it.

About the Exception that is thrown: `java.lang.Exception. "Database requires manual upgrade."`. I think that it should be an specific Exception, something like `ManualMigrationException`. But, I don't know how to do it, because I never worked with Clojure before, so, I kept it this way knowing it wouldn't work 
(Sorry).

During test execution, this was reported: `src/metabase/db.clj:259:5: unused-ret-vals: Var value is discarded: println` but, I don't know how to fix it either.

###### Before submitting the PR, please make sure you do the following 
-  [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [x] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

2018-09-18 23:28 UTC, cgimenes commented
I updated the Dockerfile base image and moved one migration from data migrations to an liquibase migration, because IMO a DROP TABLE isn't a data migration.

2018-11-02 14:13 UTC, senior requested changes
Regarding the `Exception`, it's very uncommon in Clojure to write your own exception subclass. It's more common to use use an `ex-info` which allows you to throw a map of data on about your error along with a message. I don't think that's needed in this case though and I think `Exception` is fine.

2018-11-02 14:13 UTC, senior commented on src/metabase/db.clj
> +    (println (let [sql (migrations-sql liquibase)]
I think this `println` is not correct. This was wrong in the code before as well. The SQL is being written via the log message below `log/info`. The result of that invocation will be nil, then an exception will be thrown.

Usually we always want to log things and not use `println`. In this case though, the user is starting up Metabase to see the migrations and wants that written to the console. It seems like we should swap the `log/info` for a `println`. Then we can remove this outer `println`

2018-12-11 17:53 UTC, cgimenes reviewed
Fixed

2019-09-02 17:46 UTC, mazameli commented
Assigning this to you, @camsaul, since it deals with DB migrations. Still relevant?

2020-01-20 21:57 UTC, cgimenes commented
.

2020-03-02 19:09 UTC, camsaul commented on resources/migrations/000_migrations.yaml
> +      author: camsaul
I'm not the author of this migration

2020-03-02 19:10 UTC, camsaul approved these changes
This LGTM, I can go ahead and fix the merge conflicts and merge this

2020-03-02 20:52 UTC, camsaul commented
Merged in PR #12023

2020-03-02 20:52 UTC, closed without merging