fix postgres connection string
metabase/metabase pull request #8598
Opened 2018-09-27 15:51 UTC by argvader

This is an update to pass query parameters to the postgres connection string during validates and execution. This addresses an issue when upgrading postgres and getting the an error when using a string like:
postgresql://host:port/database?user=toto@toto&password=xxxxxx&ssl=true&sslmode=require

###### Before submitting the PR, please make sure you do the following 
-  [ ] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [ ] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

2018-09-27 16:54 UTC, BrandonEvansAsurion approved these changes

2018-09-27 16:55 UTC, BrandonEvansAsurion commented
Fixes https://github.com/metabase/metabase/issues/8254

2018-09-27 18:16 UTC, pettyalex approved these changes

2018-10-01 14:25 UTC, senior requested changes
@argvader This seems like a good change other than the whitespace part that I think was an accident. I'm surprised we haven't had more issues around this.

@camsaul Any thoughts on this? Seems like we should follow this up with fixes for the other two databases.

2018-10-01 17:31 UTC, argvader commented on src/metabase/db.clj
> +     (merge {:type     (case (keyword protocol)
Yep sorry i missed it. I'll correct this.

2018-10-02 14:18 UTC, senior commented
@argvader The code looks good to me but when I run the tests I see 3 test failures in `metabase.driver.postgres-test`. Were the tests running successfully for you?

2018-10-02 18:59 UTC, senior commented
@argvader I was running `lein test` on this branch when I saw the errors.

2018-10-05 13:48 UTC, argvader commented
@senior Updated the tests.. thanks for patience.

2018-10-05 13:50 UTC, senior commented
@argvader I didn't know that you fixed up the tests, thanks for the ping. I'll get this merged today.

2018-10-05 16:21 UTC, senior approved these changes

2018-10-05 21:52 UTC, merged

2018-10-06 14:45 UTC, BrandonEvansAsurion commented
Thanks for getting this change in, @senior! Do you know when there will be a new Metabase release that includes this change? Our team would love to start to use the new features included in 0.30.x, but our only way of doing this right now is building a Docker image off of @argvader's branch and publishing it internally.

2018-10-08 11:19 UTC, bduterte commented
Thanks, also impatient to test a new release !

2018-10-29 20:18 UTC, doodlebro commented
@senior: This fix helps a very large number of your users to upgrade and use a lot of the new functionality added in 0.30. You might consider a hotfix 0.30.5 version so that we can stop being on such an old version! Thanks!