Show task history in the admin section
metabase/metabase pull request #8692
Opened 2018-10-15 20:49 UTC by kdoh

Frontend display the task history that began in #8397 to show tasks MB is running to help users debug performance and other issues.

TODOs
- [ ] API endpoint to return task history - (@senior)
- [ ] Replace stub with actual api list from endpoint
- [ ] Modal route to show details of a particular task
- [ ] Come up with a better name than `Task` ?

2018-10-16 18:35 UTC, senior requested changes
Seems pretty close, happy to jump in and help if you need it @kdoh .

2018-10-16 18:35 UTC, senior commented on src/metabase/api/task.clj
> +  (as-> (db/select TaskHistory) tasks))
```suggestion
  (api/check-superuser)
  (db/select TaskHistory)
```

2018-10-16 18:35 UTC, senior commented on src/metabase/api/task.clj
> +               api/read-check)))
Looks like I can't "suggest" with two lines. What you have will work, but this is an easier way to say it:
```
(api/read-check TaskHistory id)
```
That will check for existence, permissions and query the DB.

2018-10-16 18:35 UTC, senior commented on src/metabase/api/task.clj
> +    [metabase
When there's just one namespace, you are importing, you can use:
```
[metabase.util :as u]
```
Separating it like you're doing here used more when you're importing more than one, i.e.
```
[metabase
  [schema :as s]
  [util :as u]]
```

2018-10-16 18:35 UTC, senior commented on src/metabase/api/task.clj
> +  (as-> (db/select TaskHistory) tasks))
This will also fix the linter error in this code.

2018-10-16 18:53 UTC, mazameli commented
Re: what to call this tab/page, maybe `Troubleshooting`? I.e., in the future we can envision putting additional logs here, such as ones that detail information about timezone-related things to help troubleshoot TZ issues.

If we go with that label, I think the page will need some context-setting text at the top, like "Trying to get to the bottom of something? This section shows logs of Metabase's background tasks, which can help shed light on what's going on."

(This could then also be a place where we could consider including a link to our paid support info page.)

2018-10-16 19:56 UTC, kdoh commented
Yeah I think in terms of the long term vision for what this section of the admin section will do I dig `Troubleshooting` as the overall section heading. I went ahead and updated the nav item and urls to start. I'll fix up the header and add some context here in a little.

2018-10-17 22:44 UTC, mazameli commented
The details modal content can sometimes overflow. Seems like we'd want it to wrap.

![overflow](https://user-images.githubusercontent.com/2223916/47120415-739a9900-d223-11e8-892a-c8e751c6d868.png)

2018-10-17 22:48 UTC, mazameli commented
It'd be great if these timestamps were formatted in a friendlier way.

![screen shot 2018-10-17 at 3 48 05 pm](https://user-images.githubusercontent.com/2223916/47120573-105d3680-d224-11e8-843c-21f7784027cf.png)

2018-10-17 22:55 UTC, mazameli commented
Minor annoyance: if I open up the details modal, it'll scroll me to the top of the page if I click outside the modal to close it. If I click the X to close it, I stay at my scroll position as expected:

![scrolls-to-top](https://user-images.githubusercontent.com/2223916/47120829-08ea5d00-d225-11e8-828d-231a1819ae6e.gif)

2018-10-17 22:57 UTC, mazameli commented
If I'm being super duper nit-picky, I'd expect the colors here to match or for the info icon to be lighter than the heading I think, and the icon to be scooted down a little to align it with the heading.

![screen shot 2018-10-17 at 3 55 55 pm](https://user-images.githubusercontent.com/2223916/47120883-4e0e8f00-d225-11e8-9ecc-2a9376c3c11f.png)

2018-10-17 23:01 UTC, mazameli commented
Could we relatively easily do a remapping so that the `DB ID` column displays the name of the database instead?

![screen shot 2018-10-17 at 4 00 33 pm](https://user-images.githubusercontent.com/2223916/47121016-d8ef8980-d225-11e8-8f68-cdf795ba9fe8.png)

2018-10-18 21:43 UTC, mazameli commented
Cool, as discussed, I'm a 👍on merging this, with the timestamp and DB ID formatting changes coming later as time allows as follow-ons. I'll create a task history polish issue.

2018-10-18 21:45 UTC, merged