Make new native queries default to using the last-selected database
metabase/metabase pull request #8781
Opened 2018-10-26 00:29 UTC by kdoh

Implements #8780 by setting a localStorage item with the last selected database id if a user is creating native queries.

2018-10-26 18:54 UTC, tlrobinson commented on frontend/src/metabase/query_builder/actions.js
> +          "METABASE_LAST_USED_DB_ID",
Maybe make this a `const`

2018-10-26 18:55 UTC, tlrobinson approved these changes
LGTM but if you feel like making that key a const that might be nice.

2018-10-26 19:44 UTC, mazameli commented
@tlrobinson Don't know if you tried this out in the branch, but it has some problems when selecting saved SQL-based questions, i.e. it's either showing the New Question screen, or it'll show an empty editor:

![existing-qs](https://user-images.githubusercontent.com/2223916/47588951-9bbd8280-d91c-11e8-8248-3bb683eb81d6.gif)

2018-10-26 19:54 UTC, tlrobinson commented
@mazameli You're right, retracting my LGTM.

2018-10-26 20:07 UTC, tlrobinson requested changes
We need to inject the recent db ID in a different place. Currently it blows away saved/serialized cards.

I think the two ways to get to a new native query are the new question flow, and clicking "Switch to SQL" before selecting a database (though that currently defaults to the first DB for some reason)

2018-10-26 20:07 UTC, tlrobinson commented on frontend/src/metabase/query_builder/actions.js
> +        if (card.dataset_query.type === "native" && recentDb) {
Looks like this blows away existing cards.

2019-02-14 18:17 UTC, mazameli commented
Would be cool to figure out how to keep this from blowing away existing questions. It'd be a nice little UX lift.

2020-01-17 15:55 UTC, kdoh commented
Declaring PR bankruptcy on this one.

2020-01-17 15:55 UTC, closed without merging

2020-01-17 17:43 UTC, mazameli commented
![image](https://user-images.githubusercontent.com/2223916/72633665-ccb51900-390d-11ea-8740-593363d009d5.png)