Query Builder bugs: sorting, aggregation dimensions, field name rendering, etc [WIP]
metabase/metabase pull request #9429
Opened 2019-02-15 19:43 UTC by tlrobinson

* fixes sorting behavior in table when there is more than one aggregation
  * sort correct column applying SortAction
  * display sort indicator on correct column
* cleans up rendering of aggregation column names
  * previously duplicate aggregations showed as: "Sum" then "sum", now they are at least consistently capitalized, but still don't contain the aggregated column name (#2725 )

I'm not sure if issues for these exist.

Related backend issues which are NOT yet resolved:

* #1851 "Display metric name instead of underlying aggregation name in column header"
* #2725 "Give better names to aggregation columns returned by query processor"
* #6042 "Sorting by two columns with the same name fails with ambiguous column error"
* #8283 "Not possible to sort by metric"

2019-02-15 20:02 UTC, tlrobinson commented
Also #8988  would simplify some of this.

2019-03-04 19:00 UTC, kdoh requested changes
Could we get some tests around the aggregation sorting cases this fixes? It'd also be nice to just have a quick sanity check for `getFriendlyName`

2019-03-04 22:05 UTC, tlrobinson commented
Might be worth merging this for 0.32

2019-03-04 22:08 UTC, kdoh approved these changes

2019-03-04 23:26 UTC, merged