visualizations: fix x-axis for year in > GMT TZ
metabase/metabase pull request #9512
Opened 2019-03-05 02:01 UTC by perrinjerome

when timeserie has a `year` granularity, the time column is a int.
parseTimestamp understand this, but needs to be passed the unit to
return the timestamp in client timezone.

Fixes #7910 
cc @salsakran 

###### Before submitting the PR, please make sure you do the following
- [ ] If you're attempting to fix a translation issue, please submit your changes to our [POEditor project](https://poeditor.com/join/project/ynjQmwSsGh) instead of opening a PR.
### Tests
-  [x] Run the frontend and integration tests with  `yarn lint && yarn flow && yarn test`)
-  [ ] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && lein check-namespace-decls && ./bin/reflection-linter`

-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
(unless it's a tiny documentation change).

2019-03-09 05:11 UTC, perrinjerome commented
( I removed the PR template from the description )

/cc @salsakran

2019-04-11 07:04 UTC, perrinjerome commented
Apparently, this cause`(0 , i.default)(...).year(...).startOf is not a function` when date is null, I need to check more.

2019-08-29 00:36 UTC, camsaul requested changes
- [ ] Resolve merge conflict(s)
- [ ] Resolve "this causes `(0 , i.default)(...).year(...).startOf is not a function` when date is null."

2019-09-02 08:21 UTC, perrinjerome commented
I'll try to revisit this in the next few days, if I can find the time.

For the records, I was not confortable with the fact that this is a fix for a problem only happening when the browser uses some specifc timezones (the ones after GMT) and that I could not find a way to add a non-regression test reproducing the issue. In other words, I was waiting that https://github.com/metabase/metabase/pull/7247 , because it seems that with these changes there would be a way to run the frontend tests under a different timezone, which would make it possible to reproduce issue.

In any case, I will try first to rebase the changes and see if this MR still makes sense. Thanks  !

2019-09-02 17:19 UTC, mazameli commented
Thanks, @perrinjerome!

2019-09-08 04:38 UTC, perrinjerome commented
>  Resolve merge conflict(s)

I rebased these changes on current master and push forced in this branch, after confirming that #7910 still happens on master.

>  Resolve "this causes (0 , i.default)(...).year(...).startOf is not a function when date is null."

This was because when a row is null `parseTimeStamp` was called with `parseTimeStamp(null, "year")` which called:

https://github.com/metabase/metabase/blob/392ceddf640db338721d9d89082c275b9d6a9349/frontend/src/metabase/lib/time.js#L51

https://github.com/metabase/metabase/blob/392ceddf640db338721d9d89082c275b9d6a9349/frontend/src/metabase/lib/time.js#L5-L8

what happens is something like this:
```
> moment().year(null)
< 2019
> moment().year(null).startOf('year')
< Uncaught TypeError: moment(...).year(...).startOf is not a function
```

to prevent this, I updated the patch to pass the first non-null row to `parseTimeStamp`.

2020-01-17 16:32 UTC, paulrosenzweig commented
Closing this since the bug was fixed in #11111. We no longer use `dataOffset` and instead explicitly pass down timezone data from the server.

2020-01-17 16:32 UTC, closed without merging